-- This file deals with uploads pertaining to the Characteristics system
-- Colours
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('black', 0, 0, 0, 0, 'a pure shade of black');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('white', 1, 255, 255, 255, 'a pure shade of white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grey', 2, 127, 127, 127, 'a pure shade of grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('light grey', 2, 175, 175, 175, 'a pure shade of light grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dark grey', 2, 75, 75, 75, 'a pure shade of dark grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('red', 3, 255, 0, 0, 'a pure shade of red');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dark red', 3, 160, 0, 0, 'a pure shade of dark red');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blue', 4, 0, 0, 255, 'a pure shade of blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dark blue', 4, 0, 0, 160, 'a pure shade of dark blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('green', 5, 0, 255, 0, 'a pure shade of green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('brown', 10, 175, 175, 0, 'a pure shade of brown');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dark green', 5, 0, 160, 0, 'a pure shade of dark green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('hazel', 10, 175, 255, 0, 'a complex misture of brown, green and gold');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pale white', 1, 255, 255, 255, 'a pale white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('olive', 5, 25, 160, 0, 'the dark, deep brownish-green of an olive');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('caramel', 10, 185, 175, 0, 'the deep, rich brown of melted caramel');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ebony', 0, 10, 10, 10, 'the deep, rich black of polished ebony');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('emerald green', 5, 0, 255, 15, 'the radiant green of a cut emerald');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cerulean', 4, 0, 75, 255, 'the vibrant, bright cyan of cerulean');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('violet', 8, 225, 0, 225, 'the bright pure purple colour of violet');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sandy brown', 10, 125, 125, 10, 'the light brown colour of beach sand');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('light brown', 10, 125, 125, 0, 'a rich, light brown');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dark brown', 10, 225, 225, 0, 'a dark brown');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('auburn', 3, 160, 10, 10, 'the rich, reddish brown of auburn');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ebony', 0, 0, 0, 0, 'the deep, rich black of polished ebony');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('onyx', 0, 0, 0, 0, 'the colour of an onyx gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('obsidian', 0, 0, 0, 0, 'a deep obsidian black');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('midnight black', 0, 0, 0, 0, 'the colour of a starless midnight sky');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ink black', 0, 0, 0, 0, 'the colour of a pot of black ink');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('jet black', 0, 0, 0, 0, 'a tenebrous, jet black');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pitch black', 0, 0, 0, 0, 'the colour of absolute darkness');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ivory', 1, 0, 0, 0, 'the colour of polished ivory');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('seashell', 1, 0, 0, 0, 'the colour of a weathered seashell');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('snow white', 1, 0, 0, 0, 'the colour of fresh snow');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('gleaming white', 1, 0, 0, 0, 'a bright, gleaming white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pure white', 1, 0, 0, 0, 'a perfect, pure white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pearl white', 1, 0, 0, 0, 'the colour of a polished pearl');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bright white', 1, 0, 0, 0, 'a bold, bright white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bone white', 1, 0, 0, 0, 'the colour of weathered bone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ghost white', 1, 0, 0, 0, 'a ghostly shade of white');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('mist grey', 2, 0, 0, 0, 'the colour of a thick morning mist');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('charcoal grey', 2, 0, 0, 0, 'the colour of charcoal');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('thistle grey', 2, 0, 0, 0, 'the colour of a thistle bush');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('smoky grey', 2, 0, 0, 0, 'the colour of wood smoke');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('slate grey', 2, 0, 0, 0, 'the grey-blue colour of a slab of slate');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('silver grey', 2, 0, 0, 0, 'a rich, silvery grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('soft grey', 2, 0, 0, 0, 'a soft grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ash grey', 2, 0, 0, 0, 'the grey colour of cold ash');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('crimson', 3, 0, 0, 0, 'a strong, deep crimson red');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('scarlet', 3, 0, 0, 0, 'the bright, orangey-red colour of scarlet');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ruby red', 3, 0, 0, 0, 'the colour of a ruby gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blood red', 3, 0, 0, 0, 'the colour of arterial blood');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('rose red', 3, 0, 0, 0, 'the colour of a rose in bloom');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('wine red', 3, 0, 0, 0, 'the deep purplish-red of wine');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('flame red', 3, 0, 0, 0, 'the bold red of burning flame');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('coral', 7, 0, 0, 0, 'the dark reddish-pink of coral');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('copper', 7, 0, 0, 0, 'the reddish-brown of the metal copper');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('fiery orange', 7, 0, 0, 0, 'the bold orange of a burning flame');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ochre', 7, 0, 0, 0, 'the yellowish-brown of ochre');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sunset orange', 7, 0, 0, 0, 'the brilliant yellowish-orange of a sunset');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('amber', 7, 0, 0, 0, 'the colour of a block of polished amber');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('goldenrod', 6, 0, 0, 0, 'the yellow of the goldenrod flower');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pale yellow', 6, 0, 0, 0, 'a gentle, pale yellow');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('golden yellow', 6, 0, 0, 0, 'a rich, golden yellow');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sand yellow', 6, 0, 0, 0, 'the light brownish-yellow of beach sand');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('topaz hued', 6, 0, 0, 0, 'the colour of the topaz gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('gold-coloured', 6, 0, 0, 0, 'a full-bodied gold hue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('spring green', 5, 0, 0, 0, 'the light, bluish-green of early spring');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sea green', 5, 0, 0, 0, 'the deep bluish-green of the sea');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('hunter green', 5, 0, 0, 0, 'the dark green of woodland leaves');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('olive green', 5, 0, 0, 0, 'an olive green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sage green', 5, 0, 0, 0, 'the light, pale green of sage leaves');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pine green', 5, 0, 0, 0, 'the rich, dark green of pine leaves');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bright green', 5, 0, 0, 0, 'a bold, bright green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('rich green', 5, 0, 0, 0, 'a deep, rich green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pale green', 5, 0, 0, 0, 'a pale greyish-green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('verdant green', 5, 0, 0, 0, 'the verdant green of summer');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('forest green', 5, 0, 0, 0, 'a forest green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('chartreuse', 6, 0, 0, 0, 'the slight greenish-yellow colour of chartreuse');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('slate blue', 4, 0, 0, 0, 'the greyish-blue of slate');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bright blue', 4, 0, 0, 0, 'a bright, vibrant blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('powder blue', 4, 0, 0, 0, 'the bright cyan colour of powder snow');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sapphire blue', 4, 0, 0, 0, 'the colour of the sapphire gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('royal blue', 4, 0, 0, 0, 'a dark shade of azure blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ocean blue', 4, 0, 0, 0, 'the deep, multihued blue of the ocean');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('teal', 11, 0, 0, 0, 'a dark bluish-green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cornflour blue', 4, 0, 0, 0, 'the medium blue of the sapphire gem');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sky blue', 4, 0, 0, 0, 'the rich colour of a cloudless sky');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('azure', 3, 0, 0, 0, 'the blue colour of the azure gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('beryl', 4, 0, 0, 0, 'the bluish-green colour of the beryl gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cerulean', 11, 0, 0, 0, 'a rich, pure cerulean blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cobalt', 4, 0, 0, 0, 'a medium-dark cobalt blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('rich indigo', 8, 0, 0, 0, 'the vibrant colour of indigo dye');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('deep indigo', 8, 0, 0, 0, 'the deep indigo of the bottom of a rainbow ');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('vivid indigo', 8, 0, 0, 0, 'a vivid, bold indigo');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('earthen brown', 10, 0, 0, 0, 'the brown of rich soil');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('deep brown', 10, 0, 0, 0, 'a deep, dark brown');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('rich brown', 10, 0, 0, 0, 'a rich, bold brown');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('burnt sienna', 10, 0, 0, 0, 'the colour of fired sienna earth');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('chocolate', 10, 0, 0, 0, 'the colour of dark chocolate');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cinnamon', 10, 0, 0, 0, 'the light pinkish-brown of cinnamon');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('mahogany', 10, 0, 0, 0, 'the rich, dark colour of mahogany timber');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('nut brown', 10, 0, 0, 0, 'the light brown of a chestnut shell');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('umber', 10, 0, 0, 0, 'the deep reddish-brown of umber');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('amethyst', 4, 0, 0, 0, 'the vivid purple of the amethyst gemstone');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('mauve', 8, 0, 0, 0, 'the greyish-magenta of the mallow flower');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('mulbery', 8, 0, 0, 0, 'the rich blackish-purple hue of ripe mulberries');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('plum', 8, 0, 0, 0, 'the rich reddish-purple hue of a plum');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('lavender', 8, 0, 0, 0, 'the pure light-purple of a lavender bush');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('royal purple', 8, 0, 0, 0, 'a rich, dark purple');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded black', 0, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('tattered black', 0, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('shabby black', 0, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy black', 0, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('off-white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blotched red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dull orange', 7, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bland yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded indigo', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('drab brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dim grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dusky slate grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sooty grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('chalky pale grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dull mist grey', 2, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ashen off-white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dirty bone-white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('wan ivory', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('spotted white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blotched white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy off-white', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained ivory', 1, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('shabby sallow-coloured', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('lurid pale yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('gaudy mustard yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sickly pale yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('shabby pale yellow', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('murky brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dreary brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bland brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('spotted muddy brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dismal sand brown', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dreary beige', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy beige', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('shabby beige', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dirty beige', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('tattered beige', 10, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('bland wheat-coloured', 6, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('drab olive', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('murky olive', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dim olive', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('shabby green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dull green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sickly greyish-green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grisly brownish-green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('discoloured green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blotchy green', 5, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy rust-red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blotchy rust-red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy salmon', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained salmon', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blotched red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dull red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded salmon', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('well-worn blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded slate blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pallid blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy blue', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dim blue-black', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded blue-black', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dreary blue-black', 4, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dull orange', 7, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded reddish-orange', 7, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('tattered reddish-orange', 7, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('discoloured orange', 7, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained orange-red', 3, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('drab peach-coloured', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('lurid peach-coloured', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('sickly peach-coloured', 9, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('tattered violet', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('grimy lavender', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('spotted lavender', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('discoloured purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dirty purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dingy purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('faded purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('stained purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dusty faded purple', 8, 0, 0, 0, '');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('blonde', 6, 0, 125, 125, 'a fair, yellow blonde');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('dirty blonde', 6, 0, 125, 125, 'a darker brownish blonde');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('silver blonde', 6, 255, 255, 255, 'a light blonde with a silvery hue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('ash blonde', 6, 0, 55, 55, 'an ashen, greyish blonde');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('strawberry blonde', 6, 55, 100, 100, 'the colour of blonde with a reddish tinge');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('platinum blonde', 6, 0, 25, 25, 'an almost whitish shade of blonde');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('light blonde', 6, 0, 55, 55, 'a pure, light shade of blonde');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('salt-and-pepper', 0, 0, 0, 0, 'a dark greyish-black with speckles of grey');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('orange', 7, 200, 100, 100, 'a pure orange');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('light blue', 4, 50, 50, 255, 'a light shade of blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('light green', 5, 0, 100, 0, 'a light shade of green');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('pale blue', 4, 0, 0, 200, 'a pale shade of blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('yellow', 6, 0, 255, 255, 'a pure shade of yellow');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('cyan', 11, 0, 75, 255, 'a light, greenish blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('navy blue', 4, 0, 0, 180, 'a very dark shade of the colour blue');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('reddish brown', 10, 200, 155, 10, 'the colour of brown with a tinge of red');
INSERT INTO Colours (`Name`, Basic, Red, Green, Blue, Fancy) VALUES ('beige', 10, 75, 75, 0, 'the pale brown of natural wool');

-- Characteristic Definitions
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Colour', 2, 'colou?r', 'Generic Colour Variable', NULL, NULL);
set @colourchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Relative Height', 0, 'height', 'Relative Height', NULL, NULL);
set @relativeheightchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Humanoid Frame', 3, 'frame', 'Frame Description for Humanoids', NULL, 1);
set @humanoidframechardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Person Word', 3, 'person', 'Word Describing Personage, e.g. man, woman, maiden', NULL, 0);
set @personwordchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Eye Colour', 2, 'eyecolou?r', 'Colour of the Eyes', @colourchardef, 1);
set @eyecolourchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Eye Shape', 1, 'eyeshape', 'Shape of the Eyes', NULL, 0);
set @eyeshapechardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Hair Colour', 2, '^haircolou?r', 'Colour of the Hair', @colourchardef, 1);
set @haircolourchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Facial Hair Colour', 2, 'facialhaircolou?r', 'Colour of the Facial Hair', @haircolourchardef, 1);
set @facialhaircolourchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Hair Length', 1, '^hairlength', 'Length of the Hair', NULL, 0);
set @hairlengthchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Facial Hair Length', 1, 'facialhairlength', 'Length of the Facial Hair', NULL, 0);
set @facialhairlengthchardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Hair Style', 3, '^hairstyle', 'Style of the Hair', NULL, 0);
set @hairstylechardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Facial Hair Style', 3, 'facialhairstyle', 'Style of the Facial Hair', NULL, 0);
set @facialhairstylechardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Skin Tone', 3, 'skincolou?r', 'Skin Tone', NULL, 0);
set @skintonechardef = LAST_INSERT_ID();
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Colour1', 2, 'colou?r1', '1st Colour Variable', @colourchardef, NULL);
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Colour2', 2, 'colou?r2', '2nd Colour Variable', @colourchardef, NULL);
INSERT INTO CharacteristicDefinitions (`Name`, `Type`, Pattern, Description, ParentId, ChargenDisplayType) VALUES ('Colour3', 2, 'colou?r3', '2nd Colour Variable', @colourchardef, NULL);

-- BMI

insert into Futureprogs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public, AcceptsAnyParameters) values ('GetBMI', 'Gets the BMI of a toon.', 'return (@ch.Weight / 1000) / ((@ch.Height/100) ^ 2)', 2, 'Core', 'Character', b'1', b'0');

set @bmiprog = LAST_INSERT_ID();

insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@bmiprog, 0, 4200, 'ch');

insert into Futureprogs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public, AcceptsAnyParameters) values ('IsObese', 'Determines if a toon has BMI >32.', 'return (@GetBMI(@ch) >= 32)', 4, 'Core', 'Character', b'1', b'0');

set @obeseprog = LAST_INSERT_ID();

insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@obeseprog, 0, 4200, 'ch');

insert into Futureprogs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public, AcceptsAnyParameters) values ('IsOverweight', 'Determines if a toon has BMI between 25 - 34.', 'var bmi as number
bmi = @GetBMI(@ch)
return (@Bmi >= 25 and @bmi < 34)', 4, 'Core', 'Character', b'1', b'0');

set @overweightprog = LAST_INSERT_ID();

insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@overweightprog, 0, 4200, 'ch');

insert into Futureprogs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public, AcceptsAnyParameters) values ('IsNormalWeight', 'Determines if a toon has BMI between 17 - 27.', 'var bmi as number
bmi = @GetBMI(@ch)
return (@bmi > 17 and @bmi < 27)', 4, 'Core', 'Character', b'1', b'0');

set @normalweightprog = LAST_INSERT_ID();

insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@normalweightprog, 0, 4200, 'ch');

insert into Futureprogs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public, AcceptsAnyParameters) values ('IsUnderweight', 'Determines if a toon has BMI <20.', 'return @GetBMI(@ch) < 20', 4, 'Core', 'Character', b'1', b'0');

set @underweightprog = LAST_INSERT_ID();

insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@underweightprog, 0, 4200, 'ch');

-- Person Word
INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsBoy', 'Determines if the character counts as a boy', 'return (@ch.Gender == ToGender("Male") and @ch.Age <= 14)', 4, 'Chargen', 'Age', 0);
set @isboyprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isboyprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsGirl', 'Determines if the character counts as a girl', 'return (@ch.Gender == ToGender("Female") and @ch.Age <= 14)', 4, 'Chargen', 'Age', 0);
set @isgirlprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isgirlprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsYoungMan', 'Determines if the character counts as a young man', 'return (@ch.Gender == ToGender("Male") and @ch.Age > 14 and @ch.Age < 25)', 4, 'Chargen', 'Age', 0);
set @isyoungmanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isyoungmanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsYoungWoman', 'Determines if the character counts as a young woman', 'return (@ch.Gender == ToGender("Female") and @ch.Age > 14 and @ch.Age < 25)', 4, 'Chargen', 'Age', 0);
set @isyoungwomanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isyoungwomanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsMan', 'Determines if the character counts as a man', 'return (@ch.Gender == ToGender("Male") and @ch.Age >= 25 and @ch.Age < 50)', 4, 'Chargen', 'Age', 0);
set @ismanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@ismanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsWoman', 'Determines if the character counts as a woman', 'return (@ch.Gender == ToGender("Female") and @ch.Age >= 25 and @ch.Age < 50)', 4, 'Chargen', 'Age', 0);
set @iswomanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@iswomanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsOldMan', 'Determines if the character counts as an old man', 'return (@ch.Gender == ToGender("Male") and @ch.Age >= 50 and @ch.Age < 70)', 4, 'Chargen', 'Age', 0);
set @isoldmanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isoldmanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsOldWoman', 'Determines if the character counts as an old woman', 'return (@ch.Gender == ToGender("Female") and @ch.Age >= 50 and @ch.Age < 70)', 4, 'Chargen', 'Age', 0);
set @isoldwomanprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isoldwomanprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsGeezer', 'Determines if the character counts as a geezer', 'return (@ch.Gender == ToGender("Male") and @ch.Age >= 70)', 4, 'Chargen', 'Age', 0);
set @isgeezerprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@isgeezerprog, 0, 4200, 'ch');

INSERT INTO FutureProgs (FunctionName, FunctionComment, FunctionText, ReturnType, Category, Subcategory, Public) VALUES ('IsCrone', 'Determines if the character counts as a crone', 'return (@ch.Gender == ToGender("Female") and @ch.Age >= 70)', 4, 'Chargen', 'Age', 0);
set @iscroneprog = LAST_INSERT_ID();
insert into Futureprogs_Parameters (FutureProgId, ParameterIndex, ParameterType, ParameterName) values (@iscroneprog, 0, 4200, 'ch');


-- Characteristic Values
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('emaciated', 'emaciated', b'0', 'abnormally thin and emaciated', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('gaunt', 'emaciated', b'0', 'lean and haggard, looking gaunt', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('lean', 'thin', b'0', 'of a lean, thin build', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very thin', 'emaciated', b'0', 'very thin frame, with not an ounce of fat', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('thin', 'thin', b'0', 'tends towards the thin side of a healthy frame', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('skinny', 'thin', b'0', 'of a very skinny build', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('lanky', 'thin', b'0', 'ungracefully tall and skinny', @humanoidframechardef, @underweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('well proportioned', 'normal', b'0', 'of an extremely fit and healthy build, being well proportioned in all respects', @humanoidframechardef, @normalweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('muscular', 'muscular', b'0', 'extremely fit looking, with well defined musculature', @humanoidframechardef, @normalweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('ripped', 'muscular', b'0', 'in every respect ripped, with showy, well-developed muscles', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bulky', 'muscular', b'0', 'bulky but muscular looking', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('normal', 'normal', b'0', 'of a perfectly ordinary build, with little excess fat or muscle and ordinary proportions', @humanoidframechardef, @normalweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('flabby', 'fat', b'0', 'flabby, with various pockets of loose, dangling skin', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('chubby', 'fat', b'0', 'a little heavier than normal, with chubby features and a small amount of excess fat', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('voluptuous', 'fat', b'0', 'large, but well proportioned', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('curvaceous', 'fat', b'0', 'shapely and of ample proportion, with well defined curves', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('curvy', 'fat', b'0', 'shapely and of ample proportion, with well defined curves', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('fat', 'fat', b'0', 'unambiguously fat, being too heavy for their frame', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('overweight', 'fat', b'0', 'a little overweight, with plenty of excess body fat', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pudgy', 'fat', b'0', 'fat in the face, or pudgy', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('obese', 'obese', b'0', 'grossly overweight, with significant extra fat all over the body', @humanoidframechardef, @obeseprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very fat', 'obese', b'0', 'very fat, in the obese range', @humanoidframechardef, @obeseprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('morbidly obese', 'obese', b'0', 'belarded by great, hanging sacks of fat', @humanoidframechardef, @obeseprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pot bellied', 'obese', b'0', 'in possession of an enormous, round pot belly', @humanoidframechardef, @obeseprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('barrel chested', 'fat', b'0', 'in possession of a huge barrel chest, on an otherwise large but muscular frame', @humanoidframechardef, @overweightprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('man', 'man', b'0', '', @personwordchardef, @ismanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('woman', 'woman', b'0', '', @personwordchardef, @iswomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('lad', 'boy', b'0', '', @personwordchardef, @isboyprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('boy', 'boy', b'0', '', @personwordchardef, @isboyprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('youth', 'boy', b'0', '', @personwordchardef, @isboyprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('young man', 'man', b'0', '', @personwordchardef, @isyoungmanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('gaffer', 'old man', b'0', '', @personwordchardef, @isgeezerprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('lass', 'girl', b'0', '', @personwordchardef, @isyoungwomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('girl', 'girl', b'0', '', @personwordchardef, @isgirlprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('young woman', 'girl', b'0', '', @personwordchardef, @isyoungwomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('maiden', 'woman', b'0', '', @personwordchardef, @isyoungwomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('crone', 'old woman', b'0', '', @personwordchardef, @iscroneprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('old woman', 'old woman', b'0', '', @personwordchardef, @isoldwomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('harridan', 'old woman', b'0', '', @personwordchardef, @iscroneprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('old man', 'old man', b'0', '', @personwordchardef, @isoldmanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('geezer', 'old man', b'0', '', @personwordchardef, @isoldmanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('spinster', 'old woman', b'0', '', @personwordchardef, @isoldwomanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('brute', 'man', b'0', '', @personwordchardef, @ismanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('guy', 'man', b'0', '', @personwordchardef, @ismanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('fellow', 'man', b'0', '', @personwordchardef, @ismanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('adolescent', 'young man', b'0', '', @personwordchardef, @isyoungmanprog);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('round', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('almond-shaped', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('slanted', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('beady', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('narrow', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('teardrop-shaped', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('sunken', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('droopy', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('hooded', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('close-set', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('deep-set', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('hollow', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('puffy', '', b'0', '', @eyeshapechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bald', 'none', b'0', '', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very short', 'very short', b'0', 'less than an inch or so in length', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('short', 'short', b'0', 'only a few inches in length', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('mid-length', 'mid-length', b'0', 'more than a few inches long', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('long', 'long', b'0', 'around ten inches long', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very long', 'very long', b'0', 'more than twenty inches long', @hairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('clean-shaven', 'none', b'0', '', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very short', 'very short', b'0', 'which is barely more than scratchy stubble', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('short', 'short', b'0', 'less than an inch long', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('mid-length', 'mid-length', b'0', 'a few inches long', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('long', 'long', b'0', 'more than a few inches long', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very long', 'very long', b'0', 'more than ten inches long', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bushy', 'bushy', b'0', 'which is a big, bushy tangle of significant length', @facialhairlengthchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('afro', 'afro-haired', b'0', 'a frizzy halo of hair', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('beehive', 'beehive-haired', b'0', 'a conical pile of hair in the shape of a beehive', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bob cut', 'bob-cut', b'0', 'bangs and an even bob cut', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bouffant', 'bouffant-styled', b'0', 'a puffed out, raised section of hair atop the head which hangs down on the sides', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bowl cut', 'bowl-cut', b'0', 'an all-around even haircut', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('braid', 'braided', b'0', 'hair woven into a tight braid', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bun', 'bun-haired', b'0', 'hair tied up into a bun atop the head', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pigtails', 'pigtailed', b'0', 'hair tied into two pig tails', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('ponytail', 'ponytailed', b'0', 'hair tied back into a ponytail', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('buzz cut', 'buzz-cut', b'0', 'closely cropped hair', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('chignon', 'chignon-haired', b'0', 'hair tied into a chingon bun', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('chonmage', 'chonmage-haired', b'0', 'a shaved pate, with longer back and sides', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('combover', 'comb-overed', b'0', 'thin hair combed over a bald spot', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('cornrows', 'corn-rowed', b'0', 'hair tied into thin, parallel rows of braids', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('crew cut', 'crew-cut', b'0', 'hair closely cropped but tapering longest to shortest from front to back', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('cropped cut', 'crop-haired', b'0', 'an all-around even haircut', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('curtain cut', 'curtain-haired', b'0', 'hair parted neatly in the center', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('dreadlocks', 'dreadlocked', b'0', 'combed into locked dreads', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('liberty spikes', 'liberty-spiked', b'0', 'clean, distinct spikes of hair', @hairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('clean shave', 'clean-shaven', b'0', '', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('handlebar moustache', 'handlebar-moustached', b'0', 'a moustache with lengthy and upwardly curved extremities', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('moustache', 'moustached', b'0', 'a naturally-styled moustache', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('goatee', 'goateed', b'0', 'a naturally-styled moustache and adjoining chin beard', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('beard', 'bearded', b'0', 'a full face beard', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('muttonchops', 'muttonchopped', b'0', 'sideburns extending well onto the jawline', @facialhairstylechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('white', 'caucasian', b'0', 'of light, caucasian tone', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('milky white', 'caucasian', b'0', 'of milky, pale white tone', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pale white', 'caucasian', b'0', 'of pale white tone', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pasty white', 'caucasian', b'0', 'of a pasty, pale white tone', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('tanned', 'caucasian', b'0', 'tanned a healthy brown colour', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('olive', 'mediterranian', b'0', 'of an olive complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('oriental', 'oriental', b'0', 'of an oriental complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('bronzed', 'caucasian', b'0', 'of a deep, bronze tone', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('dark olive', 'mediterranian', b'0', 'of a dark olive complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('light brown', 'brown', b'0', 'of a light brown complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('brown', 'brown', b'0', 'of a brown complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('dark brown', 'brown', b'0', 'of a dark brown complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('ebony', 'black', b'0', 'of a deep, ebony complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('black', 'black', b'0', 'of a deep, black complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('pale olive', 'oriental', b'0', 'of a pale olive complexion', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('ruddy', 'caucasian', b'0', 'of generally white complexion with areas of a ruddy red', @skintonechardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('', '0.9', b'0', '1.1', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('miniscule', '0', b'0', '0.25', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('tiny', '0.25', b'0', '0.5', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very short', '0.5', b'0', '0.7', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('short', '0.7', b'0', '0.9', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('tall', '1.1', b'0', '1.2', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('very tall', '1.2', b'0', '1.4', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('gigantic', '1.4', b'0', '4', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('colossal', '4', b'0', '10', @relativeheightchardef, NULL);
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) VALUES ('titanic', '10', b'0', '100000', @relativeheightchardef, NULL);

-- Colour Characteristics
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) SELECT Name, Id, b'0', NULL, @colourchardef, NULL FROM Colours Where (`Name` not like '%blonde%' and `Name` != 'salt-and-pepper' and `Name` != 'hazel');
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) SELECT Name, Id, b'0', NULL, @haircolourchardef, NULL FROM Colours Where (`Name` like '%blonde%');
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) SELECT Name, Id, b'0', NULL, @haircolourchardef, NULL FROM Colours Where (`Name` = 'salt-and-pepper');
INSERT INTO CharacteristicValues (`Name`, `Value`, `Default`, AdditionalValue, DefinitionId, FutureProgId) SELECT Name, Id, b'0', NULL, @eyecolourchardef, NULL FROM Colours Where (`Name` = 'hazel');

-- Standard "All" type profiles
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_colours', '<Definition/>', 'all', @colourchardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_frames', '<Definition/>', 'all', @humanoidframechardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_persons', '<Definition/>', 'all', @personwordchardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_eyeshapes', '<Definition/>', 'all', @eyeshapechardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_hairlengths', '<Definition/>', 'all', @hairlengthchardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_facialhairlengths', '<Definition/>', 'all', @facialhairlengthchardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_hairstyles', '<Definition/>', 'all', @hairstylechardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_facialhairstyles', '<Definition/>', 'all', @facialhairstylechardef, 'All Defined Colours');
INSERT INTO CharacteristicProfiles (`Name`, Definition, `Type`, TargetDefinitionId, Description) VALUES ('all_skintones', '<Definition/>', 'all', @skintonechardef, 'All Defined Colours');