//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureMUD_Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FutureMUD_Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF Core does not track changes to ICollection.Clear(), instead use Dbset.RemoveRange(...).
        /// </summary>
        internal static string EFCoreMigrationDescription {
            get {
                return ResourceManager.GetString("EFCoreMigrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICollection &apos;{0}&apos; on EF POCO &apos;{1}&apos;  incorrectly uses .Clear().
        /// </summary>
        internal static string EFCoreMigrationMessageFormat {
            get {
                return ResourceManager.GetString("EFCoreMigrationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICollection on EF POCO should not use .Clear().
        /// </summary>
        internal static string EFCoreMigrationTitle {
            get {
                return ResourceManager.GetString("EFCoreMigrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that all Effect types that are marked as saving effects have an associated method to register a loader for it.
        /// </summary>
        internal static string EffectSavingAnalyzerDescription {
            get {
                return ResourceManager.GetString("EffectSavingAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect type &apos;{0}&apos; is set to be a saving effect type but does not contain a static void method with no parameters called InitialiseEffectType.
        /// </summary>
        internal static string EffectSavingAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EffectSavingAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect type is set to be a saving effect type but does not contain a static void method with no parameters called InitialiseEffectType.
        /// </summary>
        internal static string EffectSavingAnalyzerTitle {
            get {
                return ResourceManager.GetString("EffectSavingAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that all FutureProg Statements register themselves with the FutureProg compiler.
        /// </summary>
        internal static string FutureProgStatementAnalyzerDescription {
            get {
                return ResourceManager.GetString("FutureProgStatementAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FutureProg Statement type &apos;{0}&apos; does not contain a static void method with no parameters named RegisterCompiler, which will be invoked to register it with the statement compiler.
        /// </summary>
        internal static string FutureProgStatementAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("FutureProgStatementAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FutureProg Statement type does not implement required static field for registering compiler via reflection.
        /// </summary>
        internal static string FutureProgStatementAnalyzerTitle {
            get {
                return ResourceManager.GetString("FutureProgStatementAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that all concrete GameItemComponentProtos register a loader and builder loader.
        /// </summary>
        internal static string GameItemComponentProtoAnalyzerDescription {
            get {
                return ResourceManager.GetString("GameItemComponentProtoAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameItemComponentProto type &apos;{0}&apos; does not contain a static method with a GameItemComponentManager parameter called RegisterComponentInitialiser, which will be invoked to register a method to load items components of its type.
        /// </summary>
        internal static string GameItemComponentProtoAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("GameItemComponentProtoAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameItemComponentProto type does not implement required static field for registering loader via reflection.
        /// </summary>
        internal static string GameItemComponentProtoAnalyzerTitle {
            get {
                return ResourceManager.GetString("GameItemComponentProtoAnalyzerTitle", resourceCulture);
            }
        }
    }
}
