using System;
using System.Collections.Generic;
using System.Linq;

#nullable enable

namespace MudSharp.Economy.Employment;

public enum EmploymentActionCategory
{
	Planning,
	Authorisation,
	Logistics,
	Purchasing,
	Production,
	Communication,
	Administration
}

public enum EmploymentActionCatalogStatus
{
	Executable,
	AuditOnlyShell,
	Deferred
}

[Flags]
public enum EmploymentActionInvocationSource
{
	ManualTask = 1,
	ScheduledRule = 2,
	ManagerGoal = 4,
	HostSystem = 8,
	All = ManualTask | ScheduledRule | ManagerGoal | HostSystem
}

public sealed record EmploymentActionDefinition(
	string Key,
	EmploymentActionCategory Category,
	string Syntax,
	EmploymentActionCatalogStatus Status,
	EmploymentActionStepType? StepType,
	EmploymentAuthoritySet RequiredAuthority,
	IReadOnlySet<EmploymentAICapability> RequiredCapabilities,
	bool RequiresPaymentAuthorisation,
	bool IsFinancial,
	EmploymentActionInvocationSource InvocationSources,
	string Summary,
	IReadOnlyCollection<string>? Aliases = null,
	string? DeferredReason = null);

public static class EmploymentActionCatalog
{
	private static readonly EmploymentActionDefinition[] Definitions =
	[
		Executable("getid", EmploymentActionCategory.Logistics,
			"tasks step getid <quantity> <prototype ids|*item ids...> from <here|cell ids...>",
			EmploymentActionStepType.GetItemsById,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Collects a quantity of items matching one or more item prototype IDs.",
			Aliases("id", "prototype")),
		Executable("gettag", EmploymentActionCategory.Logistics,
			"tasks step gettag <quantity> <&tag id|&tag name> from <here|cell ids...>",
			EmploymentActionStepType.GetItemsByTag,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Collects a quantity of items matching a verified item tag.",
			Aliases("tag")),
		Executable("commodity", EmploymentActionCategory.Logistics,
			"tasks step commodity <weight> <material> [tag <&tag id|&tag name>] from <here|cell ids...> [char <name>=<value> ...]",
			EmploymentActionStepType.GetCommodity,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Collects a commodity weight by material, optional verified tag, and optional characteristics.",
			Aliases("material")),
		Executable("deliver", EmploymentActionCategory.Logistics,
			"tasks step deliver to <here|cell id> [container <prototype id|*item id|&tag|keyword>]",
			EmploymentActionStepType.DeliverItems,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Delivers all carried task items to a destination, optionally into a container.",
			Aliases("delivery")),
		Executable("stocktransfer", EmploymentActionCategory.Logistics,
			"tasks step stocktransfer to <shop id|name|self> merch <target merchandise id|name> [destination <here|cell id>] [container <prototype id|*item id|&tag|keyword>]",
			EmploymentActionStepType.ShopStockTransfer,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Delivers carried source-shop stock into a permanent shop destination and retags it through native shop stock records.",
			Aliases("transferstock", "stockmove")),
		Executable("auctionlist", EmploymentActionCategory.Administration,
			"tasks step auctionlist <prototype id|*item id|&tag|keyword> reserve <amount> [buyout <amount>] [duration <timespan>]",
			EmploymentActionStepType.AuctionLotListing,
			EmploymentAuthority.ManageStockRules,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Lists a carried task-custody item as an auction-house-owned lot through the native auction house.",
			Aliases("lotlist", "listauction")),
		Executable("auctionsettle", EmploymentActionCategory.Administration,
			"tasks step auctionsettle due OR auctionsettle lot <asset id|keyword>",
			EmploymentActionStepType.AuctionSettlement,
			EmploymentAuthority.SettleHostAccounts,
			Caps(EmploymentAICapability.CanUseBankAccount),
			"Settles due auction lots through the native auction house result, payout, refund, and unclaimed-item records.",
			Aliases("settleauction", "lotsettle"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("auctionclaim", EmploymentActionCategory.Logistics,
			"tasks step auctionclaim <asset id|keyword>",
			EmploymentActionStepType.AuctionClaim,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Claims an unclaimed movable auction lot into task custody for normal delivery steps.",
			Aliases("claimauction", "lotclaim")),
		Executable("arenaevent", EmploymentActionCategory.Administration,
			"tasks step arenaevent create <event type id|name> at <date/time> OR arenaevent phase <event id|name> <state> OR arenaevent abort <event id|name> <reason>",
			EmploymentActionStepType.ArenaEventAdministration,
			EmploymentAuthority.CreateScheduledRules | EmploymentAuthority.ModifyScheduledRules,
			Caps(),
			"Creates, advances, or aborts native combat arena events through the arena lifecycle services.",
			Aliases("event", "arenaadmin", "arenaeventadmin")),
		Executable("bankadmin", EmploymentActionCategory.Administration,
			"tasks step bankadmin reserve audit|deposit <amount>|withdraw <amount> OR bankadmin account credit <account> <amount> for <reason>|status <account> <active|suspended|locked> [reason]|close <account> <reason> OR bankadmin branch post <here|cell id> <note>|courier <from> to <to> <note>",
			EmploymentActionStepType.BankAdministration,
			EmploymentAuthority.DepositBusinessCash | EmploymentAuthority.WithdrawBusinessCash | EmploymentAuthority.UseStoreAccount | EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanUseBankAccount, EmploymentAICapability.CanHandleCash, EmploymentAICapability.CanDeliverItems),
			"Performs native bank reserve, account-service, and branch-evidence tasks for a bank employment host.",
			Aliases("bank", "bankreserve", "bankaccount")),
		Executable("load", EmploymentActionCategory.Logistics,
			"tasks step load all into <prototype id|*item id|&tag|keyword> [at <here|cell id>]",
			EmploymentActionStepType.LoadItems,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Uses inventory plans to load all carried task items into a container or accessible cargo projection.",
			Aliases("loaditems")),
		Executable("unload", EmploymentActionCategory.Logistics,
			"tasks step unload <prototype id|*item id|&tag|keyword> [at <here|cell id>]",
			EmploymentActionStepType.UnloadItems,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Uses inventory plans to retrieve previously task-loaded items from a container or cargo projection.",
			Aliases("unloaditems")),
		Executable("return", EmploymentActionCategory.Logistics,
			"tasks step return container <prototype id|*item id|&tag|keyword> to <here|cell id> [container <prototype id|*item id|&tag|keyword>]",
			EmploymentActionStepType.ReturnAsset,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Uses inventory plans to carry and return a reusable container; vehicle and animal return remain separate follow-ups.",
			Aliases("returncontainer")),
		Executable("vehicle", EmploymentActionCategory.Logistics,
			"tasks step vehicle assign <vehicle id|exterior item id> OR vehicle cargo <vehicle id|exterior item id> <cargo id|cargo name>",
			EmploymentActionStepType.VehicleOperation,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanUseVehicles),
			"Assigns a reachable vehicle to the driver for an employment task or validates an accessible vehicle cargo-space selection without autonomous driving.",
			Aliases("cargo")),
		Executable("animal", EmploymentActionCategory.Logistics,
			"tasks step animal lead <mount id|name> to <here|cell id> OR animal ride <mount id|name> OR animal lodge <mount id|name> at <stable id|name> OR animal return <stay id> from <stable id|name> [waive]",
			EmploymentActionStepType.StableAnimalOperation,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanManageStableAnimals),
			"Records animal leading plans and executes native mount, stable lodge, and stable return operations.",
			Aliases("mount", "stableanimal")),
		Executable("stableadmin", EmploymentActionCategory.Administration,
			"tasks step stableadmin care <inspect|feed|groom|exercise> <stay id> <note> OR stableadmin fees <all|stay id> [note] OR stableadmin stay <stay id> <note> OR stableadmin account <account id|name> <note>",
			EmploymentActionStepType.StableAdministration,
			EmploymentAuthority.ManageDeliveryRoutes | EmploymentAuthority.UseStoreAccount,
			Caps(EmploymentAICapability.CanManageStableAnimals),
			"Records stable care/reconciliation evidence and invokes native stable fee assessment where supported.",
			Aliases("stablecare", "stablereconcile")),
		Executable("hoteladmin", EmploymentActionCategory.Administration,
			"tasks step hoteladmin room <inspect|clean|ready|maintenance> <room id|name|here> <note> OR hoteladmin lost check [note]|audit <lost #> <note> OR hoteladmin balance <patron id|name> <note>",
			EmploymentActionStepType.HotelAdministration,
			EmploymentAuthority.ManageDeliveryRoutes | EmploymentAuthority.UseStoreAccount,
			Caps(EmploymentAICapability.CanManageHotelRooms),
			"Records hotel room, lost-property, and patron-balance evidence and invokes native lost-property expiry checks where supported.",
			Aliases("hotelroom", "hotelreconcile")),
		Executable("hospitalservice", EmploymentActionCategory.Administration,
			"tasks step hospitalservice <request id>",
			EmploymentActionStepType.HospitalService,
			EmploymentAuthority.PerformMedicalServices,
			Caps(EmploymentAICapability.CanPerformMedicalServices),
			"Performs a queued hospital service request through the native medical-service runner.",
			Aliases("medicalservice", "treatpatient", "hospitaltreat")),
		Executable("hospitalprep", EmploymentActionCategory.Administration,
			"tasks step hospitalprep <request id>",
			EmploymentActionStepType.HospitalPatientPreparation,
			EmploymentAuthority.PerformMedicalServices,
			Caps(EmploymentAICapability.CanPerformMedicalServices),
			"Moves a queued hospital patient to the reserved treatment theatre before supplies or service execution.",
			Aliases("hospitalpatient", "medicalprep", "patientprep")),
		Executable("hospitalsupply", EmploymentActionCategory.Logistics,
			"tasks step hospitalsupply <request id>",
			EmploymentActionStepType.HospitalSupplyPreparation,
			EmploymentAuthority.PrepareMedicalSupplies,
			Caps(EmploymentAICapability.CanPrepareHospitalSupplies),
			"Collects configured hospital service supplies from a supply room and delivers them to the reserved theatre.",
			Aliases("medicalsupply", "prepareprocedure", "proceduresupply")),
		Executable("hospitaladmin", EmploymentActionCategory.Administration,
			"tasks step hospitaladmin service|debt|theatre|supply|request <note>",
			EmploymentActionStepType.HospitalAdministration,
			EmploymentAuthority.ManageMedicalServices | EmploymentAuthority.ManageHospitalAccounts | EmploymentAuthority.ManageHospitalFacilities,
			Caps(EmploymentAICapability.CanPerformMedicalServices),
			"Records hospital service, debt, theatre, supply, and request audit evidence.",
			Aliases("hospitalaudit", "medicaladmin")),
		Executable("move", EmploymentActionCategory.Logistics,
			"tasks step move to <here|cell id>",
			EmploymentActionStepType.MoveOrDeliver,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Moves to the target location and completes there."),
		Executable("board", EmploymentActionCategory.Communication,
			"tasks step board <title> = <text>",
			EmploymentActionStepType.BoardPost,
			EmploymentAuthority.PostToHostBoard,
			Caps(EmploymentAICapability.CanPostToBoard),
			"Posts a notice to the host staff communication board.",
			Aliases("post")),
		Executable("command", EmploymentActionCategory.Communication,
			"tasks step command [at <here|cell id>] <command> [arguments...]",
			EmploymentActionStepType.Command,
			EmploymentAuthority.AssignTasks,
			Caps(EmploymentAICapability.CanExecuteCommandTask),
			"Executes an allowlisted command, optionally at a target location."),
		Executable("report", EmploymentActionCategory.Communication,
			"tasks step report <text>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.AssignTasks,
			Caps(),
			"Records a report-style action in the employment register and durable task state."),
		Executable("supplier", EmploymentActionCategory.Planning,
			"tasks step supplier <quantity> <merchandise id|name> from <shop id|name|any> [max <amount>] [keyword <keywords>] OR tasks step supplier <quantity> item <prototype id|*item id|&tag|keyword> from <shop id|name|any> [max <amount>] OR tasks step supplier <weight> commodity <descriptor> from <shop id|name|any> [max <amount>]",
			EmploymentActionStepType.SupplierSelection,
			EmploymentAuthority.ManageStockRules,
			Caps(EmploymentAICapability.CanPurchaseCommodities),
			"Finds the cheapest currently stocked supplier target using the native purchase resolver and records supplier, merchandise, price, and location evidence.",
			Aliases("findsupplier", "suppliercheck", "source")),
		Executable("purchase", EmploymentActionCategory.Purchasing,
			"tasks step purchase <quantity> <merchandise id|name> from <shop id|name|any> [max <amount>] [keyword <keywords>] OR purchase <quantity> item <prototype id|*item id|&tag|keyword> from <shop id|name|any> [max <amount>] OR purchase <weight> commodity <descriptor> from <shop id|name|any> [max <amount>]",
			EmploymentActionStepType.Purchase,
			EmploymentAuthority.ApprovePurchases,
			Caps(EmploymentAICapability.CanPurchaseCommodities),
			"Buys stocked merchandise, item selectors, or commodity descriptors through the native shop transaction system using employer authorisation and reserved funds.",
			Aliases("buy"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("bankdeposit", EmploymentActionCategory.Purchasing,
			"tasks step bankdeposit <amount>",
			EmploymentActionStepType.BankDeposit,
			EmploymentAuthority.DepositBusinessCash,
			Caps(EmploymentAICapability.CanUseBankAccount, EmploymentAICapability.CanHandleCash),
			"Moves employer virtual cash into the linked native bank account and records employment audit evidence.",
			Aliases("deposit"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("bankwithdraw", EmploymentActionCategory.Purchasing,
			"tasks step bankwithdraw <amount>",
			EmploymentActionStepType.BankWithdrawal,
			EmploymentAuthority.WithdrawBusinessCash,
			Caps(EmploymentAICapability.CanUseBankAccount, EmploymentAICapability.CanHandleCash),
			"Moves linked native bank funds into employer virtual cash and records employment audit evidence.",
			Aliases("withdraw", "bankwithdrawal"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("transfer", EmploymentActionCategory.Purchasing,
			"tasks step transfer <amount> to <bank account id|bankcode:account|alias>",
			EmploymentActionStepType.AccountTransfer,
			EmploymentAuthority.UseStoreAccount,
			Caps(EmploymentAICapability.CanUseBankAccount),
			"Transfers funds from the employer linked native bank account to another native bank account with paired transfer records.",
			Aliases("banktransfer", "accounttransfer"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("settle", EmploymentActionCategory.Purchasing,
			"tasks step settle <amount> to <host type> <id|name>",
			EmploymentActionStepType.HostSettlement,
			EmploymentAuthority.SettleHostAccounts,
			Caps(EmploymentAICapability.CanUseBankAccount),
			"Settles same-currency funds from this employment host to another supported employment host using native finance records.",
			Aliases("hostsettle", "settlement"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("storepay", EmploymentActionCategory.Purchasing,
			"tasks step storepay <shop id|name> account <account id|name> amount <amount>",
			EmploymentActionStepType.StoreAccountPayment,
			EmploymentAuthority.UseStoreAccount,
			Caps(EmploymentAICapability.CanPurchaseCommodities),
			"Pays down a native shop line-of-credit account using employer authorisation and reserved funds.",
			Aliases("storeaccount", "accountpay"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("paytax", EmploymentActionCategory.Purchasing,
			"tasks step paytax <amount|all>",
			EmploymentActionStepType.TaxPayment,
			EmploymentAuthority.PayTaxes,
			Caps(EmploymentAICapability.CanUseBankAccount),
			"Pays supported host taxes through the native tax pathway using employer authorisation and reserved funds.",
			Aliases("tax", "taxpay"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("payroll", EmploymentActionCategory.Purchasing,
			"tasks step payroll settle <all|#payable> [reason]",
			EmploymentActionStepType.PayrollSettlement,
			EmploymentAuthority.ManagePayroll,
			Caps(EmploymentAICapability.CanUseBankAccount, EmploymentAICapability.CanHandleCash),
			"Settles accrued employment wage payables through the native payroll pathway using employer authorisation and available funds.",
			Aliases("wages", "payables"),
			isFinancial: true),
		Executable("float", EmploymentActionCategory.Purchasing,
			"tasks step float fill|skim <amount> [register <prototype|*item|&tag|keyword>]",
			EmploymentActionStepType.ShopFloatAdjustment,
			EmploymentAuthority.WithdrawBusinessCash,
			Caps(EmploymentAICapability.CanHandleCash),
			"Maintains permanent-shop register float by filling from employer virtual funds or skimming to virtual funds.",
			Aliases("cashfloat"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("physicalfloat", EmploymentActionCategory.Purchasing,
			"tasks step physicalfloat issue <amount> from <bank|register|container selector> OR physicalfloat return <amount|all> to <bank|register|container selector> OR physicalfloat settle <amount|all>",
			EmploymentActionStepType.PhysicalFloat,
			EmploymentAuthority.WithdrawBusinessCash,
			Caps(EmploymentAICapability.CanHandleCash),
			"Issues, returns, or settles employer physical currency as durable task-custody cash.",
			Aliases("cashtrip", "employeefloat"),
			requiresPaymentAuthorisation: true,
			isFinancial: true),
		Executable("craft", EmploymentActionCategory.Production,
			"tasks step craft <craft id|craft name>",
			EmploymentActionStepType.CraftTrigger,
			EmploymentAuthority.ManageCraftRules,
			Caps(EmploymentAICapability.CanCraft),
			"Starts or resumes a native craft, waits for completion, and adopts item outputs into task custody."),
		Executable("station", EmploymentActionCategory.Production,
			"tasks step station <craft station selector|here>",
			EmploymentActionStepType.CraftStation,
			EmploymentAuthority.ManageCraftRules,
			Caps(EmploymentAICapability.CanCraft),
			"Validates the worker is at a craft station or selected workshop location before later craft steps use it."),
		Executable("inspect", EmploymentActionCategory.Production,
			"tasks step inspect <inspection note>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageCraftRules,
			Caps(EmploymentAICapability.CanCraft),
			"Records a quality-control inspection note against the worker's current task-custody items.",
			Aliases("qc", "quality")),
		Executable("batch", EmploymentActionCategory.Production,
			"tasks step batch demand <target> storage <capacity> size <quantity> <rationale>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageCraftRules,
			Caps(EmploymentAICapability.CanCraft),
			"Records a demand- and storage-aware production batch plan and rejects oversized batches.",
			Aliases("batchsize", "sizing")),
		Executable("authorise", EmploymentActionCategory.Authorisation,
			"tasks step authorise [<amount> for] <description>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ApprovePurchases,
			Caps(),
			"Records a durable auditable manager authorisation note for later financial steps in the same active task.",
			Aliases("authorize"),
			isFinancial: true),
		Executable("reserve", EmploymentActionCategory.Authorisation,
			"tasks step reserve [<amount> for] <description>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageStockRules,
			Caps(),
			"Creates a durable employer-funds reservation for later financial steps in the same active task.",
			isFinancial: true),
		Executable("release", EmploymentActionCategory.Authorisation,
			"tasks step release [reservation <id>|all]",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageStockRules,
			Caps(),
			"Releases durable employer-funds reservations for the same active task.",
			isFinancial: true),
		Executable("select", EmploymentActionCategory.Planning,
			"tasks step select <description>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(),
			"Records a durable source, destination, supplier, container, or vehicle selection note."),
		Executable("estimate", EmploymentActionCategory.Planning,
			"tasks step estimate <description>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.AssignTasks,
			Caps(),
			"Records a durable estimated cost, route, stock, or timing note."),
		Executable("route", EmploymentActionCategory.Planning,
			"tasks step route to <here|cell id> [then <here|cell id> ...] [description]",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Records a durable ordered route plan and completes only when the worker can reach every route stop."),
		Executable("routebatch", EmploymentActionCategory.Logistics,
			"tasks step routebatch total <quantity> each <quantity> to <here|cell id> [then <here|cell id> ...] <rationale>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Records a durable multi-stop delivery batch allocation against ordered route stops.",
			Aliases("deliverybatch", "multistop")),
		Executable("tripcheck", EmploymentActionCategory.Logistics,
			"tasks step tripcheck fuel <policy> feed <policy> maintenance <policy> rest <policy> [to <here|cell id> [then <here|cell id> ...]] <rationale>",
			EmploymentActionStepType.CataloguedShell,
			EmploymentAuthority.ManageDeliveryRoutes,
			Caps(EmploymentAICapability.CanDeliverItems),
			"Records a durable fuel, feed, maintenance, and rest policy check for a transport assignment.",
			Aliases("routepolicy", "logisticspolicy", "logisticscheck")),
		Executable("cashreconcile", EmploymentActionCategory.Administration,
			"tasks step cashreconcile [note]",
			EmploymentActionStepType.ShopCashReconciliation,
			EmploymentAuthority.WithdrawBusinessCash | EmploymentAuthority.DepositBusinessCash,
			Caps(EmploymentAICapability.CanHandleCash),
			"Snapshots shop virtual cash, physical same-currency float, expected float, runs native CheckFloat, and records reconciliation evidence.",
			Aliases("reconcilecash", "cashcheck", "tillcheck")),		Executable("stocktake", EmploymentActionCategory.Administration,
			"tasks step stocktake all OR tasks step stocktake merch <id|name>",
			EmploymentActionStepType.ShopStocktake,
			EmploymentAuthority.ManageStockRules,
			Caps(),
			"Calls native shop stocktake routines for all merchandise or one merchandise entry and records count/weight evidence.",
			Aliases("stockcount", "inventorycount")),
		Executable("price", EmploymentActionCategory.Administration,
			"tasks step price merch <id|name> <amount>",
			EmploymentActionStepType.PriceChange,
			EmploymentAuthority.AdjustPrices,
			Caps(EmploymentAICapability.CanManagePrices),
			"Changes exact shop merchandise base prices. Employment market-influence mutation is deprecated and quarantined on load.",
			Aliases("pricing")),
		Executable("sale", EmploymentActionCategory.Administration,
			"tasks step sale create <name> target all|merchandise <which>|tag <which> adjustment <signed %> [type sale|volume <quantity>] [applies sell|buy|both] [eligibility none|<prog>] [cumulative true|false] [expires never|<datetime|duration>] OR tasks step sale modify <deal id|name> target ... adjustment ... OR tasks step sale cancel <deal id|name>",
			EmploymentActionStepType.ShopDealAdministration,
			EmploymentAuthority.AdjustPrices,
			Caps(EmploymentAICapability.CanManagePrices),
			"Creates, modifies, or cancels native shop deals, including temporary sales and volume deals, without mutating regional market influences.",
			Aliases("deal", "shopdeal")),
		Executable("jobopening", EmploymentActionCategory.Administration,
			"tasks step jobopening create ... OR tasks step jobopening close <#opening> [reason] OR tasks step jobopening modify <#opening> ...",
			EmploymentActionStepType.JobOpeningAdministration,
			EmploymentAuthority.CreateJobOpenings,
			Caps(),
			"Creates, closes, or modifies employment openings using durable job-opening definitions; market-rate pay clauses require min <amount>.",
			Aliases("opening", "job")),
		Executable("rule", EmploymentActionCategory.Administration,
			"tasks step rule pause|resume|cancel <#|name|id> [reason] OR tasks step rule evaluate <#|name|id> [manual <key>]",
			EmploymentActionStepType.ScheduledRuleAdministration,
			EmploymentAuthority.ModifyScheduledRules,
			Caps(),
			"Pauses, resumes, cancels, or evaluates an existing scheduled rule through the host task board with audit evidence.",
			Aliases("scheduledrule", "schedulerule")),
		Executable("admintask", EmploymentActionCategory.Administration,
			"tasks step admintask retry|requeue|cancel <#|name|id> [reason] OR tasks step admintask assign <#|name|id> to <employee id|name> [reason]",
			EmploymentActionStepType.ActiveTaskAdministration,
			EmploymentAuthority.AssignTasks | EmploymentAuthority.CancelTasks,
			Caps(),
			"Retries, requeues, assigns, or cancels existing active tasks through the host task board with custody safeguards.",
			Aliases("taskadmin", "taskctl")),
		Executable("goal", EmploymentActionCategory.Administration,
			"tasks step goal evaluate|cancel|reactivate <#|type|description> [reason]",
			EmploymentActionStepType.ManagerGoalAdministration,
			EmploymentAuthority.ModifyManagerGoals,
			Caps(),
			"Evaluates, cancels, or reactivates an existing manager goal through the host goal board with audit evidence.",
			Aliases("managergoal", "goaladmin")),
		Deferred("marktask", EmploymentActionCategory.Administration,
			"tasks step marktask <blocked|failed|completed> <task>",
			EmploymentAuthority.CancelTasks,
			"Task state mutation from inside tasks is deferred to keep audit and dispatcher ownership clear.")
	];

	private static readonly Dictionary<string, EmploymentActionDefinition> Lookup =
		Definitions
			.SelectMany(x => new[] { x.Key }.Concat(x.Aliases ?? Array.Empty<string>())
				.Select(alias => (Alias: alias, Definition: x)))
			.ToDictionary(x => x.Alias, x => x.Definition, StringComparer.InvariantCultureIgnoreCase);

	public static IReadOnlyCollection<EmploymentActionDefinition> All => Definitions;

	public static IReadOnlyCollection<EmploymentActionCategory> Categories =>
		Definitions
			.Select(x => x.Category)
			.Distinct()
			.OrderBy(x => x)
			.ToList();

	public static EmploymentActionDefinition? Get(string keyOrAlias)
	{
		return Lookup.GetValueOrDefault(keyOrAlias);
	}

	public static IReadOnlyCollection<EmploymentActionDefinition> ForCategory(string categoryOrAlias)
	{
		if (!Enum.TryParse<EmploymentActionCategory>(categoryOrAlias, true, out var category))
		{
			return Array.Empty<EmploymentActionDefinition>();
		}

		return Definitions
		       .Where(x => x.Category == category)
		       .OrderBy(x => x.Key)
		       .ToList();
	}

	public static EmploymentActionDefinition? ForStepType(EmploymentActionStepType stepType)
	{
		return Definitions.FirstOrDefault(x => x.StepType == stepType && x.Status != EmploymentActionCatalogStatus.Deferred);
	}

	private static EmploymentActionDefinition Executable(string key, EmploymentActionCategory category, string syntax,
		EmploymentActionStepType stepType, EmploymentAuthority authority,
		IReadOnlySet<EmploymentAICapability> requiredCapabilities, string summary,
		IReadOnlyCollection<string>? aliases = null, bool requiresPaymentAuthorisation = false,
		bool isFinancial = false,
		EmploymentActionInvocationSource invocationSources = EmploymentActionInvocationSource.All)
	{
		return new EmploymentActionDefinition(
			key,
			category,
			syntax,
			EmploymentActionCatalogStatus.Executable,
			stepType,
			authority,
			requiredCapabilities,
			requiresPaymentAuthorisation,
			isFinancial,
			invocationSources,
			summary,
			aliases);
	}

	private static IReadOnlySet<EmploymentAICapability> Caps(params EmploymentAICapability[] capabilities)
	{
		return new HashSet<EmploymentAICapability>(capabilities);
	}

	private static IReadOnlyCollection<string> Aliases(params string[] aliases)
	{
		return aliases;
	}

	private static EmploymentActionDefinition AuditOnly(string key, EmploymentActionCategory category, string syntax,
		EmploymentActionStepType stepType, EmploymentAuthority authority,
		IReadOnlySet<EmploymentAICapability> requiredCapabilities, string summary,
		IReadOnlyCollection<string>? aliases = null, bool requiresPaymentAuthorisation = false, bool isFinancial = false,
		EmploymentActionInvocationSource invocationSources = EmploymentActionInvocationSource.All)
	{
		return new EmploymentActionDefinition(
			key,
			category,
			syntax,
			EmploymentActionCatalogStatus.AuditOnlyShell,
			stepType,
			authority,
			requiredCapabilities,
			requiresPaymentAuthorisation,
			isFinancial,
			invocationSources,
			summary,
			aliases);
	}

	private static EmploymentActionDefinition Deferred(string key, EmploymentActionCategory category, string syntax,
		EmploymentAuthority authority, string deferredReason,
		IReadOnlySet<EmploymentAICapability>? requiredCapabilities = null, bool isFinancial = false)
	{
		return new EmploymentActionDefinition(
			key,
			category,
			syntax,
			EmploymentActionCatalogStatus.Deferred,
			null,
			authority,
			requiredCapabilities ?? new HashSet<EmploymentAICapability>(),
			false,
			isFinancial,
			EmploymentActionInvocationSource.ManualTask,
			deferredReason,
			null,
			deferredReason);
	}
}
