#nullable enable

using MudSharp.Body;
using MudSharp.GameItems;
using System.Collections.Generic;

namespace DatabaseSeeder.Seeders;

public partial class AnimalSeeder
{
    private static IEnumerable<AnimalRaceTemplate> GetMammalRaceTemplates()
    {
        static AnimalRaceTemplate Mammal(
            string name,
            string adjective,
            string bodyKey,
            SizeCategory size,
            double health,
            string model,
            string ageProfile,
            string loadout,
            AnimalDescriptionPack pack,
            string? description = null,
            bool canClimb = false,
            string? bloodProfile = null,
            IReadOnlyList<AnimalBodypartUsageTemplate>? usages = null,
            string combatStrategyKey = "Beast Brawler")
        {
            return new AnimalRaceTemplate(
                name,
                adjective,
                description,
                bodyKey,
                size,
                canClimb,
                health,
                model,
                model,
                ageProfile,
                loadout,
                pack,
                true,
                AnimalBreathingMode.Simple,
                bloodProfile,
                bodyKey switch
                {
                    "Ungulate" => "ungulate",
                    "Toed Quadruped" => "toed-quadruped",
                    _ => null
                },
                usages,
                combatStrategyKey
            );
        }

        List<AnimalBodypartUsageTemplate> udder = new()
        { new("udder", "female") };
        List<AnimalBodypartUsageTemplate> hornedMale = new()
        { new("rhorn", "male"), new("lhorn", "male") };
        List<AnimalBodypartUsageTemplate> hornedFemale = new()
        { new("udder", "female"), new("rhorn", "male"), new("lhorn", "male") };
        List<AnimalBodypartUsageTemplate> antlered = new()
        { new("udder", "female"), new("rantler", "male"), new("lantler", "male") };
        List<AnimalBodypartUsageTemplate> antleredGeneral = new()
        { new("udder", "female"), new("rantler", "general"), new("lantler", "general") };
        List<AnimalBodypartUsageTemplate> tuskedMale = new()
        { new("rtusk", "male"), new("ltusk", "male") };
        List<AnimalBodypartUsageTemplate> tuskedGeneral = new()
        { new("rtusk", "general"), new("ltusk", "general") };
        List<AnimalBodypartUsageTemplate> rhinoHorn = new()
        { new("udder", "female"), new("horn", "general") };

        yield return Mammal("Rabbit", "Leporine", "Toed Quadruped", SizeCategory.VerySmall, 0.3, "Lagomorph",
            "tiny-fast", "small-herbivore",
            MammalPack("a rabbit kit", "a young buck rabbit", "a young doe rabbit", "a buck rabbit", "a doe rabbit",
                "It has soft fur, large ears and quick, spring-loaded hindlegs.",
                "Its wide-set eyes and alert ears leave it looking permanently watchful.",
                "It looks ready to bolt at the first hint of danger.",
                "burrows, hedgerows and open grassland"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Hare", "Hare", "Toed Quadruped", SizeCategory.VerySmall, 0.5, "Lagomorph",
            "tiny-fast", "small-herbivore",
            MammalPack("a leveret", "a young jack hare", "a young jill hare", "a jack hare", "a jill hare",
                "It is long-limbed and lean, with oversized ears and a rangier frame than a rabbit.",
                "Its powerful hindquarters look built for explosive speed across open ground.",
                "It stands tense and light on its feet, as if made to run.",
                "heath, scrub and open country"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Beaver", "Beaver", "Toed Quadruped", SizeCategory.Small, 0.8, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a beaver kit", "a young male beaver", "a young female beaver", "a male beaver", "a female beaver",
                "It is stocky and brown-furred, with a broad flat tail and heavy incisors.",
                "Its teeth and webbed feet betray a life of gnawing timber and working in water.",
                "It has the purposeful, busy air of a tireless builder.",
                "riverbanks and quiet waterways"));
        yield return Mammal("Otter", "Otter", "Toed Quadruped", SizeCategory.VerySmall, 0.5, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("an otter pup", "a young male otter", "a young female otter", "a male otter", "a female otter",
                "It has sleek waterproof fur, a long body and quick webbed paws.",
                "Its whiskered muzzle and supple frame suit it to swift hunting in water.",
                "It moves with playful grace and easy confidence.",
                "rivers, marshes and sheltered coasts"),
            combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Dog", "Canine", "Toed Quadruped", SizeCategory.Small, 0.8, "Small Canid",
            "standard-mammal", "doglike",
            MammalPack("a puppy", "a young dog", "a young dog", "a dog", "a bitch",
                "It has a compact, muscular frame, keen nose and a coat that varies by breed.",
                "Its bright eyes and alert ears give it an eager, highly social look.",
                "It carries itself with the curious, companionable energy of a domestic hunter.",
                "farmsteads, roads and human settlements") with
            { AddDogBreedDescriptions = true },
            "Common domestic dogs", bloodProfile: "canine");
        yield return Mammal("Cat", "Feline", "Toed Quadruped", SizeCategory.Small, 0.5, "Domestic Cat",
            "standard-mammal", "cat",
            MammalPack("a kitten", "a young tomcat", "a young cat", "a tomcat", "a cat",
                "It is compact and graceful, with a supple spine and soft fur.",
                "Its eyes are bright, its whiskers keen and its paws are armed with fine retractile claws.",
                "It has the poised, self-contained air of a patient little predator.",
                "hearths, rooftops and the edges of human habitation") with
            { UseCatCoatDescriptions = true },
            "Common domestic cats", bloodProfile: "feline");
        yield return Mammal("Wolf", "Lupine", "Toed Quadruped", SizeCategory.Normal, 1.0, "Large Canid",
            "standard-mammal", "wolfpack",
            MammalPack("a wolf pup", "a young male wolf", "a young female wolf", "a male wolf", "a female wolf",
                "It is long-legged and powerfully built, with a deep chest and thick grey coat.",
                "Its heavy jaws, triangular ears and keen eyes make it look every inch a pack hunter.",
                "It carries itself with wary confidence and relentless focus.",
                "forest, tundra and broken wilderness"),
            "Wild grey wolves", bloodProfile: "canine");
        yield return Mammal("Fox", "Vulpine", "Toed Quadruped", SizeCategory.Small, 0.8, "Small Canid",
            "standard-mammal", "small-predator",
            MammalPack("a fox kit", "a young dog fox", "a young vixen", "a dog fox", "a vixen",
                "It is slim, light-footed and wrapped in a neat coat of reddish fur.",
                "Its pointed muzzle, sharp ears and brush tail give it a quick, crafty look.",
                "It seems perpetually ready to slip away into cover.",
                "woodland edges, scrub and farmland"),
            "Foxes", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Coyote", "Coyote", "Toed Quadruped", SizeCategory.Small, 0.8, "Small Canid",
            "standard-mammal", "wolfpack",
            MammalPack("a coyote pup", "a young male coyote", "a young female coyote", "a male coyote", "a female coyote",
                "It is rangy and dust-coloured, with narrow shoulders and a brushy tail.",
                "Its wary amber eyes and oversized ears mark it as a watchful opportunist.",
                "It looks nervous, clever and ready to run or bite in an instant.",
                "dry scrub, prairie and rough hill country"),
            "Coyote");
        yield return Mammal("Hyena", "Hyena", "Toed Quadruped", SizeCategory.Small, 0.8, "Small Canid",
            "standard-mammal", "wolfpack",
            MammalPack("a hyena cub", "a young male hyena", "a young female hyena", "a male hyena", "a female hyena",
                "It has a sloping back, coarse spotted coat and a massively developed neck and shoulders.",
                "Its heavy jaws look capable of breaking bone with ugly ease.",
                "It gives off a rough, shambling power rather than feline grace.",
                "savannah, thorn scrub and dry plains"),
            "Hyena");
        yield return Mammal("Lion", "Leonine", "Toed Quadruped", SizeCategory.Normal, 1.3, "Big Felid",
            "standard-mammal", "big-cat",
            MammalPack("a lion cub", "a young lion", "a young lioness", "a lion", "a lioness",
                "It is large, deep-chested and heavily muscled beneath a close tawny coat.",
                "Its broad head and predatory shoulders make it look built to dominate prey with raw strength.",
                "It carries itself with slow assurance and the easy authority of an apex hunter.",
                "grassland and open savannah"),
            "Lions");
        yield return Mammal("Tiger", "Tigrine", "Toed Quadruped", SizeCategory.Normal, 1.3, "Big Felid",
            "standard-mammal", "big-cat",
            MammalPack("a tiger cub", "a young tiger", "a young tigress", "a tiger", "a tigress",
                "It is massive and sinewy, striped black over a rich orange coat.",
                "Its broad skull, huge forequarters and deep jaws speak of ambush and overpowering force.",
                "It moves with the silent certainty of a predator that expects the world to part before it.",
                "thick jungle, swamp and broken forest"),
            "Tigers");
        yield return Mammal("Sabretooth Tiger", "Sabretoothed", "Toed Quadruped", SizeCategory.Large, 1.5, "Big Felid",
            "standard-mammal", "big-cat",
            MammalPack("a sabretooth cub", "a young male sabretooth", "a young female sabretooth", "a male sabretooth", "a female sabretooth",
                "It is a hulking great cat, deep in the chest and powerful through the shoulders, with elongated upper fangs that dominate its face.",
                "Its forequarters are built for grappling impact rather than speed alone, and the paired sabres give it a terrifying silhouette.",
                "It carries itself with the confidence of a predator that ends struggles up close and violently.",
                "cold steppe, broken woodland and glacial plain"),
            "Sabretooth tigers", bloodProfile: "feline", combatStrategyKey: "Beast Brawler");
        yield return Mammal("Cheetah", "Cheetah", "Toed Quadruped", SizeCategory.Small, 0.8, "Big Felid",
            "standard-mammal", "wolfpack",
            MammalPack("a cheetah cub", "a young male cheetah", "a young female cheetah", "a male cheetah", "a female cheetah",
                "It is long-limbed and lightly built, with a spotted coat and dark tear-streaks beneath the eyes.",
                "Its narrow chest, fine waist and springy back look made for speed more than wrestling strength.",
                "It stands alert and taut, like something meant to explode into motion.",
                "open savannah and sparse scrub"),
            "Cheetah", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Leopard", "Leopard", "Toed Quadruped", SizeCategory.Small, 0.8, "Big Felid",
            "standard-mammal", "wolfpack",
            MammalPack("a leopard cub", "a young male leopard", "a young female leopard", "a male leopard", "a female leopard",
                "It is compact, muscled and rosetted in gold and black.",
                "Its heavy shoulders and powerful neck suggest an animal built to drag kills into trees.",
                "It has the quiet, coiled air of a born ambush predator.",
                "forest, rocky scrub and broken woodland"),
            "Leopard", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Panther", "Panther", "Toed Quadruped", SizeCategory.Small, 0.8, "Big Felid",
            "standard-mammal", "wolfpack",
            MammalPack("a panther cub", "a young male panther", "a young female panther", "a male panther", "a female panther",
                "It is sleek and dark-coated, its musculature visible beneath a glossy pelt.",
                "Its eyes and whiskered muzzle stand out sharply against its shadow-black fur.",
                "It moves like a piece of living night, smooth and deliberate.",
                "forest canopy, jungle edge and rocky cover"),
            "Panther", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Jaguar", "Jaguar", "Toed Quadruped", SizeCategory.Small, 0.8, "Big Felid",
            "standard-mammal", "wolfpack",
            MammalPack("a jaguar cub", "a young male jaguar", "a young female jaguar", "a male jaguar", "a female jaguar",
                "It is thickset and broad-headed, patterned with heavy rosettes marked by central spots.",
                "Its jaws look unusually deep and powerful even for a great cat.",
                "It has a dense, forceful presence rather than a runner's lightness.",
                "rainforest, swamp and riverbank"),
            "Jaguar", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Jackal", "Jackal", "Toed Quadruped", SizeCategory.Small, 0.8, "Small Canid",
            "standard-mammal", "doglike",
            MammalPack("a jackal pup", "a young male jackal", "a young female jackal", "a male jackal", "a female jackal",
                "It is a lean tawny canine with a narrow face and brush tail.",
                "Its tall ears and restless expression make it look perpetually alert for danger or carrion.",
                "It gives off a scavenger's cunning and a hunter's opportunism.",
                "dry plains, scrub and broken desert"),
            "Jackal");
        yield return Mammal("Deer", "Cervine", "Ungulate", SizeCategory.Normal, 0.8, "Small Ungulate",
            "stock-mammal", "antlered-herbivore",
            MammalPack("a fawn", "a young stag", "a young doe", "a stag", "a doe",
                "It is slender and long-legged, with a neat coat and finely boned head.",
                "Its large ears, dark eyes and delicate muzzle give it a perpetually sensitive look.",
                "It stands ready to leap away at any sudden sound.",
                "woodland, meadow and forest edge"),
            "Deer", usages: antlered, combatStrategyKey: "Beast Coward");
        yield return Mammal("Moose", "Moose", "Ungulate", SizeCategory.Large, 1.5, "Large Ungulate",
            "stock-mammal", "antlered-herbivore",
            MammalPack("a moose calf", "a young bull moose", "a young cow moose", "a bull moose", "a cow moose",
                "It is towering and long-legged, with a heavy neck and dark shaggy coat.",
                "Its pendulous muzzle and deep shoulders make it look awkward until it begins to move.",
                "It has the placid bulk of an animal that can still become terrifyingly violent when pressed.",
                "swamp, taiga and cold forest"),
            "Moose", usages: antlered, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Elk", "Elk", "Ungulate", SizeCategory.Large, 1.3, "Large Ungulate",
            "large-hooved", "antlered-herbivore",
            MammalPack("an elk calf", "a young bull elk", "a young cow elk", "a bull elk", "a cow elk",
                "It is tall-shouldered and deep-bodied, with a dark neck and long legs built for covering country.",
                "Its broad muzzle and sweeping antlers give it the look of a grazer that can still become dangerous in an instant.",
                "It holds itself with a rangy, watchful calm more suited to open woodland than close pens.",
                "mountain meadow, open forest and cold grassland"),
            "Elk", usages: antlered, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Reindeer", "Reindeer", "Ungulate", SizeCategory.Large, 1.1, "Large Ungulate",
            "stock-mammal", "antlered-herbivore",
            MammalPack("a reindeer calf", "a young bull reindeer", "a young cow reindeer", "a bull reindeer", "a cow reindeer",
                "It is compact and shaggy-coated, with broad hooves and a thick neck built for cold country.",
                "Its muzzle is blunt and furred, and even its antlers look shaped by hard seasons and long migration.",
                "It moves with steady endurance, as though distance and weather were ordinary inconveniences.",
                "tundra, lichen plain and northern woodland"),
            "Reindeer", usages: antleredGeneral, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Pig", "Porcine", "Ungulate", SizeCategory.Normal, 1.0, "Small Ungulate",
            "stock-mammal", "herbivore-charge",
            MammalPack("a piglet", "a young boar", "a young sow", "a boar", "a sow",
                "It is thick-bodied and snub-legged, with a broad snout and stiff bristles.",
                "Its rooting nose and wedge-shaped head make it look built to shove through earth and brush.",
                "It has a blunt, practical sort of confidence.",
                "farm pens, muddy woodland and scrub"),
            "Pigs", usages: udder);
        yield return Mammal("Boar", "Boar", "Ungulate", SizeCategory.Normal, 1.2, "Small Ungulate",
            "stock-mammal", "tusked-herbivore",
            MammalPack("a piglet", "a young boar", "a young sow", "a boar", "a sow",
                "It is broad-shouldered and bristled, with a wedge head and restless little eyes.",
                "Its protruding tusks and dense neck make it look ready to crash straight through trouble.",
                "It gives off the prickly aggression of a wild rooting animal.",
                "thick scrub, marsh edge and rough woodland"),
            usages: tuskedMale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Warthog", "Warthog", "Ungulate", SizeCategory.Normal, 1.2, "Small Ungulate",
            "stock-mammal", "tusked-herbivore",
            MammalPack("a warthog piglet", "a young male warthog", "a young female warthog", "a male warthog", "a female warthog",
                "It is high-shouldered and sparse-haired, with a long face and ridged snout.",
                "Its curved tusks and facial bosses give it a rugged, ill-tempered look.",
                "It looks as though it would rather charge than retreat.",
                "dry savannah and thorn scrub"),
            usages: tuskedMale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Sheep", "Ovine", "Ungulate", SizeCategory.Normal, 0.8, "Small Ungulate",
            "stock-mammal", "bovid",
            MammalPack("a lamb", "a young ram", "a young ewe", "a ram", "a ewe",
                "It is woolly and round-bodied, with a narrow face and placid eyes.",
                "Its thick fleece makes it look larger and softer than the muscle beneath would suggest.",
                "It has the mild, herd-bound stillness of a grazing prey animal.",
                "pasture, upland meadow and folded hills"),
            "Sheep", bloodProfile: "ovine", usages: hornedFemale, combatStrategyKey: "Beast Coward");
        yield return Mammal("Goat", "Caprine", "Ungulate", SizeCategory.Normal, 0.8, "Small Ungulate",
            "standard-mammal", "goat",
            MammalPack("a kid goat", "a young billy goat", "a young nanny goat", "a billy goat", "a nanny goat",
                "It is narrow-bodied and sure-footed, with a rough coat and bright horizontal pupils.",
                "Its beard, angular skull and sweeping horns give it a stubbornly self-possessed look.",
                "It looks happiest when climbing where other animals should not.",
                "crags, rough pasture and broken hills"),
            "Goats", usages: hornedFemale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Llama", "Llama", "Ungulate", SizeCategory.Normal, 1.0, "Large Ungulate",
            "stock-mammal", "camelid-spitter",
            MammalPack("a cria", "a young male llama", "a young female llama", "a male llama", "a female llama",
                "It is long-necked and narrow-faced, with a thick woolly coat and large watchful eyes.",
                "Its upright neck and neatly placed feet give it a wary, elegant silhouette.",
                "It holds itself with an aloof, steady calm.",
                "high pasture, dry plain and mountain track"),
            "Llamas", usages: udder, combatStrategyKey: "Beast Artillery");
        yield return Mammal("Alpaca", "Alpaca", "Ungulate", SizeCategory.Normal, 0.8, "Large Ungulate",
            "stock-mammal", "camelid-spitter",
            MammalPack("a cria", "a young male alpaca", "a young female alpaca", "a male alpaca", "a female alpaca",
                "It is smaller and fluffier than a llama, with a dense soft fleece and compact body.",
                "Its rounded face and oversized eyes give it a gentle, almost toy-like look.",
                "It moves with quiet delicacy and herd-bred caution.",
                "cool pasture and upland meadow"),
            "Alpacas", usages: udder, combatStrategyKey: "Beast Artillery");
        yield return Mammal("Camel", "Camelid", "Ungulate", SizeCategory.Large, 1.2, "Horse",
            "large-hooved", "camelid-spitter",
            MammalPack("a camel calf", "a young bull camel", "a young cow camel", "a bull camel", "a cow camel",
                "It is high-backed and long-legged, with broad padded feet, long lashes and a heavy-lipped muzzle.",
                "Its deep chest and swaying hump make the whole frame look engineered for thirst, distance and bad terrain.",
                "It carries itself with patient hauteur and the stubborn composure of an animal that expects the world to be hot and difficult.",
                "desert caravan, dry steppe and stony waste"),
            "Camels", usages: udder, combatStrategyKey: "Beast Artillery");
        yield return Mammal("Bear", "Ursine", "Toed Quadruped", SizeCategory.Large, 1.4, "Bear",
            "large-hooved", "bear",
            MammalPack("a bear cub", "a young male bear", "a young female bear", "a male bear", "a female bear",
                "It is huge and broad, with dense fur, thick shoulders and a heavy swinging gait.",
                "Its paws are enormous and its claws long enough to dig, tear and hold with dreadful force.",
                "It radiates blunt strength and the certainty that it is difficult to stop once angered.",
                "forest, mountain and rough northern country"));
        yield return Mammal("Mouse", "Murine", "Toed Quadruped", SizeCategory.Tiny, 0.1, "Small Rodent",
            "tiny-fast", "nuisance-bite",
            MammalPack("a mouse pinkie", "a young buck mouse", "a young doe mouse", "a buck mouse", "a doe mouse",
                "It is tiny and fine-boned, with a pointed muzzle, soft fur and a whip-like tail.",
                "Its whiskers and oversized ears are constantly in motion.",
                "It looks born to dart from cover to cover and vanish into impossibly small gaps.",
                "granaries, burrows and the hidden corners of habitation"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Rat", "Rat", "Toed Quadruped", SizeCategory.Tiny, 0.2, "Small Rodent",
            "tiny-fast", "nuisance-bite",
            MammalPack("a rat pup", "a young buck rat", "a young doe rat", "a buck rat", "a doe rat",
                "It is narrow-bodied and coarse-furred, with bright eyes and a long scaly tail.",
                "Its blunt muzzle and heavy incisors give it a more robust look than a mouse.",
                "It moves with shabby confidence and constant low-level vigilance.",
                "sewers, granaries and ruined corners"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Hamster", "Cricetid", "Toed Quadruped", SizeCategory.Tiny, 0.1, "Small Rodent",
            "tiny-fast", "nuisance-bite",
            MammalPack("a hamster pup", "a young male hamster", "a young female hamster", "a male hamster", "a female hamster",
                "It is tiny, round-bodied and plush-coated, with cheek pouches that seem large for its size.",
                "Its small paws and blunt face make it look built for digging and hoarding.",
                "It gives off a nervous but stubborn domestic energy.",
                "burrows, cages and dry scrub"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Guinea Pig", "Guinea Pig", "Toed Quadruped", SizeCategory.Tiny, 0.1, "Small Rodent",
            "tiny-fast", "nuisance-bite",
            MammalPack("a guinea pig pup", "a young boar guinea pig", "a young sow guinea pig", "a boar guinea pig", "a sow guinea pig",
                "It is plump, low to the ground and entirely tailless, wrapped in soft fur.",
                "Its bright eyes and twitching nose make it look gentle and perpetually concerned.",
                "It seems more likely to whistle in alarm than to stand its ground.",
                "grassy cover and domestic hutches"),
            combatStrategyKey: "Beast Coward");
        yield return Mammal("Ferret", "Ferret", "Toed Quadruped", SizeCategory.VerySmall, 0.2, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a ferret kit", "a young hob ferret", "a young jill ferret", "a hob ferret", "a jill ferret",
                "It is long, narrow and supple, with short legs and silky fur.",
                "Its sharp little face and lively black eyes make it look permanently curious.",
                "It moves in quick, snaking bursts full of mischief and predatory interest.",
                "burrows, barns and cramped passages"),
            combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Stoat", "Stoat", "Toed Quadruped", SizeCategory.VerySmall, 0.15, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a stoat kit", "a young male stoat", "a young female stoat", "a male stoat", "a female stoat",
                "It is slim, fine-boned and bright-eyed, with a narrow muzzle and a tail tipped in black.",
                "Its little body is made for darting into holes after prey, and in cold regions its coat can pale almost to white.",
                "It twitches with predatory focus despite its size, every movement fast and exact.",
                "hedgerow, stone wall and snowy field"),
            "Stoats", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Weasel", "Weasel", "Toed Quadruped", SizeCategory.VerySmall, 0.2, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a weasel kit", "a young male weasel", "a young female weasel", "a male weasel", "a female weasel",
                "It is tiny, lithe and intensely streamlined, with a narrow head and fluid spine.",
                "Its teeth look too sharp for such a small face, and its paws are quick and clever.",
                "It gives the impression of restless, purposeful violence in miniature.",
                "hedgerow, burrow and rough grass"),
            "Weasels", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Polecat", "Polecat", "Toed Quadruped", SizeCategory.VerySmall, 0.25, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a polecat kit", "a young male polecat", "a young female polecat", "a male polecat", "a female polecat",
                "It is long-bodied and dark-masked, with coarse fur and a low, flexible frame.",
                "Its face is pointed and expressive, and the whole animal has the musky look of something that would rather bite than be cornered.",
                "It moves in low, sinuous bursts that make every tunnel and hedge-line look like cover.",
                "hedgebank, rough pasture and ruin"),
            "Polecats", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Mink", "Mink", "Toed Quadruped", SizeCategory.VerySmall, 0.25, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a mink kit", "a young male mink", "a young female mink", "a male mink", "a female mink",
                "It is sleek and dark-furred, with a supple body, neat ears and bright, hard eyes.",
                "Its long tail and slightly webbed feet hint at a hunter equally comfortable on bank or in water.",
                "It gives off the quiet intent of a predator that has never needed to be large to be dangerous.",
                "riverbank, marsh edge and reed-choked pool"),
            "Minks", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Shrew", "Shrew", "Toed Quadruped", SizeCategory.Tiny, 0.1, "Small Rodent",
            "tiny-fast", "small-predator",
            MammalPack("a shrew pup", "a young male shrew", "a young female shrew", "a male shrew", "a female shrew",
                "It is tiny and sharp-snouted, with velvety fur and a body that seems perpetually in motion.",
                "Its needle teeth and frantic little paws make it look far too fierce for something so small.",
                "It lives at a pitch of constant hunger and nervous violence, never still for long.",
                "leaf litter, root tangle and damp grass"),
            "Shrews", combatStrategyKey: "Beast Skirmisher");
        yield return Mammal("Badger", "Badger", "Toed Quadruped", SizeCategory.Small, 0.8, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a badger cub", "a young boar badger", "a young sow badger", "a boar badger", "a sow badger",
                "It is low, stocky and massively built for digging, with coarse fur and a striped face.",
                "Its shoulders and foreclaws are thick and workmanlike, made for earth and stubborn labor.",
                "It has the dour, immovable look of an animal that dislikes being disturbed.",
                "setts, hedgebanks and mixed woodland"),
            "Badgers");
        yield return Mammal("Wolverine", "Wolverine", "Toed Quadruped", SizeCategory.Small, 0.5, "Mustelid",
            "standard-mammal", "small-predator",
            MammalPack("a wolverine cub", "a young male wolverine", "a young female wolverine", "a male wolverine", "a female wolverine",
                "It is broad-pawed and thick-furred, with a heavy neck and deep-set eyes.",
                "Its teeth and shoulders make it look disproportionately formidable for its size.",
                "It radiates surly endurance and a willingness to fight far above its weight.",
                "snow country, tundra and cold forest"),
            "Wolverines");
        yield return Mammal("Cow", "Bovine", "Ungulate", SizeCategory.Large, 1.5, "Large Ungulate",
            "stock-mammal", "bovid",
            MammalPack("a calf", "a young bull", "a young cow", "a bull", "a cow",
                "It is large and broad-bodied, with a heavy gut and a blunt moist muzzle.",
                "Its calm eyes and sweeping ribs speak of a lifetime spent grazing and ruminating.",
                "It has the placid, heavy patience of domestic stock.",
                "pasture, open field and cattle yard"),
            "Cows", bloodProfile: "bovine", usages: hornedFemale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Ox", "Ox", "Ungulate", SizeCategory.Large, 1.7, "Large Ungulate",
            "stock-mammal", "bovid",
            MammalPack("a calf", "a young bull", "a young cow", "an ox", "a cow",
                "It is broad-backed and deep-chested, with strong shoulders and a thick neck.",
                "Its sheer frame suggests hauling power rather than speed or elegance.",
                "It stands with the settled endurance of a working beast.",
                "field, road and draft yard"),
            "Oxen", usages: hornedFemale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Bison", "Bison", "Ungulate", SizeCategory.Large, 1.5, "Large Ungulate",
            "stock-mammal", "bovid",
            MammalPack("a bison calf", "a young bull bison", "a young cow bison", "a bull bison", "a cow bison",
                "It is massive in front, thick-maned and heavy headed, tapering behind into lighter hindquarters.",
                "Its dense shoulder hump and horned brow make it look like a wall of living muscle.",
                "It has a slow, gathered momentum that hints at tremendous explosive power.",
                "prairie, steppe and open range"),
            "Bisons", usages: hornedFemale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Buffalo", "Buffalo", "Ungulate", SizeCategory.Large, 1.5, "Large Ungulate",
            "stock-mammal", "bovid",
            MammalPack("a buffalo calf", "a young bull buffalo", "a young cow buffalo", "a bull buffalo", "a cow buffalo",
                "It is dense and dark-coated, with a broad chest and sweeping horns.",
                "Its thick hide and low-slung head make it look like an animal built to weather punishment.",
                "It stands with a dour, dangerous calm.",
                "marsh, floodplain and rough pasture"),
            "Buffalos", usages: hornedFemale, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Horse", "Equine", "Ungulate", SizeCategory.Large, 1.5, "Horse",
            "large-hooved", "herbivore-charge",
            MammalPack("a foal", "a colt", "a filly", "a stallion", "a mare",
                "It is deep-bodied and strong-legged, with a flowing mane and powerful hindquarters.",
                "Its long face, lively ears and large dark eyes give it an intelligent, responsive look.",
                "It carries itself with a mixture of high-strung energy and practiced athleticism.",
                "plain, pasture and stable"),
            "Horse", canClimb: false, bloodProfile: "equine", usages: udder, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Rhinocerous", "Ceratorhine", "Ungulate", SizeCategory.Large, 1.5, "Pachyderm",
            "large-hooved", "rhino",
            MammalPack("a rhino calf", "a young bull rhino", "a young cow rhino", "a bull rhino", "a cow rhino",
                "It is enormous and slab-sided, wrapped in thick folded hide like natural armour.",
                "Its snout carries a formidable horn and its barrel body looks difficult to injure or divert.",
                "It gives off an air of dangerous, heavy indifference.",
                "grassland, thorn scrub and muddy wallow"),
            "Rhinocerouses", usages: rhinoHorn, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Hippopotamus", "Hippopotamine", "Ungulate", SizeCategory.Large, 1.5, "Pachyderm",
            "stock-mammal", "hippo",
            MammalPack("a hippo calf", "a young bull hippo", "a young cow hippo", "a bull hippo", "a cow hippo",
                "It is barrel-shaped and heavy-skinned, with a huge head and tiny watchful ears.",
                "Its mouth is absurdly broad, and the tusks within it look more than capable of maiming anything nearby.",
                "It has the bad-tempered stillness of an animal secure in its size.",
                "river, mudbank and reed-choked water"),
            "Hippopotamuses", usages: tuskedGeneral, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Elephant", "Elephantine", "Ungulate", SizeCategory.VeryLarge, 2.0, "Pachyderm",
            "elephant", "elephant",
            MammalPack("an elephant calf", "a young bull elephant", "a young cow elephant", "a bull elephant", "a cow elephant",
                "It is colossal, grey-skinned and vast, with pillar legs and an immense domed head.",
                "Its trunk, fanlike ears and sweeping ivory tusks make it one of the most imposing animals imaginable.",
                "It moves with slow certainty, each step suggesting immense restrained force.",
                "savannah, forest edge and watering place"),
            "Elephants", usages: tuskedGeneral, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Mammoth", "Mammothine", "Ungulate", SizeCategory.VeryLarge, 2.2, "Pachyderm",
            "elephant", "elephant",
            MammalPack("a mammoth calf", "a young bull mammoth", "a young cow mammoth", "a bull mammoth", "a cow mammoth",
                "It is immense and shaggy, its towering frame wrapped in long coarse hair above pillar-like legs.",
                "Its domed skull, humped shoulders and sweeping tusks make it look like winter itself learned to charge.",
                "It moves with heavy, deliberate momentum, each stride carrying the patient force of an age-old giant.",
                "tundra, glacial plain and cold steppe"),
            "Mammoths", usages: tuskedGeneral, combatStrategyKey: "Beast Behemoth");
        yield return Mammal("Giraffe", "Giraffine", "Ungulate", SizeCategory.VeryLarge, 1.0, "Large Ungulate",
            "large-hooved", "herbivore-charge",
            MammalPack("a giraffe calf", "a young bull giraffe", "a young cow giraffe", "a bull giraffe", "a cow giraffe",
                "It is immensely tall, with a spotted coat, long legs and an even longer neck.",
                "Its small horn-like ossicones and impossibly elevated head give it a peculiar dignity.",
                "It lopes rather than walks, with an awkward grace all its own.",
                "dry savannah and scattered acacia country"),
            combatStrategyKey: "Beast Behemoth");
    }
}
