#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Combat;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Framework;
using MudSharp.GameItems.Interfaces;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.PerceptionEngine;
using MudSharp.RPG.Checks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace DatabaseSeeder.Seeders;

public partial class CombatSeeder
{
	internal static IReadOnlyList<string> EraDependencyCombatComponentNamesForTesting =>
	[
		"Armour_Brigandine",
		"Armour_BuffLeather",
		"Armour_ChainAndPlate",
		"Armour_Padded",
		"Armour_PlateLight",
		"Armour_PlateMedium",
		"Armour_ProofedPlate",
		"Armour_Rattan",
		"Armour_RigidMetal",
		"Armour_CoatOfPlates",
		"Armour_Splinted",
		"Melee_Bayonet",
		"Melee_HookedPolearm",
		"Melee_Lance",
		"Melee_Poleblade",
		"Melee_Sabre",
		"Melee_Smallsword",
		"Melee_Training_Bayonet",
		"Melee_Training_Lance",
		"Melee_Training_Poleblade",
		"Melee_Training_Sabre",
		"Melee_Training_Smallsword",
		"CompositeBow_Heavy",
		"CompositeBow_Light",
		"CompositeBow_War",
		"Yumi",
		"Crossbow_EastAsian",
		"Crossbow_Heavy",
		"Crossbow_Light",
		"Crossbow_Pellet",
		"Crossbow_Cranequin",
		"Crossbow_GoatsFoot",
		"Crossbow_Lever",
		"Crossbow_SpanningHook",
		"Crossbow_Windlass",
		"Blowgun_Long",
		"Blowgun_Short",
		"Throwing_Club",
		"Throwing_Disc",
		"Bayonet_Plug",
		"Bayonet_Socket",
		"Bayonet_Sword",
		"MusketPaperCartridge_0.45 Bore",
		"MusketPaperCartridge_0.55 Bore",
		"MusketPaperCartridge_0.6 Bore",
		"MusketPaperCartridge_0.65 Bore",
		"MusketPaperCartridge_0.7 Bore",
		"MusketPaperCartridge_0.75 Bore",
		"MusketPaperCartridge_0.8 Bore",
		.. EarlyModernMilitaryCompletionComponentNames
	];

	internal static IReadOnlyList<string> EarlyModernMilitaryCompletionComponentNames =>
	[
		"Crossbow_Repeating", "Crossbow_Repeating_Light", "Crossbow_Wall",
		"Musket_Doglock_Blunderbuss75", "Musket_Doglock_Carbine60", "Musket_Doglock_Musket70",
		"Musket_Flintlock_Blunderbuss75", "Musket_Flintlock_Carbine60", "Musket_Flintlock_FowlingPiece60", "Musket_Flintlock_WallGun80",
		"Musket_Matchlock_Arquebus55", "Musket_Matchlock_Blunderbuss75", "Musket_Matchlock_Caliver60", "Musket_Matchlock_Carbine60", "Musket_Matchlock_FowlingPiece60", "Musket_Matchlock_HeavyMusket80", "Musket_Matchlock_Jezail65", "Musket_Matchlock_Musket75", "Musket_Matchlock_Tanegashima60", "Musket_Matchlock_Toradar65", "Musket_Matchlock_WallGun80",
		"Musket_Miquelet_Blunderbuss75", "Musket_Miquelet_Carbine60", "Musket_Miquelet_Escopeta65", "Musket_Miquelet_Musket70",
		"Musket_Snaphaunce_Carbine60", "Musket_Snaphaunce_FowlingPiece60", "Musket_Snaphaunce_LongGun65", "Musket_Snaphaunce_Musket70",
		"Musket_Wheellock_Carbine60", "Musket_Wheellock_FowlingPiece60", "Musket_Wheellock_LongGun65", "Musket_Wheellock_Rifle55",
		"Pistol_Doglock55", "Pistol_Flintlock_Duelling45", "Pistol_Matchlock55", "Pistol_Miquelet55", "Pistol_Snaphaunce55", "Pistol_Wheellock45", "Pistol_Wheellock55",
		"MusketBuckAndBall_0.65 Bore", "MusketBuckAndBall_0.75 Bore", "MusketBuckshot_0.55 Bore", "MusketBuckshot_0.75 Bore",
		"Artillery_CoehornMortar", "Artillery_Culverin", "Artillery_DemiCannon", "Artillery_DemiCulverin", "Artillery_Falcon", "Artillery_Falconet", "Artillery_FieldGun12lb", "Artillery_FieldGun3lb", "Artillery_FieldGun6lb", "Artillery_FieldGun9lb", "Artillery_FieldMortar", "Artillery_FullCannon", "Artillery_Minion", "Artillery_NavalGun18lb", "Artillery_NavalGun24lb", "Artillery_NavalGun32lb", "Artillery_Peterero", "Artillery_Saker", "Artillery_SiegeMortar", "Artillery_SwivelGun",
		"ArtilleryCaseShot_12lb", "ArtilleryCaseShot_3lb", "ArtilleryCaseShot_6lb", "ArtilleryGrapeshot_Heavy", "ArtilleryGrapeshot_Light", "ArtilleryGrapeshot_Medium", "ArtilleryShell_Carcass", "ArtilleryShell_Heavy", "ArtilleryShell_Light", "ArtilleryShot_12lb", "ArtilleryShot_18lb", "ArtilleryShot_1lb", "ArtilleryShot_24lb", "ArtilleryShot_32lb", "ArtilleryShot_3lb", "ArtilleryShot_6lb", "ArtilleryShot_9lb", "ArtilleryShot_Bar", "ArtilleryStoneShot_Heavy", "ArtilleryStoneShot_Light",
		"ArtilleryMount_Swivel", "WeaponLanyard_Pistol", "WeaponLoop_LongGun", "WeaponSling_Carbine", "WeaponSling_LongGun",
		"ArtilleryChamber_Peterero", "Holster_PairedSaddle"
	];

	internal int EnsureEraDependencyCombatContentForTesting(FuturemudDatabaseContext context,
		IReadOnlyDictionary<string, string> questionAnswers)
	{
		return EnsureEraDependencyCombatContent(context, questionAnswers);
	}

	private int EnsureEraDependencyCombatContent(FuturemudDatabaseContext context,
		IReadOnlyDictionary<string, string> questionAnswers)
	{
		var added = 0;
		var account = context.Accounts.First();
		var now = DateTime.UtcNow;

		EditableItem NewEditableItem()
		{
			return new EditableItem
			{
				RevisionNumber = 0,
				RevisionStatus = 4,
				BuilderAccountId = account.Id,
				BuilderDate = now,
				BuilderComment = "Auto-generated by the system",
				ReviewerAccountId = account.Id,
				ReviewerComment = "Auto-generated by the system",
				ReviewerDate = now
			};
		}

		GameItemComponentProto EnsureComponent(string type, string name, string description, string definition)
		{
			var existing = context.GameItemComponentProtos
				.FirstOrDefault(x => x.Name == name && x.EditableItem.RevisionStatus == 4);
			if (existing is not null)
			{
				existing.Type = type;
				existing.Description = description;
				existing.Definition = definition;
				return existing;
			}

			var component = new GameItemComponentProto
			{
				Id = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1,
				RevisionNumber = 0,
				EditableItem = NewEditableItem(),
				Type = type,
				Name = name,
				Description = description,
				Definition = definition
			};
			context.GameItemComponentProtos.Add(component);
			context.SaveChanges();
			added++;
			return component;
		}

		ArmourType EnsureArmour(string name, string componentName, string donorName, int penetration,
			double baseDifficulty, double stackedDifficulty)
		{
			var donor = context.ArmourTypes.FirstOrDefault(x => x.Name == donorName) ??
						throw new InvalidOperationException(
							$"Cannot seed {componentName}: the foundational armour type '{donorName}' is missing. " +
							"Run Combat with the installweapons choice enabled first.");
			var armour = context.ArmourTypes.FirstOrDefault(x => x.Name == name);
			if (armour is null)
			{
				armour = new ArmourType
				{
					Name = name,
				};
				context.ArmourTypes.Add(armour);
				added++;
			}

			armour.MinimumPenetrationDegree = penetration;
			armour.BaseDifficultyDegrees = baseDifficulty;
			armour.StackedDifficultyDegrees = stackedDifficulty;
			armour.Definition = donor.Definition;
			context.SaveChanges();

			EnsureComponent("Armour", componentName, $"Turns an item into {name} armour",
				$"<Definition><ArmourType>{armour.Id}</ArmourType></Definition>");
			return armour;
		}

		WeaponType EnsureWeapon(string name, string componentName, string donorName, WeaponClassification classification,
			int? reach = null, double? parryBonus = null)
		{
			var donor = context.WeaponTypes
				.Include(x => x.WeaponAttacks)
				.ThenInclude(x => x.CombatMessagesWeaponAttacks)
				.FirstOrDefault(x => x.Name == donorName) ??
						throw new InvalidOperationException(
							$"Cannot seed {componentName}: the foundational weapon type '{donorName}' is missing. " +
							"Run Combat with the installweapons choice enabled first.");
			var weapon = context.WeaponTypes.FirstOrDefault(x => x.Name == name);
			if (weapon is null)
			{
				weapon = new WeaponType
				{
					Name = name,
				};
				context.WeaponTypes.Add(weapon);
				added++;
			}

			weapon.Classification = (int)classification;
			weapon.AttackTraitId = donor.AttackTraitId;
			weapon.ParryTraitId = donor.ParryTraitId;
			weapon.ParryBonus = parryBonus ?? donor.ParryBonus;
			weapon.Reach = reach ?? donor.Reach;
			weapon.StaminaPerParry = donor.StaminaPerParry;
			context.SaveChanges();

			foreach (var donorAttack in donor.WeaponAttacks)
			{
				var attackName = $"{name}: {donorAttack.Name}";
				var attack = context.WeaponAttacks
					.Include(x => x.CombatMessagesWeaponAttacks)
					.FirstOrDefault(x => x.WeaponTypeId == weapon.Id && x.Name == attackName);
				if (attack is null)
				{
					attack = new WeaponAttack
					{
						WeaponTypeId = weapon.Id,
						Name = attackName
					};
					context.WeaponAttacks.Add(attack);
					added++;
				}

				attack.Verb = donorAttack.Verb;
				attack.FutureProgId = donorAttack.FutureProgId;
				attack.BaseAttackerDifficulty = donorAttack.BaseAttackerDifficulty;
				attack.BaseBlockDifficulty = donorAttack.BaseBlockDifficulty;
				attack.BaseDodgeDifficulty = donorAttack.BaseDodgeDifficulty;
				attack.BaseParryDifficulty = donorAttack.BaseParryDifficulty;
				attack.BaseAngleOfIncidence = donorAttack.BaseAngleOfIncidence;
				attack.RecoveryDifficultySuccess = donorAttack.RecoveryDifficultySuccess;
				attack.RecoveryDifficultyFailure = donorAttack.RecoveryDifficultyFailure;
				attack.MoveType = donorAttack.MoveType;
				attack.Intentions = donorAttack.Intentions;
				attack.ExertionLevel = donorAttack.ExertionLevel;
				attack.DamageType = donorAttack.DamageType;
				attack.DamageExpressionId = donorAttack.DamageExpressionId;
				attack.StunExpressionId = donorAttack.StunExpressionId;
				attack.PainExpressionId = donorAttack.PainExpressionId;
				attack.Weighting = donorAttack.Weighting;
				attack.MaximumTargets = donorAttack.MaximumTargets;
				attack.BodypartShapeId = donorAttack.BodypartShapeId;
				attack.StaminaCost = donorAttack.StaminaCost;
				attack.BaseDelay = donorAttack.BaseDelay;
				attack.Orientation = donorAttack.Orientation;
				attack.Alignment = donorAttack.Alignment;
				attack.AdditionalInfo = donorAttack.AdditionalInfo;
				attack.HandednessOptions = donorAttack.HandednessOptions;
				attack.RequiredPositionStateIds = donorAttack.RequiredPositionStateIds;
				attack.OnUseProgId = donorAttack.OnUseProgId;
				context.SaveChanges();

				foreach (var message in donorAttack.CombatMessagesWeaponAttacks)
				{
					if (attack.CombatMessagesWeaponAttacks.Any(x => x.CombatMessageId == message.CombatMessageId))
					{
						continue;
					}

					context.CombatMessagesWeaponAttacks.Add(new CombatMessagesWeaponAttacks
					{
						CombatMessageId = message.CombatMessageId,
						WeaponAttackId = attack.Id
					});
				}

				context.SaveChanges();
			}

			EnsureComponent("MeleeWeapon", componentName, $"Turns an item into a {name} melee weapon",
				$"<Definition><WeaponType>{weapon.Id}</WeaponType></Definition>");
			return weapon;
		}

		void EnsureEarlyModernSpecialAttack(WeaponType weapon, string donorWeaponName, string? donorAttackName,
			string attackName, BuiltInCombatMoveType moveType)
		{
			var donorWeapon = context.WeaponTypes
				.Include(x => x.WeaponAttacks)
				.ThenInclude(x => x.CombatMessagesWeaponAttacks)
				.FirstOrDefault(x => x.Name == donorWeaponName) ?? weapon;
			var donorAttack = donorWeapon.WeaponAttacks.FirstOrDefault(x => x.Name == donorAttackName) ??
			                  donorWeapon.WeaponAttacks.First(x => x.MoveType == (int)BuiltInCombatMoveType.UseWeaponAttack);
			var name = $"{weapon.Name}: {attackName}";
			var attack = context.WeaponAttacks
				.Include(x => x.CombatMessagesWeaponAttacks)
				.FirstOrDefault(x => x.WeaponTypeId == weapon.Id && x.Name == name);
			if (attack is null)
			{
				attack = new WeaponAttack { WeaponTypeId = weapon.Id, Name = name };
				context.WeaponAttacks.Add(attack);
				added++;
			}

			attack.Verb = donorAttack.Verb;
			attack.FutureProgId = donorAttack.FutureProgId;
			attack.BaseAttackerDifficulty = donorAttack.BaseAttackerDifficulty;
			attack.BaseBlockDifficulty = donorAttack.BaseBlockDifficulty;
			attack.BaseDodgeDifficulty = donorAttack.BaseDodgeDifficulty;
			attack.BaseParryDifficulty = donorAttack.BaseParryDifficulty;
			attack.BaseAngleOfIncidence = donorAttack.BaseAngleOfIncidence;
			attack.RecoveryDifficultySuccess = donorAttack.RecoveryDifficultySuccess;
			attack.RecoveryDifficultyFailure = donorAttack.RecoveryDifficultyFailure;
			attack.MoveType = (int)moveType;
			attack.Intentions = donorAttack.Intentions;
			attack.ExertionLevel = donorAttack.ExertionLevel;
			attack.DamageType = donorAttack.DamageType;
			attack.DamageExpressionId = donorAttack.DamageExpressionId;
			attack.StunExpressionId = donorAttack.StunExpressionId;
			attack.PainExpressionId = donorAttack.PainExpressionId;
			attack.Weighting = donorAttack.Weighting;
			attack.MaximumTargets = donorAttack.MaximumTargets;
			attack.BodypartShapeId = donorAttack.BodypartShapeId;
			attack.StaminaCost = donorAttack.StaminaCost;
			attack.BaseDelay = donorAttack.BaseDelay;
			attack.Orientation = donorAttack.Orientation;
			attack.Alignment = donorAttack.Alignment;
			attack.AdditionalInfo = donorAttack.AdditionalInfo;
			attack.HandednessOptions = donorAttack.HandednessOptions;
			attack.RequiredPositionStateIds = donorAttack.RequiredPositionStateIds;
			attack.OnUseProgId = donorAttack.OnUseProgId;
			context.SaveChanges();

			foreach (var message in donorAttack.CombatMessagesWeaponAttacks.Where(x =>
				!attack.CombatMessagesWeaponAttacks.Any(y => y.CombatMessageId == x.CombatMessageId)))
			{
				context.CombatMessagesWeaponAttacks.Add(new CombatMessagesWeaponAttacks
				{
					CombatMessageId = message.CombatMessageId,
					WeaponAttackId = attack.Id
				});
			}
			context.SaveChanges();
		}

		RangedWeaponTypes EnsureRanged(string name, string componentName, string componentType, string donorName,
			Action<RangedWeaponTypes>? configure = null, string? meleeDonorName = null)
		{
			var donor = context.RangedWeaponTypes.FirstOrDefault(x => x.Name == donorName) ??
						throw new InvalidOperationException(
							$"Cannot seed {componentName}: the foundational ranged-weapon type '{donorName}' is missing. " +
							"Run Combat with the installranged choice enabled first.");
			var ranged = context.RangedWeaponTypes.FirstOrDefault(x => x.Name == name);
			if (ranged is null)
			{
				ranged = new RangedWeaponTypes
				{
					Name = name,
				};
				context.RangedWeaponTypes.Add(ranged);
				added++;
			}

			ranged.Classification = donor.Classification;
			ranged.FireTraitId = donor.FireTraitId;
			ranged.OperateTraitId = donor.OperateTraitId;
			ranged.FireableInMelee = donor.FireableInMelee;
			ranged.DefaultRangeInRooms = donor.DefaultRangeInRooms;
			ranged.AccuracyBonusExpression = donor.AccuracyBonusExpression;
			ranged.DamageBonusExpression = donor.DamageBonusExpression;
			ranged.AmmunitionLoadType = donor.AmmunitionLoadType;
			ranged.SpecificAmmunitionGrade = donor.SpecificAmmunitionGrade;
			ranged.AmmunitionCapacity = donor.AmmunitionCapacity;
			ranged.RangedWeaponType = donor.RangedWeaponType;
			ranged.StaminaToFire = donor.StaminaToFire;
			ranged.StaminaPerLoadStage = donor.StaminaPerLoadStage;
			ranged.CoverBonus = donor.CoverBonus;
			ranged.BaseAimDifficulty = donor.BaseAimDifficulty;
			ranged.LoadDelay = donor.LoadDelay;
			ranged.ReadyDelay = donor.ReadyDelay;
			ranged.FireDelay = donor.FireDelay;
			ranged.AimBonusLostPerShot = donor.AimBonusLostPerShot;
			ranged.RequiresFreeHandToReady = donor.RequiresFreeHandToReady;
			ranged.AlwaysRequiresTwoHandsToWield = donor.AlwaysRequiresTwoHandsToWield;
			configure?.Invoke(ranged);
			context.SaveChanges();

			var meleeElement = meleeDonorName is null
				? string.Empty
				: $"<MeleeWeaponType>{(context.WeaponTypes.FirstOrDefault(x => x.Name == meleeDonorName) ??
					throw new InvalidOperationException(
						$"Cannot seed {componentName}: the foundational weapon type '{meleeDonorName}' is missing. " +
						"Run Combat with the installweapons choice enabled first.")).Id}</MeleeWeaponType>";
			EnsureComponent(componentType, componentName, $"Turns an item into a {name}",
				$"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType>{meleeElement}</Definition>");
			return ranged;
		}

		long RequireTagId(string name)
		{
			return context.Tags
					   .AsEnumerable()
					   .SingleOrDefault(x => x.Name.Equals(name, StringComparison.OrdinalIgnoreCase))?.Id ??
				   throw new InvalidOperationException(
					   $"Cannot seed combat profile: the required tag '{name}' is missing. Run the Useful Items package first.");
		}

		void EnsureSpannedCrossbow(string name, string componentName, string toolTagName,
			Action<RangedWeaponTypes> configure)
		{
			var ranged = EnsureRanged(name, componentName, "Crossbow", "Crossbow", configure);
			var component = context.GameItemComponentProtos.Single(x =>
				x.Name == componentName && x.EditableItem.RevisionStatus == 4);
			component.Definition = new XElement("Definition",
				new XElement("RangedWeaponType", ranged.Id),
				new XElement("RequiredSpanningToolTag", RequireTagId(toolTagName)),
				new XElement("ReadyEmote",
					new XCData("@ use|uses $2 to span and ready $1, drawing its string into the firing catch.")))
				.ToString();
		}


		EnsureArmour("Brigandine", "Armour_Brigandine", "Metal Scale", 1, 1, 2);
		EnsureArmour("Buff Leather", "Armour_BuffLeather", "Boiled Leather", 1, 1, 2);
		EnsureArmour("Chain and Plate", "Armour_ChainAndPlate", "Platemail", 1, 2, 3);
		EnsureArmour("Padded", "Armour_Padded", "Ultra Heavy Clothing", 1, 1, 2);
		EnsureArmour("Plate Light", "Armour_PlateLight", "Platemail", 1, 1, 2);
		EnsureArmour("Plate Medium", "Armour_PlateMedium", "Platemail", 1, 2, 3);
		EnsureArmour("Proofed Plate", "Armour_ProofedPlate", "Platemail", 2, 2, 4);
		EnsureArmour("Rattan", "Armour_Rattan", "Leather Scale", 1, 1, 2);
		EnsureArmour("Rigid Metal", "Armour_RigidMetal", "Platemail", 1, 2, 3);
		EnsureArmour("Coat of Plates", "Armour_CoatOfPlates", "Platemail", 1, 2, 3);
		EnsureArmour("Splinted", "Armour_Splinted", "Studded Leather", 1, 1, 2);

		EnsureWeapon("Bayonet", "Melee_Bayonet", "Dagger", WeaponClassification.Lethal, 2);
		var hookedPolearm = EnsureWeapon("Hooked Polearm", "Melee_HookedPolearm", "Halberd", WeaponClassification.Lethal, 4);
		var lance = EnsureWeapon("Lance", "Melee_Lance", "Long Spear", WeaponClassification.Lethal, 5);
		EnsureEarlyModernSpecialAttack(hookedPolearm, "Quarterstaff", "Quarterstaff Hook and Pull", "Hook and Pull", BuiltInCombatMoveType.PullToMelee);
		EnsureEarlyModernSpecialAttack(lance, "Long Spear", null, "Couched Charge", BuiltInCombatMoveType.CouchedLanceAttack);
		EnsureWeapon("Poleblade", "Melee_Poleblade", "Halberd", WeaponClassification.Lethal, 4);
		EnsureWeapon("Sabre", "Melee_Sabre", "Longsword", WeaponClassification.Lethal, 3);
		EnsureWeapon("Smallsword", "Melee_Smallsword", "Rapier", WeaponClassification.Lethal, 2);
		EnsureWeapon("Training Bayonet", "Melee_Training_Bayonet", "Training Dagger",
			WeaponClassification.Training, 2);
		EnsureWeapon("Training Lance", "Melee_Training_Lance", "Training Spear",
			WeaponClassification.Training, 5);
		EnsureWeapon("Training Poleblade", "Melee_Training_Poleblade", "Training Halberd",
			WeaponClassification.Training, 4);
		EnsureWeapon("Training Sabre", "Melee_Training_Sabre", "Training Longsword",
			WeaponClassification.Training, 3);
		EnsureWeapon("Training Smallsword", "Melee_Training_Smallsword", "Training Rapier",
			WeaponClassification.Training, 2);

		foreach (var (name, style) in new[]
				 {
						 ("Bayonet_Plug", "Plug"),
						 ("Bayonet_Socket", "Socket"),
						 ("Bayonet_Sword", "Sword")
					 })
		{
			EnsureComponent("BayonetAttachment", name,
				$"Turns an item into a {style.ToLowerInvariant()} bayonet attachment",
				new XElement("Definition",
					new XElement("Style", style),
					new XElement("MinimumBore", 0.45),
					new XElement("MaximumBore", 0.8))
					.ToString());
		}


		EnsureRanged("Composite Bow Heavy", "CompositeBow_Heavy", "Bow", "Longbow", x =>
		{
			x.DefaultRangeInRooms = 5;
			x.StaminaPerLoadStage *= 1.2;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 3";
		});
		EnsureRanged("Composite Bow Light", "CompositeBow_Light", "Bow", "Shortbow", x =>
		{
			x.DefaultRangeInRooms = Math.Max(3, x.DefaultRangeInRooms);
			x.LoadDelay *= 0.8;
		});
		EnsureRanged("Composite Bow War", "CompositeBow_War", "Bow", "Longbow", x =>
		{
			x.DefaultRangeInRooms = 4;
			x.LoadDelay *= 0.9;
		});
		EnsureRanged("Yumi", "Yumi", "Bow", "Longbow", x =>
		{
			x.DefaultRangeInRooms = 5;
			x.AlwaysRequiresTwoHandsToWield = true;
		});

		EnsureRanged("East Asian Crossbow", "Crossbow_EastAsian", "Crossbow", "Crossbow");
		EnsureRanged("Heavy Crossbow", "Crossbow_Heavy", "Crossbow", "Crossbow", x =>
		{
			x.DefaultRangeInRooms = 5;
			x.LoadDelay *= 1.5;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 4";
		});
		EnsureRanged("Light Crossbow", "Crossbow_Light", "Crossbow", "Hand Crossbow", x =>
		{
			x.DefaultRangeInRooms = 3;
			x.AlwaysRequiresTwoHandsToWield = false;
		});
		EnsureRanged("Pellet Crossbow", "Crossbow_Pellet", "Crossbow", "Crossbow", x =>
		{
			x.DefaultRangeInRooms = 2;
			x.SpecificAmmunitionGrade = "Sling Bullet";
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) - 3";
		});
		EnsureSpannedCrossbow("Cranequin Crossbow", "Crossbow_Cranequin", "Cranequin", x =>
		{
			x.ReadyDelay *= 3.0;
			x.StaminaPerLoadStage *= 0.9;
			x.DefaultRangeInRooms = 6;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 6";
		});
		EnsureSpannedCrossbow("Goat's Foot Crossbow", "Crossbow_GoatsFoot", "Goat's Foot", x =>
		{
			x.ReadyDelay *= 1.5;
			x.StaminaPerLoadStage *= 1.15;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 2";
		});
		EnsureSpannedCrossbow("Lever Crossbow", "Crossbow_Lever", "Lever", x =>
		{
			x.ReadyDelay *= 1.75;
			x.StaminaPerLoadStage *= 1.2;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 3";
		});
		EnsureSpannedCrossbow("Spanning Hook Crossbow", "Crossbow_SpanningHook", "Spanning Hook", x =>
		{
			x.ReadyDelay *= 1.25;
			x.StaminaPerLoadStage *= 1.1;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 1";
		});
		EnsureSpannedCrossbow("Windlass Crossbow", "Crossbow_Windlass", "Windlass", x =>
		{
			x.ReadyDelay *= 2.5;
			x.DefaultRangeInRooms = 5;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 5";
		});

		EnsureRanged("Long Blowgun", "Blowgun_Long", "Blowgun", "Blowgun", x =>
		{
			x.DefaultRangeInRooms = 2;
			x.AlwaysRequiresTwoHandsToWield = true;
		});
		EnsureRanged("Short Blowgun", "Blowgun_Short", "Blowgun", "Blowgun", x =>
		{
			x.DefaultRangeInRooms = 1;
			x.AlwaysRequiresTwoHandsToWield = false;
			x.LoadDelay *= 0.8;
		});
		EnsureRanged("Throwing Club", "Throwing_Club", "ThrownWeapon", "Throwing Axe", null, "Club");
		EnsureRanged("Throwing Disc", "Throwing_Disc", "ThrownWeapon", "Throwing Knife", x =>
		{
			x.DefaultRangeInRooms = 1;
			x.DamageBonusExpression = $"({x.DamageBonusExpression}) - 2";
		}, "Dagger");

		var slingBullet = context.AmmunitionTypes.FirstOrDefault(x => x.Name == "Sling Bullet") ??
						  throw new InvalidOperationException(
							  "Cannot seed Crossbow_Pellet: the foundational ammunition type 'Sling Bullet' is missing. " +
							  "Run Combat with the installranged choice enabled first.");
		var types = slingBullet.RangedWeaponTypes
			.Split(' ', StringSplitOptions.RemoveEmptyEntries)
			.ToHashSet(StringComparer.Ordinal);
		if (types.Add(((int)RangedWeaponType.Crossbow).ToString()))
		{
			slingBullet.RangedWeaponTypes = types.OrderBy(x => x).ListToCommaSeparatedValues(" ");
			added++;
		}


		if (questionAnswers.TryGetValue("installmuskets", out var installMuskets) &&
			installMuskets.EqualToAny("yes", "y"))
		{
			var paperTagId = RequireTagId("Paper Cartridges");
			foreach (var boreName in new[] { "0.45 Bore", "0.55 Bore", "0.6 Bore", "0.65 Bore", "0.7 Bore", "0.75 Bore", "0.8 Bore" })
			{
				var baseComponent = context.GameItemComponentProtos
					.Where(x => x.Name == $"MusketCartridge_{boreName}" && x.EditableItem.RevisionStatus == 4)
					.OrderByDescending(x => x.Id)
					.FirstOrDefault() ??
					throw new InvalidOperationException(
						$"Cannot seed MusketPaperCartridge_{boreName}: the base musket cartridge component is missing. " +
						"Run Combat with installmuskets enabled first.");
				var baseDefinition = XElement.Parse(baseComponent.Definition);
				var bore = double.Parse(
					baseDefinition.Element("BulletBore")?.Value ??
					throw new InvalidOperationException(
						$"Cannot seed MusketPaperCartridge_{boreName}: the base cartridge component has no BulletBore value."),
					System.Globalization.CultureInfo.InvariantCulture);
				var musketDefinition = context.GameItemComponentProtos
					.Where(x => x.Type == "Musket")
					.AsEnumerable()
					.Select(x => XElement.Parse(x.Definition))
					.FirstOrDefault(x =>
						double.TryParse(x.Element("BarrelBore")?.Value, System.Globalization.NumberStyles.Float,
							System.Globalization.CultureInfo.InvariantCulture, out var musketBore) &&
						Math.Abs(musketBore - bore) < 0.000001) ??
					throw new InvalidOperationException(
						$"Cannot seed MusketPaperCartridge_{boreName}: no Musket component has a matching BarrelBore value.");
				var powderMass = double.Parse(
					musketDefinition.Element("PowderVolumePerShot")?.Value ??
					throw new InvalidOperationException(
						$"Cannot seed MusketPaperCartridge_{boreName}: the matching Musket component has no PowderVolumePerShot value."),
					System.Globalization.CultureInfo.InvariantCulture);
				var definition = new XElement(baseDefinition);
				definition.Add(new XElement("PowderMass", powderMass), new XElement("IncludesWad", true));
				EnsureComponent("MusketCartridge", $"MusketPaperCartridge_{boreName}",
					$"A measured paper cartridge with powder, wad, and round ball for a {boreName} musket",
					definition.ToString());

				foreach (var item in context.GameItemProtos
							 .Include(x => x.GameItemProtosGameItemComponentProtos)
							 .Include(x => x.GameItemProtosTags)
							 .Where(x => x.GameItemProtosGameItemComponentProtos.Any(y =>
								 y.GameItemComponentProtoId == baseComponent.Id &&
								 y.GameItemComponentRevision == baseComponent.RevisionNumber)))
				{
					if (item.GameItemProtosTags.All(x => x.TagId != paperTagId))
					{
						item.GameItemProtosTags.Add(new GameItemProtosTags
						{
							GameItemProto = item,
							TagId = paperTagId,
							GameItemProtoRevisionNumber = item.RevisionNumber
						});
						added++;
					}
				}
			}
		}

		// The Early Modern catalogue deliberately keeps every weapon family as a separately named,
		// stable component.  Definitions are derived from live donors so a clean install never relies
		// on brittle database IDs from a development database.
		if (context.GameItemComponentProtos.Any(x => x.Type == "Ammunition" && x.EditableItem.RevisionStatus == 4) &&
			context.GameItemComponentProtos.Any(x => x.Type == "Musket" && x.EditableItem.RevisionStatus == 4) &&
			context.RangedWeaponTypes.Any(x => x.Name == "Flintlock Musket"))
		{
		XElement CloneDefinition(GameItemComponentProto component) => XElement.Parse(component.Definition);
		void SetElement(XElement definition, string name, object value) => definition.SetElementValue(name, value);
		var musketDonor = context.GameItemComponentProtos
			.FirstOrDefault(x => x.Type == "Musket" && x.EditableItem.RevisionStatus == 4) ??
			throw new InvalidOperationException("Cannot seed Early Modern muskets because no Musket donor component exists. Run Combat with installmuskets enabled first.");
		var cartridgeDonor = context.GameItemComponentProtos
			.FirstOrDefault(x => x.Type == "MusketCartridge" && x.EditableItem.RevisionStatus == 4) ??
			throw new InvalidOperationException("Cannot seed Early Modern cartridge profiles because no MusketCartridge donor component exists.");
		var ammunitionDonor = context.GameItemComponentProtos
			.FirstOrDefault(x => x.Type == "Ammunition" && x.EditableItem.RevisionStatus == 4) ??
			throw new InvalidOperationException("Cannot seed artillery ammunition because no Ammunition donor component exists. Run Combat with installranged enabled first.");

		AmmunitionTypes EnsureArtilleryAmmunitionType(string name, string profile, ArtilleryPayloadType payload,
			int projectileCount, RangedScatterType? scatterType, double spreadPenalty, string damage)
		{
			var existing = context.AmmunitionTypes.FirstOrDefault(x => x.Name == name);
			if (existing is not null)
			{
				var changed = existing.RangedWeaponTypes != ((int)RangedWeaponType.Artillery).ToString() ||
					existing.ProjectileCount != projectileCount || existing.ScatterType != (int?)scatterType ||
					Math.Abs(existing.SpreadPenalty - spreadPenalty) > 0.0001 || existing.DamageExpression != damage;
				existing.SpecificType = profile;
				existing.RangedWeaponTypes = ((int)RangedWeaponType.Artillery).ToString();
				existing.ProjectileCount = projectileCount;
				existing.ScatterType = scatterType is null ? null : (int)scatterType.Value;
				existing.SpreadPenalty = spreadPenalty;
				existing.DamageExpression = damage;
				existing.StunExpression = damage;
				existing.PainExpression = damage;
				if (changed) added++;
				return existing;
			}

			var ammunition = new AmmunitionTypes
			{
				Name = name,
				SpecificType = profile,
				RangedWeaponTypes = ((int)RangedWeaponType.Artillery).ToString(),
				BaseAccuracy = 0.0,
				Loudness = (int)AudioVolume.ExtremelyLoud,
				BreakChanceOnHit = payload is ArtilleryPayloadType.StoneShot ? 0.75 : 0.15,
				BreakChanceOnMiss = payload is ArtilleryPayloadType.StoneShot ? 0.9 : 0.25,
				BaseBlockDifficulty = (int)Difficulty.Impossible,
				BaseDodgeDifficulty = (int)Difficulty.Insane,
				DamageExpression = damage,
				StunExpression = damage,
				PainExpression = damage,
				DamageType = (int)DamageType.Ballistic,
				ProjectileCount = projectileCount,
				ScatterType = scatterType is null ? null : (int)scatterType.Value,
				SpreadPenalty = spreadPenalty
			};
			context.AmmunitionTypes.Add(ammunition);
			context.SaveChanges();
			added++;
			return ammunition;
		}

		string ArtilleryProfileForPiece(string name) => name switch
		{
			var x when x.Contains("Swivel") || x.Contains("Falcon") || x.Contains("Peterero") || x.Contains("Coehorn") => "light",
			var x when x.Contains("Demi") || x.Contains("Saker") || x.Contains("FieldGun3") || x.Contains("FieldGun6") || x.Contains("FieldMortar") => "medium",
			_ => "heavy"
		};

		(string Profile, ArtilleryPayloadType Payload, int ProjectileCount, RangedScatterType? Scatter, double SpreadPenalty, string Damage) ArtilleryAmmunitionData(string name)
		{
			var payload = name.Contains("Grape") ? ArtilleryPayloadType.Grapeshot :
				name.Contains("Case") ? ArtilleryPayloadType.CaseShot : name.Contains("Carcass") ? ArtilleryPayloadType.Carcass :
				name.Contains("Shell") ? ArtilleryPayloadType.Shell : name.Contains("Stone") ? ArtilleryPayloadType.StoneShot :
				name.Contains("Bar") ? ArtilleryPayloadType.BarShot : ArtilleryPayloadType.SolidShot;
			var profile = name.Contains("1lb") || name.Contains("3lb") || name.Contains("6lb") || name.Contains("Light") ? "light" :
				name.Contains("9lb") || name.Contains("12lb") || name.Contains("Medium") ? "medium" : "heavy";
			var count = name.Contains("Grapeshot_Light") ? 6 : name.Contains("Grapeshot_Medium") ? 9 :
				name.Contains("Grapeshot_Heavy") ? 12 : payload == ArtilleryPayloadType.CaseShot ? 10 : 1;
			var scatter = count > 1 ? RangedScatterType.Spread : (RangedScatterType?)null;
			var damage = payload switch
			{
				ArtilleryPayloadType.Grapeshot or ArtilleryPayloadType.CaseShot => "8 + degree * 3",
				ArtilleryPayloadType.StoneShot => "18 + degree * 5",
				ArtilleryPayloadType.Shell or ArtilleryPayloadType.Carcass => "22 + degree * 6",
				_ => "30 + degree * 8"
			};
			return (profile, payload, count, scatter, count > 1 ? 0.45 : 0.0, damage);
		}

		var musketProfiles = new (string Name, string Ignition, double Bore, bool Rifled, bool Rested)[]
		{
			("Musket_Doglock_Blunderbuss75", "Doglock", 0.75, false, false), ("Musket_Doglock_Carbine60", "Doglock", 0.60, false, false), ("Musket_Doglock_Musket70", "Doglock", 0.70, false, false),
			("Musket_Flintlock_Blunderbuss75", "Flintlock", 0.75, false, false), ("Musket_Flintlock_Carbine60", "Flintlock", 0.60, false, false), ("Musket_Flintlock_FowlingPiece60", "Flintlock", 0.60, false, false), ("Musket_Flintlock_WallGun80", "Flintlock", 0.80, false, true),
			("Musket_Matchlock_Arquebus55", "Matchlock", 0.55, false, false), ("Musket_Matchlock_Blunderbuss75", "Matchlock", 0.75, false, false), ("Musket_Matchlock_Caliver60", "Matchlock", 0.60, false, false), ("Musket_Matchlock_Carbine60", "Matchlock", 0.60, false, false), ("Musket_Matchlock_FowlingPiece60", "Matchlock", 0.60, false, false), ("Musket_Matchlock_HeavyMusket80", "Matchlock", 0.80, false, true), ("Musket_Matchlock_Jezail65", "Matchlock", 0.65, true, false), ("Musket_Matchlock_Musket75", "Matchlock", 0.75, false, false), ("Musket_Matchlock_Tanegashima60", "Matchlock", 0.60, false, false), ("Musket_Matchlock_Toradar65", "Matchlock", 0.65, true, false), ("Musket_Matchlock_WallGun80", "Matchlock", 0.80, false, true),
			("Musket_Miquelet_Blunderbuss75", "Miquelet", 0.75, false, false), ("Musket_Miquelet_Carbine60", "Miquelet", 0.60, false, false), ("Musket_Miquelet_Escopeta65", "Miquelet", 0.65, false, false), ("Musket_Miquelet_Musket70", "Miquelet", 0.70, false, false),
			("Musket_Snaphaunce_Carbine60", "Snaphaunce", 0.60, false, false), ("Musket_Snaphaunce_FowlingPiece60", "Snaphaunce", 0.60, false, false), ("Musket_Snaphaunce_LongGun65", "Snaphaunce", 0.65, true, false), ("Musket_Snaphaunce_Musket70", "Snaphaunce", 0.70, false, false),
			("Musket_Wheellock_Carbine60", "Wheellock", 0.60, false, false), ("Musket_Wheellock_FowlingPiece60", "Wheellock", 0.60, false, false), ("Musket_Wheellock_LongGun65", "Wheellock", 0.65, true, false), ("Musket_Wheellock_Rifle55", "Wheellock", 0.55, true, false),
			("Pistol_Doglock55", "Doglock", 0.55, false, false), ("Pistol_Flintlock_Duelling45", "Flintlock", 0.45, true, false), ("Pistol_Matchlock55", "Matchlock", 0.55, false, false), ("Pistol_Miquelet55", "Miquelet", 0.55, false, false), ("Pistol_Snaphaunce55", "Snaphaunce", 0.55, false, false), ("Pistol_Wheellock45", "Wheellock", 0.45, true, false), ("Pistol_Wheellock55", "Wheellock", 0.55, false, false)
		};
		foreach (var profile in musketProfiles)
		{
			var ranged = EnsureRanged(profile.Name.Replace('_', ' '), profile.Name, "Musket", "Flintlock Musket", x =>
			{
				if (profile.Rifled)
				{
					x.DefaultRangeInRooms += 2;
					x.LoadDelay *= 1.2;
				}
				if (profile.Rested)
				{
					x.StaminaToFire *= 0.75;
				}
			});
			var definition = CloneDefinition(musketDonor);
			SetElement(definition, "RangedWeaponType", ranged.Id);
			SetElement(definition, "BarrelBore", profile.Bore.ToString(System.Globalization.CultureInfo.InvariantCulture));
			SetElement(definition, "Ignition", profile.Ignition);
			SetElement(definition, "Rifled", profile.Rifled);
			SetElement(definition, "RequiresRest", profile.Rested);
			EnsureComponent("Musket", profile.Name, $"An {profile.Ignition.ToLowerInvariant()} {profile.Name.Replace('_', ' ').ToLowerInvariant()} profile", definition.ToString());
		}

		foreach (var (name, donorName, capacity, emplaced) in new[]
		{
			("Crossbow_Repeating", "Crossbow", 8, false), ("Crossbow_Repeating_Light", "Hand Crossbow", 6, false), ("Crossbow_Wall", "Crossbow", 1, true)
		})
		{
			var ranged = EnsureRanged(name.Replace('_', ' '), name, "Crossbow", donorName, x => x.AmmunitionCapacity = capacity);
			var component = context.GameItemComponentProtos.Single(x => x.Name == name && x.EditableItem.RevisionStatus == 4);
			var definition = CloneDefinition(component);
			SetElement(definition, "MagazineCapacity", capacity);
			SetElement(definition, "RequiresEmplacement", emplaced);
			component.Definition = definition.ToString();
		}

		foreach (var (name, bore, projectileCount) in new[]
		{
			("MusketBuckshot_0.55 Bore", 0.55, 8), ("MusketBuckshot_0.75 Bore", 0.75, 12), ("MusketBuckAndBall_0.65 Bore", 0.65, 7), ("MusketBuckAndBall_0.75 Bore", 0.75, 9)
		})
		{
			var definition = CloneDefinition(cartridgeDonor);
			SetElement(definition, "BulletBore", bore.ToString(System.Globalization.CultureInfo.InvariantCulture));
			SetElement(definition, "ProjectileCount", projectileCount);
			EnsureComponent("MusketCartridge", name, $"A multi-projectile musket cartridge for {bore:0.00} bore firearms", definition.ToString());
		}

		foreach (var name in EarlyModernMilitaryCompletionComponentNames.Where(x => x.StartsWith("Artillery_")).ToList())
		{
			var gunnery = context.TraitDefinitions.FirstOrDefault(x => x.Name == "Gunnery") ??
				throw new InvalidOperationException("Cannot seed artillery profiles because the Gunnery trait is missing.");
			var ranged = EnsureRanged(name.Replace('_', ' '), name, "ArtilleryPiece", "Flintlock Musket", x =>
			{
				x.RangedWeaponType = (int)RangedWeaponType.Artillery;
				x.FireTraitId = gunnery.Id;
				x.OperateTraitId = gunnery.Id;
				x.DefaultRangeInRooms = Math.Max(x.DefaultRangeInRooms, 8);
			});
			var mechanism = name == "Artillery_Peterero" ? "RemovableChamber" : "MuzzleLoading";
			EnsureComponent("ArtilleryPiece", name, $"A crew-served {name.Replace('_', ' ').ToLowerInvariant()}",
				new XElement("Definition", new XElement("RangedWeaponType", ranged.Id), new XElement("ArtilleryProfile", ArtilleryProfileForPiece(name)),
					new XElement("LoadingMechanism", mechanism), new XElement("MinimumCrew", name.Contains("Swivel") ? 1 : 3), new XElement("RequiresEmplacement", true)).ToString());
		}

		foreach (var name in EarlyModernMilitaryCompletionComponentNames.Where(x => x.StartsWith("ArtilleryShot_") || x.StartsWith("ArtilleryStone") || x.StartsWith("ArtilleryGrape") || x.StartsWith("ArtilleryCase") || x.StartsWith("ArtilleryShell")))
		{
			var data = ArtilleryAmmunitionData(name);
			var ammoType = EnsureArtilleryAmmunitionType(name.Replace('_', ' '), data.Profile, data.Payload,
				data.ProjectileCount, data.Scatter, data.SpreadPenalty, data.Damage);
			var definition = CloneDefinition(ammunitionDonor);
			SetElement(definition, "AmmoType", ammoType.Id);
			SetElement(definition, "ArtilleryProfile", data.Profile);
			SetElement(definition, "PayloadType", data.Payload);
			EnsureComponent("ArtilleryAmmunition", name, $"Artillery ammunition profile {name.Replace('_', ' ')}", definition.ToString());
		}

		EnsureComponent("ArtilleryMount", "ArtilleryMount_Swivel", "A configurable swivel-gun mount",
			new XElement("Definition", new XElement("Fixed", false), new XElement("TraverseArc", 360), new XElement("ElevationArc", 60)).ToString());
		EnsureComponent("ArtilleryChamber", "ArtilleryChamber_Peterero", "A reusable removable chamber for a peterero", new XElement("Definition", new XElement("ArtilleryProfile", "light")).ToString());
		var sheathDonor = context.GameItemComponentProtos.FirstOrDefault(x => x.Type == "Sheath" && x.EditableItem.RevisionStatus == 4) ??
			throw new InvalidOperationException("Cannot seed Holster_PairedSaddle because no Sheath donor component exists.");
		var pairedHolster = CloneDefinition(sheathDonor);
		SetElement(pairedHolster, "Capacity", 2);
		EnsureComponent("Sheath", "Holster_PairedSaddle", "A two-slot paired saddle holster", pairedHolster.ToString());
		foreach (var (name, profile) in new[] { ("WeaponLanyard_Pistol", "pistol"), ("WeaponLoop_LongGun", "longgun"), ("WeaponSling_Carbine", "carbine"), ("WeaponSling_LongGun", "longgun") })
		{
			EnsureComponent("WeaponCarrierAttachment", name, $"A {profile} weapon carrier", new XElement("Definition", new XElement("CompatibleProfile", profile), new XElement("RetainsDroppedWeapon", true)).ToString());
		}
		}

		context.SaveChanges();
		return added;
	}
}
