#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Combat;
using MudSharp.Database;
using MudSharp.Framework;
using MudSharp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace DatabaseSeeder.Seeders;

public partial class CombatSeeder
{
	internal static IReadOnlyList<string> EraDependencyCombatComponentNamesForTesting =>
	[
		"Armour_Brigandine",
		"Armour_BuffLeather",
		"Armour_ChainAndPlate",
		"Armour_Padded",
		"Armour_PlateLight",
		"Armour_PlateMedium",
		"Armour_ProofedPlate",
		"Armour_Rattan",
		"Armour_RigidMetal",
		"Armour_CoatOfPlates",
		"Armour_Splinted",
		"Melee_Bayonet",
		"Melee_HookedPolearm",
		"Melee_Lance",
		"Melee_Poleblade",
		"Melee_Sabre",
		"Melee_Smallsword",
		"Melee_Training_Bayonet",
		"Melee_Training_Lance",
		"Melee_Training_Poleblade",
		"Melee_Training_Sabre",
		"Melee_Training_Smallsword",
		"CompositeBow_Heavy",
		"CompositeBow_Light",
		"CompositeBow_War",
		"Yumi",
		"Crossbow_EastAsian",
		"Crossbow_Heavy",
		"Crossbow_Light",
		"Crossbow_Pellet",
		"Crossbow_Cranequin",
		"Crossbow_GoatsFoot",
		"Crossbow_Lever",
		"Crossbow_SpanningHook",
		"Crossbow_Windlass",
		"Blowgun_Long",
		"Blowgun_Short",
		"Throwing_Club",
		"Throwing_Disc",
		"Bayonet_Plug",
		"Bayonet_Socket",
		"Bayonet_Sword",
		"MusketPaperCartridge_0.45 Bore",
		"MusketPaperCartridge_0.55 Bore",
		"MusketPaperCartridge_0.6 Bore",
		"MusketPaperCartridge_0.65 Bore",
		"MusketPaperCartridge_0.7 Bore",
		"MusketPaperCartridge_0.75 Bore",
		"MusketPaperCartridge_0.8 Bore"
	];

	internal int EnsureEraDependencyCombatContentForTesting(FuturemudDatabaseContext context,
		IReadOnlyDictionary<string, string> questionAnswers)
	{
		return EnsureEraDependencyCombatContent(context, questionAnswers);
	}

	private int EnsureEraDependencyCombatContent(FuturemudDatabaseContext context,
		IReadOnlyDictionary<string, string> questionAnswers)
	{
		var added = 0;
		var account = context.Accounts.First();
		var now = DateTime.UtcNow;

		EditableItem NewEditableItem()
		{
			return new EditableItem
			{
				RevisionNumber = 0,
				RevisionStatus = 4,
				BuilderAccountId = account.Id,
				BuilderDate = now,
				BuilderComment = "Auto-generated by the system",
				ReviewerAccountId = account.Id,
				ReviewerComment = "Auto-generated by the system",
				ReviewerDate = now
			};
		}

		GameItemComponentProto EnsureComponent(string type, string name, string description, string definition)
		{
			var existing = context.GameItemComponentProtos
				.FirstOrDefault(x => x.Name == name && x.EditableItem.RevisionStatus == 4);
			if (existing is not null)
			{
				existing.Type = type;
				existing.Description = description;
				existing.Definition = definition;
				return existing;
			}

			var component = new GameItemComponentProto
			{
				Id = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1,
				RevisionNumber = 0,
				EditableItem = NewEditableItem(),
				Type = type,
				Name = name,
				Description = description,
				Definition = definition
			};
			context.GameItemComponentProtos.Add(component);
			context.SaveChanges();
			added++;
			return component;
		}

		ArmourType EnsureArmour(string name, string componentName, string donorName, int penetration,
			double baseDifficulty, double stackedDifficulty)
		{
			var donor = context.ArmourTypes.FirstOrDefault(x => x.Name == donorName) ??
			            throw new InvalidOperationException(
				            $"Cannot seed {componentName}: the foundational armour type '{donorName}' is missing. " +
				            "Run Combat with the installweapons choice enabled first.");
			var armour = context.ArmourTypes.FirstOrDefault(x => x.Name == name);
			if (armour is null)
			{
				armour = new ArmourType
				{
					Name = name,
				};
				context.ArmourTypes.Add(armour);
				added++;
			}

			armour.MinimumPenetrationDegree = penetration;
			armour.BaseDifficultyDegrees = baseDifficulty;
			armour.StackedDifficultyDegrees = stackedDifficulty;
			armour.Definition = donor.Definition;
			context.SaveChanges();

			EnsureComponent("Armour", componentName, $"Turns an item into {name} armour",
				$"<Definition><ArmourType>{armour.Id}</ArmourType></Definition>");
			return armour;
		}

		WeaponType EnsureWeapon(string name, string componentName, string donorName, WeaponClassification classification,
			int? reach = null, double? parryBonus = null)
		{
			var donor = context.WeaponTypes
				.Include(x => x.WeaponAttacks)
				.ThenInclude(x => x.CombatMessagesWeaponAttacks)
				.FirstOrDefault(x => x.Name == donorName) ??
			            throw new InvalidOperationException(
				            $"Cannot seed {componentName}: the foundational weapon type '{donorName}' is missing. " +
				            "Run Combat with the installweapons choice enabled first.");
			var weapon = context.WeaponTypes.FirstOrDefault(x => x.Name == name);
			if (weapon is null)
			{
				weapon = new WeaponType
				{
					Name = name,
				};
				context.WeaponTypes.Add(weapon);
				added++;
			}

			weapon.Classification = (int)classification;
			weapon.AttackTraitId = donor.AttackTraitId;
			weapon.ParryTraitId = donor.ParryTraitId;
			weapon.ParryBonus = parryBonus ?? donor.ParryBonus;
			weapon.Reach = reach ?? donor.Reach;
			weapon.StaminaPerParry = donor.StaminaPerParry;
			context.SaveChanges();

			foreach (var donorAttack in donor.WeaponAttacks)
			{
				var attackName = $"{name}: {donorAttack.Name}";
				var attack = context.WeaponAttacks
					.Include(x => x.CombatMessagesWeaponAttacks)
					.FirstOrDefault(x => x.WeaponTypeId == weapon.Id && x.Name == attackName);
				if (attack is null)
				{
					attack = new WeaponAttack
					{
						WeaponTypeId = weapon.Id,
						Name = attackName
					};
					context.WeaponAttacks.Add(attack);
					added++;
				}

				attack.Verb = donorAttack.Verb;
				attack.FutureProgId = donorAttack.FutureProgId;
				attack.BaseAttackerDifficulty = donorAttack.BaseAttackerDifficulty;
				attack.BaseBlockDifficulty = donorAttack.BaseBlockDifficulty;
				attack.BaseDodgeDifficulty = donorAttack.BaseDodgeDifficulty;
				attack.BaseParryDifficulty = donorAttack.BaseParryDifficulty;
				attack.BaseAngleOfIncidence = donorAttack.BaseAngleOfIncidence;
				attack.RecoveryDifficultySuccess = donorAttack.RecoveryDifficultySuccess;
				attack.RecoveryDifficultyFailure = donorAttack.RecoveryDifficultyFailure;
				attack.MoveType = donorAttack.MoveType;
				attack.Intentions = donorAttack.Intentions;
				attack.ExertionLevel = donorAttack.ExertionLevel;
				attack.DamageType = donorAttack.DamageType;
				attack.DamageExpressionId = donorAttack.DamageExpressionId;
				attack.StunExpressionId = donorAttack.StunExpressionId;
				attack.PainExpressionId = donorAttack.PainExpressionId;
				attack.Weighting = donorAttack.Weighting;
				attack.MaximumTargets = donorAttack.MaximumTargets;
				attack.BodypartShapeId = donorAttack.BodypartShapeId;
				attack.StaminaCost = donorAttack.StaminaCost;
				attack.BaseDelay = donorAttack.BaseDelay;
				attack.Orientation = donorAttack.Orientation;
				attack.Alignment = donorAttack.Alignment;
				attack.AdditionalInfo = donorAttack.AdditionalInfo;
				attack.HandednessOptions = donorAttack.HandednessOptions;
				attack.RequiredPositionStateIds = donorAttack.RequiredPositionStateIds;
				attack.OnUseProgId = donorAttack.OnUseProgId;
				context.SaveChanges();

				foreach (var message in donorAttack.CombatMessagesWeaponAttacks)
				{
					if (attack.CombatMessagesWeaponAttacks.Any(x => x.CombatMessageId == message.CombatMessageId))
					{
						continue;
					}

					context.CombatMessagesWeaponAttacks.Add(new CombatMessagesWeaponAttacks
					{
						CombatMessageId = message.CombatMessageId,
						WeaponAttackId = attack.Id
					});
				}

				context.SaveChanges();
			}

			EnsureComponent("MeleeWeapon", componentName, $"Turns an item into a {name} melee weapon",
				$"<Definition><WeaponType>{weapon.Id}</WeaponType></Definition>");
			return weapon;
		}

		RangedWeaponTypes EnsureRanged(string name, string componentName, string componentType, string donorName,
			Action<RangedWeaponTypes>? configure = null, string? meleeDonorName = null)
		{
			var donor = context.RangedWeaponTypes.FirstOrDefault(x => x.Name == donorName) ??
			            throw new InvalidOperationException(
				            $"Cannot seed {componentName}: the foundational ranged-weapon type '{donorName}' is missing. " +
				            "Run Combat with the installranged choice enabled first.");
			var ranged = context.RangedWeaponTypes.FirstOrDefault(x => x.Name == name);
			if (ranged is null)
			{
				ranged = new RangedWeaponTypes
				{
					Name = name,
				};
				context.RangedWeaponTypes.Add(ranged);
				added++;
			}

			ranged.Classification = donor.Classification;
			ranged.FireTraitId = donor.FireTraitId;
			ranged.OperateTraitId = donor.OperateTraitId;
			ranged.FireableInMelee = donor.FireableInMelee;
			ranged.DefaultRangeInRooms = donor.DefaultRangeInRooms;
			ranged.AccuracyBonusExpression = donor.AccuracyBonusExpression;
			ranged.DamageBonusExpression = donor.DamageBonusExpression;
			ranged.AmmunitionLoadType = donor.AmmunitionLoadType;
			ranged.SpecificAmmunitionGrade = donor.SpecificAmmunitionGrade;
			ranged.AmmunitionCapacity = donor.AmmunitionCapacity;
			ranged.RangedWeaponType = donor.RangedWeaponType;
			ranged.StaminaToFire = donor.StaminaToFire;
			ranged.StaminaPerLoadStage = donor.StaminaPerLoadStage;
			ranged.CoverBonus = donor.CoverBonus;
			ranged.BaseAimDifficulty = donor.BaseAimDifficulty;
			ranged.LoadDelay = donor.LoadDelay;
			ranged.ReadyDelay = donor.ReadyDelay;
			ranged.FireDelay = donor.FireDelay;
			ranged.AimBonusLostPerShot = donor.AimBonusLostPerShot;
			ranged.RequiresFreeHandToReady = donor.RequiresFreeHandToReady;
			ranged.AlwaysRequiresTwoHandsToWield = donor.AlwaysRequiresTwoHandsToWield;
			configure?.Invoke(ranged);
			context.SaveChanges();

			var meleeElement = meleeDonorName is null
				? string.Empty
				: $"<MeleeWeaponType>{(context.WeaponTypes.FirstOrDefault(x => x.Name == meleeDonorName) ??
					throw new InvalidOperationException(
						$"Cannot seed {componentName}: the foundational weapon type '{meleeDonorName}' is missing. " +
						"Run Combat with the installweapons choice enabled first.")).Id}</MeleeWeaponType>";
			EnsureComponent(componentType, componentName, $"Turns an item into a {name}",
				$"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType>{meleeElement}</Definition>");
			return ranged;
		}

		long RequireTagId(string name)
		{
			return context.Tags
				       .AsEnumerable()
				       .SingleOrDefault(x => x.Name.Equals(name, StringComparison.OrdinalIgnoreCase))?.Id ??
			       throw new InvalidOperationException(
				       $"Cannot seed combat profile: the required tag '{name}' is missing. Run the Useful Items package first.");
		}

		void EnsureSpannedCrossbow(string name, string componentName, string toolTagName,
			Action<RangedWeaponTypes> configure)
		{
			var ranged = EnsureRanged(name, componentName, "Crossbow", "Crossbow", configure);
			var component = context.GameItemComponentProtos.Single(x =>
				x.Name == componentName && x.EditableItem.RevisionStatus == 4);
			component.Definition = new XElement("Definition",
				new XElement("RangedWeaponType", ranged.Id),
				new XElement("RequiredSpanningToolTag", RequireTagId(toolTagName)),
				new XElement("ReadyEmote",
					new XCData("@ use|uses $2 to span and ready $1, drawing its string into the firing catch.")))
				.ToString();
		}

		if (questionAnswers["installweapons"].EqualToAny("yes", "y"))
		{
			EnsureArmour("Brigandine", "Armour_Brigandine", "Metal Scale", 1, 1, 2);
			EnsureArmour("Buff Leather", "Armour_BuffLeather", "Boiled Leather", 1, 1, 2);
			EnsureArmour("Chain and Plate", "Armour_ChainAndPlate", "Platemail", 1, 2, 3);
			EnsureArmour("Padded", "Armour_Padded", "Ultra Heavy Clothing", 1, 1, 2);
			EnsureArmour("Plate Light", "Armour_PlateLight", "Platemail", 1, 1, 2);
			EnsureArmour("Plate Medium", "Armour_PlateMedium", "Platemail", 1, 2, 3);
			EnsureArmour("Proofed Plate", "Armour_ProofedPlate", "Platemail", 2, 2, 4);
			EnsureArmour("Rattan", "Armour_Rattan", "Leather Scale", 1, 1, 2);
			EnsureArmour("Rigid Metal", "Armour_RigidMetal", "Platemail", 1, 2, 3);
			EnsureArmour("Coat of Plates", "Armour_CoatOfPlates", "Platemail", 1, 2, 3);
			EnsureArmour("Splinted", "Armour_Splinted", "Studded Leather", 1, 1, 2);

			EnsureWeapon("Bayonet", "Melee_Bayonet", "Dagger", WeaponClassification.Lethal, 2);
			EnsureWeapon("Hooked Polearm", "Melee_HookedPolearm", "Halberd", WeaponClassification.Lethal, 4);
			EnsureWeapon("Lance", "Melee_Lance", "Long Spear", WeaponClassification.Lethal, 5);
			EnsureWeapon("Poleblade", "Melee_Poleblade", "Halberd", WeaponClassification.Lethal, 4);
			EnsureWeapon("Sabre", "Melee_Sabre", "Longsword", WeaponClassification.Lethal, 3);
			EnsureWeapon("Smallsword", "Melee_Smallsword", "Rapier", WeaponClassification.Lethal, 2);
			EnsureWeapon("Training Bayonet", "Melee_Training_Bayonet", "Training Dagger",
				WeaponClassification.Training, 2);
			EnsureWeapon("Training Lance", "Melee_Training_Lance", "Training Spear",
				WeaponClassification.Training, 5);
			EnsureWeapon("Training Poleblade", "Melee_Training_Poleblade", "Training Halberd",
				WeaponClassification.Training, 4);
			EnsureWeapon("Training Sabre", "Melee_Training_Sabre", "Training Longsword",
				WeaponClassification.Training, 3);
			EnsureWeapon("Training Smallsword", "Melee_Training_Smallsword", "Training Rapier",
				WeaponClassification.Training, 2);

			foreach (var (name, style) in new[]
			         {
				         ("Bayonet_Plug", "Plug"),
				         ("Bayonet_Socket", "Socket"),
				         ("Bayonet_Sword", "Sword")
			         })
			{
				EnsureComponent("BayonetAttachment", name,
					$"Turns an item into a {style.ToLowerInvariant()} bayonet attachment",
					new XElement("Definition",
						new XElement("Style", style),
						new XElement("MinimumBore", 0.45),
						new XElement("MaximumBore", 0.8))
						.ToString());
			}
		}

		if (questionAnswers["installranged"].EqualToAny("yes", "y"))
		{
			EnsureRanged("Composite Bow Heavy", "CompositeBow_Heavy", "Bow", "Longbow", x =>
			{
				x.DefaultRangeInRooms = 5;
				x.StaminaPerLoadStage *= 1.2;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 3";
			});
			EnsureRanged("Composite Bow Light", "CompositeBow_Light", "Bow", "Shortbow", x =>
			{
				x.DefaultRangeInRooms = Math.Max(3, x.DefaultRangeInRooms);
				x.LoadDelay *= 0.8;
			});
			EnsureRanged("Composite Bow War", "CompositeBow_War", "Bow", "Longbow", x =>
			{
				x.DefaultRangeInRooms = 4;
				x.LoadDelay *= 0.9;
			});
			EnsureRanged("Yumi", "Yumi", "Bow", "Longbow", x =>
			{
				x.DefaultRangeInRooms = 5;
				x.AlwaysRequiresTwoHandsToWield = true;
			});

			EnsureRanged("East Asian Crossbow", "Crossbow_EastAsian", "Crossbow", "Crossbow");
			EnsureRanged("Heavy Crossbow", "Crossbow_Heavy", "Crossbow", "Crossbow", x =>
			{
				x.DefaultRangeInRooms = 5;
				x.LoadDelay *= 1.5;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 4";
			});
			EnsureRanged("Light Crossbow", "Crossbow_Light", "Crossbow", "Hand Crossbow", x =>
			{
				x.DefaultRangeInRooms = 3;
				x.AlwaysRequiresTwoHandsToWield = false;
			});
			EnsureRanged("Pellet Crossbow", "Crossbow_Pellet", "Crossbow", "Crossbow", x =>
			{
				x.DefaultRangeInRooms = 2;
				x.SpecificAmmunitionGrade = "Sling Bullet";
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) - 3";
			});
			EnsureSpannedCrossbow("Cranequin Crossbow", "Crossbow_Cranequin", "Cranequin", x =>
			{
				x.ReadyDelay *= 3.0;
				x.StaminaPerLoadStage *= 0.9;
				x.DefaultRangeInRooms = 6;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 6";
			});
			EnsureSpannedCrossbow("Goat's Foot Crossbow", "Crossbow_GoatsFoot", "Goat's Foot", x =>
			{
				x.ReadyDelay *= 1.5;
				x.StaminaPerLoadStage *= 1.15;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 2";
			});
			EnsureSpannedCrossbow("Lever Crossbow", "Crossbow_Lever", "Lever", x =>
			{
				x.ReadyDelay *= 1.75;
				x.StaminaPerLoadStage *= 1.2;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 3";
			});
			EnsureSpannedCrossbow("Spanning Hook Crossbow", "Crossbow_SpanningHook", "Spanning Hook", x =>
			{
				x.ReadyDelay *= 1.25;
				x.StaminaPerLoadStage *= 1.1;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 1";
			});
			EnsureSpannedCrossbow("Windlass Crossbow", "Crossbow_Windlass", "Windlass", x =>
			{
				x.ReadyDelay *= 2.5;
				x.DefaultRangeInRooms = 5;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) + 5";
			});

			EnsureRanged("Long Blowgun", "Blowgun_Long", "Blowgun", "Blowgun", x =>
			{
				x.DefaultRangeInRooms = 2;
				x.AlwaysRequiresTwoHandsToWield = true;
			});
			EnsureRanged("Short Blowgun", "Blowgun_Short", "Blowgun", "Blowgun", x =>
			{
				x.DefaultRangeInRooms = 1;
				x.AlwaysRequiresTwoHandsToWield = false;
				x.LoadDelay *= 0.8;
			});
			EnsureRanged("Throwing Club", "Throwing_Club", "ThrownWeapon", "Throwing Axe", null, "Club");
			EnsureRanged("Throwing Disc", "Throwing_Disc", "ThrownWeapon", "Throwing Knife", x =>
			{
				x.DefaultRangeInRooms = 1;
				x.DamageBonusExpression = $"({x.DamageBonusExpression}) - 2";
			}, "Dagger");

			var slingBullet = context.AmmunitionTypes.FirstOrDefault(x => x.Name == "Sling Bullet") ??
			                  throw new InvalidOperationException(
				                  "Cannot seed Crossbow_Pellet: the foundational ammunition type 'Sling Bullet' is missing. " +
				                  "Run Combat with the installranged choice enabled first.");
			var types = slingBullet.RangedWeaponTypes
				.Split(' ', StringSplitOptions.RemoveEmptyEntries)
				.ToHashSet(StringComparer.Ordinal);
			if (types.Add(((int)RangedWeaponType.Crossbow).ToString()))
			{
				slingBullet.RangedWeaponTypes = types.OrderBy(x => x).ListToCommaSeparatedValues(" ");
				added++;
			}
		}

		if (questionAnswers.TryGetValue("installmuskets", out var installMuskets) &&
		    installMuskets.EqualToAny("yes", "y"))
		{
			var paperTagId = RequireTagId("Paper Cartridges");
			foreach (var boreName in new[] { "0.45 Bore", "0.55 Bore", "0.6 Bore", "0.65 Bore", "0.7 Bore", "0.75 Bore", "0.8 Bore" })
			{
				var baseComponent = context.GameItemComponentProtos
					.Single(x => x.Name == $"MusketCartridge_{boreName}" && x.EditableItem.RevisionStatus == 4);
				var baseDefinition = XElement.Parse(baseComponent.Definition);
				var bore = double.Parse(baseDefinition.Element("BulletBore")!.Value);
				var musketDefinition = context.GameItemComponentProtos
					.Where(x => x.Type == "Musket")
					.AsEnumerable()
					.Select(x => XElement.Parse(x.Definition))
					.First(x => Math.Abs(double.Parse(x.Element("BulletBore")!.Value) - bore) < 0.000001);
				var powderMass = double.Parse(musketDefinition.Element("PowderVolumePerShot")!.Value);
				var definition = new XElement(baseDefinition);
				definition.Add(new XElement("PowderMass", powderMass), new XElement("IncludesWad", true));
				EnsureComponent("MusketCartridge", $"MusketPaperCartridge_{boreName}",
					$"A measured paper cartridge with powder, wad, and round ball for a {boreName} musket",
					definition.ToString());

				foreach (var item in context.GameItemProtos
					         .Include(x => x.GameItemProtosGameItemComponentProtos)
					         .Include(x => x.GameItemProtosTags)
					         .Where(x => x.GameItemProtosGameItemComponentProtos.Any(y =>
						         y.GameItemComponentProtoId == baseComponent.Id &&
						         y.GameItemComponentRevision == baseComponent.RevisionNumber)))
				{
					if (item.GameItemProtosTags.All(x => x.TagId != paperTagId))
					{
						item.GameItemProtosTags.Add(new GameItemProtosTags
						{
							GameItemProto = item,
							TagId = paperTagId,
							GameItemProtoRevisionNumber = item.RevisionNumber
						});
						added++;
					}
				}
			}
		}

		context.SaveChanges();
		return added;
	}
}
