#nullable enable

using MudSharp.Body.Traits;
using MudSharp.Combat;
using MudSharp.Construction;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Framework;
using MudSharp.GameItems;
using MudSharp.GameItems.Interfaces;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace DatabaseSeeder.Seeders;

public partial class CombatSeeder
{
	private int EnsureModernFirearmSamples(FuturemudDatabaseContext context)
	{
		var changes = 0;
		var account = context.Accounts.First();
		var now = DateTime.UtcNow;

		EditableItem CreateEditableItem()
		{
			return new EditableItem
			{
				RevisionNumber = 0,
				RevisionStatus = 4,
				BuilderAccountId = account.Id,
				BuilderDate = now,
				BuilderComment = "Auto-generated by the system",
				ReviewerAccountId = account.Id,
				ReviewerComment = "Auto-generated by the system",
				ReviewerDate = now
			};
		}

		TraitDefinition EnsureLongarmsSkill()
		{
			var existing = context.TraitDefinitions.FirstOrDefault(x => x.Name == "Longarms");
			if (existing is not null)
			{
				return existing;
			}

			var dexterity = context.TraitDefinitions
				.Where(x => x.Type == 1 || x.Type == 3)
				.FirstOrDefault(x => x.Name == "Agility" || x.Name == "Dexterity" || x.Name == "Speed") ??
			                context.TraitDefinitions.First(x => x.Type == 1 || x.Type == 3);
			var expression = new TraitExpression
			{
				Name = "Longarms Skill Cap",
				Expression = $"min(99,5.5*{dexterity.Alias}:{dexterity.Id})"
			};
			var skill = new TraitDefinition
			{
				Name = "Longarms",
				Type = (int)TraitType.Skill,
				Expression = expression,
				TraitGroup = "Combat",
				AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
				TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
				LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
				TeachDifficulty = 7,
				LearnDifficulty = 7,
				Hidden = false,
				ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
				DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
				DerivedType = 0,
				ChargenBlurb = string.Empty,
				BranchMultiplier = 1.0
			};
			context.TraitDefinitions.Add(skill);
			context.SaveChanges();
			changes++;
			return skill;
		}

		RangedWeaponTypes EnsureRangedType(string name, string grade, AmmunitionLoadType loadType,
			int ammunitionCapacity, bool fireableInMelee, int range, double stamina, double fireDelay,
			double aimLoss)
		{
			var existing = context.RangedWeaponTypes.FirstOrDefault(x => x.Name == name);
			if (existing is not null)
			{
				var repaired = false;
				if (existing.AmmunitionLoadType != (int)loadType)
				{
					existing.AmmunitionLoadType = (int)loadType;
					repaired = true;
				}

				if (existing.AmmunitionCapacity != ammunitionCapacity)
				{
					existing.AmmunitionCapacity = ammunitionCapacity;
					repaired = true;
				}

				if (repaired)
				{
					changes++;
				}

				return existing;
			}

			var skill = EnsureLongarmsSkill();
			var ranged = new RangedWeaponTypes
			{
				Name = name,
				Classification = (int)WeaponClassification.Lethal,
				FireTrait = skill,
				OperateTrait = skill,
				FireableInMelee = fireableInMelee,
				DefaultRangeInRooms = range,
				AccuracyBonusExpression = "(-1.5*range)-(pow(1-aim,2)*4.0)",
				DamageBonusExpression = "-6*range",
				AmmunitionLoadType = (int)loadType,
				SpecificAmmunitionGrade = grade,
				AmmunitionCapacity = ammunitionCapacity,
				RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
				StaminaToFire = stamina,
				StaminaPerLoadStage = 7.0,
				CoverBonus = -3.0,
				BaseAimDifficulty = (int)Difficulty.Normal,
				LoadDelay = 1.2,
				ReadyDelay = 0.4,
				FireDelay = fireDelay,
				AimBonusLostPerShot = aimLoss,
				RequiresFreeHandToReady = true,
				AlwaysRequiresTwoHandsToWield = true
			};
			context.RangedWeaponTypes.Add(ranged);
			context.SaveChanges();
			changes++;
			return ranged;
		}

		AmmunitionTypes EnsureAmmunition(string name, string grade, int projectiles, RangedScatterType? scatterType,
			double spreadPenalty, string damage)
		{
			var existing = context.AmmunitionTypes.FirstOrDefault(x => x.Name == name);
			if (existing is not null)
			{
				var repaired = false;
				if (existing.ProjectileCount != projectiles)
				{
					existing.ProjectileCount = projectiles;
					repaired = true;
				}

				int? scatterValue = scatterType is null ? null : (int)scatterType.Value;
				if (existing.ScatterType != scatterValue)
				{
					existing.ScatterType = scatterValue;
					repaired = true;
				}

				if (Math.Abs(existing.SpreadPenalty - spreadPenalty) > 0.0001)
				{
					existing.SpreadPenalty = spreadPenalty;
					repaired = true;
				}

				if (repaired)
				{
					changes++;
				}

				return existing;
			}

			var ammunition = new AmmunitionTypes
			{
				Name = name,
				SpecificType = grade,
				RangedWeaponTypes = ((int)RangedWeaponType.ModernFirearm).ToString(),
				BaseAccuracy = 0.0,
				Loudness = (int)AudioVolume.ExtremelyLoud,
				BreakChanceOnHit = 0.2,
				BreakChanceOnMiss = 0.5,
				BaseBlockDifficulty = (int)Difficulty.Insane,
				BaseDodgeDifficulty = (int)Difficulty.Insane,
				DamageExpression = damage,
				StunExpression = damage,
				PainExpression = damage,
				DamageType = (int)DamageType.Ballistic,
				ProjectileCount = projectiles,
				ScatterType = scatterType is null ? null : (int)scatterType.Value,
				SpreadPenalty = spreadPenalty
			};
			context.AmmunitionTypes.Add(ammunition);
			context.SaveChanges();
			changes++;
			return ammunition;
		}

		GameItemComponentProto EnsureComponent(string type, string name, string description, XElement definition)
		{
			var existing = context.GameItemComponentProtos
				.FirstOrDefault(x => x.Type == type && x.Name == name);
			if (existing is not null)
			{
				return existing;
			}

			var component = new GameItemComponentProto
			{
				Id = context.GameItemComponentProtos.Any()
					? context.GameItemComponentProtos.Max(x => x.Id) + 1
					: 1,
				RevisionNumber = 0,
				EditableItem = CreateEditableItem(),
				Type = type,
				Name = name,
				Description = description,
				Definition = definition.ToString()
			};
			context.GameItemComponentProtos.Add(component);
			context.SaveChanges();
			changes++;
			return component;
		}

		GameItemProto EnsureItemPrototype(string uniqueName, string name, string keywords, string shortDescription,
			string longDescription, string fullDescription, SizeCategory size, double weight,
			params GameItemComponentProto[] components)
		{
			var item = context.GameItemProtos.FirstOrDefault(x => x.UniqueName == uniqueName);
			if (item is null)
			{
				var material = context.Materials.FirstOrDefault(x => x.Name == "Steel") ??
				               context.Materials.First();
				item = new GameItemProto
				{
					Id = context.GameItemProtos.Any() ? context.GameItemProtos.Max(x => x.Id) + 1 : 1,
					Name = name,
					UniqueName = uniqueName,
					RevisionNumber = 0,
					EditableItem = CreateEditableItem(),
					Keywords = keywords,
					ShortDescription = shortDescription,
					LongDescription = longDescription,
					FullDescription = fullDescription,
					Size = (int)size,
					Weight = weight,
					MaterialId = material.Id,
					ReadOnly = false,
					BaseItemQuality = (int)ItemQuality.Standard,
					PermitPlayerSkins = true
				};
				context.GameItemProtos.Add(item);
				context.SaveChanges();
				changes++;
			}

			foreach (var component in components.DistinctBy(x => (x.Id, x.RevisionNumber)))
			{
				if (context.GameItemProtosGameItemComponentProtos.Any(x =>
					    x.GameItemProtoId == item.Id &&
					    x.GameItemProtoRevision == item.RevisionNumber &&
					    x.GameItemComponentProtoId == component.Id &&
					    x.GameItemComponentRevision == component.RevisionNumber))
				{
					continue;
				}

				context.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
				{
					GameItemProtoId = item.Id,
					GameItemProtoRevision = item.RevisionNumber,
					GameItemComponentProtoId = component.Id,
					GameItemComponentRevision = component.RevisionNumber
				});
				changes++;
			}

			context.SaveChanges();
			return item;
		}

		XElement FirearmDefinition(RangedWeaponTypes type, bool internalMagazine)
		{
			return new XElement("Definition",
				new XElement("LoadEmote", new XCData("@ insert|inserts $2 into $1.")),
				new XElement("ReadyEmote", new XCData("@ work|works the action on $1.")),
				new XElement("UnloadEmote", new XCData("@ unload|unloads $2 from $1.")),
				new XElement("UnreadyEmote", new XCData("@ clear|clears $2 from $1's chamber.")),
				new XElement("UnreadyEmoteNoChamberedRound",
					new XCData("@ check|checks $1's already empty chamber.")),
				new XElement("FireEmote", new XCData("@ squeeze|squeezes the trigger on $2 and $2 fires.")),
				new XElement("FireEmoteNoChamberedRound",
					new XCData("@ squeeze|squeezes the trigger on $2, producing only a click.")),
				new XElement("RangedWeaponType", type.Id),
				internalMagazine ? new XElement("InternalMagazineCapacity", 6) : null,
				internalMagazine ? new XElement("EjectOnFire", true) : new XElement("ClipType", "STANAG 5.56"),
				new XElement("CycleType", internalMagazine ? FirearmCycleType.Manual : FirearmCycleType.SelfLoading),
				new XElement("AttachmentSlots",
					new XElement("Slot", new XAttribute("name", "optic"), new XAttribute("type", "Optic"),
						new XAttribute("formFactor", "picatinny")),
					new XElement("Slot", new XAttribute("name", "muzzle"), new XAttribute("type", "Muzzle"),
						new XAttribute("formFactor", internalMagazine ? "12ga-threaded" : "5.56-threaded")),
					new XElement("Slot", new XAttribute("name", "stock"), new XAttribute("type", "Stock"),
						new XAttribute("formFactor", "buffer-tube")),
					new XElement("Slot", new XAttribute("name", "grip"), new XAttribute("type", "Grip"),
						new XAttribute("formFactor", "picatinny")),
					new XElement("Slot", new XAttribute("name", "underbarrel"),
						new XAttribute("type", "Underbarrel"), new XAttribute("formFactor", "picatinny")),
					new XElement("Slot", new XAttribute("name", "side"), new XAttribute("type", "Side"),
						new XAttribute("formFactor", "picatinny")),
					new XElement("Slot", new XAttribute("name", "bayonet"), new XAttribute("type", "Bayonet"),
						new XAttribute("formFactor", "modern-lug"))),
				new XElement("FireModes",
					new XElement("Mode", new XAttribute("type", "Single"), new XAttribute("rounds", 1),
						new XAttribute("recoil", 0.0), new XAttribute("stamina", 0.0),
						new XAttribute("delay", 0.0)),
					internalMagazine
						? null
						: new XElement("Mode", new XAttribute("type", "Burst"), new XAttribute("rounds", 3),
							new XAttribute("recoil", 1.0), new XAttribute("stamina", 2.0),
							new XAttribute("delay", 0.08)),
					internalMagazine
						? null
						: new XElement("Mode", new XAttribute("type", "Automatic"), new XAttribute("rounds", 6),
							new XAttribute("recoil", 1.25), new XAttribute("stamina", 2.5),
							new XAttribute("delay", 0.1))));
		}

		XElement UnderbarrelLauncherDefinition(RangedWeaponTypes type, long meleeWeaponTypeId)
		{
			return new XElement("Definition",
				new XElement("LoadEmote", new XCData("@ open|opens $1 and insert|inserts $2 into its breech.")),
				new XElement("ReadyEmote", new XCData("@ close|closes the breech of $1.")),
				new XElement("UnloadEmote", new XCData("@ open|opens $1 and remove|removes $2.")),
				new XElement("UnreadyEmote", new XCData("@ open|opens $1 and clear|clears $2 from its breech.")),
				new XElement("UnreadyEmoteNoChamberedRound",
					new XCData("@ check|checks the empty breech of $1.")),
				new XElement("FireEmote",
					new XCData("@ squeeze|squeezes the trigger on $2 and launch|launches a grenade toward $1.")),
				new XElement("FireEmoteNoChamberedRound",
					new XCData("@ squeeze|squeezes the trigger on $2, producing only a hollow click.")),
				new XElement("RangedWeaponType", type.Id),
				new XElement("InternalMagazineCapacity", 1),
				new XElement("EjectOnFire", true),
				new XElement("MeleeWeaponType", meleeWeaponTypeId),
				new XElement("CycleType", FirearmCycleType.Manual),
				new XElement("AttachmentSlots"),
				new XElement("FireModes",
					new XElement("Mode", new XAttribute("type", FirearmFireModeType.Single),
						new XAttribute("rounds", 1), new XAttribute("recoil", 0.0),
						new XAttribute("stamina", 0.0), new XAttribute("delay", 0.0))));
		}

		var shotgun = EnsureRangedType("12 Gauge Pump Shotgun", "12 Gauge", AmmunitionLoadType.Direct, 6,
			false, 3, 9.0, 0.35, 0.8);
		var rifle = EnsureRangedType("5.56 Select-Fire Rifle", "5.56x45mm NATO", AmmunitionLoadType.Magazine, 30,
			false, 6, 7.0, 0.15, 0.5);
		var grenadeLauncher = EnsureRangedType("40mm Underbarrel Grenade Launcher", "40x46mm Grenade",
			AmmunitionLoadType.Direct, 1, false, 5, 10.0, 0.5, 1.0);
		EnsureComponent("InternalMagazineGun", "Shotgun_12_Gauge_Pump",
			"Turns an item into a modular 12-gauge pump-action shotgun", FirearmDefinition(shotgun, true));
		EnsureComponent("Gun", "Rifle_556_Select_Fire",
			"Turns an item into a modular 5.56mm select-fire rifle", FirearmDefinition(rifle, false));
		EnsureAmmunition("12 Gauge Slug", "12 Gauge", 1, RangedScatterType.Ballistic, 0.0,
			"(11+(pointblank*8))*quality*sqrt(degree+1)");
		EnsureAmmunition("12 Gauge 00 Buckshot", "12 Gauge", 9, RangedScatterType.Spread, 0.6,
			"(3.2+(pointblank*2))*quality*sqrt(degree+1)");
		EnsureAmmunition("5.56x45mm Ball", "5.56x45mm NATO", 1, RangedScatterType.Ballistic, 0.0,
			"(8+(pointblank*5))*quality*sqrt(degree+1)");
		var grenadeAmmunition = EnsureAmmunition("40mm Low-Velocity Grenade", "40x46mm Grenade", 1,
			RangedScatterType.Arcing, 0.0, "(3+pointblank)*quality*sqrt(degree+1)");

		GameItemComponentProto EnsureAttachment(string name, FirearmAttachmentSlotType slotType, string[] formFactors,
			double accuracy = 0.0, double aim = 0.0, double damage = 1.0, double range = 1.0,
			double recoil = 1.0, double stamina = 1.0, double delay = 1.0, double aimLoss = 1.0,
			int loudness = 0, string? fireEmote = null, IReadOnlyCollection<Type>? requiredCapabilities = null)
		{
			return EnsureComponent("FirearmAttachment", name.Replace(' ', '_'),
				$"Turns an item into a {name.ToLowerInvariant()} firearm attachment",
				new XElement("Definition",
					new XElement("SlotType", slotType),
					new XElement("FormFactors", formFactors.Select(x => new XElement("FormFactor", x))),
					new XElement("Modifiers",
						new XAttribute("accuracy", accuracy),
						new XAttribute("aim", aim),
						new XAttribute("damage", damage),
						new XAttribute("range", range),
						new XAttribute("recoil", recoil),
						new XAttribute("stamina", stamina),
						new XAttribute("delay", delay),
						new XAttribute("aimloss", aimLoss),
						new XAttribute("loudness", loudness)),
					new XElement("FireEmote", new XCData(fireEmote ?? string.Empty)),
					new XElement("Requirements",
						(requiredCapabilities ?? [])
						.Select(x => new XElement("Requirement",
							new XAttribute("capability", x.FullName ?? x.Name))))));
		}

		EnsureAttachment("Reflex Optic", FirearmAttachmentSlotType.Optic, ["picatinny"], accuracy: 1.0, aim: 1.0);
		EnsureAttachment("Adjustable Stock", FirearmAttachmentSlotType.Stock, ["buffer-tube"], recoil: 0.8,
			aimLoss: 0.85);
		EnsureAttachment("Vertical Grip", FirearmAttachmentSlotType.Grip, ["picatinny"], recoil: 0.85);
		EnsureAttachment("Sound Suppressor 556", FirearmAttachmentSlotType.Muzzle, ["5.56-threaded"],
			range: 0.95, loudness: -3,
			fireEmote: "@ squeeze|squeezes the trigger on $2, which fires with a muted report.");
		var weaponLightAttachment =
			EnsureAttachment("Weapon Light Mount", FirearmAttachmentSlotType.Underbarrel, ["picatinny"],
				requiredCapabilities: [typeof(IProduceLight), typeof(IProducePower)]);
		var launcherAttachment =
			EnsureAttachment("Underbarrel Launcher Mount", FirearmAttachmentSlotType.Underbarrel, ["picatinny"],
				recoil: 1.05, requiredCapabilities: [typeof(IRangedWeapon)]);
		var bayonetAttachment =
			EnsureAttachment("Modern Bayonet Mount", FirearmAttachmentSlotType.Bayonet, ["modern-lug"],
				requiredCapabilities: [typeof(IMeleeWeapon)]);

		var bayonetWeaponType = context.WeaponTypes.FirstOrDefault(x => x.Name == "Bayonet") ??
		                        context.WeaponTypes.First(x => x.Name == "Dagger");
		var launcherMeleeWeaponType = context.WeaponTypes.First(x => x.Name == "Improvised Bludgeon");
		var bayonetMelee = EnsureComponent("MeleeWeapon", "Melee_Modern_Bayonet",
			"Turns an item into a modern bayonet melee weapon",
			new XElement("Definition", new XElement("WeaponType", bayonetWeaponType.Id)));
		var launcherWeapon = EnsureComponent("InternalMagazineGun", "Launcher_40mm_Underbarrel",
			"Turns an item into a single-shot 40mm underbarrel grenade launcher",
			UnderbarrelLauncherDefinition(grenadeLauncher, launcherMeleeWeaponType.Id));
		var weaponLight = EnsureComponent("ElectricLight", "ElectricLight_WeaponMounted",
			"Turns an item into a low-draw weapon-mounted flashlight",
			new XElement("Definition",
				new XElement("IlluminationProvided", 250),
				new XElement("Wattage", 8),
				new XElement("OnLightProg", 0),
				new XElement("OnOffProg", 0),
				new XElement("LightOnEmote", new XCData("@ click|clicks on, casting a focused white beam.")),
				new XElement("LightOffEmote", new XCData("@ click|clicks off and go|goes dark."))));
		var weaponLightPower = EnsureComponent("BatteryPowered", "BatteryPowered_WeaponLight",
			"Provides a weapon light with power from two CR123 batteries",
			new XElement("Definition",
				new XElement("BatteryType", "CR123"),
				new XElement("BatteryQuantity", 2),
				new XElement("BatteriesInSeries", true),
				new XElement("ChargeWattage", 8.0),
				new XElement("Transparent", false),
				new XElement("ContentsPreposition", "in"),
				new XElement("Connectors")));
		var grenadeBomb = EnsureComponent("Bomb", "Bomb_40mm_Impact_Grenade",
			"Turns a fired 40mm projectile into a compact fragmentation explosive",
			new XElement("Definition",
				new XElement("MaximumProximity", (int)Proximity.Proximate),
				new XElement("ExplosionVolume", (int)AudioVolume.DangerouslyLoud),
				new XElement("ExplosionSize", (int)SizeCategory.Normal),
				new XElement("FeltInZone", true),
				new XElement("ExplosionEmoteText",
					new XCData("@ explode|explodes in a sharp blast of pressure and fragments!")),
				new XElement("Damages",
					new XElement("Damage",
						new XElement("DamageType", (int)DamageType.Shockwave),
						new XElement("Damage", new XCData("8+quality*2")),
						new XElement("Stun", new XCData("12+quality*2"))),
					new XElement("Damage",
						new XElement("DamageType", (int)DamageType.Shrapnel),
						new XElement("Damage", new XCData("10+quality*3")),
						new XElement("Stun", new XCData("5+quality"))))));
		var impactDetonator = EnsureComponent("ImpactDetonator", "ImpactDetonator_Fired_Grenade",
			"Detonates a sibling bomb component after fired-ammunition impact resolution",
			new XElement("Definition"));
		var holdable = context.GameItemComponentProtos.First(x => x.Type == "Holdable");
		var stackable = context.GameItemComponentProtos.First(x => x.Name == "Stack_Number");

		var grenadeProjectile = EnsureItemPrototype(
			"ModernFirearms_40mm_Grenade_Projectile",
			"40mm grenade projectile",
			"40mm grenade projectile fragmentation impact",
			"a 40mm fragmentation grenade projectile",
			"A 40mm fragmentation grenade projectile lies here.",
			"This compact steel-and-polymer projectile contains an impact-fused fragmentation payload.",
			SizeCategory.VerySmall, 180.0, holdable, grenadeBomb, impactDetonator);
		var grenadeCasing = EnsureItemPrototype(
			"ModernFirearms_40mm_Grenade_Casing",
			"spent 40mm grenade casing",
			"spent 40mm grenade casing shell",
			"a spent 40mm grenade casing",
			"A spent 40mm grenade casing lies here.",
			"This is the empty casing from a fired low-velocity 40mm grenade round.",
			SizeCategory.Tiny, 40.0, holdable, stackable);
		var grenadeRoundComponent = EnsureComponent("Ammunition", "Ammunition_40mm_Low_Velocity_Grenade",
			"Turns an item into a 40mm low-velocity impact grenade round",
			new XElement("Definition",
				new XElement("AmmoType", grenadeAmmunition.Id),
				new XElement("CasingProto", grenadeCasing.Id),
				new XElement("BulletProto", grenadeProjectile.Id)));

		EnsureItemPrototype(
			"ModernFirearms_Bayonet_Example",
			"modern rifle bayonet",
			"modern rifle bayonet knife blade lug",
			"a modern rifle bayonet",
			"A modern rifle bayonet lies here.",
			"This is a sturdy fighting knife with a modern-lug mounting ring and locking catch.",
			SizeCategory.Small, 450.0, holdable, bayonetAttachment, bayonetMelee);
		EnsureItemPrototype(
			"ModernFirearms_Underbarrel_Launcher_Example",
			"underbarrel 40mm grenade launcher",
			"underbarrel 40mm grenade launcher tube picatinny",
			"an underbarrel 40mm grenade launcher",
			"An underbarrel 40mm grenade launcher lies here.",
			"This compact single-shot launcher has a Picatinny clamp for mounting beneath a compatible rifle.",
			SizeCategory.Normal, 1450.0, holdable, launcherAttachment, launcherWeapon);
		EnsureItemPrototype(
			"ModernFirearms_Weapon_Light_Example",
			"underbarrel weapon flashlight",
			"underbarrel weapon flashlight light picatinny",
			"an underbarrel weapon flashlight",
			"An underbarrel weapon flashlight lies here.",
			"This rugged flashlight has a Picatinny clamp and a sealed compartment for two CR123 batteries.",
			SizeCategory.Small, 220.0, holdable, weaponLightAttachment, weaponLight, weaponLightPower);
		EnsureItemPrototype(
			"ModernFirearms_40mm_Grenade_Round_Example",
			"40mm low-velocity grenade round",
			"40mm low velocity grenade round ammunition",
			"a 40mm low-velocity grenade round",
			"A 40mm low-velocity grenade round lies here.",
			"This complete 40mm round contains a low-velocity impact-fused fragmentation grenade.",
			SizeCategory.VerySmall, 240.0, holdable, stackable, grenadeRoundComponent);

		return changes;
	}
}
