#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Body.Traits;
using MudSharp.Body;
using MudSharp.Combat;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Framework;
using MudSharp.GameItems;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using System;

namespace DatabaseSeeder.Seeders;

public partial class CombatSeeder
{
    private void SeedDataGuns(FuturemudDatabaseContext context, IReadOnlyDictionary<string, string> questionAnswers)
    {
        Account dbaccount = context.Accounts.First();
        DateTime now = DateTime.UtcNow;
        Dictionary<string, TraitDefinition> attributes = context.TraitDefinitions.Where(x => x.Type == 1 || x.Type == 3)
            .ToDictionary(x => x.Name, x => x, StringComparer.OrdinalIgnoreCase);
        TraitDefinition dex =
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Dexterity") ??
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Speed") ??
            attributes["Body"];

        TraitDefinition pistols;
        if (!context.TraitDefinitions.Any(x => x.Name == "Pistols"))
        {
            TraitExpression expression = new()
            {
                Name = "Pistol Skill Cap",
                Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
            };
            pistols = new TraitDefinition
            {
                Name = "Pistols",
                Type = (int)TraitType.Skill,
                Expression = expression,
                TraitGroup = "Combat",
                AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
                TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
                LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
                TeachDifficulty = 7,
                LearnDifficulty = 7,
                Hidden = false,
                ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
                DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
                DerivedType = 0,
                ChargenBlurb = string.Empty,
                BranchMultiplier = 1.0
            };
            context.TraitDefinitions.Add(pistols);
            context.SaveChanges();
        }
        else
        {
			pistols = context.TraitDefinitions.First(x => x.Name == "Pistols");
        }

        RangedWeaponTypes ranged = new()
        {
            Name = "9mm Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-10*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = "9x19mm Parabellum",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 5.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.4,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        GameItemComponentProto component = new()
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_9mm",
            Description = "Turns an item into a 9mm Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = ".25 ACP Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.3*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-10*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = ".25 ACP",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 3.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.25,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_25ACP",
            Description = "Turns an item into a .25 ACP Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = ".32 ACP Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-10*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = ".32 ACP",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 5.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.4,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_32ACP",
            Description = "Turns an item into a .32 ACP Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = ".38 ACP Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-8*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = ".38 ACP",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 5.5,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.45,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_38ACP",
            Description = "Turns an item into a .38 ACP Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = ".38 Super ACP Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-8*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = ".38 Super ACP",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 6.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.45,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_38SuperACP",
            Description = "Turns an item into a .38 Super ACP Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = ".45 ACP Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = pistols,
            FireableInMelee = true,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-2.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-7*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = ".45 ACP",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.ModernFirearm,
            StaminaToFire = 7.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 0.6,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gun",
            Name = "Pistol_45ACP",
            Description = "Turns an item into a .45 ACP Pistol",
            Definition =
                @$"<Definition>
   <LoadEmote><![CDATA[@ insert|inserts $2 into $1 and it clicks into place.]]></LoadEmote>
   <ReadyEmote><![CDATA[@ rack|racks the slide on $1, and it clicks back into place.]]></ReadyEmote>
   <UnloadEmote><![CDATA[@ hit|hits the eject button on $1 and $2 is ejected.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[@ open|opens the slide on $1 and work|works out $2 from the chamber.]]></UnreadyEmote>
   <UnreadyEmoteNoChamberedRound><![CDATA[@ open|opens the slide on $1, but there is no round in the chamber.]]></UnreadyEmoteNoChamberedRound>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it fires a round with an extremely loud bang.]]></FireEmote>
   <FireEmoteNoChamberedRound><![CDATA[@ squeeze|squeezes the trigger on $2, and nothing happens except a quiet click.]]></FireEmoteNoChamberedRound>
   <RangedWeaponType>{ranged.Id}</RangedWeaponType>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        GameItemComponentProto holdable = context.GameItemComponentProtos.First(x => x.Type == "Holdable");
        GameItemComponentProto stackable = context.GameItemComponentProtos.First(x => x.Name == "Stack_Number");

        (long RoundId, long BulletId, long CaseId) CreateAmmoItems(string name, GameItemComponentProto ammoComponent,
            AmmunitionTypes ammo, string bulletMaterial, string caseMaterial)
        {
            GameItemProto round = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "round",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} round",
                Size = (int)SizeCategory.VerySmall,
                Weight = 9.0,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"{name} round",
                FullDescription =
                    $"This is a {name} round, made out of {caseMaterial} with a bullet made of {bulletMaterial} inside.",
                MaterialId = context.Materials.First(x => x.Name == caseMaterial).Id
            };
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = holdable
            });
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = stackable
            });
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = ammoComponent
            });
            context.GameItemProtos.Add(round);
            context.SaveChanges();

            GameItemProto bullet = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "bullet",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} bullet",
                Size = (int)SizeCategory.Tiny,
                Weight = 7.0,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"@material {name} bullet",
                FullDescription =
                    $"This is a tiny {name} bullet, made out of @material. It has clearly been fired out of a gun and is deformed.",
                MaterialId = context.Materials.First(x => x.Name == bulletMaterial).Id
            };
            bullet.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = bullet,
                GameItemComponent = holdable
            });
            bullet.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = bullet,
                GameItemComponent = stackable
            });
            context.GameItemProtos.Add(bullet);
            context.SaveChanges();

            GameItemProto casing = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "casing",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} casing",
                Size = (int)SizeCategory.Tiny,
                Weight = 2.0,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"spent @material {name} casing",
                FullDescription =
                    $"This is a tiny {name} casing made of @material. It has been fired and the firing cap and bullet are both gone.",
                MaterialId = context.Materials.First(x => x.Name == caseMaterial).Id
            };
            casing.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = casing,
                GameItemComponent = holdable
            });
            casing.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = casing,
                GameItemComponent = stackable
            });
            context.GameItemProtos.Add(casing);
            context.SaveChanges();

            return (round.Id, bullet.Id, casing.Id);
        }

        void AddAmmoType(string name, string specific, string shortname, string damage, DamageType damageType)
        {
            AmmunitionTypes ammo = new()
            {
                Name = name,
                SpecificType = specific,
                RangedWeaponTypes = "2",
                BaseAccuracy = 0.0,
                Loudness = (int)AudioVolume.ExtremelyLoud,
                BreakChanceOnHit = 0.2,
                BreakChanceOnMiss = 0.5,
                BaseBlockDifficulty = (int)Difficulty.Insane,
                BaseDodgeDifficulty = (int)Difficulty.Insane,
                DamageExpression = damage,
                StunExpression = damage,
                PainExpression = damage,
                DamageType = (int)damageType
            };
            context.AmmunitionTypes.Add(ammo);
            context.SaveChanges();

            component = new GameItemComponentProto
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "Ammunition",
                Name = $"Ammo_{shortname}",
                Description = $"Turns an item into {shortname} rounds",
                Definition = ""
            };
            context.GameItemComponentProtos.Add(component);
            context.SaveChanges();

            (long roundid, long bulletid, long caseid) = CreateAmmoItems(name, component, ammo, "lead", "brass");
            component.Definition = @$"<Definition>
   <AmmoType>{ammo.Id}</AmmoType>
   <CasingProto>{caseid}</CasingProto>
   <BulletProto>{bulletid}</BulletProto>
 </Definition>";
            context.SaveChanges();
        }

        AddAmmoType("9mm Parabellum", "9x19mm Parabellum", "9mm", "(6+(pointblank*6))*quality*sqrt(degree+1)",
            DamageType.Ballistic);
        AddAmmoType("25ACP", ".25 ACP", ".25 ACP", "(4.5+(pointblank*6))*quality*sqrt(degree+1)", DamageType.Ballistic);
        AddAmmoType("32ACP", ".32 ACP", ".32 ACP", "(6+(pointblank*6))*quality*sqrt(degree+1)", DamageType.Ballistic);
        AddAmmoType("38ACP", ".38 ACP", ".38 ACP", "(6.5+(pointblank*6))*quality*sqrt(degree+1)", DamageType.Ballistic);
        AddAmmoType("38Super", ".38 Super ACP", ".38 Super ACP", "(7.4+(pointblank*6))*quality*sqrt(degree+1)",
            DamageType.Ballistic);
        AddAmmoType("45ACP", ".45 ACP", ".45 ACP", "(9+(pointblank*6))*quality*sqrt(degree+1)", DamageType.Ballistic);
    }

    private void SeedDataMuskets(FuturemudDatabaseContext context, IReadOnlyDictionary<string, string> questionAnswers)
    {
        Account dbaccount = context.Accounts.First();
        DateTime now = DateTime.UtcNow;
        Dictionary<string, TraitDefinition> attributes = context.TraitDefinitions.Where(x => x.Type == 1 || x.Type == 3)
            .ToDictionary(x => x.Name, x => x, StringComparer.OrdinalIgnoreCase);
        TraitDefinition dex =
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Dexterity") ??
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Speed") ??
            attributes["Body"];

        TraitExpression expression = new()
        {
            Name = "Flintlocks Skill Cap",
            Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
        };
        TraitDefinition flintlocks = new()
        {
            Name = "Flintlocks",
            Type = (int)TraitType.Skill,
            Expression = expression,
            TraitGroup = "Combat",
            AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
            LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachDifficulty = 7,
            LearnDifficulty = 7,
            Hidden = false,
            ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
            DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
            DerivedType = 0,
            ChargenBlurb = string.Empty,
            BranchMultiplier = 1.0
        };
        context.TraitDefinitions.Add(flintlocks);
        context.SaveChanges();

        #region Pistols
        TraitDefinition pistols;
        if (!context.TraitDefinitions.Any(x => x.Name == "Pistols"))
        {
            expression = new TraitExpression
            {
                Name = "Pistol Skill Cap",
                Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
            };
            pistols = new TraitDefinition
            {
                Name = "Pistols",
                Type = (int)TraitType.Skill,
                Expression = expression,
                TraitGroup = "Combat",
                AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
                TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
                LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
                TeachDifficulty = 7,
                LearnDifficulty = 7,
                Hidden = false,
                ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
                DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
                DerivedType = 0,
                ChargenBlurb = string.Empty,
                BranchMultiplier = 1.0
            };
            context.TraitDefinitions.Add(pistols);
            context.SaveChanges();
        }
        else
        {
			pistols = context.TraitDefinitions.First(x => x.Name == "Pistols");
        }

        RangedWeaponTypes ranged = new()
        {
            Name = "Flintlock Pistol",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = pistols,
            OperateTrait = flintlocks,
            FireableInMelee = true,
            DefaultRangeInRooms = 1,
            AccuracyBonusExpression = "(-3.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-15*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = "Musket Ball",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Musket,
            StaminaToFire = 5.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        GameItemComponentProto component = new()
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Pistol_Flintlock65",
            Description = "Turns an item into a 65 Bore Flintlock Pistol",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>5.1839128</PowderVolumePerShot>
   <BarrelBore>0.65</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d40</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Pistol_Flintlock55",
            Description = "Turns an item into a 55 Bore Flintlock Pistol",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>3.8879346</PowderVolumePerShot>
   <BarrelBore>0.55</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d30</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Pistol_Flintlock45",
            Description = "Turns an item into a 45 Bore Flintlock Pistol",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>3.8879346</PowderVolumePerShot>
   <BarrelBore>0.45</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d30</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();
        #endregion

        #region Muskets
        expression = new TraitExpression
        {
            Name = "Muskets Skill Cap",
            Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
        };
        TraitDefinition muskets = new()
        {
            Name = "Muskets",
            Type = (int)TraitType.Skill,
            Expression = expression,
            TraitGroup = "Combat",
            AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
            LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachDifficulty = 7,
            LearnDifficulty = 7,
            Hidden = false,
            ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
            DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
            DerivedType = 0,
            ChargenBlurb = string.Empty,
            BranchMultiplier = 1.0
        };
        context.TraitDefinitions.Add(muskets);
        context.SaveChanges();
        ranged = new RangedWeaponTypes
        {
            Name = "Flintlock Musket",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = muskets,
            OperateTrait = flintlocks,
            FireableInMelee = false,
            DefaultRangeInRooms = 4,
            AccuracyBonusExpression = "(-3.0*range)-(pow(1-aim,2)*4.0)",
            DamageBonusExpression = "-12*range",
            AmmunitionLoadType = (int)AmmunitionLoadType.Magazine,
            SpecificAmmunitionGrade = "Musket Ball",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Musket,
            StaminaToFire = 5.0,
            StaminaPerLoadStage = 7.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Easy,
            LoadDelay = 1.2,
            ReadyDelay = 0.3,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = true
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Musket_Flintlock80",
            Description = "Turns an item into a 80 Bore Flintlock Musket",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>7.7758692</PowderVolumePerShot>
   <BarrelBore>0.8</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d40</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Musket_Flintlock75",
            Description = "Turns an item into a 75 Bore Flintlock Musket",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>7.7758692</PowderVolumePerShot>
   <BarrelBore>0.75</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d40</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Musket_Flintlock70",
            Description = "Turns an item into a 70 Bore Flintlock Musket",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>7.7758692</PowderVolumePerShot>
   <BarrelBore>0.70</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d40</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Musket",
            Name = "Musket_Flintlock60",
            Description = "Turns an item into a 60 Bore Flintlock Musket",
            Definition =
                @$"<Definition>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <LoadEmoteCartridge><![CDATA[$0 bite|bites open $2 and pour|pours a small amount of the charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and shove|shoves the cartridge down into the barrel.]]></LoadEmoteCartridge>
   <LoadEmotePowder><![CDATA[$0 pour|pours a small amount of charge into the priming pan of $1, close|closes the frizzen, rest|rests the whole gun butt-first on the ground and pour|pours $2 down the barrel.]]></LoadEmotePowder>
   <LoadEmoteBall><![CDATA[$0 push|pushes $2$?3| wrapped in $3||$ into $1.]]></LoadEmoteBall>
   <LoadEmoteRamrod><![CDATA[$0 push|pushes the ram-end of $2 into the barrel of $1, tamping down on the loaded shot.]]></LoadEmoteRamrod>
   <LoadEmoteTap><![CDATA[$0 hit|hits the butt-end of $1 on the ground, using gravity to force the shot into place.]]></LoadEmoteTap>
   <LoadEmoteClean><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1 and remove|removes any remaining debris from previous shots.]]></LoadEmoteClean>
   <ReadyEmote><![CDATA[$0 pull|pulls the cock into the fire position on $1.]]></ReadyEmote>
   <UnloadEmote><![CDATA[$0 empty|empties and discards the contents of the barrel of $1.]]></UnloadEmote>
   <UnreadyEmote><![CDATA[$0 gently lower|lowers the cock of $1 out of the firing position.]]></UnreadyEmote>
   <StartUnjamEmote><![CDATA[$0 push|pushes the worm-end of $2 into the barrel of $1, laboriously attempting to remove the jam.]]></StartUnjamEmote>
   <FailUnjamEmote><![CDATA[$0 fail|fails to dislodge the debris in the barrel of $1, but continue|continues with &his efforts.]]></FailUnjamEmote>
   <FinishUnjamEmote><![CDATA[$0 successfully dislodge|dislodges the blockage in the barrel of $1, and discard|discards the debris.]]></FinishUnjamEmote>
   <FireEmote><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1.]]></FireEmote>
   <FireEmoteJam><![CDATA[@ squeeze|squeezes the trigger on $2 and it lets off a thundering blast towards $1, with a larger than usual kick.]]></FireEmoteJam>
   <FireEmoteMisfire><![CDATA[@ squeeze|squeezes the trigger on $2 and it misfires, discharging its ammunition harmlessly and ineffectively with a thunderous blast of smoke.]]></FireEmoteMisfire>
   <FireEmoteCatastrophy><![CDATA[@ squeeze|squeezes the trigger on $2 and it catastrophically explodes in &0's face!]]></FireEmoteCatastrophy>
   <RangedWeaponType>14</RangedWeaponType>
   <MeleeWeaponType>7</MeleeWeaponType>
   <PowderVolumePerShot>7.7758692</PowderVolumePerShot>
   <BarrelBore>0.6</BarrelBore>
   <MisfireChance>Max(0, sqrt(max(0, 70-operate))*0.075 + taploaded*0.1 + skipclean*0.1 + if(precipitation&lt;3,precipitation,pow(precipitation,1.5))+(5-gunquality)*0.03+cartridgeused*(5-cartridgequality)*0.03+(1-sqrt(condition))*0.5-wadused*0.2+wetpowder*0.5)</MisfireChance>
   <JamChance>0.1+cartridgeused*0.1+(1-condition)*0.5</JamChance>
   <CatastrophyDamageFormula>10+1d40</CatastrophyDamageFormula>
 </Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();
        #endregion

        #region Ammunition
        GameItemComponentProto holdable = context.GameItemComponentProtos.First(x => x.Type == "Holdable");
        GameItemComponentProto stackable = context.GameItemComponentProtos.First(x => x.Name == "Stack_Number");

        (long BallId, long BulletId, long CartridgeId) CreateAmmoItems(string name, GameItemComponentProto ammoComponent, GameItemComponentProto ballComponent, AmmunitionTypes ammo, string bulletMaterial, string caseMaterial, double bulletWeight)
        {
            GameItemProto round = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "ball",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} ball",
                Size = (int)SizeCategory.Tiny,
                Weight = bulletWeight,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"{name} ball",
                FullDescription =
                    $"This is a new {name} musket ball, made out of {bulletMaterial}, ready to be fired in an appropriate weapon.",
                MaterialId = context.Materials.First(x => x.Name == bulletMaterial).Id
            };
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = holdable
            });
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = stackable
            });
            round.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = round,
                GameItemComponent = ballComponent
            });
            context.GameItemProtos.Add(round);
            context.SaveChanges();

            GameItemProto bullet = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "ball",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} ball",
                Size = (int)SizeCategory.Tiny,
                Weight = bulletWeight,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"a fired {name} ball",
                FullDescription =
                    $"This is a {name} musket ball that has been fired, made out of {bulletMaterial}. It's no longer useful as ammunition due to deformation but might be able to be melted back down into fresh ammunition.",
                MaterialId = context.Materials.First(x => x.Name == bulletMaterial).Id
            };
            bullet.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = bullet,
                GameItemComponent = holdable
            });
            bullet.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = bullet,
                GameItemComponent = stackable
            });
            context.GameItemProtos.Add(bullet);
            context.SaveChanges();

            GameItemProto cartridge = new()
            {
                Id = context.GameItemProtos.Max(x => x.Id) + 1,
                Name = "cartridge",
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Keywords = $"{name} cartridge",
                Size = (int)SizeCategory.VerySmall,
                Weight = 56.0,
                ReadOnly = false,
                BaseItemQuality = (int)ItemQuality.Standard,
                ShortDescription = $"a {name} musket cartridge",
                FullDescription =
                    $"This is a pre-assembled cartridge for firing a {name} musket, containing a pre-measured amount of powder and a ball of the appropriate gauge. This skips the step of pouring powder, adding wadding and adding the ball separately.",
                MaterialId = context.Materials.First(x => x.Name == caseMaterial).Id
            };
            cartridge.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = cartridge,
                GameItemComponent = holdable
            });
            cartridge.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = cartridge,
                GameItemComponent = stackable
            });
            cartridge.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
            {
                GameItemProto = cartridge,
                GameItemComponent = ammoComponent
            });
            context.GameItemProtos.Add(cartridge);
            context.SaveChanges();

            return (round.Id, bullet.Id, cartridge.Id);
        }

        void AddAmmoType(string name, string specific, string shortname, string damage, DamageType damageType, double bore, double bulletWeight, double accuracy)
        {
            AmmunitionTypes ammo = new()
            {
                Name = name,
                SpecificType = specific,
                RangedWeaponTypes = "7",
                BaseAccuracy = accuracy,
                Loudness = (int)AudioVolume.ExtremelyLoud,
                BreakChanceOnHit = 0.5,
                BreakChanceOnMiss = 0.2,
                BaseBlockDifficulty = (int)Difficulty.Insane,
                BaseDodgeDifficulty = (int)Difficulty.Insane,
                DamageExpression = damage,
                StunExpression = damage,
                PainExpression = damage,
                DamageType = (int)damageType
            };
            context.AmmunitionTypes.Add(ammo);
            context.SaveChanges();

            GameItemComponentProto cartridgeComponent = new()
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "MusketCartridge",
                Name = $"MusketCartridge_{shortname}",
                Description = $"Turns an item into {shortname} musket cartridges",
                Definition = ""
            };
            context.GameItemComponentProtos.Add(cartridgeComponent);
            context.SaveChanges();

            GameItemComponentProto ammoComponent = new()
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "MusketBall",
                Name = $"MusketBall_{shortname}",
                Description = $"Turns an item into {shortname} musket cartridges",
                Definition = ""
            };
            context.GameItemComponentProtos.Add(ammoComponent);
            context.SaveChanges();

            (long ballid, long bulletid, long cartridgeid) = CreateAmmoItems(name, cartridgeComponent, ammoComponent, ammo, "lead", "lead", bulletWeight);
            cartridgeComponent.Definition = @$"<Definition>
   <AmmoType>{ammo.Id}</AmmoType>
   <BulletBore>{bore}</BulletBore>
   <BulletProto>{bulletid}</BulletProto>
 </Definition>";
            ammoComponent.Definition = @$"<Definition>
   <AmmoType>{ammo.Id}</AmmoType>
   <BulletBore>{bore}</BulletBore>
   <BulletProto>{bulletid}</BulletProto>
 </Definition>";
            context.SaveChanges();
        }

        AddAmmoType("0.8 Bore Musket Shot", "Musket Ball", "0.8 Bore", "rand(10,30) + quality * sqrt(degree+1) + (pointblank * 30)", DamageType.Ballistic, 0.8, 56, -2.0);
        AddAmmoType("0.75 Bore Musket Shot", "Musket Ball", "0.75 Bore", "rand(8,27) + quality * sqrt(degree+1) + (pointblank * 30)", DamageType.Ballistic, 0.75, 56, -1.0);
        AddAmmoType("0.7 Bore Musket Shot", "Musket Ball", "0.7 Bore", "rand(7,24) + quality * sqrt(degree+1) * 0.9 + (pointblank * 30)", DamageType.Ballistic, 0.7, 56, 0.0);
        AddAmmoType("0.65 Bore Musket Shot", "Musket Ball", "0.65 Bore", "rand(6,21) + quality * sqrt(degree+1) * 0.8 + (pointblank * 30)", DamageType.Ballistic, 0.65, 56, 0.0);
        AddAmmoType("0.60 Bore Musket Shot", "Musket Ball", "0.6 Bore", "rand(6,18) + quality * sqrt(degree+1) * 0.7 + (pointblank * 30)", DamageType.Ballistic, 0.6, 56, 1.0);
        AddAmmoType("0.55 Bore Musket Shot", "Musket Ball", "0.55 Bore", "rand(6,18) + quality * sqrt(degree+1) * 0.6 + (pointblank * 30)", DamageType.Ballistic, 0.55, 56, 1.0);
        AddAmmoType("0.45 Bore Musket Shot", "Musket Ball", "0.45 Bore", "rand(5,15) + quality * sqrt(degree+1) * 0.5 + (pointblank * 30)", DamageType.Ballistic, 0.45, 56, 2.0);
        #endregion
    }

    private void SeedDataRanged(FuturemudDatabaseContext context,
        IReadOnlyDictionary<string, string> questionAnswers,
        IReadOnlyDictionary<string, TraitDefinition> skills)
    {
        Account dbaccount = context.Accounts.First();
        DateTime now = DateTime.UtcNow;
        Dictionary<string, TraitDefinition> attributes = context.TraitDefinitions.Where(x => x.Type == 1 || x.Type == 3)
            .ToDictionary(x => x.Name, x => x, StringComparer.OrdinalIgnoreCase);
        TraitDefinition dex =
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Dexterity") ??
            attributes.GetValueOrDefault("Agility") ??
            attributes.GetValueOrDefault("Speed") ??
            attributes["Body"];

        TraitExpression expression = new()
        {
            Name = "Bow Skill Cap",
            Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
        };
        TraitDefinition bows = new()
        {
            Name = "Bows",
            Type = (int)TraitType.Skill,
            Expression = expression,
            TraitGroup = "Combat",
            AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
            LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachDifficulty = 7,
            LearnDifficulty = 7,
            Hidden = false,
            ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
            DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
            DerivedType = 0,
            ChargenBlurb = string.Empty,
            BranchMultiplier = 1.0
        };
        context.TraitDefinitions.Add(bows);
        context.SaveChanges();

        RangedWeaponTypes ranged = new()
        {
            Name = "Shortbow",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = bows,
            OperateTrait = bows,
            FireableInMelee = false,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-1.0*range)-(pow(1-aim,2)*3.0)",
            DamageBonusExpression = $"quality - (4.0*range) - (({dex.Alias}:{dex.Id}-10)*1.5)",
            AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
            SpecificAmmunitionGrade = "Arrow",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Bow,
            StaminaToFire = 5,
            StaminaPerLoadStage = 10.0,
            CoverBonus = -2.0,
            BaseAimDifficulty = (int)Difficulty.Normal,
            LoadDelay = 0.5,
            ReadyDelay = 0.1,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        GameItemComponentProto component = new()
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Bow",
            Name = "Shortbow",
            Description = "Turns an item into a shortbow",
            Definition =
                $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType></Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = "Longbow",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = bows,
            OperateTrait = bows,
            FireableInMelee = false,
            DefaultRangeInRooms = 4,
            AccuracyBonusExpression = "(-1.0*range)-(pow(1-aim,2)*2.0)",
            DamageBonusExpression = $"2*quality - (4.0*range) - (({dex.Alias}:{dex.Id}-10)*2.5)",
            AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
            SpecificAmmunitionGrade = "Arrow",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Bow,
            StaminaToFire = 10,
            StaminaPerLoadStage = 15.0,
            CoverBonus = -1.0,
            BaseAimDifficulty = (int)Difficulty.Hard,
            LoadDelay = 0.5,
            ReadyDelay = 0.1,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Bow",
            Name = "Longbow",
            Description = "Turns an item into a longbow",
            Definition =
                $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType></Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        expression = new TraitExpression
        {
            Name = "Crossbows Skill Cap",
            Expression = $"min(99,5.5*{dex.Alias}:{dex.Id})"
        };
        TraitDefinition crossbows = new()
        {
            Name = "Crossbows",
            Type = (int)TraitType.Skill,
            Expression = expression,
            TraitGroup = "Combat",
            AvailabilityProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysFalse"),
            LearnableProg = context.FutureProgs.First(x => x.FunctionName == "AlwaysTrue"),
            TeachDifficulty = 7,
            LearnDifficulty = 7,
            Hidden = false,
            ImproverId = context.Improvers.First(x => x.Name == "Skill Improver").Id,
            DecoratorId = context.TraitDecorators.First(x => x.Name == "General Skill").Id,
            DerivedType = 0,
            ChargenBlurb = string.Empty,
            BranchMultiplier = 1.0
        };
        context.TraitDefinitions.Add(crossbows);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = "Hand Crossbow",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = crossbows,
            OperateTrait = crossbows,
            FireableInMelee = false,
            DefaultRangeInRooms = 2,
            AccuracyBonusExpression = "(-1.5*range)-(pow(1-aim,2)*5.0)",
            DamageBonusExpression = "quality - (4.0*range)",
            AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
            SpecificAmmunitionGrade = "Bolt",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Crossbow,
            StaminaToFire = 1,
            StaminaPerLoadStage = 20.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Normal,
            LoadDelay = 1.5,
            ReadyDelay = 0.1,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = false
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Crossbow",
            Name = "Hand Crossbow",
            Description = "Turns an item into a hand crossbow",
            Definition =
                $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType></Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        ranged = new RangedWeaponTypes
        {
            Name = "Crossbow",
            Classification = (int)WeaponClassification.Lethal,
            FireTrait = crossbows,
            OperateTrait = crossbows,
            FireableInMelee = false,
            DefaultRangeInRooms = 4,
            AccuracyBonusExpression = "(-1.0*range)-(pow(1-aim,2)*5.0)",
            DamageBonusExpression = "2*quality - (4.0*range)",
            AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
            SpecificAmmunitionGrade = "Bolt",
            AmmunitionCapacity = 1,
            RangedWeaponType = (int)RangedWeaponType.Crossbow,
            StaminaToFire = 1,
            StaminaPerLoadStage = 30.0,
            CoverBonus = -3.0,
            BaseAimDifficulty = (int)Difficulty.Normal,
            LoadDelay = 2.0,
            ReadyDelay = 0.1,
            FireDelay = 0.1,
            AimBonusLostPerShot = 1.0,
            RequiresFreeHandToReady = true,
            AlwaysRequiresTwoHandsToWield = true
        };
        context.RangedWeaponTypes.Add(ranged);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Crossbow",
            Name = "Crossbow",
            Description = "Turns an item into a crossbow",
            Definition =
                $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType></Definition>"
        };
        context.GameItemComponentProtos.Add(component);
        context.SaveChanges();

        void AddAmmoType(string name, string specific, RangedWeaponType type, double accuracy, AudioVolume loudness,
            double breakOnHit, double breakOnMiss, Difficulty block, Difficulty dodge, DamageType damageType,
            string damageExpression)
        {
            AmmunitionTypes dbammo = new()
            {
                Name = name,
                SpecificType = specific,
                DamageType = (int)damageType,
                RangedWeaponTypes = ((int)type).ToString(),
                BaseAccuracy = accuracy,
                BreakChanceOnHit = breakOnHit,
                BreakChanceOnMiss = breakOnMiss,
                Loudness = (int)loudness,
                BaseBlockDifficulty = (int)block,
                BaseDodgeDifficulty = (int)dodge,
                DamageExpression = damageExpression,
                StunExpression = damageExpression,
                PainExpression = damageExpression
            };
            context.AmmunitionTypes.Add(dbammo);
            context.SaveChanges();

            component = new GameItemComponentProto
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "Ammunition",
                Name = $"Ammo_{name.CollapseString()}",
                Description = $"Turns an item into {name.A_An()}",
                Definition = $"<Definition><AmmoType>{dbammo.Id}</AmmoType></Definition>"
            };
            context.GameItemComponentProtos.Add(component);
            context.SaveChanges();
        }

        AddAmmoType("Field Point Arrow", "Arrow", RangedWeaponType.Bow, 0.0, AudioVolume.Quiet, 0.5, 0.3,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.BallisticArmourPiercing, "15 + quality * 0.75 * degree");
        AddAmmoType("Bodkin Arrow", "Arrow", RangedWeaponType.Bow, 0.0, AudioVolume.Quiet, 0.5, 0.3,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.BallisticArmourPiercing, "20 + quality * 0.75 * degree");
        AddAmmoType("Broadhead Arrow", "Arrow", RangedWeaponType.Bow, 0.0, AudioVolume.Quiet, 0.5, 0.3, Difficulty.Easy,
            Difficulty.VeryHard, DamageType.Piercing, "30 + quality * 0.75 * degree");
        AddAmmoType("Concussive Arrow", "Arrow", RangedWeaponType.Bow, 0.0, AudioVolume.Quiet, 0.6, 0.4,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.Crushing, "20 + quality * 0.75 * degree");
        AddAmmoType("Target Arrow", "Arrow", RangedWeaponType.Bow, 1.0, AudioVolume.Quiet, 0.05, 0.2, Difficulty.Easy,
            Difficulty.VeryHard, DamageType.Piercing, "quality * 0.75 * degree");
        AddAmmoType("Padded Arrow", "Arrow", RangedWeaponType.Bow, 0.0, AudioVolume.Quiet, 0.1, 0.2, Difficulty.Easy,
            Difficulty.VeryHard, DamageType.Crushing, "10-quality");
        AddAmmoType("Field Point Bolt", "Bolt", RangedWeaponType.Crossbow, 0.0, AudioVolume.Quiet, 0.5, 0.3,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.BallisticArmourPiercing, "15 + quality * 0.75 * degree");
        AddAmmoType("Bodkin Bolt", "Bolt", RangedWeaponType.Crossbow, 0.0, AudioVolume.Quiet, 0.5, 0.3,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.BallisticArmourPiercing, "20 + quality * 0.75 * degree");
        AddAmmoType("Broadhead Bolt", "Bolt", RangedWeaponType.Crossbow, 0.0, AudioVolume.Quiet, 0.5, 0.3,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.Piercing, "30 + quality * 0.75 * degree");
        AddAmmoType("Concussive Bolt", "Bolt", RangedWeaponType.Crossbow, 0.0, AudioVolume.Quiet, 0.6, 0.4,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.Crushing, "20 + quality * 0.75 * degree");
        AddAmmoType("Target Bolt", "Bolt", RangedWeaponType.Crossbow, 1.0, AudioVolume.Quiet, 0.05, 0.2,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.Piercing, "quality * 0.75 * degree");
        AddAmmoType("Padded Bolt", "Bolt", RangedWeaponType.Crossbow, 0.0, AudioVolume.Quiet, 0.1, 0.2,
            Difficulty.Easy, Difficulty.VeryHard, DamageType.Crushing, "10-quality");
        AddAmmoType("Sling Bullet", "Sling Bullet", RangedWeaponType.Sling, 0.0, AudioVolume.Quiet, 0.2, 0.2,
            Difficulty.Easy, Difficulty.Hard, DamageType.Crushing, "quality * 0.75 * degree");

        if (context.WeaponTypes.Any())
        {
            TraitDefinition throwing = skills.GetValueOrDefault("Throwing") ?? skills["Throw"];

            ranged = new RangedWeaponTypes
            {
                Name = "Throwing Knife",
                Classification = (int)WeaponClassification.Lethal,
                FireTrait = throwing,
                OperateTrait = throwing,
                FireableInMelee = false,
                DefaultRangeInRooms = 0,
                AccuracyBonusExpression = "(-1.5*range)-(pow(1-aim,2)*5.0)",
                DamageBonusExpression = $"quality/2 * ({dex.Alias}:{dex.Id}/2)",
                AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
                SpecificAmmunitionGrade = "Throwing",
                AmmunitionCapacity = 1,
                RangedWeaponType = (int)RangedWeaponType.Thrown,
                StaminaToFire = 15.0,
                StaminaPerLoadStage = 0.0,
                CoverBonus = -3.0,
                BaseAimDifficulty = (int)Difficulty.VeryHard,
                LoadDelay = 0.0,
                ReadyDelay = 0.0,
                FireDelay = 0.5,
                AimBonusLostPerShot = 1.0,
                RequiresFreeHandToReady = true,
                AlwaysRequiresTwoHandsToWield = false
            };
            context.RangedWeaponTypes.Add(ranged);
            context.SaveChanges();

            component = new GameItemComponentProto
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "ThrownWeapon",
                Name = "Throwing_Knife",
                Description = "Turns an item into a throwing knife",
                Definition =
                    $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType><MeleeWeaponType>{context.WeaponTypes.First(x => x.Name == "Dagger").Id}</MeleeWeaponType></Definition>"
            };
            context.GameItemComponentProtos.Add(component);
            context.SaveChanges();

            ranged = new RangedWeaponTypes
            {
                Name = "Throwing Axe",
                Classification = (int)WeaponClassification.Lethal,
                FireTrait = throwing,
                OperateTrait = throwing,
                FireableInMelee = false,
                DefaultRangeInRooms = 0,
                AccuracyBonusExpression = "(-1.5*range)-(pow(1-aim,2)*5.0)",
                DamageBonusExpression = $"quality/2 * ({dex.Alias}:{dex.Id})",
                AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
                SpecificAmmunitionGrade = "Throwing",
                AmmunitionCapacity = 1,
                RangedWeaponType = (int)RangedWeaponType.Thrown,
                StaminaToFire = 30.0,
                StaminaPerLoadStage = 0.0,
                CoverBonus = -3.0,
                BaseAimDifficulty = (int)Difficulty.VeryHard,
                LoadDelay = 0.0,
                ReadyDelay = 0.0,
                FireDelay = 0.5,
                AimBonusLostPerShot = 1.0,
                RequiresFreeHandToReady = true,
                AlwaysRequiresTwoHandsToWield = false
            };
            context.RangedWeaponTypes.Add(ranged);
            context.SaveChanges();

            component = new GameItemComponentProto
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "ThrownWeapon",
                Name = "Throwing_Axe",
                Description = "Turns an item into a throwing axe",
                Definition =
                    $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType><MeleeWeaponType>{context.WeaponTypes.First(x => x.Name == "Axe").Id}</MeleeWeaponType></Definition>"
            };
            context.GameItemComponentProtos.Add(component);
            context.SaveChanges();

            ranged = new RangedWeaponTypes
            {
                Name = "Throwing Spear",
                Classification = (int)WeaponClassification.Lethal,
                FireTrait = throwing,
                OperateTrait = throwing,
                FireableInMelee = false,
                DefaultRangeInRooms = 1,
                AccuracyBonusExpression = "(-3.0*range)-(pow(1-aim,2)*5.0)",
                DamageBonusExpression = $"quality * ({dex.Alias}:{dex.Id})",
                AmmunitionLoadType = (int)AmmunitionLoadType.Direct,
                SpecificAmmunitionGrade = "Throwing",
                AmmunitionCapacity = 1,
                RangedWeaponType = (int)RangedWeaponType.Thrown,
                StaminaToFire = 30.0,
                StaminaPerLoadStage = 0.0,
                CoverBonus = -2.0,
                BaseAimDifficulty = (int)Difficulty.VeryHard,
                LoadDelay = 0.0,
                ReadyDelay = 0.0,
                FireDelay = 0.5,
                AimBonusLostPerShot = 1.0,
                RequiresFreeHandToReady = true,
                AlwaysRequiresTwoHandsToWield = false
            };
            context.RangedWeaponTypes.Add(ranged);
            context.SaveChanges();

            component = new GameItemComponentProto
            {
                Id = context.GameItemComponentProtos.Max(x => x.Id) + 1,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "ThrownWeapon",
                Name = "Throwing_Spear",
                Description = "Turns an item into a throwing spear",
                Definition =
                    $"<Definition><RangedWeaponType>{ranged.Id}</RangedWeaponType><MeleeWeaponType>{context.WeaponTypes.First(x => x.Name == "Short Spear").Id}</MeleeWeaponType></Definition>"
            };
            context.GameItemComponentProtos.Add(component);
            context.SaveChanges();
        }

        EnsurePrimitiveRangedContent(context, skills);
    }
}
