#nullable enable

using MudSharp.Character.Name;
using MudSharp.Form.Shape;
using MudSharp.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DatabaseSeeder.Seeders;

public partial class CultureSeeder
{
	private enum ModernNameOrder
	{
		GivenFamily,
		FamilyGiven
	}

	private sealed record ModernEthnicityProfileSeed(
		string EthnicityName,
		string CultureName,
		ModernNameOrder NameOrder,
		string MaleNames,
		string FemaleNames,
		string Surnames);

	private static readonly IReadOnlyList<ModernEthnicityProfileSeed> ModernEthnicityProfileSeeds =
	[
		new("Germanic", "Modern Germanic", ModernNameOrder.GivenFamily, GermanicMaleNames, GermanicFemaleNames, GermanicSurnames),
		new("Italic", "Modern Italic", ModernNameOrder.GivenFamily, ItalianMaleNames, ItalianFemaleNames, ItalianSurnames),
		new("Hispanic", "Modern Iberian", ModernNameOrder.GivenFamily, IberianMaleNames, IberianFemaleNames, IberianSurnames),
		new("Celtic", "Modern Celtic", ModernNameOrder.GivenFamily, IrishMaleNames, IrishFemaleNames, IrishSurnames),
		new("Slavic", "Modern Slavic", ModernNameOrder.GivenFamily, EasternSlavicMaleNames, EasternSlavicFemaleNames, EasternSlavicSurnames),
		new("Greek", "Modern Greek", ModernNameOrder.GivenFamily, GreekMaleNames, GreekFemaleNames, GreekSurnames),
		new("Turkish", "Modern Turkic", ModernNameOrder.GivenFamily, TurkishMaleNames, TurkishFemaleNames, TurkishSurnames),
		new("Arabic", "Modern Arabic", ModernNameOrder.GivenFamily, LevantineMaleNames, LevantineFemaleNames, LevantineSurnames),
		new("Persian", "Modern Persian", ModernNameOrder.GivenFamily, PersianMaleNames, PersianFemaleNames, PersianSurnames),
		new("Scandanavian", "Modern Scandinavian", ModernNameOrder.GivenFamily, ScandinavianMaleNames, ScandinavianFemaleNames, ScandinavianSurnames),
		new("North African", "Modern North African", ModernNameOrder.GivenFamily, MorrocanMaleNames, MorrocanFemaleNames, MorrocanSurnames),
		new("Bantu", "Modern Sub-Saharan", ModernNameOrder.GivenFamily, SubSaharanMaleNames, SubSaharanFemaleNames, SubSaharanSurnames),
		new("Khoisan", "Modern Sub-Saharan", ModernNameOrder.GivenFamily, SubSaharanMaleNames, SubSaharanFemaleNames, SubSaharanSurnames),
		new("Swahili", "Modern Swahili", ModernNameOrder.GivenFamily, SwahiliMaleNames, SwahiliFemaleNames, SwahiliSurnames),
		new("Polynesian", "Modern Oceanic", ModernNameOrder.GivenFamily, OceanicMaleNames, OceanicFemaleNames, OceanicSurnames),
		new("Austronesian", "Modern Southeast Asian", ModernNameOrder.GivenFamily, SoutheastAsianMaleNames, SoutheastAsianFemaleNames, SoutheastAsianSurnames),
		new("Melanesian", "Modern Oceanic", ModernNameOrder.GivenFamily, OceanicMaleNames, OceanicFemaleNames, OceanicSurnames),
		new("Afro-Carribean", "Modern Afro-Caribbean", ModernNameOrder.GivenFamily, AfroCaribbeanMaleNames, AfroCaribbeanFemaleNames, AfroCaribbeanSurnames),
		new("Afro-American", "Modern Afro-American", ModernNameOrder.GivenFamily, AfroAmericanMaleNames, AfroAmericanFemaleNames, AfroAmericanSurnames),
		new("Eskimo", "Modern Indigenous North American", ModernNameOrder.GivenFamily, IndigenousNorthMaleNames, IndigenousNorthFemaleNames, IndigenousNorthSurnames),
		new("Amerindian", "Modern Indigenous North American", ModernNameOrder.GivenFamily, IndigenousNorthMaleNames, IndigenousNorthFemaleNames, IndigenousNorthSurnames),
		new("Mesoamerican", "Modern Indigenous Latin American", ModernNameOrder.GivenFamily, IndigenousLatinMaleNames, IndigenousLatinFemaleNames, IndigenousLatinSurnames),
		new("Andean", "Modern Indigenous Latin American", ModernNameOrder.GivenFamily, IndigenousLatinMaleNames, IndigenousLatinFemaleNames, IndigenousLatinSurnames),
		new("Mongolian", "Modern Central Asian", ModernNameOrder.GivenFamily, CentralAsianMaleNames, CentralAsianFemaleNames, CentralAsianSurnames),
		new("Yamato", "Modern Japanese", ModernNameOrder.FamilyGiven, JapaneseMaleNames, JapaneseFemaleNames, JapaneseSurnames),
		new("Korean", "Modern Korean", ModernNameOrder.FamilyGiven, KoreanMaleNames, KoreanFemaleNames, KoreanSurnames),
		new("Tibetan", "Modern Central Asian", ModernNameOrder.GivenFamily, CentralAsianMaleNames, CentralAsianFemaleNames, CentralAsianSurnames),
		new("Uyghur", "Modern Turkic", ModernNameOrder.GivenFamily, TurkishMaleNames, TurkishFemaleNames, TurkishSurnames),
		new("Ainu", "Modern Japanese", ModernNameOrder.FamilyGiven, JapaneseMaleNames, JapaneseFemaleNames, JapaneseSurnames),
		new("Aboriginal Australian", "Modern Aboriginal Australian", ModernNameOrder.GivenFamily, AboriginalAustralianMaleNames, AboriginalAustralianFemaleNames, AboriginalAustralianSurnames),
		new("Austro-Asiatic", "Modern Southeast Asian", ModernNameOrder.GivenFamily, SoutheastAsianMaleNames, SoutheastAsianFemaleNames, SoutheastAsianSurnames),
		new("Tai-Kadai", "Modern Southeast Asian", ModernNameOrder.GivenFamily, SoutheastAsianMaleNames, SoutheastAsianFemaleNames, SoutheastAsianSurnames),
		new("Anglo-Saxon", "Modern Anglo-Saxon", ModernNameOrder.GivenFamily, EnglishMaleNames, EnglishFemaleNames, EnglishSurnames)
	];

	private const string GermanicMaleNames = "Johann|Heinrich|Wilhelm|Karl|Franz|Friedrich|Paul|Hans|Ernst|Otto|Hermann|Kurt|Walter|Gustav|Leo|Max|Ludwig|Emil|Bruno|Albert|Leopold|Tobias|Sebastian|Alexander|Dieter|Martin|Markus|Rainer|Stefan|Andreas|Dietmar|Peter|Matthias|Uwe|Volker|Manfred|Rolf|Klaus|Reinhard|Joachim|Hartmut|Jurgen|Werner|Armin|Bernd|Claus|Eckhard|Erich|Falk|Frank|Gerd|Gunther|Helmut|Horst|Jan|Jorg|Kai|Karl-Heinz|Lothar|Marcus|Mario|Norbert";
	private const string GermanicFemaleNames = "Maria|Anna|Elisabeth|Margarete|Hedwig|Luise|Clara|Gertrud|Agathe|Helene|Johanna|Rosa|Emma|Frieda|Marianne|Auguste|Mathilde|Else|Agnes|Anna-Lena|Brigitte|Daniela|Erika|Gisela|Ilse|Ingrid|Karin|Katarina|Klara|Kristina|Laura|Lena|Leonie|Lisa|Lorelei|Marlene|Monika|Nadine|Paula|Petra|Renate|Sabine|Simone|Sonja|Stefanie|Susanne|Ursula|Vera|Victoria|Viola|Waltraud|Yvonne|Zita|Adelheid|Annette|Astrid|Bettina|Birgit|Dagmar|Elke|Elfriede|Gerda|Hilda|Hildegard|Inge|Irmgard";
	private const string GermanicSurnames = "Muller|Schmidt|Schneider|Fischer|Weber|Meyer|Wagner|Becker|Hoffmann|Schulz|Braun|Zimmermann|Schaefer|Koch|Richter|Klein|Wolf|Schroder|Neumann|Schwarz|Hartmann|Lange|Schmitt|Werner|Krause|Schmid|Weiss|Vogel|Keller|Bohm|Brandt|Seidel|Albrecht|Lorenz|Sauer|Peters|Frank|Gunther|Schulte|Busch|Konig|Winkler|Schreiber|Thomas|Arnold|Ludwig|Dietrich|Otto|Sebastian|Tobias|Detlef|Dirk|Stefan|Michael|Ralf|Thorsten|Wilfried|Horst|Arne|Berndt|Carsten|Edgar|Falkenberg|Herbert|Jurgen|Karl|Manfred|Norbert|Reinhardt|Siegfried|Wilhelm|Wolfgang|Alfred|Clausen|Dieterich|Eberhardt|Fritz|Guido|Helmut|Jens|Nikolaus|Olaf|Pascal|Roland|Theodor|Volker|Xaver|Alois|Benedikt|Christoph|Eckhard|Florian|Gregor|Hartmut|Isidor|Janzen|Maximilian|Philipp|Quirin|Ulrich|Walter";

	private const string EnglishMaleNames = "James|John|William|Robert|Michael|David|Richard|Joseph|Thomas|Charles|Christopher|Daniel|Matthew|Anthony|Mark|Donald|Steven|Paul|Andrew|Joshua|Kenneth|Kevin|Brian|George|Timothy|Ronald|Edward|Jason|Jeffrey|Ryan|Jacob|Gary|Nicholas|Eric|Stephen|Larry|Justin|Scott|Brandon|Benjamin|Adam|Harry|Samuel|Gregory|Frank|Raymond|Alexander|Patrick|Jack|Dennis|Jerry|Tyler|Aaron|Henry|Douglas|Peter|Kyle|Walter|Ethan|Jeremy|Harold|Keith|Christian|Roger|Noah|Gerald|Carl|Terry|Sean|Austin|Arthur|Lawrence|Jesse|Dylan";
	private const string EnglishFemaleNames = "Mary|Patricia|Jennifer|Linda|Elizabeth|Barbara|Susan|Jessica|Sarah|Karen|Nancy|Lisa|Betty|Margaret|Sandra|Ashley|Kimberly|Donna|Emily|Michelle|Carol|Amanda|Dorothy|Melissa|Debra|Stephanie|Rebecca|Laura|Sharon|Cynthia|Kathleen|Amy|Shirley|Angela|Helen|Anna|Brenda|Pamela|Nicole|Ruth|Katherine|Samantha|Christine|Emma|Catherine|Virginia|Rachel|Carolyn|Janet|Maria|Heather|Diane|Julie|Joyce|Victoria|Kelly|Christina|Lauren|Joan|Evelyn|Frances|Gloria|Ann|Jean|Alice|Kathryn|Judy|Cheryl|Megan|Andrea|Jacqueline|Rose";
	private const string EnglishSurnames = "Smith|Jones|Williams|Taylor|Brown|Davies|Wilson|Evans|Thomas|Roberts|Johnson|Lewis|Walker|Robinson|Wood|Thompson|White|Clark|Hall|Harris|Martin|Moore|Jackson|Wright|Hill|Green|Adams|Baker|Mitchell|Turner|Cooper|Ward|Cox|Phillips|Collins|Bell|Foster|Gray|Price|Hughes|Long|Richardson|Russell|Simmons|Graham|Bennett|Patterson|Wallace|Jenkins|Perry|Powell|Butler|Barnes|Fisher|Gibson|Dean|Armstrong|Knight|Hicks|Crawford|Burns|Palmer|Holland|Ellis|Nash|Drake|Spencer|Harper|Bryant|Thornton|Webb|Parker|Miles|Davidson|Berry|Chapman|Heath|Shaw|Pope|Lambert|Stevenson|Gardner|Newman|Carpenter|Fleming|Fuller|Jordan|Marsh|Freeman|Fowler|Holt|Pearson|Gill|Lucas|Maxwell|Preston|Baxter|Lawson|Payne|Cross";

	private const string ItalianMaleNames = "Giovanni|Giuseppe|Francesco|Antonio|Alessandro|Marco|Matteo|Leonardo|Lorenzo|Andrea|Carlo|Stefano|Paolo|Luca|Riccardo|Fabio|Davide|Roberto|Enrico|Simone|Michele|Gabriele|Daniele|Claudio|Emanuele|Salvatore|Massimo|Vincenzo|Valentino|Giulio|Angelo|Benedetto|Giuliano|Federico|Pietro|Cesare|Domenico|Luigi|Amedeo|Bartolomeo|Biagio|Corrado|Damiano|Elia|Emilio|Fabrizio|Felice|Ferdinando|Gaetano|Gregorio|Ignazio|Jacopo|Lazzaro|Luciano|Manfredo|Nazzareno|Ottavio|Pasquale|Quirino|Renato|Rinaldo|Ruggero|Samuele|Sebastiano|Silvano|Taddeo|Ulisse|Valerio|Virgilio|Vittorio|Zeno";
	private const string ItalianFemaleNames = "Maria|Anna|Isabella|Laura|Lucia|Caterina|Francesca|Giovanna|Chiara|Beatrice|Elena|Bianca|Alessandra|Federica|Martina|Claudia|Teresa|Stefania|Valentina|Angela|Daniela|Paola|Sara|Veronica|Rita|Adriana|Emilia|Silvia|Elisa|Margherita|Antonella|Elettra|Ilaria|Irene|Letizia|Liliana|Livia|Lorenza|Luisa|Maddalena|Manuela|Marta|Matilde|Mirella|Noemi|Ornella|Pamela|Patrizia|Pia|Raffaella|Renata|Romina|Sabrina|Serena|Sofia|Valeria|Vanessa|Adele|Agnese|Alberta|Alice|Assunta|Augusta|Barbara|Benedetta|Brunella|Cecilia|Clara|Concetta|Donatella|Emma|Erminia|Ester|Evelina|Filomena|Flavia|Fulvia|Gemma|Giulia|Grazia";
	private const string ItalianSurnames = "Rossi|Bianchi|Romano|Ricci|Colombo|Ferrari|Esposito|Russo|Moretti|Gallo|Costa|Fontana|Conti|De Luca|De Santis|Ferraro|Mancini|Martino|Rizzo|Lombardi|Valentini|Giordano|Silvestri|Barbieri|De Rosa|Rinaldi|Benedetti|Sarti|Caruso|Mariani|Ricciardi|Piras|Vitale|Graziano|Marchetti|Gentile|Messina|Pugliese|Gatti|Longo|Guerra|Martini|Battaglia|Cattaneo|Lombardo|Amato|Barone|Bianco|Bruno|Caputo|D'Amico|D'Angelo|D'Alessandro|D'Antonio|D'Andrea|D'Elia|D'Emilio|De Marco|De Simone|Di Bello|Di Carlo|Di Giacomo|Di Lorenzo|Di Matteo|Di Stefano|Di Vincenzo|Diodato|Fiorentino|Fornari|Franco|Fumagalli|Galasso|Gambino|Giani|Giorgi|Giuliani|Giusti|Grassi|Greco|Iannuzzi|Lamberti|La Rocca|Leone|Longhi|Lucarelli|Luciani|Macaluso|Macri|Maggi|Marini|Marino|Mazzola|Miceli|Migliore|Morelli|Muratori|Neri|Nicastro|Pagano|Palumbo|Parisi|Pellegrini|Perini|Perri|Piana|Pirelli|Pizzuto|Polidori|Porzio|Pozzi|Quaranta|Raffaelli|Rossetti|Sanna|Santoro|Serra|Simonetti|Simone|Spada|Spinelli|Testa|Tosi|Trovato|Valli|Valente|Venturi|Verdi|Vescovi|Vianello|Villani|Vitelli|Viviani|Zamboni|Zanetti|Zanoni|Zappala|Zeni|Zocchi|Zola|Zucchi|Zucco";

	private const string IberianMaleNames = "Juan|Pedro|Francisco|Luis|Alonso|Diego|Miguel|Antonio|Gabriel|Rodrigo|Andres|Carlos|Fernando|Gonzalo|Hernando|Ignacio|Jeronimo|Lorenzo|Martin|Mateo|Pablo|Rafael|Sebastian|Tomas|Vicente|Alvaro|Bernardo|Cristobal|Esteban|Felipe|Hugo|Jacobo|Jaime|Leonardo|Mauricio|Nicolas|Oscar|Ramiro|Samuel|Silvestre|Teodoro|Valentin|Claudio|Danilo|Emilio|Fabricio|Gregorio|Isidro|Leon|Marco|Marcelo|Renato|Ruben|Salvador|Sergio|Ulises|Arturo|Braulio|Casimiro|Dante|Ezequiel|Faustino|Gerardo|Horacio|Ivan|Jacinto|Leandro|Norberto|Octavio|Pascual|Quirino";
	private const string IberianFemaleNames = "Maria|Ana|Isabel|Catalina|Juana|Teresa|Laura|Magdalena|Antonia|Margarita|Francisca|Ines|Ramona|Lucia|Pilar|Eloisa|Clara|Andrea|Cecilia|Rosa|Victoria|Angeles|Esperanza|Alicia|Beatriz|Bernarda|Dolores|Emilia|Estefania|Gabriela|Graciela|Ignacia|Jacinta|Josefina|Leonor|Leticia|Lorenza|Luisa|Manuela|Marta|Natalia|Noelia|Olivia|Paula|Regina|Renata|Rita|Sara|Silvia|Sofia|Susana|Valentina|Veronica|Yolanda|Zoraida|Angela|Berta|Carolina|Daniela|Ema|Felisa|Gema|Hortensia|Irene|Lidia|Lola|Lucrecia|Mercedes|Miriam|Rosario";
	private const string IberianSurnames = "Gonzalez|Rodriguez|Garcia|Fernandez|Lopez|Martinez|Sanchez|Perez|Gomez|Martin|Jimenez|Hernandez|Diaz|Alvarez|Torres|Ramirez|Flores|Rivera|Morales|Castro|Ortega|Herrera|Ruiz|Mendoza|Romero|Rubio|Delgado|Silva|Soto|Ramos|Molina|Guzman|Navarro|Pacheco|Camacho|Vargas|Rivas|Bravo|Salazar|Espinoza|Carrasco|Vazquez|Pena|Cordero|Castaneda|Marquez|Leon|Solis|Benitez|Montenegro|Valencia|Carrillo|Guerra|Castillo|Paredes|Montoya|Orozco|Lozano|Leiva|Valdez|Blanco|Aguirre|Barrera|Cardenas|Miranda|Acevedo|Zamora|Valdes|Quiroz|Andrade|Salinas|Varela|Suarez|Solano|Coronado|Arias|Escobar|Barrientos|Figueroa|Zambrano|Barajas|Trejo|Roldan|Aguayo|Santamaria|Cifuentes|Palacios|Alcantara|Arenas|Cortes|Cabrera|Sosa|Duran|Macias|Bautista|Valenzuela|Fuentes|Herrero|Montes|Pascual";

	private const string IrishMaleNames = "Sean|Aodh|Domhnall|Briain|Niall|Conchobhar|Donnchadh|Eoghan|Diarmaid|Toirdhealbhach|Tadhg|Ruarc|Murchadh|Cathal|Finghin|Uilliam|Eamonn|Fearghal|Maoliosa|Giolla Phadraig|Eochaidh|Cormac|Fachtna|Ultan|Aonghus|Mathghamhain|Raighne|Faolan|Oisin|Lochlann|Muireadhach|Colman|Flann|Cian|Cristoir|Piaras|Micheal|Laoghaire|Flaithri|Guaire|Ailbhe|Conghal|Ailill|Raghallach|Earc|Uaithear|Eanna|Tigernach|Cathaoir|Dalach|Senchan|Loingsech|Lorcan|Maelruanaid|Ruadri|Finbar|Conall|Cathaoirleach|Brianan|Ciaran|Padraig|Fergal|Lorcan|Ronan|Declan|Daire|Eoin|Cillian|Odhran|Donal|Aidan|Tiernan|Turlough";
	private const string IrishFemaleNames = "Maire|Brighid|Caitlin|Aoife|Grainne|Sorcha|Eibhlin|Rois|Sile|Una|Fionnuala|Nuala|Mor|Mairead|Dearbhail|Aifric|Eithne|Cait|Treasa|Damhnait|Findabair|Liadhain|Niamh|Bebhinn|Morfhlaith|Ailbhe|Mallaidh|Eilis|Onora|Eireann|Fidelma|Gormlaith|Ide|Laoiseach|Muadhnait|Orlaith|Riona|Sinead|Sadhbh|Blaithin|Clair|Dairine|Medbh|Roisin|Brianna|Clodagh|Ciara|Aisling|Bronagh|Orna|Caoimhe|Fiona|Rionaid|Eimear|Muireann|Saoirse|Dearbhla|Ailis|Aine|Etain|Nessa|Brana|Meabh|Sorley|Sinann|Taillte|Tuilelaith|Uallach";
	private const string IrishSurnames = "O Neill|O Briain|O Conchobhair|O Domhnaill|O Suilleabhain|Mac Carthaigh|O Cearbhaill|O Ceallaigh|O Raghallaigh|Mac Murchadha|O hAodha|O Dalaigh|Mac Domhnaill|O Dubhda|O Gairbhith|O hEidhin|O Riain|Mac Conmara|O Fiachra|O Griofa|O Laoghaire|O Madadhain|O Murchadha|O Coinn|O hAirt|Mac Giolla Eain|O Ceallachain|O Muireadhaigh|O Donnabhain|O Flaithbheartaigh|O Gadhra|O hAnluain|Mac Diarmada|Mac Aodhagain|O Cinnsealach|O Donnghaile|Mac Cana|O Lorcain|O Lochlainn|O Mathghamhna|O Cadhla|O Cianain|Mac Giolla Chainnigh|Mac Giollarnath|O Giollain|O Bruadair|Mac Murchu|O hEachach|O Maoilriain|O Braoin|O Donnchadha|O Maonaigh|O Ceochain|Mac Tighearnain|O Foghludha|O Haolain|O Conaill|O Dufaigh|O Liathain|O Muireartaigh|O Reachtabhra|O Seachnasaigh|O Sionnaigh|Mac Branain|O Branain|O Longain|Mac Ailin|O Cuilinn|O Draighnain|O Duibhne|O Fallamhain|O Glaisne|O hInnse|O Mael Eoin|O Taichligh|O Roduibh|Mac Aodh|O hUltachain|O hIci|Mac Giolla Fhiondain|O hAonghusa|O Mael Fhabhaill|O Muireagain|O hUiginn|Mac Uidhir|O Maoilchonaire|O hAinbheith|Mac Suibhne|O hEaghra|O hEoghanain|O Duibhidhir|Mac Gilla Patrick|O Dwyer|O Driscoll|O Malley|O Dea|Mac Gearailt|O Meachair|Mac Raghnaill|O Muldoon";

	private const string EasternSlavicMaleNames = "Ivan|Pyotr|Vasily|Dmitry|Mikhail|Nikolai|Andrei|Aleksei|Boris|Yury|Fedor|Roman|Timofey|Konstantin|Pavel|Yaroslav|Vladislav|Gleb|Rodion|Nikita|Stepan|Grigory|Semyon|Matvey|Yevgeny|Afanasy|Bogdan|Makar|Anton|Lavrenty|Yefim|Danila|Mstislav|Rostislav|Vladimir|Leonid|Maksim|Filipp|Spiridon|Feofan|Tikhon|Nazar|Arkady|Trofim|Yefrem|Gordey|Vsevolod|Prokhor|Emelyan|Kondrat|Isidor|Dionisy|Faddey|Yakov|Luka|Zakhar|Porfyry|Gerasim|Savva|Nikon|Terenty|Savely|Markel|Frol|Gury|Dorofey|Demid|Taras|Pakhom|Svyatoslav|Radomir|Lyubomir|Avgust|Marian|Sava|Dragan|Kostya|Gennady|Foma|Lazar|Varlaam|Orest|Miron|Ostap|Alexei";
	private const string EasternSlavicFemaleNames = "Anastasia|Elena|Maria|Darya|Feodora|Irina|Sofia|Yekaterina|Anna|Tatyana|Olga|Ulyana|Galina|Lyubov|Varvara|Nadezhda|Alena|Vasilisa|Pelageya|Kseniya|Evdokia|Praskovya|Natalya|Melania|Agrippina|Antonina|Marta|Lukerya|Solomonia|Feodosia|Paraska|Marfa|Efrosinya|Marina|Apollinaria|Margarita|Nina|Darina|Anfisa|Fevronia|Vasilina|Polina|Zoya|Agafya|Domna|Pelagia|Zlata|Lada|Bronislava|Yaroslava|Svetlana|Bozena|Radmila|Dragana|Lidya|Miroslava|Albina|Rostislava|Larysa|Oksana|Vira|Bohdana|Vladislava|Roksolana|Kupava|Malusha|Dobrava|Mirra|Zhanna|Nadya|Aksana|Ustinya|Raisa|Dasha|Nyura|Roksana|Halyna|Olena|Zoreslava|Mlada|Velislava";
	private const string EasternSlavicSurnames = "Ivanov|Petrov|Vasiliev|Fedorov|Nikolaev|Andreev|Pavlov|Grigoryev|Egorov|Sergeev|Mikhailov|Alexandrov|Kirillov|Nikitin|Timofeev|Dmitriev|Georgiev|Romanov|Maksimov|Yuriev|Borisov|Danilov|Rodionov|Lukin|Sidorov|Stepanov|Filippov|Afanasiev|Artemiev|Morozov|Belov|Trofimov|Voronin|Kravchuk|Rudenko|Boyko|Melnik|Sychev|Panov|Karpov|Vaschenko|Korolev|Volkov|Sorokin|Ershov|Golubev|Smirnov|Zaitsev|Koval|Yakovlev|Chaika|Drozdov|Pavlenko|Marchenko|Bondar|Kutsenko|Kornilov|Osipov|Sergienko|Markov|Kuznetsov|Myshkin|Lukashenko|Gromov|Kalashnikov|Babich|Polivanov|Tsarev|Khrustalev|Malakhov|Dudinsky|Timchenko|Levitsky|Bolshakov|Balabanov|Dehtyarenko|Gapon|Popov|Yudin|Filonov|Shostak|Klimov|Romanchenko|Kozlov|Tikhomirov|Volokh|Durnev|Malinov|Lysenko|Rusakov|Vronsky|Zhuravlev|Nemirov|Denisov|Bunyachenko|Raskolnikov|Sokolov|Tretyakov|Vorobyov|Kravtsov";

	private const string GreekMaleNames = "Georgios|Giannis|Dimitrios|Nikolaos|Konstantinos|Panagiotis|Vasileios|Christos|Theodoros|Athanasios|Andreas|Ioannis|Sotirios|Alexandros|Evangelos|Stavros|Spiros|Antonios|Petros|Manolis|Marios|Leonidas|Michalis|Anastasios|Haralambos|Lefteris|Odysseas|Pavlos|Nikos|Kostas|Babis|Tasos|Thanasis|Grigoris|Kyriakos|Apostolos|Fotis|Ilias|Lambros|Minas|Nektarios|Pantelis|Renos|Sakis|Takis|Vangelis|Xenophon|Zisis|Achilleas|Aris|Dionysis|Emmanouil|Filippos|Haris|Iakovos|Kleon|Loukas|Markos|Nestor|Orfeas|Prodromos|Rafail|Stefanos|Timoleon|Yorgos|Zafiris";
	private const string GreekFemaleNames = "Maria|Eleni|Katerina|Sofia|Dimitra|Ioanna|Georgia|Vasiliki|Panagiota|Anastasia|Christina|Angeliki|Konstantina|Despoina|Niki|Eirini|Alexandra|Anthoula|Aspasia|Chrysanthi|Daphne|Efstathia|Evangelia|Fotini|Glykeria|Hariklia|Ioulia|Kalliope|Lambrini|Leda|Margarita|Marina|Natasa|Ourania|Paraskevi|Rania|Smaragda|Styliani|Theodora|Vicky|Xenia|Zoe|Ariadni|Dora|Eugenia|Irida|Iro|Kleopatra|Loukia|Melina|Nefeli|Olga|Pavlina|Roxani|Stella|Tasia|Vasilia|Yiota|Zacharoula|Agapi|Danae|Elpida|Evdokia|Fenia|Irini|Lilian|Nantia";
	private const string GreekSurnames = "Papadopoulos|Papadakis|Papageorgiou|Papandreou|Pappas|Nikolaou|Georgiou|Dimitriou|Ioannou|Konstantinou|Vasiliou|Christodoulou|Theodorou|Alexiou|Antonopoulos|Stavropoulos|Andreadis|Kostopoulos|Panagopoulos|Oikonomou|Katsaros|Spyridakis|Makris|Kalogeropoulos|Vlahos|Raptis|Tsakalos|Manolakis|Mavros|Doukas|Zervas|Aggelopoulos|Margaritis|Karakostas|Karamitsos|Laskaridis|Mylonas|Roussos|Tsitsipas|Moutsakis|Economidis|Kontos|Deligiannis|Sarris|Bakalos|Drakos|Kanelopoulos|Karalis|Vassilakis|Sideris|Avramidis|Koutroubis|Kyriazis|Lappas|Liakos|Mastoras|Mazarakis|Mpelos|Nikolopoulos|Pagkalos|Pavlidis|Samaras|Skouras|Tzortzis|Xydis|Zacharopoulos|Athanasiou|Bellos|Diamantidis|Fountas|Karagiannis|Karathanasis|Koufos|Lazaridis|Mitsotakis|Nastos|Papanikolaou|Rallis|Sakellariou|Triantafyllou|Vogiatzis|Xanthopoulos|Zafeiropoulos|Arvanitis|Bartzokas|Charalampidis|Daskalakis|Evangelou|Fasoulas|Giannakopoulos|Hatzis|Kokkinos|Leventis|Marinakis|Nerantzis|Petridis|Roumeliotis|Sotiriou|Tsoukalas|Valavanis|Xenakis|Zournatzis";

	private const string TurkishMaleNames = "Mehmet|Mustafa|Ahmed|Hasan|Huseyin|Ali|Ibrahim|Suleyman|Osman|Murat|Fatih|Cemal|Rustem|Selim|Ahmet|Kemal|Emir|Baris|Zeki|Halil|Tuncay|Yilmaz|Orhan|Burak|Kadir|Onur|Sefer|Enver|Bulent|Ekrem|Necdet|Gokhan|Naim|Fahri|Cenk|Tarkan|Erhan|Tayfun|Dogan|Levent|Sahin|Veli|Serkan|Haluk|Ferit|Cevdet|Enis|Ramazan|Fikret|Ismail|Yunus|Fuat|Harun|Nihat|Behcet|Sefa|Cem|Adnan|Asim|Tarik|Zafer|Oktay|Engin|Metin|Mert|Erkan|Tolga|Sezgin|Muhammed|Halit|Necati|Hakan|Riza|Erol|Sabri|Yavuz|Kenan|Adil|Fevzi|Ferhat|Irfan|Bahadir|Enes|Ilker|Faruk|Nuri";
	private const string TurkishFemaleNames = "Ayse|Emine|Zeynep|Hatice|Elif|Meryem|Aylin|Esra|Ozlem|Yasemin|Sevgi|Selin|Busra|Derya|Melike|Burcu|Irem|Sibel|Ebru|Gul|Cansu|Sedef|Pinar|Asli|Papatya|Damla|Ceren|Gizem|Eda|Dilara|Nazli|Sevil|Buse|Lale|Sirin|Funda|Nihal|Zeliha|Ahu|Rabia|Nalan|Feride|Secil|Nermin|Ruya|Perihan|Tuba|Vildan|Ozge|Aysun|Nazan|Melis|Sila|Aysel|Berrin|Feraye|Pervin|Sebnem|Yildiz|Huriye|Gulsum|Ilayda|Alev|Melek|Simge|Meltem|Tulay|Suna|Canan|Yeliz|Zerrin|Nursel|Gulnur|Aybike|Hicran|Leman|Arzu|Hande|Sule|Bade|Beste|Meral|Seda|Reyhan|Alara";
	private const string TurkishSurnames = "Demir|Yildirim|Kaya|Celik|Arslan|Aydin|Aslan|Ozdemir|Korkmaz|Dogan|Sahin|Kurt|Ozturk|Acar|Altun|Gunes|Ugur|Gungor|Erdem|Efe|Basturk|Kilic|Koc|Yilmaz|Sari|Can|Erbas|Soylu|Turkmen|Bayraktar|Bektas|Ceylan|Karaca|Isik|Kocak|Oztuna|Aksoy|Polat|Gurkan|Bulut|Sen|Tekin|Bozkurt|Demirtas|Kocaman|Karadeniz|Erdogan|Cetin|Soydas|Karatas|Kaplan|Yalcin|Duman|Altin|Gul|Aktas|Boz|Aydinli|Elmas|Ercan|Gokcen|Balci|Kocer|Kucuk|Yuce|Basar|Yurekli|Ozkan|Inan|Aydogan|Toprak|Sonmez|Goksu|Ozlu|Arikan|Ekinci|Aksu|Yagmur|Gezer|Yenigun|Goktas|Gurbuz|Orhan|Savas|Canli|Mete|Tunc|Uslu|Baran|Caglar|Alper|Guclu|Numan|Yildiz|Basarir|Demirel|Ates|Bingol|Aydemir|Bayram";

	private const string PersianMaleNames = "Ali|Hossein|Mohammad|Reza|Mahmoud|Amir|Ebrahim|Kaveh|Farhad|Navid|Behruz|Kourosh|Sohrab|Shapur|Dariush|Ramin|Babak|Bijan|Arash|Rostam|Cyrus|Nader|Jamshid|Ghasem|Vahid|Parsa|Soroush|Mehrdad|Shervin|Javad|Salar|Yashar|Sam|Pedram|Esfandiar|Bahram|Nima|Siavash|Ashkan|Mehran|Kian|Alireza|Bahman|Daryush|Fariborz|Hamed|Iman|Kamran|Mahdi|Nasser|Omid|Parviz|Qasem|Rasoul|Shahin|Taha|Vali|Younes|Zaid|Adel|Baran|Ehsan|Faramarz|Lotfi|Masoud|Pirooz|Ramtin|Taher|Abbas|Behzad";
	private const string PersianFemaleNames = "Fatemeh|Zahra|Leila|Shirin|Maryam|Nasim|Parisa|Soraya|Mahin|Narges|Nazanin|Mitra|Setareh|Anahita|Ladan|Nahid|Azar|Roya|Simin|Golnaz|Mina|Roxana|Samira|Farah|Darya|Elham|Shahrzad|Firouzeh|Mahsa|Elaheh|Parvaneh|Shadi|Golnar|Neda|Tahmineh|Yasaman|Fereshteh|Bahar|Sepideh|Negar|Sahar|Niloofar|Goli|Homa|Tala|Raha|Arghavan|Sadaf|Atefeh|Azita|Laleh|Taraneh|Nazli|Marjan|Ghazal|Negin|Niloufar|Mahdieh|Bahareh|Azadeh|Farnaz|Mahnaz|Fariba|Soheila|Narmin|Mehrnoush|Pouneh|Roksana|Shabnam";
	private const string PersianSurnames = "Abbasi|Farahani|Khorasani|Shirazi|Isfahani|Qazvini|Tabrizi|Mashhadi|Balkhi|Semnani|Sistani|Mazandarani|Gilanese|Turkmeni|Yazdi|Farsiani|Kermani|Heratiani|Nishapuri|Bukhari|Khuzestani|Luri|Arakian|Ahvazi|Tabaristani|Ilamite|Zanjani|Marvdashti|Baluchi|Qomzadeh|Khorramdin|Dezfuli|Etemadi|Rostami|Dehghani|Fattahi|Sabziwari|Khademi|Saidi|Zare|Moradi|Bahrami|Momeni|Yusefian|Rasti|Vaziri|Aminzadeh|Sadeghi|Alavi|Nouri|Rahimi|Sheikhi|Bostani|Payami|Shamsi|Ghasemi|Jalali|Barzani|Samavati|Kousari|Mohammadi|Rastegar|Sadri|Aghaei|Ebrahimi|Najafi|Rouhani|Zamani|Talebi|Saadat|Karimzadeh|Hashemi|Taheri|Ghorbani|Shakeri|Khatami|Majidi|Rezai|Piri|Nazari|Basiri|Mirzaei|Rahbar|Taghavi|Sharifi|Farzaneh|Jahanbani|Mahdavi|Noorzadeh|Pakzad|Ravanbakhsh|Shadmani|Tavakoli|Yeganeh|Zolfaghari|Afshar|Darvishi|Kermanshahi|Sahraei|Yazdani";

	private const string LevantineMaleNames = "Ahmed|Mohammed|Ali|Hassan|Ibrahim|Omar|Khalid|Youssef|Mustafa|Tariq|Zaid|Rami|Samir|Farid|Nabil|Karim|Faisal|Saleh|Anwar|Sami|Bilal|Rashid|Jamal|Nasir|Idris|Adel|Luay|Amir|Majid|Khalil|Ammar|Imran|Anas|Hadi|Khaled|Qasim|Saif|Wael|Zain|Fahd|Habib|Malik|Yasin|Zayd|Basim|Firas|Hamza|Mazin|Umar|Ziad";
	private const string LevantineFemaleNames = "Aisha|Fatima|Zainab|Mariam|Khadija|Layla|Salma|Yasmin|Noor|Sara|Rania|Hana|Samira|Nadia|Leila|Aaliyah|Dina|Iman|Farah|Laila|Amira|Zeina|Dalia|Rasha|Samar|Noura|Reem|Dana|Malak|Amina|Bushra|Huda|Rima|Lamis|Jamila|Karima|Najwa|Farida|Wafa|Lubna|Nawal|Haniya|Rehana|Tahira|Abeer|Mona|Rana|Shireen|Tahani|Yara|Maysa|Widad|Sawsan|Amani|Dalal";
	private const string LevantineSurnames = "Al-Farsi|Al-Masri|Al-Zahiri|Al-Hakim|Al-Salem|Al-Rashid|Al-Khalili|Al-Najjar|Al-Baghdadi|Al-Qadir|Al-Farouq|Al-Sayeed|Al-Hassan|Al-Jabari|Al-Hashimi|Al-Mansour|Al-Tikriti|Al-Karim|Al-Fadil|Al-Mutairi|Al-Saadi|Al-Mutlaq|Al-Sabah|Al-Nasser|Al-Maari|Al-Hakeem|Al-Qasim|Al-Hussein|Al-Muqaddam|Al-Sharif|Al-Rumi|Al-Taher|Al-Mutawakel|Al-Hakimi|Al-Najafi|Al-Khatib|Al-Jabiri|Al-Sayyid|Al-Rifai|Al-Hamdan|Al-Balushi|Al-Shehabi|Al-Amin|Al-Ghamdi|Al-Muhairi|Al-Baqi|Al-Jundi|Al-Harthy|Al-Quraishi|Al-Turki|Al-Azmi|Al-Sulayman|Al-Bayati|Al-Rahman|Al-Bukhari|Al-Hamidi|Al-Mansouri|Al-Abadi|Al-Atassi|Al-Atrash|Al-Ayoubi|Al-Banna|Al-Barazi|Al-Bitar|Al-Dabbagh|Al-Din|Al-Haddad|Al-Halabi|Al-Hijazi|Al-Jamal|Al-Karmi|Al-Khoury|Al-Kilani|Al-Laham|Al-Masalha|Al-Momani|Al-Nouri|Al-Obaidi|Al-Qudsi|Al-Sabbagh|Al-Safadi|Al-Shami|Al-Shawwa|Al-Tal|Al-Wazir|Barakat|Darwish|Habib|Khoury|Mansour|Nassar|Saadeh|Shammas|Tannous|Yacoub|Zein|Abbas|Kanaan|Matar|Sabbah";

	private const string MorrocanMaleNames = LevantineMaleNames;
	private const string MorrocanFemaleNames = LevantineFemaleNames;
	private const string MorrocanSurnames = LevantineSurnames;

	private const string ScandinavianMaleNames = "Anders|Erik|Nils|Olaf|Sven|Karl|Bjorn|Hakon|Einar|Jonas|Magnus|Torvald|Harald|Leif|Gunnar|Torgeir|Arvid|Halvard|Sigurd|Rolf|Axel|Jesper|Steinar|Mads|Knud|Vidar|Egil|Folke|Torben|Eskil|Sten|Bo|Tord|Odd|Tore|Hallvard|Orm|Thor|Brynjulf|Eskild|Frithjof|Gudmund|Haakon|Hans|Ivar|Kolbein|Ove|Ragvald|Sune|Ulf|Bjarne|Sigfrid|Peder|Johann|Eske|Jakob|Martin|Ake|Thore|Vegard|Kjell|Gisle|Mikkel|Ture|Emund|Hogne|Hauk|Kyrre|Storm|Borge|Dreng|Embret|Geir|Helge|Lasse|Rune|Torgils|Yngvar";
	private const string ScandinavianFemaleNames = "Anna|Margareta|Ingeborg|Sigrid|Karin|Birgitta|Cecilia|Gunhild|Kristina|Botilda|Ragnhild|Bodil|Helga|Astrid|Ingrid|Gyda|Magda|Elsken|Eline|Marta|Gertrud|Elsa|Mari|Johanna|Benedicta|Malin|Dordi|Lucia|Eufemia|Ragnfrid|Dorotea|Sunniva|Tora|Beret|Tyri|Dorte|Alfilda|Lovisa|Mette|Torborg|Rannveig|Katri|Silja|Guro|Eira|Hanna|Ella|Hedevig|Inga|Kjersti|Inger|Oline|Clara|Gro|Hild|Birta|Kaja|Margit|Gunvor|Randi|Signy|Tordis|Frida|Gyrid|Helene|Sanna|Oda|Linnea|Solveig|Tove|Gunna|Ebba|Ylva|Thea|Helmi|Ada|Bertha|Kristine";
	private const string ScandinavianSurnames = "Andersen|Jensen|Nielsen|Hansen|Pedersen|Christensen|Larsen|Sorensen|Rasmussen|Jorgensen|Petersen|Madsen|Kristensen|Olsen|Thomsen|Poulsen|Johnsen|Magnussen|Eriksen|Iversen|Svensson|Johansson|Karlsson|Nilsson|Olsson|Persson|Gustafsson|Andersson|Larsson|Bergstrom|Lundgren|Lindberg|Lundqvist|Dahlberg|Nygaard|Mikkelsen|Mortensen|Knudsen|Svendsen|Moen|Dahl|Solberg|Haugen|Aasen|Eide|Bakke|Nygard|Bjerke|Odegard|Sundberg|Lindgren|Berglund|Soderberg|Ahlstrom|Hellstrom|Lundin|Nordstrom|Viklund|Westberg|Ronnberg|Bergman|Lindholm|Soderlund|Aas|Skov|Holm|Engstrom|Eklund|Granlund|Isaksen|Jakobsen|Halvorsen|Henriksen|Mathisen|Torgersen|Wiklund|Strom|Borg|Rosenberg|Falck|Molander|Ekstrom|Fagerstrom|Korsgaard|Hedlund|Bergqvist|Akerlund|Nyberg|Skoglund|Lundberg|Granberg|Hedman|Norrman|Sjoberg|Stenberg|Dalen|Nordahl|Vestergaard|Lindstrom|Bjerregaard";

	private const string SubSaharanMaleNames = "Kwame|Kofi|Kojo|Kwaku|Yaw|Kwabena|Kwesi|Ade|Adewale|Adebayo|Oluwaseun|Olumide|Chinedu|Chukwuemeka|Emeka|Obinna|Nnamdi|Ifeanyi|Sibusiso|Themba|Thabo|Sipho|Andile|Mandla|Simphiwe|Tendai|Tatenda|Tawanda|Bongani|Bhekizizwe|Kagiso|Lethabo|Neo|Tshepo|Kamau|Otieno|Baraka|Jelani|Juma|Mosi|Nuru|Amadou|Mamadou|Ibrahim|Cheikh|Moussa|Ousmane|Abdoulaye|Idrissa|Sekou|Boubacar|Fode|Alpha|Salif|Modibo|Ayo|Femi|Kunle|Tunde|Omari|Zuberi|Ajani|Tau|Samora|Kabelo|Mpho";
	private const string SubSaharanFemaleNames = "Ama|Akosua|Abena|Akua|Efua|Adwoa|Yaa|Adjoa|Amahle|Ayanda|Nokuthula|Nomsa|Nandi|Thandiwe|Busisiwe|Lindiwe|Zanele|Nosipho|Gugulethu|Thandeka|Nomvula|Naledi|Lerato|Neo|Mpho|Amina|Zainab|Fatou|Mariama|Aissatou|Kadiatou|Awa|Aicha|Seynabou|Nafissatou|Ifeoma|Chioma|Chinwe|Uchechi|Ngozi|Amara|Temitope|Funmilayo|Bisi|Yetunde|Omotola|Esi|Naa|Abiola|Ayodele|Makena|Achieng|Barika|Eshe|Nia|Zola|Bukola|Chiamaka|Eunice|Kehinde|Mirembe|Ntombi|Pendo|Sade";
	private const string SubSaharanSurnames = "Mensah|Owusu|Boateng|Osei|Appiah|Agyeman|Adeyemi|Adeleke|Afolayan|Okafor|Okonkwo|Nwosu|Balogun|Adebayo|Ajayi|Abiola|Onyango|Mwangi|Kamau|Omondi|Otieno|Ochieng|Wekesa|Ncube|Dlamini|Khumalo|Ndlovu|Moyo|Sibanda|Zulu|Mthembu|Mkhize|Naidoo|Pillay|Gumede|Masango|Mahlangu|Phiri|Banda|Tembo|Ngoma|Kalumba|Mwale|Soko|Konate|Keita|Camara|Diallo|Ba|Sow|Cisse|Toure|Traore|Coulibaly|Kone|Sissoko|Diop|Ndiaye|Faye|Seck|Gueye|Sarr|Barry|Jallow|Manneh|Conteh|Kamara|Kabba|Kargbo|Sesay|Bangura|Koroma|Bah|Abebe|Bekele|Tesfaye|Mekonnen|Girma|Tadesse|Negash|Hailu|Haile|Assefa|Worku|Shiferaw|Belay|Zewde|Abdullahi|Farah|Warsame|Mohamud|Osman|Elmi|Buhari|Mahama|Nyathi|Radebe|Chirwa|Musonda|Mwansa|Gondwe|Nkosi|Mabaso|Mugabe|Karume|Mbeki|Mandela";

	private const string SwahiliMaleNames = "Juma|Omari|Hamisi|Bakari|Baraka|Khamis|Rashid|Said|Salim|Hassan|Ali|Idd|Abdallah|Azizi|Jabari|Jelani|Kamili|Khalfani|Mwinyi|Nassor|Ramadhani|Sadik|Sefu|Simba|Shomari|Tumaini|Abasi|Ayubu|Daudi|Faraji|Hasani|Imani|Jafari|Karim|Lutalo|Nuru|Ombeni|Rafiki|Salum|Yusuf|Ahmed|Mohamed|Ismail|Haroun|Mansur|Mbarak|Suleiman|Zuberi|Hamad|Musa|Rajabu|Bwana|Hafidh|Jelani|Khamisi|Mgeni|Mosi|Nasibu|Riziki|Shabani|Tajiri|Yahya";
	private const string SwahiliFemaleNames = "Amina|Saada|Zawadi|Jamila|Halima|Khadija|Fatuma|Mwanajuma|Mwanahamisi|Mwanaheri|Rehema|Neema|Pendo|Upendo|Subira|Tumaini|Asha|Zulekha|Mariam|Ruqaya|Sauda|Nuru|Farida|Hasina|Latifa|Malkia|Nasra|Ramla|Salma|Saumu|Siti|Aziza|Bahati|Chausiku|Doto|Husna|Imani|Jalia|Kesia|Lulu|Maulida|Nadia|Ombeni|Rahma|Rukia|Sabah|Shukuru|Tunu|Zena|Aisha|Amani|Malkia|Mwanamkuu|Nafisa|Nuruya|Pili|Raha|Saumu|Thamini|Upendo|Zuhura";
	private const string SwahiliSurnames = "Bakari|Baraza|Bwire|Chande|Chege|Darwish|Hassan|Issa|Juma|Kassim|Khamis|Kibwana|Kombo|Liwali|Maalim|Makame|Mashauri|Mbaruk|Mohamed|Mpunga|Msuya|Mtoro|Mwangi|Omari|Ramadhani|Rashid|Said|Salim|Shabani|Sharif|Suleiman|Tumbo|Yahya|Zuberi|Abdalla|Hamisi|Mwinyi|Nassir|Riziki|Hemed|Mgeni|Mshenga|Mushi|Mrema|Mlacha|Mkapa|Mkude|Mnyazi|Ngowi|Nyoni|Sanga|Semboja|Swalehe|Warioba|Kidata|Kilango|Kinabo|Kweka|Lema|Macha|Mhando|Mollel|Moshi|Mtui|Mwakyusa|Mwakitalima|Mwampamba|Mziray|Nyalandu|Sugu|Tibaijuka|Yona|Mushiwa|Abass|Bakar|Chacha|Cheka|Jabir|Lukonge|Maige|Mgeja|Mponda|Mtema|Mwamasika|Mwasaru|Ngasa|Nyerere|Rwegasira|Samatta|Ulimwengu|Zena|Mzirai|Ndaro|Mwakipesile|Kitwana|Marwa|Mwombeki|Mushiwo|Msafiri|Kileo";

	private const string OceanicMaleNames = "Tane|Rangi|Hemi|Wiremu|Rawiri|Matiu|Tamati|Hone|Ari|Aorangi|Kauri|Manaia|Nikau|Tama|Tamatoa|Tavita|Sione|Peni|Tevita|Samiu|Filipe|Aisake|Jone|Pita|Viliame|Inoke|Mikaele|Taito|Uaine|Ropati|Haukea|Keoni|Kaleo|Kainoa|Keola|Lopeti|Lotoala|Maleko|Manase|Nainoa|Noa|Kimo|Makani|Makoa|Nakoa|Kalani|Keahi|Kekoa|Moana|Sefa|Tupou|Vaea|Semisi|Afa|Anitelu|Laki|Likiliki|Siale|Toa|Ula|Vili|Teina";
	private const string OceanicFemaleNames = "Moana|Aroha|Hine|Ripeka|Ana|Mere|Mele|Sina|Litia|Lupe|Talia|Kalolaine|Sela|Tiare|Vaiana|Leilani|Malia|Nalani|Noelani|Mahina|Teuila|Salote|Kiana|Kailani|Anahera|Atarangi|Eseta|Hana|Hinemoa|Kaia|Kiri|Mereana|Moerani|Ngaio|Pare|Rina|Rongomai|Sala|Vika|Fifita|Lavinia|Meleane|Vaine|Fetu|Lani|Miriama|Nina|Pua|Talise|Ula|Ataahua|Ema|Hinerangi|Kahe|Kiriwai|Luisa|Marama|Pania|Rarahu|Sosefina|Tupou";
	private const string OceanicSurnames = "Ngata|Mahuta|Paki|Raukawa|Tamihana|Wiremu|Kepa|Hetaraka|Reihana|Te Aho|Te Kani|Te Rau|Te Whiu|Te Puni|Waaka|Wanoa|Tupuola|Taufua|Sefo|Fepuleai|Ieremia|Malietoa|Fatialofa|Toala|Satele|Taufa|Tupou|Vaea|Tukuafu|Finau|Havea|Moala|Pahulu|Veikoso|Racule|Koroi|Rabuka|Naivalurua|Rokovada|Bainimarama|Qoro|Cakobau|Tikoisuva|Naisarani|Lewaravu|Waqa|Nadalo|Tamanisau|Kalama|Kealoha|Kawika|Kahale|Kahananui|Mahelona|Keliikoa|Kahele|Kekoa|Kainoa|Leota|Misa|Mulipola|Paea|Puni|Taufetee|Toleafoa|Vui|Aiono|Faumuina|Fuimaono|Ioane|Leaana|Mataafa|Peniamina|Pomare|Ropata|Herewini|Te Heuheu|Wiari|Hauiti|Te Rito|Tairua|Koroheke|Anitelea|Faletau|Ikahihifo|Latu|Pule|Sopoaga|Taumoepeau|Tokolahi|Tuifua|Vunipola|Wulf|Yandall|Kalolo|Mailangi|Taito|Talakai|Manu|Tevita|Aupouri";

	private const string AfroAmericanMaleNames = "James|Michael|Darnell|Lamar|Tyrone|Jamal|Malik|Andre|Darius|Marquis|Marcellus|Terrell|DeAndre|Maurice|Keon|Darrell|Cedric|Deshawn|Keshawn|Isaiah|Xavier|Demetrius|Reginald|Terrence|Jerome|Byron|Curtis|Kendall|Tremayne|Devon|Malcolm|Kofi|Darian|Omar|Jalen|Jaylen|Jordan|Anthony|Kareem|Khalil|Lamarcus|Leon|Lionel|Marlon|Myron|Rashad|Raheem|Shawn|Trevon|Tyrell|Vernon|Warren|Willie|Quincy|Cornell|Earl|Franklin|Harold|Marvin|Tariq|Devin|Elijah|Marcus|Roderick|Tristan";
	private const string AfroAmericanFemaleNames = "Aaliyah|Keisha|Latoya|Tamika|Tameka|Shanice|Monique|Dominique|Imani|Jasmine|Brianna|Tierra|Tiana|Kiara|Nia|Aisha|Latasha|Ebony|Candace|Danielle|Gabrielle|Janelle|Kendra|Kenya|Lashonda|Patrice|Tasha|Simone|Tia|Toni|Whitney|Yolanda|Zaria|Amara|Ayana|Bria|Ciara|Denisha|Erika|Felicia|Janay|Kayla|Maya|Octavia|Raven|Sade|Tamara|Tanesha|Unique|Valencia|Zoe|Autumn|Brea|Dionne|Jada|Kamaria|Nakia|Rochelle|Shakira|Trina|Zuri";
	private const string AfroAmericanSurnames = EnglishSurnames;

	private const string AfroCaribbeanMaleNames = "Andre|Dwayne|Kareem|Malik|Jamal|Kemar|Kieron|Marlon|Devon|Darnell|Sheldon|Dwight|Ricardo|Desmond|Fabian|Leroy|Clifton|Orlando|Jermaine|Troy|Winston|Delroy|Oshane|Romario|Tavis|Tafari|Akil|Omari|Mikhail|Jahmal|Zavian|Tyrique|Kwesi|Kevon|Dario|Javon|Rohan|Kirk|Dane|Kadeem|Isaiah|Zane|Akeem|Blaine|Carlton|Damian|Everton|Jevon|Kenroy|Linton|Mekhi|Nigel|Omarion|Rashawn|Sean|Tarique|Uriah|Vaughn|Wayne|Zion";
	private const string AfroCaribbeanFemaleNames = "Althea|Marcia|Patrice|Rochelle|Anika|Shanice|Simone|Tanesha|Alicia|Nadine|Keisha|Janelle|Monique|Safiya|Brianna|Latoya|Tia|Tameka|Sade|Tricia|Naomi|Mikaela|Krystal|Janine|Aaliyah|Chantel|Dione|Kizzy|Shakira|Tamara|Veronica|Natasha|Giselle|Ayana|Kayla|Leandra|Marielle|Nadisha|Riana|Samara|Talia|Zaria|Fabienne|Celeste|Dominique|Kamaria|Kalila|Jada|Kianna|Asha|Amoy|Davina|Imani|Jadine|Khadija|Lashae|Marlene|Nia|Rasheeda|Yvette";
	private const string AfroCaribbeanSurnames = "Brown|Williams|Thomas|Jones|Johnson|Campbell|Clarke|Morgan|Francis|James|Edwards|McKenzie|Reid|Henry|Miller|Grant|Lewis|Smith|Roberts|Graham|Powell|Hinds|Fraser|Scott|Richards|Thompson|Gayle|Samuels|Russell|Ellis|Morrison|Beckford|Bailey|McLean|Sinclair|Rowe|Walters|Lawrence|Walker|Howell|Holder|Best|Boyce|Brathwaite|Forde|Haynes|Prescod|Gill|Browne|Nurse|Baptiste|Joseph|Pierre|St Clair|Charles|Julien|Laurent|Toussaint|Desir|Antoine|Belizaire|Etienne|Celestin|Francois|Garnier|Borde|Petit|Moreau|Noel|Rivera|Rodriguez|Gonzalez|Reyes|Cruz|Santiago|Rosario|Batista|Delgado|Santana|Cabrera|Mendez|Ponce|Acevedo|Figueroa|Ocasio|Rios|Torres|Morales|Vega|Ortiz|Perez|Vazquez|Solis|Cordero|Colon|Medina|Castillo|Valdes|Guerra|Lugo|Marrero";

	private const string IndigenousNorthMaleNames = "Joseph|Daniel|Michael|David|Noah|Ethan|Aaron|Jacob|Joshua|Samuel|Chayton|Dakota|Takoda|Elan|Nodin|Nashoba|Mato|Wapi|Ahanu|Ahote|Hakan|Kitchi|Tokala|Yuma|Bidziil|Adahy|Akecheta|Chaske|Enapay|Hotah|Keme|Koi|Mochni|Ohanzee|Paytah|Sahale|Tasunke|Tayanita|Wahkan|Yiska|Aponivi|Atohi|Chatan|Etu|Honovi|Kohana|Mika|Pawnee|Sani|Shilah|Tala|Tawa|Yoki|Zitkaduta|Leon|Nathan|Isaac|Gabriel|Elias|Connor";
	private const string IndigenousNorthFemaleNames = "Sarah|Mary|Leah|Grace|Elena|Ariana|Aiyana|Winona|Tallulah|Aponi|Chenoa|Kaya|Nizhoni|Tala|Tayen|Dyani|Alaqua|Maka|Wynona|Sakari|Adsila|Ahyoka|Awinita|Catori|Halona|Kiona|Liwanu|Meda|Nahimana|Onida|Pocahontas|Shikoba|Takoda|Talulah|Wichahpi|Yoki|Zitkala|Kimama|Luyu|Nina|Nova|Tiva|Waniya|Aleshanee|Anaba|Enola|Istas|Kachina|Mina|Nita|Orenda|Pavati|Salali|Tahnee|Tallis|Winema|Yazhi|Zaltana|Avianna|Leila";
	private const string IndigenousNorthSurnames = EnglishSurnames;

	private const string IndigenousLatinMaleNames = "Juan|Jose|Miguel|Mateo|Diego|Luis|Rafael|Carlos|Andres|Sebastian|Tupaq|Amaru|Inti|Manco|Atahualpa|Huayna|Pachacuti|Titu|Yupanqui|Rumi|Mayu|Sumaq|Illari|Kuntur|Nayra|Qori|Aukan|Cusi|Anku|Chaska|Sayri|Yawar|Tariq|Izel|Tenoch|Cuauhtemoc|Itzcotl|Moctezuma|Nezahual|Xolotl|Balam|Itzamna|Nahuel|Tlaloc|Yupan|Auki|Kusi|Kallpa|Santos|Rene|Victor|Edgar|Felipe|Julio|Marco|Nestor|Pablo|Tomas|Valentin|Wilmer";
	private const string IndigenousLatinFemaleNames = "Maria|Ana|Lucia|Rosa|Elena|Sofia|Isabel|Juana|Teresa|Carmen|Killa|Nina|Mayu|Sumaq|Illari|Nayra|Qori|Pacha|Rumi|Chaska|Kusi|Sayri|Yma|Micaela|Dominga|Tomasa|Roxana|Alicia|Beatriz|Celia|Dolores|Felipa|Hortensia|Luz|Margarita|Natividad|Paulina|Reina|Rosalia|Valeria|Ximena|Yaritza|Citlali|Itzel|Nayeli|Xochitl|Yaretzi|Marisol|Belen|Esperanza|Graciela|Juliana|Leonor|Micaela|Olinda|Pilar|Ruth|Silvia|Teodora|Veronica";
	private const string IndigenousLatinSurnames = "Quispe|Huaman|Mamani|Choque|Condori|Flores|Arias|Cruz|Chura|Calla|Cutipa|Llanque|Mendoza|Colque|Copa|Guaman|Maita|Nina|Puma|Suni|Ticona|Yucra|Zeballos|Apaza|Canaza|Carhuancho|Huanca|Quisbert|Cahuana|Mendoza|Pacco|Sisa|Mamani Quispe|Huanca Quispe|Quispe Mamani|Chambi|Quillca|Sullca|Vilca|Yanarico|Aguayo|Bautista|Ccallo|Choquecota|Huanaco|Illanes|Lipa|Mollo|Paredes|Paucar|Rojas|Saire|Ttito|Ucharico|Vargas|Yupanqui|Zevallos|Canchari|Coaquira|Huallpa|Janampa|Llanos|Luque|Mamani Choque|Mamani Condori|Pallca|Paucar|Quenta|Salluca|Sotelo|Tito|Turpo|Vasquez|Vilcapoma|Zarate|Aguilar|Cruz Mamani|Dela Cruz|Garcia|Gonzales|Hernandez|Lopez|Martinez|Perez|Ramirez|Reyes|Rivera|Rodriguez|Sanchez|Silva|Torres|Valdez|Velasquez|Zuniga|Acurio|Ccallata|Huayta|Inga|Naccha|Quichua|Sarapura|Tenorio";

	private const string JapaneseMaleNames = "Haruto|Yuto|Sota|Yuki|Takumi|Ren|Hiroto|Yuma|Kenta|Daiki|Hayato|Kazuki|Kaito|Ryota|Shota|Tsubasa|Naoki|Masato|Taro|Jiro|Kenji|Shinji|Atsushi|Akira|Takeshi|Toru|Yusuke|Jun|Koji|Makoto|Noboru|Riku|Ryusei|Shun|Shohei|Taichi|Daisuke|Eiji|Fumio|Goro|Hajime|Itsuki|Kazuhiro|Kiyoshi|Masaru|Nobuhiro|Osamu|Saburo|Tadashi|Yuji|Yuichi|Yoshio|Yoshinori|Haruki|Issei|Keisuke|Mamoru|Shigeru|Tomoya|Yoshiro|Zen";
	private const string JapaneseFemaleNames = "Yui|Aoi|Sakura|Hina|Rin|Yuna|Mei|Akari|Nanami|Haruka|Ayaka|Mika|Natsumi|Misaki|Kaori|Yoko|Keiko|Naoko|Chie|Emi|Erika|Fumika|Hana|Hitomi|Izumi|Kana|Kanako|Kumiko|Madoka|Mai|Mami|Mariko|Mayu|Michiko|Midori|Mina|Mio|Miyu|Nana|Noriko|Reina|Rika|Rina|Sachiko|Satomi|Sayaka|Shiori|Tomoko|Yayoi|Yukari|Yukiko|Airi|Asami|Chisato|Eri|Honoka|Kiyomi|Nozomi|Saki|Yuriko|Yuzuki";
	private const string JapaneseSurnames = "Sato|Suzuki|Takahashi|Tanaka|Watanabe|Ito|Yamamoto|Nakamura|Kobayashi|Kato|Yoshida|Yamada|Sasaki|Yamaguchi|Matsumoto|Inoue|Kimura|Hayashi|Shimizu|Yamazaki|Mori|Abe|Ikeda|Hashimoto|Ishikawa|Nakajima|Maeda|Fujita|Ogawa|Goto|Okada|Hasegawa|Murakami|Kondo|Ishii|Saito|Sakamoto|Endo|Aoki|Fujii|Nishimura|Miura|Takeuchi|Kaneko|Nakagawa|Harada|Ono|Tamura|Fukuda|Nakano|Ueda|Matsuda|Shibata|Sakurai|Kudo|Yokoyama|Miyazaki|Uchida|Fujiwara|Ando|Maruyama|Sugimoto|Naito|Shimada|Kojima|Takeda|Murata|Ogata|Hirano|Otsuka|Kikuchi|Kubo|Matsui|Iwasaki|Honda|Araki|Kawai|Noguchi|Nomura|Kinoshita|Hirai|Kurata|Okamoto|Matsunaga|Horiuchi|Furukawa|Katayama|Tsukamoto|Mochizuki|Hattori|Ueno|Morita|Toda|Hotta|Nagata|Kamei|Arai|Kitamura|Fujimoto|Matsubara";

	private const string KoreanMaleNames = "Min-jun|Seo-jun|Do-yun|Ji-hoon|Hyun-woo|Jun-seo|Min-jae|Seung-hyun|Joon-ho|Dong-hyun|Tae-hyun|Jae-hyun|Sung-ho|Hyeon-seok|Kyung-soo|Young-ho|Jin-woo|Ji-sung|Sang-hoon|Won-ho|Seok-jin|Dae-hyun|Yong-ho|Byung-ho|Chang-min|Woo-jin|Hyun-seung|Joon-young|Ki-tae|Hwan|Geon-woo|Jung-ho|Min-kyu|Soo-hyun|Tae-min|Jin-ho|Jae-min|Yoon-ho|Si-woo|Do-hyun|Eun-ho|Gyu-min|Hyeon-joon|Jae-won|Min-ho|Sung-min|Tae-woo|Woo-seok|Ye-jun|Young-min|Jae-ho|Kang-min|Nam-joon|Seung-ho|Tae-yang";
	private const string KoreanFemaleNames = "Seo-yeon|Ji-woo|Ha-yoon|Min-seo|Soo-jin|Eun-ji|Ji-yoon|Hye-jin|Ye-jin|Seo-hyun|Na-young|Min-ji|Yoon-seo|Ji-hye|Hye-won|Bo-kyung|Eun-seo|Da-eun|Mi-young|Sun-hee|Young-sook|Ji-eun|So-young|Hye-young|Soo-yeon|Ji-min|Seul-gi|Yuri|Hae-in|Yoon-ah|Ji-ah|Eun-young|Mina|Ara|Hana|Bora|Chae-won|Da-hee|Ga-young|Hyo-jin|In-young|Joo-eun|Kyung-hee|Min-kyung|Nari|Seo-yoon|Soo-ah|Ye-eun|Yuna|Young-hee|Ji-an|Seo-ah|Yu-na|Yun-hee|Ha-eun";
	private const string KoreanSurnames = "Kim|Lee|Park|Choi|Jung|Kang|Cho|Yoon|Jang|Lim|Han|Oh|Seo|Shin|Kwon|Hwang|Ahn|Song|Ryu|Jeon|Hong|Ko|Moon|Yang|Baek|Heo|Nam|Sim|No|Bae|Min|Ha|Ju|Jin|Byun|Son|Yu|Won|Cheon|Bang";

	private const string CentralAsianMaleNames = "Batu|Temur|Altan|Jochi|Bayar|Batzorig|Erdene|Ganbaatar|Munkhbayar|Naranbaatar|Sukhbaatar|Tseren|Tuvshin|Zorig|Bilguun|Chingis|Enkhbat|Gantulga|Jargal|Nasanjargal|Odgerel|Baldan|Dorj|Ganzorig|Mendsaikhan|Otgonbayar|Sainbayar|Tumen|Tenzin|Dorje|Lobsang|Ngawang|Jigme|Sonam|Thinley|Karma|Pasang|Norbu|Gyatso|Kelsang|Ananda|Batbold|Batsaikhan|Ganbold|Nergui|Ochirbat|Purev|Sainkhuu|Tsogt|Yesui|Zamling|Ariunbold|Bilegt|Chuluun|Lhagva";
	private const string CentralAsianFemaleNames = "Altantsetseg|Anu|Bolormaa|Buyan|Delgermaa|Enkhjargal|Munkhtuya|Narantuya|Odmaa|Oyun|Saikhan|Saruul|Tsetseg|Tsolmon|Ujin|Vanchig|Yanjmaa|Zolzaya|Ariunaa|Battsetseg|Gerelmaa|Khulan|Munkhzul|Naraa|Narangerel|Oyuntsetseg|Solongo|Tuul|Undral|Urantsetseg|Tungalag|Tsendmaa|Pagma|Pema|Dolkar|Yangchen|Lhamo|Tsering|Deki|Sonam|Kunzang|Jampa|Nyima|Kelsang|Choden|Tenzin|Yeshi|Drolma|Tashi|Wangmo|Altansetseg|Erdenetuya|Munkhzaya|Namjil|Oyuka";
	private const string CentralAsianSurnames = "Borjigin|Besud|Suldus|Jadaran|Khatagin|Khongirad|Naiman|Oirat|Barulas|Kereit|Merkit|Torguud|Dorvod|Zakhchin|Buryat|Khalka|Bat|Bold|Erdene|Gan|Munkh|Tsogt|Baatar|Temur|Altan|Bayar|Sukh|Dorj|Lkhagva|Purev|Norbu|Gyatso|Lobsang|Tsering|Namgyal|Paljor|Samdup|Sherpa|Tsarong|Lhalu|Phala|Shatra|Yuthok|Surkhang|Doring|Nangso|Jamyang|Kunga|Ngapo|Trinley|Baldan|Ganzorig|Jargalsaikhan|Mendsaikhan|Naran|Otgon|Purevdorj|Sainbayar|Tserendorj|Zorigt";

	private const string SoutheastAsianMaleNames = "Minh|Huy|Duc|Tuan|Khoa|An|Bao|Thanh|Long|Vinh|Dat|Hieu|Son|Nam|Kiet|Tri|Quan|Phuc|Khoi|Tien|Surya|Agus|Budi|Rizky|Adi|Hendra|Joko|Dwi|Rahmat|Fajar|Arif|Bagus|Raden|Iskandar|Sufian|Hafiz|Faizal|Rashid|Aiman|Zulkifli|Ananda|Preecha|Anan|Somchai|Sakda|Nattapong|Chaiwat|Kittisak|Narong|Sokha|Dara|Vannak|Piseth|Rithy|Sokun|Kosal|Savuth|Kham|Phonesavanh|Bounmy";
	private const string SoutheastAsianFemaleNames = "Linh|Trang|Huong|Thao|Mai|Lan|Ngoc|Anh|Vy|Nhi|Phuong|Hanh|Truc|Diep|Quynh|Suda|Nok|Supaporn|Somying|Malee|Sunee|Chariya|Kanya|Pimchanok|Araya|Nanthida|Ratana|Dewi|Ayu|Kartika|Fitri|Sari|Lestari|Indah|Melati|Putri|Intan|Siti|Nurul|Aisyah|Farah|Salmah|Zaleha|Sokha|Chanthou|Sophea|Malis|Pisey|Vicheka|Davy|Lina|Mony|Pailin|Bounthavy|Khamla|Manee|Dao|Hoa|Kim|Nisa";
	private const string SoutheastAsianSurnames = "Nguyen|Tran|Le|Pham|Hoang|Huynh|Vu|Phan|Bui|Dang|Do|Ngo|Duong|Ly|Chau|Cao|Lam|Truong|Thai|Mai|Vuong|Trinh|Dinh|Dao|Vo|Ong|Lim|Tan|Goh|Teo|Koh|Low|Sim|Tng|Chua|Quek|Cheong|Chiang|Liew|Santoso|Wijaya|Saputra|Hidayat|Gunawan|Kurniawan|Prakoso|Setiawan|Hartono|Siregar|Nasution|Halim|Abdullah|Ahmad|Hassan|Ismail|Yusuf|Latif|Ibrahim|Rahman|Nor|Zulkifli|Azhar|Mahathir|Ananda|Boonmee|Chaiyawat|Rattanapong|Srisai|Sukhum|Wongsa|Phanuphong|Chan|Chen|Chong|Heng|Khiev|Ros|Sok|Vann|Yim|Khamphou|Phommasane|Sisoulath|Souvannasane|Aguinaldo|Bautista|Cruz|Dela Cruz|Garcia|Mendoza|Reyes|Santos|Velasco|Wongsawat|Tancharoen|Mahaputra|Suphachai|Ratanakorn|Manoban|Sihombing";

	private const string AboriginalAustralianMaleNames = "Jarrah|Jandamarra|Yarran|Binarri|Darri|Miro|Bodhi|Jayden|Noah|Liam|Isaac|Ethan|Mason|Kai|Jacob|Joshua|Tyson|Corey|Dylan|Nathan|Coen|Bailey|Callum|Jye|Riley|Taj|Talon|Brodie|Blake|Cody|Jaylen|Kye|Kyson|Marley|Mitchell|Reece|Shane|Troy|Tyler|Warren|Zane|Ari|Ben|Clinton|Dean|Elijah|Flynn|Harvey|Jett|Kieran|Levi|Micah|Rhys|Sam|Tristan|Vance|Wade|Yani|Zac";
	private const string AboriginalAustralianFemaleNames = "Kirra|Kylie|Lowanna|Merri|Alinta|Keira|Aaliyah|Ava|Charlotte|Chloe|Ella|Emily|Evie|Grace|Hannah|Isla|Jade|Jessica|Kayla|Leila|Lily|Maya|Mia|Olivia|Ruby|Sienna|Skye|Sophie|Tahlia|Tiana|Yindi|Zali|Amber|Brooke|Caitlin|Dakota|Ella-May|Georgia|Indi|Jasmine|Kiara|Layla|Mackenzie|Monique|Nikita|Paige|Rhiannon|Sasha|Sharnie|Tara|Taylah|Teagan|Tia|Willow|Yasmin|Zara|Ainsley|Danika|Elena|Marli";
	private const string AboriginalAustralianSurnames = "Ah Chee|Bamblett|Barunga|Bostock|Briggs|Bunney|Burns|Clarke|Coleman|Corowa|Costello|Doolan|Eades|Ella|Ellis|Foley|Graham|Harrison|Hart|Hill|Hobson|Miller|Mundine|Murray|Naden|Nelson|Nolan|Phillips|Prior|Riley|Robertson|Saunders|Shead|Smith|Stanley|Sykes|Walker|Walley|Wandin|Weatherall|Williams|Wilson|Wunungmurra|Yunupingu|Abbott|Anderson|Bailey|Baker|Bell|Bennett|Black|Brown|Campbell|Carter|Cooper|Davis|Edwards|Evans|Fisher|Fletcher|Gibson|Green|Hall|Harris|Jackson|Johnson|Jones|Kelly|King|Lawson|Lewis|Long|Martin|Mitchell|Moore|Morgan|Morris|Parker|Perry|Price|Reynolds|Roberts|Robinson|Ross|Scott|Shaw|Taylor|Thomas|Thompson|Turner|Walsh|Ward|Webb|White|Woods|Young|Bonney|Munkara|Pearson|Dale";

	private static IReadOnlyList<(string Name, int Weight)> SplitWeightedEntries(string values)
	{
		return values
			.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
			.Select(x => (Name: x, Weight: 100))
			.ToList();
	}

	private void SeedModernEthnicityProfiles()
	{
		foreach (ModernEthnicityProfileSeed seed in ModernEthnicityProfileSeeds)
		{
			NameCulture culture = seed.NameOrder == ModernNameOrder.FamilyGiven
				? EnsureModernFamilyGivenCulture(seed.CultureName)
				: EnsureModernGivenFamilyCulture(seed.CultureName);

			SeedGivenFamilyProfile(
				$"{seed.CultureName} Male",
				Gender.Male,
				culture,
				SplitWeightedEntries(seed.MaleNames),
				SplitWeightedEntries(seed.Surnames));
			SeedGivenFamilyProfile(
				$"{seed.CultureName} Female",
				Gender.Female,
				culture,
				SplitWeightedEntries(seed.FemaleNames),
				SplitWeightedEntries(seed.Surnames));
		}
	}

	private NameCulture EnsureModernFamilyGivenCulture(string name)
	{
		return AddNameCulture(name, @"^(?<surname>[\w'-]+)\s+(?<birthname>[\w'-]+)$",
			new[]
			{
				("Family Name", 1, 1, "Your family name identifies your wider family or clan and comes first.", NameUsage.Surname),
				("Given Name", 1, 1, "Your given name follows your family name and is the personal name chosen for you.", NameUsage.BirthName)
			},
			new[]
			{
				(NameStyle.GivenOnly, "{0}", new[] { NameUsage.BirthName }),
				(NameStyle.SimpleFull, "{0} {1}", new[] { NameUsage.Surname, NameUsage.BirthName }),
				(NameStyle.FullName, "{0} {1}", new[] { NameUsage.Surname, NameUsage.BirthName }),
				(NameStyle.Affectionate, "{0}", new[] { NameUsage.BirthName }),
				(NameStyle.SurnameOnly, "{0}", new[] { NameUsage.Surname }),
				(NameStyle.FullWithNickname, "{0} {1}", new[] { NameUsage.Surname, NameUsage.BirthName })
			});
	}
}
