#nullable enable

namespace DatabaseSeeder.Seeders;

public partial class CultureSeeder
{
	private void SeedRenaissanceWorldExpansionHeritageExpansion()
	{
		SeedHistoricalEthnicityVariants(RenaissanceWorldEthnicityVariants);
	}

	private static readonly HistoricalEthnicityVariantSeed[] RenaissanceWorldEthnicityVariants =
	[
		new("Renaissance Eastern Armenian", "Late Medieval Armenian", "Renaissance Armenian", "Caucasian", "Eastern Armenian Highlands",
			"Eastern Armenians belong to the highland towns, villages, monasteries and merchant networks east of the Euphrates."),
		new("Renaissance Cilician Armenian", "Late Medieval Armenian", "Renaissance Armenian", "Caucasian", "Cilicia and Mediterranean Diaspora",
			"Cilician Armenians belong to southern and diasporic communities shaped by the former Cilician kingdom and Mediterranean trade."),

		new("Renaissance Kartlian Georgian", "Late Medieval Georgian", "Renaissance Georgian", "Caucasian", "Kartli",
			"Kartlians belong to the eastern Georgian heartland around Tbilisi and the central Kura valley."),
		new("Renaissance Imeretian Georgian", "Late Medieval Georgian", "Renaissance Georgian", "Caucasian", "Imereti",
			"Imeretians belong to the western Georgian kingdom and its river valleys, towns and noble houses."),
		new("Renaissance Kakhetian Georgian", "Late Medieval Georgian", "Renaissance Georgian", "Caucasian", "Kakheti",
			"Kakhetians belong to the eastern Georgian wine-growing valleys and frontier lordships."),
		new("Renaissance Mingrelian", "Late Medieval Georgian", "Renaissance Georgian", "Caucasian", "Samegrelo",
			"Mingrelians belong to the western Caucasian communities of Samegrelo, with their own Kartvelian speech and princely traditions."),

		new("Renaissance Kurmanji Kurd", "Late Medieval Kurd", "Renaissance Kurdish", "Iranian", "Kurmanji Principalities",
			"Kurmanji Kurds belong to northern Kurdish-speaking tribal, village and emirate communities."),
		new("Renaissance Gorani Kurd", "Late Medieval Kurd", "Renaissance Kurdish", "Iranian", "Gorani Principalities",
			"Gorani communities belong to the central Zagros principalities and learned traditions associated with Gorani speech."),

		new("Renaissance Egyptian Arab", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Middle Eastern", "Mamluk Egypt",
			"Egyptian Arabs belong to the Arabic-speaking towns, villages and tribal communities of the Nile valley and delta."),
		new("Renaissance Syrian Arab", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Middle Eastern", "Mamluk Syria",
			"Syrian Arabs belong to the cities, villages and pastoral communities of the Mamluk Levant."),
		new("Renaissance Egyptian Copt", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Egyptian", "Coptic Egyptian",
			"Copts belong to Egypt's indigenous Christian communities, maintaining strong village, clerical and scribal networks."),
		new("Renaissance Circassian Mamluk", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Caucasian", "Burji Military Household",
			"Circassian Mamluks belong to the military households that dominated the late Mamluk ruling elite after the Burji transition."),
		new("Renaissance Turkic Mamluk", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Central Asian", "Mamluk Military Household",
			"Turkic Mamluks belong to military households descended from or recruited through the Kipchak and wider Turkic steppe world."),
		new("Renaissance Levantine Bedouin", "Mamluk-Era Egyptian Arab", "Renaissance Mamluk Arabic", "Middle Eastern", "Levantine Bedouin",
			"Levantine Bedouins belong to mobile and settled Arab tribal confederations across Syria, Palestine and the desert margins."),

		new("Renaissance Chagatai Turk", "Late Medieval Chagatai Turk", "Renaissance Timurid Persianate", "Central Asian", "Chagatai Turk",
			"Chagatai Turks belong to Turkic military, pastoral and settled communities within the Timurid realms."),
		new("Renaissance Tajik Persian", "Late Medieval Chagatai Turk", "Renaissance Timurid Persianate", "Iranian", "Tajik Persian",
			"Tajik Persians belong to Persian-speaking urban, agricultural, scholarly and administrative communities of Central Asia."),
		new("Renaissance Khorasani Persian", "Late Medieval Chagatai Turk", "Renaissance Timurid Persianate", "Iranian", "Khorasan",
			"Khorasani Persians belong to the cities, oases and estates of Herat, Mashhad and the wider northeastern Iranian world."),
		new("Renaissance Timurid Mongol", "Late Medieval Chagatai Turk", "Renaissance Timurid Persianate", "Central Asian", "Timurid Mongol Lineages",
			"Timurid Mongols belong to clans retaining Mongol lineage identities within an increasingly Turkic and Persianate political world."),

		new("Renaissance Hindustani", "Late Medieval Afghan", "Renaissance Delhi Sultanate", "South Asian", "Hindustan",
			"Hindustanis belong to the Indo-Aryan-speaking urban and rural communities of the Delhi Sultanate's north Indian heartland."),
		new("Renaissance Afghan Pashtun", "Late Medieval Afghan", "Renaissance Delhi Sultanate", "South Asian", "Afghan Pashtun",
			"Afghan Pashtuns belong to highland and frontier lineages increasingly prominent in north Indian military and political service."),
		new("Renaissance Punjabi", "Late Medieval Afghan", "Renaissance Delhi Sultanate", "South Asian", "Punjab",
			"Punjabis belong to the agrarian, mercantile and military communities of the five-river country."),
		new("Renaissance Delhi Turk", "Late Medieval Afghan", "Renaissance Delhi Sultanate", "Central Asian", "Sultanate Military Households",
			"Delhi Turks belong to Turkic-descended military and court households established in northern India."),
		new("Renaissance Indo-Persian", "Late Medieval Afghan", "Renaissance Delhi Sultanate", "Iranian and South Asian", "Persianate Diaspora",
			"Indo-Persians belong to migrant and locally rooted families serving the sultanate through scholarship, administration and commerce."),

		new("Renaissance Mewar Rajput", "Late Medieval Rajput", "Renaissance Rajput", "South Asian", "Sisodia of Mewar",
			"Mewar Rajputs belong to Sisodia-led communities of the Aravalli country and the kingdom of Mewar."),
		new("Renaissance Marwar Rajput", "Late Medieval Rajput", "Renaissance Rajput", "South Asian", "Rathore of Marwar",
			"Marwar Rajputs belong to Rathore-led communities of the western Rajasthan desert and the kingdom of Marwar."),
		new("Renaissance Amber Rajput", "Late Medieval Rajput", "Renaissance Rajput", "South Asian", "Kachwaha of Amber",
			"Amber Rajputs belong to Kachwaha-led communities around Dhundhar and the fortress of Amber."),

		new("Renaissance Eastern Bengali", "Late Medieval Bengali", "Renaissance Bengali", "South Asian", "Eastern Bengal",
			"Eastern Bengalis belong to the deltaic communities east of the main Ganges channels, shaped by river settlement and frontier cultivation."),
		new("Renaissance Western Bengali", "Late Medieval Bengali", "Renaissance Bengali", "South Asian", "Western Bengal",
			"Western Bengalis belong to the older towns, temple lands and agrarian districts of western Bengal."),
		new("Renaissance Sylheti", "Late Medieval Bengali", "Renaissance Bengali", "South Asian", "Sylhet",
			"Sylhetis belong to the northeastern valley communities around Sylhet and its expanding agrarian frontier."),

		new("Renaissance Kannadiga", "Late Medieval Kannadiga", "Renaissance Vijayanagara", "South Asian", "Kannada Country",
			"Kannadigas belong to the Kannada-speaking heartlands, towns and military estates of the Vijayanagara sphere."),
		new("Renaissance Telugu", "Late Medieval Kannadiga", "Renaissance Vijayanagara", "South Asian", "Telugu Country",
			"Telugus belong to the eastern Deccan communities prominent in Vijayanagara warfare, administration and literature."),
		new("Renaissance Tamil", "Late Medieval Kannadiga", "Renaissance Vijayanagara", "South Asian", "Tamil Country",
			"Tamils belong to the southern temple, agrarian and mercantile communities within and alongside the empire."),
		new("Renaissance Tuluva", "Late Medieval Kannadiga", "Renaissance Vijayanagara", "South Asian", "Tulu Coast",
			"Tuluvas belong to the southwestern coastal communities whose military and merchant networks reached deep into the empire."),

		new("Renaissance Northern Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "North China",
			"Northern Han communities belong to the capital regions, Yellow River plains and northern military-agricultural settlements."),
		new("Renaissance Jiangnan Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Jiangnan",
			"Jiangnan Han communities belong to the densely urbanised and commercially rich lower Yangtze region."),
		new("Renaissance Wu-Speaking Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Wu Region",
			"Wu-speaking Han communities belong to the lower Yangtze and Taihu cities and countryside."),
		new("Renaissance Gan-Speaking Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Jiangxi",
			"Gan-speaking Han communities belong principally to Jiangxi and neighbouring inland river valleys."),
		new("Renaissance Hakka Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Hakka Communities",
			"Hakka communities belong to mobile Han lineages established across the uplands of Jiangxi, Fujian and Guangdong."),
		new("Renaissance Yue-Speaking Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Lingnan Yue Region",
			"Yue-speaking Han communities belong to the Pearl River basin and the wider Lingnan south."),
		new("Renaissance Southern Min Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Southern Fujian",
			"Southern Min communities belong to the ports, valleys and maritime networks of southern Fujian."),
		new("Renaissance Eastern Min Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Eastern Fujian",
			"Eastern Min communities belong to the lower Min River, Fuzhou region and adjacent coast."),
		new("Renaissance Northern Min Han", "Ming Han Chinese", "Renaissance Ming Chinese", "East Asian", "Northern Fujian",
			"Northern Min communities belong to the mountain basins and river corridors of northern Fujian."),

		new("Renaissance Gyeonggi Korean", "Joseon Korean", "Renaissance Joseon Korean", "East Asian", "Gyeonggi",
			"Gyeonggi Koreans belong to communities around the Joseon capital and its central administrative region."),
		new("Renaissance Gyeongsang Korean", "Joseon Korean", "Renaissance Joseon Korean", "East Asian", "Gyeongsang",
			"Gyeongsang Koreans belong to southeastern communities shaped by former Silla lands, ports and provincial elites."),
		new("Renaissance Jeolla Korean", "Joseon Korean", "Renaissance Joseon Korean", "East Asian", "Jeolla",
			"Jeolla Koreans belong to the southwestern rice-growing plains, towns and coastal communities."),
		new("Renaissance Hamgyong Korean", "Joseon Korean", "Renaissance Joseon Korean", "East Asian", "Hamgyong Frontier",
			"Hamgyong Koreans belong to northeastern frontier communities shaped by resettlement, defence and exchange with Jurchen neighbours."),
		new("Renaissance Jeju Islander", "Joseon Korean", "Renaissance Joseon Korean", "East Asian", "Jeju",
			"Jeju islanders belong to a distinctive maritime and pastoral community with its own regional speech and former kingdom traditions."),

		new("Renaissance Kinai Japanese", "Muromachi Japanese", "Renaissance Muromachi Japanese", "East Asian", "Kinai",
			"Kinai Japanese belong to the capital, temple and commercial communities around Kyoto, Nara and the central provinces."),
		new("Renaissance Kanto Japanese", "Muromachi Japanese", "Renaissance Muromachi Japanese", "East Asian", "Kanto",
			"Kanto Japanese belong to eastern warrior houses, towns and villages shaped by Kamakura and later regional powers."),
		new("Renaissance Tohoku Japanese", "Muromachi Japanese", "Renaissance Muromachi Japanese", "East Asian", "Tohoku",
			"Tohoku Japanese belong to northern Honshu communities formed through frontier settlement and exchange."),
		new("Renaissance Kyushu Japanese", "Muromachi Japanese", "Renaissance Muromachi Japanese", "East Asian", "Kyushu",
			"Kyushu Japanese belong to southern island communities closely connected to continental and maritime trade."),

		new("Renaissance U-Tsang Tibetan", "Late Medieval Tibetan", "Renaissance Tibetan", "Tibeto-Burman", "U-Tsang",
			"U-Tsang Tibetans belong to the central plateau communities around Lhasa, Shigatse, monasteries and landed estates."),
		new("Renaissance Khampa", "Late Medieval Tibetan", "Renaissance Tibetan", "Tibeto-Burman", "Kham",
			"Khampas belong to the eastern plateau's highland valleys, pastoral districts and locally powerful lineages."),
		new("Renaissance Amdo Tibetan", "Late Medieval Tibetan", "Renaissance Tibetan", "Tibeto-Burman", "Amdo",
			"Amdo Tibetans belong to northeastern plateau communities tied to monasteries, pastoralism and frontier exchange."),

		new("Renaissance Red River Kinh", "Late Medieval Viet", "Renaissance Dai Viet", "Southeast Asian", "Red River Delta",
			"Red River Kinh belong to the densely settled villages, towns and court districts of the Dai Viet heartland."),
		new("Renaissance Thanh-Nghe Kinh", "Late Medieval Viet", "Renaissance Dai Viet", "Southeast Asian", "Thanh-Nghe",
			"Thanh-Nghe Kinh belong to the south-central Vietnamese provinces noted for military households and frontier settlement."),

		new("Renaissance Ayutthaya Central Tai", "Late Medieval Tai", "Renaissance Ayutthaya Thai", "Southeast Asian", "Chao Phraya Plain",
			"Central Tai belong to the riverine towns, rice villages and courtly networks of the Ayutthaya heartland."),
		new("Renaissance Northern Tai", "Late Medieval Tai", "Renaissance Ayutthaya Thai", "Southeast Asian", "Northern Tai Principalities",
			"Northern Tai belong to the upland and valley principalities north of the Chao Phraya basin."),
		new("Renaissance Lao Tai", "Late Medieval Tai", "Renaissance Ayutthaya Thai", "Southeast Asian", "Lao Mekong",
			"Lao Tai belong to Mekong valley communities linked to Lan Xang and neighbouring Tai polities."),

		new("Renaissance Central Javanese", "Late Majapahit Javanese", "Renaissance Majapahit Javanese", "Southeast Asian", "Central Java",
			"Central Javanese belong to the agrarian, court and temple communities of Java's central interior."),
		new("Renaissance Eastern Javanese", "Late Majapahit Javanese", "Renaissance Majapahit Javanese", "Southeast Asian", "Eastern Java",
			"Eastern Javanese belong to the Majapahit heartland, Brantas basin and ports of eastern Java."),
		new("Renaissance Sundanese", "Late Majapahit Javanese", "Renaissance Majapahit Javanese", "Southeast Asian", "Sunda",
			"Sundanese belong to the western Javanese highlands and the independent Sunda realm."),
		new("Renaissance Madurese", "Late Majapahit Javanese", "Renaissance Majapahit Javanese", "Southeast Asian", "Madura",
			"Madurese belong to the island and coastal communities of Madura, closely tied to eastern Java."),

		new("Renaissance Malaccan Malay", "Late Medieval Malay", "Renaissance Malay", "Southeast Asian", "Malacca",
			"Malaccan Malays belong to the entrepot, court and coastal communities of the Malacca Sultanate."),
		new("Renaissance Sumatran Malay", "Late Medieval Malay", "Renaissance Malay", "Southeast Asian", "Eastern Sumatra",
			"Sumatran Malays belong to the riverine and coastal communities of eastern Sumatra."),
		new("Renaissance Bornean Malay", "Late Medieval Malay", "Renaissance Malay", "Southeast Asian", "Coastal Borneo",
			"Bornean Malays belong to coastal sultanates and trading settlements around Borneo."),
		new("Renaissance Acehnese", "Late Medieval Malay", "Renaissance Malay", "Southeast Asian", "Aceh",
			"Acehnese belong to northern Sumatra's port, farming and emerging sultanate communities."),

		new("Renaissance Amhara", "Late Medieval Amhara", "Renaissance Ethiopian Highland", "Horn of Africa", "Amhara Highlands",
			"Amhara belong to the central highland communities closely associated with Solomonic court, church and landed institutions."),
		new("Renaissance Tigrayan", "Late Medieval Amhara", "Renaissance Ethiopian Highland", "Horn of Africa", "Tigray",
			"Tigrayans belong to the northern highland communities preserving strong Aksumite, monastic and regional traditions."),
		new("Renaissance Agaw", "Late Medieval Amhara", "Renaissance Ethiopian Highland", "Horn of Africa", "Agaw Highlands",
			"Agaw peoples belong to Cushitic-speaking highland communities incorporated into and neighbouring the Solomonic realm."),

		new("Renaissance Darod Somali", "Late Medieval Somali", "Renaissance Somali", "Horn of Africa", "Darod Clan Families",
			"Darod Somalis belong to wide-ranging pastoral, coastal and sultanate communities across the Horn."),
		new("Renaissance Hawiye Somali", "Late Medieval Somali", "Renaissance Somali", "Horn of Africa", "Hawiye Clan Families",
			"Hawiye Somalis belong to pastoral and riverine communities of central and southern Somalia."),
		new("Renaissance Isaaq Somali", "Late Medieval Somali", "Renaissance Somali", "Horn of Africa", "Isaaq Clan Families",
			"Isaaq Somalis belong to northern pastoral and trading communities connected to Red Sea ports."),
		new("Renaissance Dir Somali", "Late Medieval Somali", "Renaissance Somali", "Horn of Africa", "Dir Clan Families",
			"Dir Somalis belong to northern and coastal clan communities spanning the Gulf of Aden and adjacent interior."),
		new("Renaissance Digil-Mirifle Somali", "Late Medieval Somali", "Renaissance Somali", "Horn of Africa", "Digil-Mirifle Communities",
			"Digil-Mirifle communities belong to the inter-riverine south, combining agro-pastoral lifeways with distinctive Maay speech."),

		new("Renaissance Lamu Swahili", "Late Medieval Swahili", "Renaissance Swahili", "East African", "Lamu Archipelago",
			"Lamu Swahili belong to the northern coastal towns and island communities of Lamu and Pate."),
		new("Renaissance Mombasa Swahili", "Late Medieval Swahili", "Renaissance Swahili", "East African", "Mombasa",
			"Mombasa Swahili belong to the port city and its mainland trading hinterland."),
		new("Renaissance Zanzibar Swahili", "Late Medieval Swahili", "Renaissance Swahili", "East African", "Zanzibar and Pemba",
			"Zanzibar Swahili belong to the island farming, fishing and mercantile communities of Zanzibar and Pemba."),
		new("Renaissance Kilwa Swahili", "Late Medieval Swahili", "Renaissance Swahili", "East African", "Kilwa Coast",
			"Kilwa Swahili belong to the southern coastal city-state network enriched by Indian Ocean gold trade."),

		new("Renaissance Mandinka", "Late Medieval Manding", "Renaissance Mande Sahelian", "West African", "Mandinka Communities",
			"Mandinka belong to Mande-speaking farming, trading and ruling communities across the western Sahel."),
		new("Renaissance Soninke", "Late Medieval Manding", "Renaissance Mande Sahelian", "West African", "Soninke Communities",
			"Soninke belong to old Sahelian merchant and farming communities linked to Ghana, Mali and trans-Saharan trade."),
		new("Renaissance Bambara", "Late Medieval Manding", "Renaissance Mande Sahelian", "West African", "Bambara Communities",
			"Bambara belong to Manding-speaking agrarian and warrior communities along the upper and middle Niger."),
		new("Renaissance Songhay", "Late Medieval Manding", "Renaissance Mande Sahelian", "West African", "Songhay Communities",
			"Songhay belong to riverine, urban and imperial communities along the middle Niger around Gao and Timbuktu."),

		new("Renaissance Kano Hausa", "Late Medieval Hausa", "Renaissance Hausa", "West African", "Kano",
			"Kano Hausa belong to the densely settled craft, farming and merchant communities centred on Kano."),
		new("Renaissance Katsina Hausa", "Late Medieval Hausa", "Renaissance Hausa", "West African", "Katsina",
			"Katsina Hausa belong to the northwestern city-state and its trans-Saharan trading hinterland."),
		new("Renaissance Gobir Hausa", "Late Medieval Hausa", "Renaissance Hausa", "West African", "Gobir",
			"Gobir Hausa belong to the western Hausa frontier, known for fortified settlements and military traditions."),
		new("Renaissance Zazzau Hausa", "Late Medieval Hausa", "Renaissance Hausa", "West African", "Zazzau",
			"Zazzau Hausa belong to the southern Hausa city-state and its mixed farming and trading frontier."),

		new("Renaissance Mpemba Bakongo", "Late Medieval Bakongo", "Renaissance Kongo", "Central African", "Mpemba Province",
			"Mpemba Bakongo belong to the central royal province and communities surrounding the Kongo capital."),
		new("Renaissance Mbata Bakongo", "Late Medieval Bakongo", "Renaissance Kongo", "Central African", "Mbata Province",
			"Mbata Bakongo belong to the important eastern province and its linked noble houses and trade routes."),
		new("Renaissance Soyo Bakongo", "Late Medieval Bakongo", "Renaissance Kongo", "Central African", "Soyo Province",
			"Soyo Bakongo belong to the Atlantic coastal province controlling river mouths, salt and maritime exchange."),

		new("Renaissance Karanga", "Late Medieval Shona", "Renaissance Shona", "Southern African", "Karanga Communities",
			"Karanga belong to southern Shona-speaking communities associated with Great Zimbabwe and the emerging Mutapa sphere."),
		new("Renaissance Zezuru", "Late Medieval Shona", "Renaissance Shona", "Southern African", "Zezuru Communities",
			"Zezuru belong to central plateau communities north and east of the older Zimbabwe heartlands."),
		new("Renaissance Korekore", "Late Medieval Shona", "Renaissance Shona", "Southern African", "Korekore Communities",
			"Korekore belong to northern plateau and Zambezi-facing communities within the wider Shona world."),
		new("Renaissance Manyika", "Late Medieval Shona", "Renaissance Shona", "Southern African", "Manyika Communities",
			"Manyika belong to eastern highland communities tied to goldfields and routes toward the Indian Ocean coast."),

		new("Renaissance Tashelhit Amazigh", "Late Medieval Amazigh", "Renaissance Amazigh", "North African", "Sous and Anti-Atlas",
			"Tashelhit-speaking Amazigh belong to the Sous valley, Anti-Atlas and southwestern Moroccan communities."),
		new("Renaissance Central Atlas Amazigh", "Late Medieval Amazigh", "Renaissance Amazigh", "North African", "Central Atlas",
			"Central Atlas Amazigh belong to the mountain and plateau communities of the Middle and eastern High Atlas."),
		new("Renaissance Riffian Amazigh", "Late Medieval Amazigh", "Renaissance Amazigh", "North African", "Rif",
			"Riffian Amazigh belong to the northern Moroccan mountain and Mediterranean coastal communities."),
		new("Renaissance Kabyle Amazigh", "Late Medieval Amazigh", "Renaissance Amazigh", "North African", "Kabylia",
			"Kabyle Amazigh belong to the mountain villages and confederations of northern Algeria."),
		new("Renaissance Nafusi Amazigh", "Late Medieval Amazigh", "Renaissance Amazigh", "North African", "Nafusa Mountains",
			"Nafusi Amazigh belong to the mountain and oasis communities of the Nafusa range and neighbouring Tripolitania."),
		new("Renaissance Maghrebi Arab", "Late Medieval Amazigh", "Renaissance Amazigh", "North African and Middle Eastern", "Maghrebi Arab",
			"Maghrebi Arabs belong to Arabic-speaking urban, rural and tribal communities across the western Islamic lands.")
	];
}
