#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Microsoft.EntityFrameworkCore;
using MudSharp.Models;

namespace DatabaseSeeder.Seeders;

public partial class HumanSeeder
{
	/// <summary>
	/// Install only the distinct thickness variants consumed by the approved clothing dependency
	/// plan. Existing source components and every revision of an installed variant are untouched.
	/// This supplies reusable components, never garments or a separate installer package.
	/// </summary>
	private bool EnsureIndustrialisedClothingWearLayers()
	{
		var components = _context.GameItemComponentProtos.Include(x => x.EditableItem).ToArray();
		var existingNames = components.Select(x => x.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);
		var missing = IndustrialisedClothingDependencyPlan.WearLayerStock.Where(x => !existingNames.Contains(x.Name)).ToArray();
		if (missing.Length == 0) return false;

		var profiles = _context.WearProfiles.ToArray();
		var progs = _context.FutureProgs.Select(x => x.Id).ToArray();
		var holdable = new GameItemComponentProto { Id = -1, Name = "Holdable", Type = "Holdable", Definition = "<Definition/>" };
		var planned = new List<(ClothingWearLayerStock Stock, string Definition)>();
		foreach (var stock in missing)
		{
			var location = new ClothingSourceLocation("HumanSeeder.WearLayers.cs", 1);
			var candidates = components.Where(x => x.Name.Equals(stock.SourceComponent, StringComparison.OrdinalIgnoreCase)).ToArray();
			if (candidates.Select(x => x.Id).Distinct().Count() != 1)
				throw location.Error($"{stock.Name}: missing or ambiguous source component {stock.SourceComponent}.");
			var source = candidates.Where(x => x.EditableItem?.RevisionStatus == 4)
				.OrderByDescending(x => x.RevisionNumber).FirstOrDefault();
			if (source is null || source.Type != "Wearable")
				throw location.Error($"{stock.Name}: {stock.SourceComponent} has no current Wearable revision.");

			// Validate the actual source before copying. Keep all its profile alternatives, default,
			// visibility flags and supported behaviour; alter thickness and only an explicitly authored
			// bulk override on a separately named identity. Never change shared source stock in place.
			IndustrialisedClothingPhysicalBindings.Bind([holdable, source], profiles, progs, location);
			var root = XElement.Parse(source.Definition);
			root.Elements("LayerWeightConsumption").Remove();
			root.Add(new XElement("LayerWeightConsumption", stock.LayerWeight));
			if (stock.Bulky is { } bulky) root.SetAttributeValue("Bulky", bulky);
			planned.Add((stock, root.ToString()));
		}

		// Resolve the entire missing batch first, so a bad source cannot leave half a layer catalogue.
		var account = _context.Accounts.First();
		var now = DateTime.UtcNow;
		var nextId = components.Select(x => x.Id).DefaultIfEmpty(0).Max() + 1;
		foreach (var (stock, definition) in planned)
		{
			_context.GameItemComponentProtos.Add(new GameItemComponentProto
			{
				Id = nextId++, RevisionNumber = 0, Name = stock.Name, Type = "Wearable",
				Description = stock.Description, Definition = definition,
				EditableItem = new EditableItem
				{
					RevisionNumber = 0, RevisionStatus = 4, BuilderAccountId = account.Id, BuilderDate = now,
					BuilderComment = "Auto-generated by the system", ReviewerAccountId = account.Id,
					ReviewerDate = now, ReviewerComment = "Auto-generated by the system"
				}
			});
		}
		_context.SaveChanges();
		return true;
	}
}
