#nullable enable

namespace DatabaseSeeder.Seeders;

internal static partial class IndustrialisedClothingDependencyPlan
{
	// Authored physical decisions, not a vocabulary matrix or a source of player descriptions.
	// Profile names identify exact required geometry; missing profiles remain reported dependencies.
	private static readonly NewBaseDependency[] NewBases =
	[
		N("button_drawers", "IMNF", "cotton", "Breeches", 0.25),
		N("split_drawers", "I", "cotton", "Split Drawers", 0.25, work: "Open-crotch coverage; do not substitute covered briefs."),
		N("union_suit", "IMN", "wool", "Jumpsuit", 0.25, insulation: "Minor"),
		N("cotton_longjohns", "MNF", "cotton", "Trousers", 0.25),
		N("wool_underjersey", "IMNF", "wool", "Shirt", 0.25, insulation: "Minor"),
		N("cotton_singlet", "MNF", "cotton", "Vest", 0.25),
		N("knit_briefs", "MNF", "cotton", "Briefs", 0.25),
		N("boxer_shorts", "MNF", "cotton", "Shorts", 0.25),
		N("boxer_briefs", "NF", "cotton", "Shorts", 0.25),
		N("cotton_knickers", "MNF", "cotton", "Briefs", 0.25),
		N("silk_camisole", "IMNF", "silk", "Camisole", 0.25),
		N("cotton_camisole", "IMNF", "cotton", "Camisole", 0.25),
		N("full_slip", "MNF", "rayon", "Sleeveless_Dress", 0.25),
		N("half_slip", "MNF", "rayon", "Skirt", 0.25),
		N("thermal_leggings", "NF", "polyester", "Trousers", 0.25, insulation: "Minor"),
		N("nursing_bra", "NF", "cotton", "Bra", 0.25, work: "Cup-opening interaction must be supported or truthfully limited; no automatic medical effect."),
		N("maternity_underpants", "NF", "cotton", "Briefs", 0.25, work: "Fit configuration must preserve the expanding abdominal construction."),
		N("cloth_nappy", "IMNF", "cotton", "Nappy", 0.25, work: "Independent nappy_pins fastening and infant fit; not adult briefs."),
		N("infant_bodysuit", "NF", "cotton", "Infant Bodysuit", 0.25, work: "Infant fit and crotch fastening; no adult-sized fallback."),
		N("infant_gown", "IMNF", "cotton", "Infant Gown", 0.25, work: "Infant fit and open-bottom coverage."),
		N("short_stays", "I", "cotton", "Short Stays", 0.5, work: "Corded short support coverage, not full-length corset geometry."),
		N("long_corset_hand", "I", "cotton", "Stays", 0.5, work: "Boning and lacing inputs; torso support is not a body-deformation effect."),
		N("long_corset_batch", "I", "cotton", "Stays", 0.5, work: "Boning and lacing inputs; separate batch economics."),
		N("corset_cover", "I", "cotton", "Camisole", 0.25),
		N("cage_crinoline", "I", "spring steel", "Skirt_Support", 0.5, work: "Open hoop geometry and textile tapes; no opaque steel skirt."),
		N("crinolette", "I", "spring steel", "Rear Skirt Support", 0.5, work: "Rear half-hoop geometry and textile tapes."),
		N("bustle_pad", "I", "cotton", "Rear Skirt Support", 0.5, work: "Stuffed rear support, not opaque full-leg coverage."),
		N("corded_petticoat", "I", "cotton", "Long_Skirt", 0.5),
		N("flounced_petticoat", "I", "cotton", "Long_Skirt", 0.5),
		N("brassiere_bandeau", "MN", "cotton", "Bra", 0.25),
		N("seamed_bra", "MNF", "cotton", "Bra", 0.25),
		N("moulded_bra", "NF", "nylon", "Bra", 0.25),
		N("sports_bra", "NF", "polyester", "Bra", 0.25),
		N("girdle", "MN", "natural rubber", "Girdle", 0.25, work: "Textile-covered elastic foundation and stocking attachments."),
		N("suspender_belt", "MNF", "cotton", "Stocking Support Belt", 0.25, tag: "Belts", work: "Stocking attachment graph; an equipment Belt component is not proof of stocking support."),
		N("collarless_shirt_hand", "IMNF", "cotton", "Shirt", 0.5),
		N("collarless_shirt_batch", "IMNF", "cotton", "Shirt", 0.5),
		N("attached_collar_shirt", "IMNF", "cotton", "Shirt", 0.5, storage: "Pocket"),
		N("dress_shirt_hand", "IMNF", "cotton", "Shirt", 0.5),
		N("stiff_bib_shirt", "IMN", "cotton", "Shirt", 0.5, work: "Independent collar/cuff attachment points and exact ensemble relations."),
		N("short_sleeve_shirt", "MNF", "cotton", "T-Shirt", 0.5),
		N("tee_shirt", "MNF", "cotton", "T-Shirt", 0.5),
		N("long_sleeve_tee", "NF", "cotton", "Shirt", 0.5),
		N("polo_shirt", "MNF", "cotton", "T-Shirt", 0.5),
		N("blouse_highneck", "IM", "cotton", "High-Neck Shirt", 0.5),
		N("blouse_silk", "MNF", "silk", "Shirt", 0.5),
		N("blouse_cotton", "MNF", "cotton", "Shirt", 0.5),
		N("wrap_blouse", "NF", "cotton", "Shirt", 0.5),
		N("knitted_jumper_hand", "IMNF", "wool", "Shirt", 0.5, insulation: "Moderate"),
		N("knitted_jumper_batch", "IMNF", "wool", "Shirt", 0.5, insulation: "Moderate"),
		N("cardigan_hand", "IMNF", "wool", "Jacket", 0.5, insulation: "Moderate"),
		N("cardigan_batch", "MNF", "wool", "Jacket", 0.5, insulation: "Moderate"),
		N("sweater_vest", "MNF", "wool", "Vest", 0.5, insulation: "Minor"),
		N("rollneck", "MNF", "wool", "High-Neck Shirt", 0.5, insulation: "Moderate"),
		N("sweatshirt", "NF", "cotton", "Shirt", 0.5, insulation: "Minor"),
		N("hooded_sweatshirt", "NF", "cotton", "Hoodie", 0.5, storage: "Pocket", insulation: "Minor"),
		N("zip_hoodie", "F", "cotton", "Hoodie", 0.5, storage: "Pocket", insulation: "Minor", work: "Zipped opening must not be confused with opening a pocket container."),
		N("wool_trousers_braced", "IMNF", "wool", "Trousers", 0.5, storage: "Pocket", insulation: "Minor", work: "Compatible braces buttons and attachment graph."),
		N("wool_trousers_batch", "IMNF", "wool", "Trousers", 0.5, storage: "Pocket", insulation: "Minor"),
		N("cotton_trousers", "IMNF", "cotton", "Trousers", 0.5, storage: "Pocket"),
		N("corduroy_trousers", "IMNF", "cotton", "Trousers", 0.5, storage: "Pocket"),
		N("denim_jeans", "IMNF", "denim", "Trousers", 0.5, storage: "Pocket"),
		N("bib_overalls", "IMNF", "denim", "Bib Overalls", 0.5, storage: "LargePocket", work: "Bib and shoulder-strap coverage without shirt sleeves."),
		N("knickerbockers", "IM", "wool", "Breeches", 0.5, storage: "Pocket"),
		N("jodhpurs", "IMNF", "cotton", "Trousers", 0.5, work: "Reinforced seat and fitted calf construction; no riding bonus."),
		N("tailored_shorts", "MNF", "cotton", "Shorts", 0.5, storage: "Pocket"),
		N("cargo_trousers", "NF", "cotton", "Trousers", 0.5, storage: "LargePocket_Closable"),
		N("track_trousers", "NF", "polyester", "Trousers", 0.5, storage: "Pocket"),
		N("leggings", "NF", "nylon", "Leggings", 0.5),
		N("gored_wool_skirt", "IMNF", "wool", "Long_Skirt", 0.5, insulation: "Minor"),
		N("narrow_walking_skirt", "IM", "wool", "Long_Skirt", 0.5),
		N("pleated_skirt", "MNF", "wool", "Skirt", 0.5),
		N("pencil_skirt", "NF", "wool", "Skirt", 0.5),
		N("circle_skirt", "NF", "cotton", "Skirt", 0.5),
		N("miniskirt", "NF", "wool", "Mini_Skirt", 0.5),
		N("denim_skirt", "NF", "denim", "Skirt", 0.5, storage: "Pocket"),
		N("separate_bodice", "I", "silk", "Stays", 0.5, work: "Boned outer bodice remains separate from skirt and inner corset."),
		N("full_silk_overskirt", "I", "silk", "Long_Skirt", 0.5),
		N("bustle_overskirt", "I", "silk", "Long_Skirt", 0.5),
		N("trained_evening_skirt", "I", "silk", "Trained Skirt", 0.5, work: "Train coverage/weight, not a short-skirt profile."),
		N("cotton_daydress", "IMNF", "cotton", "Long-Sleeved_Dress", 0.5),
		N("shirt_dress", "MNF", "cotton", "Long-Sleeved_Dress", 0.5),
		N("chemise_dress", "M", "silk", "Sleeveless_Dress", 0.5),
		N("bias_evening_gown", "MNF", "silk", "Sleeveless_Gown", 0.5),
		N("fitted_daydress", "NF", "cotton", "Dress", 0.5),
		N("shift_dress", "NF", "wool", "Dress", 0.5),
		N("wrap_dress", "NF", "cotton", "Long-Sleeved_Dress", 0.5),
		N("pinafore_dress", "IMNF", "cotton", "Sleeveless_Dress", 0.5),
		N("maternity_dress", "MNF", "cotton", "Dress", 0.5, work: "Adjustable waist and fit configuration."),
		N("adaptive_openback_dress", "F", "cotton", "Dress", 0.5, work: "Closed overlapping rear panels retain back coverage; assisted dressing and rear-opening configuration require proof, not a permanently backless profile or care subsystem."),
		N("lounge_jacket_hand", "IMNF", "wool", "Jacket", 0.5, storage: "Pocket", insulation: "Minor", bulky: false, work: "Ordinary tailored jacket permits an academic gown over it; padding and lining do not make it mutually exclusive with outer robes."),
		N("lounge_jacket_batch", "IMNF", "wool", "Jacket", 0.5, storage: "Pocket", insulation: "Minor", bulky: false, work: "Same outer-layer compatibility as the hand-tailored lounge jacket; manufacture route does not imply different bulk."),
		N("wool_waistcoat", "IMNF", "wool", "Vest", 0.5, storage: "Pocket"),
		N("silk_waistcoat", "IMNF", "silk", "Vest", 0.5),
		N("frock_coat", "I", "wool", "Long_Coat", 0.75, storage: "Pocket", insulation: "Minor"),
		N("morning_coat", "IMNF", "wool", "Cutaway Coat", 0.75, storage: "Pocket", insulation: "Minor"),
		N("evening_tailcoat", "IMNF", "wool", "Tailcoat", 0.75, storage: "Pocket", insulation: "Minor"),
		N("dinner_jacket", "IMNF", "wool", "Jacket", 0.5, storage: "Pocket"),
		N("peaked_dinner_jacket", "IMNF", "wool", "Jacket", 0.5, storage: "Pocket"),
		N("fitted_suit_jacket", "MNF", "wool", "Jacket", 0.5, storage: "Pocket"),
		N("linen_jacket", "IMNF", "linen", "Jacket", 0.5, storage: "Pocket"),
		N("unstructured_blazer", "MNF", "wool", "Jacket", 0.5, storage: "Pocket"),
		N("long_wool_overcoat", "IMNF", "wool", "Long_Coat", 1, storage: "LargePocket", insulation: "Strong"),
		N("peacoat", "IMNF", "wool", "Jacket", 1, storage: "LargePocket", insulation: "Strong"),
		N("trench_coat", "MNF", "cotton", "Long_Coat", 0.75, storage: "LargePocket", work: "Waterproofing requires explicit Wearable configuration; untreated cotton is not waterproof."),
		N("oilskin_coat", "IMNF", "canvas", "Long_Coat", 0.75, storage: "LargePocket", work: "Oiling liquid/input and waterproof Wearable configuration."),
		N("rubberised_raincoat", "IMNF", "canvas", "Long_Coat", 0.75, storage: "LargePocket", work: "Natural-rubber coating input and waterproof Wearable configuration."),
		N("rain_trousers", "MNF", "canvas", "Trousers", 0.5, work: "Waterproof coating input and Wearable configuration."),
		N("denim_jacket", "MNF", "denim", "Jacket", 0.75, storage: "Pocket", insulation: "Minor"),
		N("leather_flight_jacket", "MNF", "leather", "Jacket", 0.75, storage: "Pocket", insulation: "Moderate"),
		N("leather_riding_jacket", "NF", "leather", "Jacket", 0.75, storage: "Pocket", insulation: "Moderate"),
		N("fur_skin_parka", "IMNF", "fur", "Hooded Long Coat", 1, insulation: "Super", work: "Fur-skin construction and native fur palette; no waterproof claim."),
		N("cloth_parka", "MNF", "cotton", "Hooded Long Coat", 1, storage: "LargePocket", insulation: "Strong"),
		N("quilted_jacket", "NF", "polyester", "Jacket", 1, storage: "Pocket", insulation: "Strong"),
		N("fleece_jacket", "F", "polyester", "Jacket", 0.75, storage: "Pocket", insulation: "Moderate"),
		N("shell_jacket", "F", "nylon", "Hoodie", 0.5, storage: "Pocket", bulky: false, work: "Thin uninsulated outer shell permits a separate fleece beneath it. Weatherproof membrane/input and Wearable configuration still need proof; no reflective safety claim."),
		N("shell_overtrousers", "F", "nylon", "Trousers", 0.5, work: "Weatherproof membrane/input and ankle opening configuration."),
		N("detachable_collar", "IMN", "cotton", "Detachable Collar", 0.25, tag: "Detachable Garment Parts", work: "Independent collar fastening and compatible shirt target."),
		N("standing_collar", "IM", "cotton", "Standing Collar", 0.25, tag: "Detachable Garment Parts", work: "Independent collar fastening and compatible shirt target."),
		N("detachable_cuffs", "IMN", "cotton", "Detachable Cuffs", 0.25, tag: "Detachable Garment Parts", work: "Paired cuff fastening and compatible sleeves."),
		N("shirtfront", "IM", "cotton", "Shirtfront", 0.25, tag: "Detachable Garment Parts"),
		N("braces", "IMNF", "cotton", "Braces", 0.25, tag: "Fashion Accessories", work: "Trouser attachment graph; not an equipment belt."),
		N("woven_necktie", "IMNF", "silk", "Necktie", 0.25, tag: "Fashion Accessories"),
		N("bow_tie", "IMNF", "silk", "Bowtie", 0.25, tag: "Fashion Accessories"),
		N("cravat", "IMNF", "silk", "Scarf", 0.25, tag: "Fashion Accessories"),
		N("cummerbund", "IMNF", "silk", "Waist", 0.25, tag: "Fashion Accessories"),
		N("lapel_pin", "IMNF", "brass", "Pin", 0, colours: "MetalFinish", tag: "Jewellery / Badges", work: "Removable pin target and material-appropriate finishes."),
		N("rank_slides", "MNF", "cotton", "Rank Slides", 0.25, tag: "Detachable Garment Parts", work: "Paired tubes attached to actual shoulder straps; no membership effect."),
		N("detachable_badge", "IMNF", "brass", "Badge", 0, colours: "MetalFinish", tag: "Jewellery / Badges", work: "Removable badge target and material-appropriate finishes."),
		N("medal_ribbon", "IMNF", "cotton", "Ribbon Bar", 0.25, tag: "Fashion Accessories", work: "Removable ribbon bar fastening; metal medal is a separate domain-owned item."),
		N("fabric_belt", "MNF", "canvas", "Waist", 0.25, tag: "Belts", extra: "Belt_4"),
		N("cotton_stockings", "IMNF", "cotton", "Stockings", 0.25, tag: "Footwear"),
		N("dance_tights", "MNF", "cotton", "Tights", 0.25, tag: "Footwear"),
		N("nylon_stockings", "MNF", "nylon", "Stockings", 0.25, tag: "Footwear"),
		N("tights", "NF", "nylon", "Tights", 0.25, tag: "Footwear"),
		N("cotton_socks", "IMNF", "cotton", "Socks", 0.25, tag: "Footwear"),
		N("wool_socks_hand", "IMNF", "wool", "Socks", 0.25, tag: "Footwear", insulation: "Minor"),
		N("wool_socks_batch", "IMNF", "wool", "Socks", 0.25, tag: "Footwear", insulation: "Minor"),
		N("sports_socks", "NF", "poly-cotton blend", "Socks", 0.25, tag: "Footwear"),
		N("opera_gloves", "IMNF", "leather", "Long Gloves", 0.25, tag: "Gloves"),
		N("knitted_gloves", "IMNF", "wool", "Gloves", 0.5, tag: "Gloves", insulation: "Minor"),
		N("fingerless_gloves", "IMNF", "wool", "Fingerless_Gloves", 0.5, tag: "Gloves", insulation: "Minor"),
		N("driving_gloves", "MNF", "leather", "Gloves", 0.25, tag: "Gloves"),
		N("cotton_service_gloves", "IMNF", "cotton", "Gloves", 0.25, tag: "Gloves"),
		N("balaclava", "IMNF", "wool", "Balaclava", 0.5, tag: "Headwear", insulation: "Minor"),
		N("knitted_cap", "IMNF", "wool", "Skullcap", 0.5, tag: "Headwear", insulation: "Minor"),
		N("felt_bowler", "IMNF", "felt", "Hat", 0.5, tag: "Hats"),
		N("felt_fedora", "IMNF", "felt", "Hat", 0.5, tag: "Hats"),
		N("silk_top_hat", "I", "silk", "Hat", 0.5, tag: "Hats", work: "Stiff supporting frame and silk-facing inputs."),
		N("straw_boater", "IMNF", "straw", "Hat", 0.5, tag: "Hats", work: "Native straw finish plus variable ribbon colour; one textile palette must not recolour all straw."),
		N("straw_panama", "IMNF", "straw", "Hat", 0.5, tag: "Hats", work: "Fine plant-fibre analogue and native finish/palette evidence."),
		N("flat_cap", "IMNF", "wool", "Hat", 0.5, tag: "Hats"),
		N("newsboy_cap", "IMNF", "wool", "Hat", 0.5, tag: "Hats"),
		N("baseball_cap", "MNF", "cotton", "Hat", 0.5, tag: "Hats"),
		N("service_cap", "IMNF", "wool", "Hat", 0.5, tag: "Hats"),
		N("side_cap", "MNF", "wool", "Skullcap", 0.5, tag: "Headwear"),
		N("beret", "IMNF", "wool", "Skullcap", 0.5, tag: "Headwear"),
		N("cloth_sunhat", "MNF", "cotton", "Hat", 0.5, tag: "Hats"),
		N("pith_helmet", "IM", "pith", "Hat", 0.5, tag: "Hats", work: "Distinct source-backed plant-pith material; do not substitute ballistic helmet or wood."),
		N("bonnet", "I", "cotton", "Bonnet", 0.5, tag: "Headwear", work: "Frame and under-chin tie coverage."),
		N("hat_veil", "IMNF", "silk gauze", "Veil", 0.25, tag: "Facewear", work: "Attach separate net veil to compatible hat; variable ground and decoration."),
		N("chef_toque", "IMNF", "cotton", "Hat", 0.5, tag: "Hats"),
		N("nursing_cap", "IMN", "cotton", "Skullcap", 0.25, tag: "Headwear"),
		N("hairnet", "IMNF", "cotton", "Hairnet", 0.25, tag: "Headwear", work: "Transparent net coverage, not an opaque cap."),
		N("nightshirt", "IMNF", "cotton", "Long-Sleeved_Tunic", 0.5),
		N("pyjama_jacket", "MNF", "cotton", "Shirt", 0.5),
		N("pyjama_trousers", "MNF", "cotton", "Trousers", 0.5),
		N("silk_sleep_jacket", "MNF", "silk", "Shirt", 0.5),
		N("silk_sleep_trousers", "MNF", "silk", "Trousers", 0.5),
		N("dressing_gown", "IMNF", "cotton", "Long_Open_Robe", 0.75, storage: "Pocket"),
		N("towelling_robe", "MNF", "cotton", "Long_Open_Robe", 0.75, storage: "Pocket", work: "Absorbency and drying behaviour must agree with the cotton material."),
		N("bathing_tunic", "I", "wool", "Tunic", 0.5),
		N("bathing_drawers", "I", "wool", "Breeches", 0.5),
		N("knitted_swimsuit", "M", "wool", "Bodysuit", 0.5),
		N("stretch_swimsuit", "NF", "nylon", "Bodysuit", 0.25),
		N("bikini_top", "NF", "nylon", "Bra", 0.25),
		N("bikini_bottoms", "NF", "nylon", "Briefs", 0.25),
		N("swim_shorts", "MNF", "cotton", "Shorts", 0.5),
		N("rash_vest", "F", "polyester", "Shirt", 0.25),
		N("sports_jersey", "MNF", "cotton", "T-Shirt", 0.5),
		N("running_shorts", "MNF", "cotton", "Shorts", 0.25),
		N("track_jacket", "NF", "polyester", "Jacket", 0.5),
		N("cycling_shorts", "NF", "nylon", "Shorts", 0.25),
		N("cycling_jersey", "NF", "polyester", "T-Shirt", 0.25, storage: "Pocket"),
		N("ballet_leotard", "MNF", "cotton", "Bodysuit", 0.25),
		N("dance_tutu", "MNF", "cotton", "Net Skirt", 0.5, work: "Layered transparent net skirt; separate leotard/tights."),
		N("martial_jacket", "MNF", "cotton", "Jacket", 0.5),
		N("martial_trousers", "MNF", "cotton", "Trousers", 0.5),
		N("martial_belt", "MNF", "cotton", "Waist", 0.25, tag: "Belts"),
		N("kitchen_jacket", "IMNF", "cotton", "Jacket", 0.5),
		N("bib_apron", "IMNF", "cotton", "Apron", 0.5),
		N("waist_apron", "IMNF", "cotton", "Waist Apron", 0.5, storage: "Pocket"),
		N("laboratory_coat", "MNF", "cotton", "Long_Coat", 0.5, storage: "LargePocket"),
		N("scrub_top", "NF", "poly-cotton blend", "T-Shirt", 0.5, storage: "Pocket"),
		N("scrub_trousers", "NF", "poly-cotton blend", "Trousers", 0.5, storage: "Pocket"),
		N("boiler_suit", "MNF", "cotton", "Jumpsuit", 0.75, storage: "LargePocket"),
		N("dust_coat", "IMNF", "cotton", "Long_Coat", 0.5, storage: "Pocket"),
		N("domestic_uniform_dress", "IMN", "cotton", "Long-Sleeved_Dress", 0.5),
		N("hospital_gown", "MNF", "cotton", "Open-Back Gown", 0.25, work: "Rear opening and ties, not a closed ordinary dress."),
		N("service_tunic", "IMNF", "wool", "High-Neck Jacket", 0.75, storage: "Pocket", work: "Real shoulder straps must accept separately supplied rank slides."),
		N("tropical_tunic", "IMNF", "cotton", "Jacket", 0.5, storage: "Pocket"),
		N("parade_tunic", "IMNF", "wool", "High-Neck Jacket", 0.75),
		N("sailor_jumper", "IMNF", "wool", "Shirt", 0.5),
		N("sailor_trousers", "IMNF", "wool", "Trousers", 0.5, storage: "Pocket"),
		N("battledress_blouse", "MN", "wool", "Jacket", 0.75, storage: "Pocket", insulation: "Minor"),
		N("battledress_trousers", "MN", "wool", "Trousers", 0.5, storage: "LargePocket", insulation: "Minor"),
		N("fatigue_shirt", "MNF", "cotton", "Shirt", 0.5, storage: "Pocket_Closable"),
		N("field_smock", "NF", "cotton", "Long_Coat", 0.75, storage: "LargePocket_Closable"),
		N("ceremonial_sash", "IMNF", "silk", "Sash", 0.25, tag: "Fashion Accessories"),
		N("mess_jacket", "MNF", "wool", "Cutaway Jacket", 0.5),
		N("service_skirt", "MNF", "wool", "Skirt", 0.5),
		N("button_boots", "I", "leather", "Boots", 1, tag: "Footwear"),
		N("welted_workboots", "IMNF", "leather", "Boots", 1, tag: "Footwear"),
		N("bespoke_laceboots", "IMNF", "leather", "Boots", 1, tag: "Footwear"),
		N("rubber_boots", "IMNF", "vulcanized rubber", "High_Boots", 1, tag: "Footwear", work: "Waterproof Wearable configuration."),
		N("rubber_overshoes", "IMNF", "vulcanized rubber", "Overshoes", 0.5, tag: "Footwear", work: "Fit over shoes; waterproof Wearable configuration."),
		N("closed_lace_shoes", "IMNF", "leather", "Shoes", 1, tag: "Footwear"),
		N("open_lace_shoes", "IMNF", "leather", "Shoes", 1, tag: "Footwear"),
		N("court_shoes", "IMNF", "leather", "Low-Cut Shoes", 1, tag: "Footwear"),
		N("stiletto_shoes", "NF", "leather", "Low-Cut Shoes", 1, tag: "Footwear", work: "Narrow heel geometry and cost; no invented movement effect."),
		N("bar_shoes", "MNF", "leather", "Shoes", 1, tag: "Footwear"),
		N("loafers", "MNF", "leather", "Shoes", 1, tag: "Footwear"),
		N("canvas_trainers", "MNF", "canvas", "Shoes", 1, tag: "Footwear", work: "Rubber sole input distinct from canvas upper."),
		N("running_trainers", "NF", "polyester", "Shoes", 1, tag: "Footwear", work: "Synthetic mesh and cushioned sole inputs."),
		N("high_top_trainers", "NF", "canvas", "Boots", 1, tag: "Footwear", work: "Rubber sole input and ankle coverage."),
		N("deck_shoes", "MNF", "leather", "Shoes", 1, tag: "Footwear", work: "Flexible rubber sole input."),
		N("desert_boots", "NF", "leather", "Boots", 1, tag: "Footwear", work: "Suede surface/processing and crepe-like sole input; not a material-changing skin."),
		N("cowboy_boots", "IMNF", "leather", "High_Boots", 1, tag: "Footwear"),
		N("walking_boots", "MNF", "leather", "Boots", 1, tag: "Footwear"),
		N("snow_boots", "NF", "polyester", "Boots", 1, tag: "Footwear", insulation: "Strong", work: "Rubber sole and insulating fill inputs."),
		N("toe_post_sandals", "NF", "vulcanized rubber", "Sandals", 0.5, tag: "Footwear"),
		N("backless_mules", "IMNF", "leather", "Backless Shoes", 0.75, tag: "Footwear"),
		N("ballet_slippers", "MNF", "canvas", "Low-Cut Shoes", 0.5, tag: "Footwear"),
		N("pointe_shoes", "MNF", "canvas", "Low-Cut Shoes", 0.75, tag: "Footwear", work: "Reinforced toe-box and binding inputs, distinct from soft slippers."),
		N("studded_boots", "MNF", "leather", "Boots", 1, tag: "Footwear", work: "Studded sole input; no unsupported sport bonus."),
		N("infant_booties", "IMNF", "wool", "Infant Footwear", 0.25, tag: "Footwear", work: "Infant fit and soft knitted coverage."),
		N("sari_petticoat", "IMNF", "cotton", "Long_Skirt", 0.5),
		N("dupatta", "IMNF", "cotton", "Head_Veil", 0.25, work: "Additional shoulder/scarf wear arrangements must be explicitly admitted."),
		N("qipao", "MNF", "silk", "High-Neck Dress", 0.5),
		N("chinese_padded_jacket", "IMNF", "cotton", "Jacket", 0.75, insulation: "Moderate"),
		N("jeogori", "IMNF", "cotton", "Short Wrap Jacket", 0.5),
		N("chima", "IMNF", "cotton", "High-Waisted Skirt", 0.5),
		N("agbada", "IMNF", "cotton", "Wide Over-Robe", 0.75),
		N("tiputa", "IMNF", "barkcloth", "Poncho", 0.5),
		N("long_tropical_skirt", "IMNF", "cotton", "Long_Skirt", 0.5),
		N("clerical_collar", "MNF", "cotton", "Clerical Collar", 0.25, colours: "Colour", tag: "Detachable Garment Parts", work: "Separate neck band attachment; white is an overridable outfit default."),
		N("clerical_shirt", "MNF", "cotton", "Shirt", 0.5, work: "Attachment for separately supplied clerical collar."),
		N("academic_hood", "IMNF", "wool", "Academic Hood", 0.5, work: "Silk lining input and shoulder cape coverage; hood is separate from gown."),
		N("liturgical_zone", "IMNF", "silk", "Waist", 0.25, tag: "Belts", work: "Backed vestment belt, not equipment support."),
		N("nappy_pins", "IMNF", "spring steel", "Nappy Pins", 0, colours: "MetalFinish", tag: "Detachable Garment Parts", work: "Supplied pair of guarded pins and independent nappy attachment graph."),
		N("spats", "IMNF", "felt", "Spats", 0.5, tag: "Footwear", work: "Ankle/instep coverage and underfoot straps, not calf gaiters.")
	];
}
