#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.GameItems;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using MudSharp.Vehicles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace DatabaseSeeder.Seeders;

public partial class ItemSeeder
{
	private long? ResolveVehicleInteriorTerrainId(
		string? terrainName,
		VehicleProto vehicle,
		VehicleCompartmentSeedSpec compartment)
	{
		if (string.IsNullOrWhiteSpace(terrainName))
		{
			return null;
		}

		var terrain = _context!.Terrains.AsEnumerable()
			.FirstOrDefault(x => x.Name.Equals(terrainName, StringComparison.OrdinalIgnoreCase));
		return terrain?.Id ?? throw new InvalidOperationException(
			$"Vehicle {vehicle.Name} compartment {compartment.Name} requires missing terrain {terrainName}.");
	}

	private long? ResolveVehicleFuelLiquidId(
		string? liquidName,
		VehicleProto vehicle,
		VehicleMovementProfileSeedSpec movement)
	{
		if (string.IsNullOrWhiteSpace(liquidName))
		{
			return null;
		}

		return _liquids.TryGetValue(liquidName, out var liquid)
			? liquid.Id
			: throw new InvalidOperationException(
				$"Vehicle {vehicle.Name} movement profile {movement.Name} requires missing liquid {liquidName}.");
	}

	private long? ResolveVehiclePropulsionTraitId(
		string? requestedName,
		VehicleProto vehicle,
		VehicleMovementProfileProto movement,
		VehiclePropulsionSeedSpec propulsion)
	{
		if (propulsion.PropulsionType is not (VehiclePropulsionType.SelfPowered or VehiclePropulsionType.Rowed))
		{
			return null;
		}

		var candidates = new[] { requestedName, "Swimming", "Swim", "Athletics" }
			.Where(x => !string.IsNullOrWhiteSpace(x))
			.Distinct(StringComparer.OrdinalIgnoreCase)
			.ToArray();
		var trait = _context!.TraitDefinitions.AsEnumerable()
			.FirstOrDefault(x => candidates.Contains(x.Name, StringComparer.OrdinalIgnoreCase));
		return trait?.Id ?? throw new InvalidOperationException(
			$"Vehicle {vehicle.Name} movement profile {movement.Name} cannot seed {propulsion.PropulsionType} propulsion because none of {string.Join(", ", candidates)} exists.");
	}

	private static long? ResolveVehicleDamageTargetId(
		VehicleDamageEffectSeedSpec spec,
		IReadOnlyDictionary<string, VehicleMovementProfileProto> movements,
		IReadOnlyDictionary<string, VehicleAccessPointProto> accesses,
		IReadOnlyDictionary<string, VehicleCargoSpaceProto> cargos,
		IReadOnlyDictionary<string, VehicleInstallationPointProto> installations,
		IReadOnlyDictionary<string, VehicleTowPointProto> towPoints)
	{
		if (spec.TargetKey is null)
		{
			return null;
		}

		return spec.TargetType switch
		{
			VehicleDamageEffectTargetType.MovementProfile => movements[spec.TargetKey].Id,
			VehicleDamageEffectTargetType.AccessPoint => accesses[spec.TargetKey].Id,
			VehicleDamageEffectTargetType.CargoSpace => cargos[spec.TargetKey].Id,
			VehicleDamageEffectTargetType.InstallationPoint => installations[spec.TargetKey].Id,
			VehicleDamageEffectTargetType.TowPoint => towPoints[spec.TargetKey].Id,
			VehicleDamageEffectTargetType.WholeVehicleMovement => null,
			_ => throw new ArgumentOutOfRangeException(nameof(spec.TargetType), spec.TargetType, null)
		};
	}

	private static T? SingleVehicleChild<T>(
		IEnumerable<T> existing,
		Func<T, string> nameSelector,
		string name,
		VehicleProto vehicle,
		string childKind)
		where T : class
	{
		var matches = existing.Where(x => nameSelector(x).Equals(name, StringComparison.OrdinalIgnoreCase)).ToArray();
		if (matches.Length > 1)
		{
			throw new InvalidOperationException(
				$"Vehicle {vehicle.Name} contains multiple {childKind} rows named {name}.");
		}

		return matches.SingleOrDefault();
	}

	private long NextVehiclePrototypeId()
	{
		var stored = _context!.VehicleProtos.Select(x => x.Id).AsEnumerable().DefaultIfEmpty().Max();
		var local = _context.VehicleProtos.Local.Select(x => x.Id).DefaultIfEmpty().Max();
		return Math.Max(stored, local) + 1L;
	}

	private long NextVehicleComponentPrototypeId()
	{
		var stored = _context!.GameItemComponentProtos.Select(x => x.Id).AsEnumerable().DefaultIfEmpty().Max();
		var local = _context.GameItemComponentProtos.Local.Select(x => x.Id).DefaultIfEmpty().Max();
		return Math.Max(stored, local) + 1L;
	}

	private EditableItem NewCurrentVehicleEditableItem(string builderComment)
	{
		return new EditableItem
		{
			RevisionNumber = 0,
			RevisionStatus = 4,
			BuilderAccountId = _dbAccount.Id,
			BuilderDate = _now,
			BuilderComment = builderComment,
			ReviewerAccountId = _dbAccount.Id,
			ReviewerComment = "Auto-generated by the item seeder vehicle catalogue.",
			ReviewerDate = _now
		};
	}

	private static string VehicleSeederMarker(string stableReference)
	{
		return $"{VehicleSeederMarkerPrefix}{stableReference}]]";
	}

	private static bool ContainsVehicleSeederMarker(string? text, string marker)
	{
		return text?
			.Split(["\r\n", "\n"], StringSplitOptions.RemoveEmptyEntries)
			.Any(x => x.Equals(marker, StringComparison.Ordinal)) == true;
	}

	private static string WithVehicleSeederMarker(string description, string marker)
	{
		var clean = description
			.Split(["\r\n", "\n"], StringSplitOptions.RemoveEmptyEntries)
			.Where(x => !x.StartsWith(VehicleSeederMarkerPrefix, StringComparison.Ordinal))
			.ToArray();
		return string.Join(Environment.NewLine, clean.Append(marker));
	}

	private static string DefaultVehicleLongDescription(string shortDescription)
	{
		if (string.IsNullOrWhiteSpace(shortDescription))
		{
			return "A vehicle is here.";
		}

		return $"{char.ToUpperInvariant(shortDescription[0])}{shortDescription[1..]} is here.";
	}
}
