using MudSharp.Framework;
using MudSharp.GameItems;
using MudSharp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DatabaseSeeder.Seeders
{
    public partial class ItemSeeder
    {
        MudSharp.Models.GameItemProto? CreateItem(string stableReference,
                                                  string noun,
                                                  string sdesc,
                                                  string? ldesc,
                                                  string fdesc,
                                                  SizeCategory size,
                                                  ItemQuality quality,
                                                  double weightInGrams,
                                                  decimal inherentCost,
                                                  bool skinnable,
                                                  bool hideFromPlayers,
                                                  string material,
                                                  IEnumerable<string> tags,
                                                  IEnumerable<string> components,
                                                  string? morphToUniqueReference,
                                                  string? morphEmote,
                                                  TimeSpan? morphTimer,
                                                  string? destroyedItemUniqueReference)
        {
            GameItemProto dbitem = new()
            {
                Id = _nextId++,
                Name = noun.ToLowerInvariant(),
                Keywords = new ExplodedString(sdesc.Strip_A_An()).Words.Distinct().ListToCommaSeparatedValues(" "),
                MaterialId = _materials[material].Id,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = _dbAccount.Id,
                    BuilderDate = _now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = _dbAccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = _now
                },
                RevisionNumber = 0,
                Size = (int)size,
                Weight = weightInGrams,
                ReadOnly = false,
                LongDescription = ldesc,
                BaseItemQuality = (int)quality,
                ShortDescription = sdesc,
                FullDescription = fdesc,
                PermitPlayerSkins = skinnable,
                CostInBaseCurrency = inherentCost,
                IsHiddenFromPlayers = hideFromPlayers,
            };
            foreach (string item in tags)
            {
                if (string.IsNullOrEmpty(item))
                {
                    continue;
                }

                if (!_tagsByFullPath.ContainsKey(item))
                {
                    return null;
                }

                dbitem.GameItemProtosTags.Add(new GameItemProtosTags
                {
                    GameItemProto = dbitem,
                    TagId = _tagsByFullPath[item].Id
                });
            }

            foreach (string item in components)
            {
                if (string.IsNullOrEmpty(item))
                {
                    continue;
                }

                if (!_components.ContainsKey(item))
                {
                    return null;
                }

                dbitem.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
                {
                    GameItemProto = dbitem,
                    GameItemComponent = _components[item]
                });
            }

            _context!.GameItemProtos.Add(dbitem);
            _items[stableReference] = dbitem;
            return dbitem;
        }

        
        public void SeedReworkItems()
        {
            if (_questionAnswers["eras"].Contains("antiquity", StringComparison.InvariantCultureIgnoreCase))
            {
                SeedAntiquityClothing();
                SeedAntiquityHouseholdCraftTools();
                SeedAntiquityJewellery();
                SeedAntiquityArmour();
                SeedAntiquityContainers();
                SeedAntiquityDoorsAndLocks();
                SeedAntiquityHouseholdFurniture();
                SeedAntiquityWeaponsShieldsAccessories();
            }

            if (_questionAnswers["eras"].Contains("medieval", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (_questionAnswers["eras"].Contains("renaissance", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (_questionAnswers["eras"].Contains("earlymodern", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (_questionAnswers["eras"].Contains("imperial", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (_questionAnswers["eras"].Contains("modern", StringComparison.InvariantCultureIgnoreCase))
            {

            }
        }
    }
}
