#nullable enable

using MudSharp.GameItems;

namespace DatabaseSeeder.Seeders;

public partial class ItemSeeder
{
	private void SeedEarlyModernHouseholdCoffeehouseTavernAndTrade()
	{
		var householdTags = new[] { "Era / Early Modern Era", "Market / Household Goods / Standard Wares" };
		var furnitureTags = new[] { "Era / Early Modern Era", "Market / Household Goods / Standard Furniture" };
		SeedStraightforwardEraCatalogueItems(
			"Early Modern household, coffeehouse, tavern, and trade catalogue",
			[
				new("earlymodern_household_coffee_cup", "cup", "a small porcelain coffee cup", "A small handleless porcelain cup is glazed inside and out for serving a modest portion of coffee.", SizeCategory.Small, ItemQuality.Good, 160.0, 8.0m, "porcelain", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Cup_150ml"], "Early Modern coffee service vessel; accepts live liquids."),
				new("earlymodern_household_coffee_pot", "pot", "a lidded copper coffee pot", "A narrow copper pot has a fitted lid, long pouring spout, and a heat-darkened base for preparing coffee service.", SizeCategory.Normal, ItemQuality.Good, 1400.0, 32.0m, "copper", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Pot_12L"], "Early Modern coffee service vessel; accepts live liquids."),
				new("earlymodern_household_coffee_grinder", "grinder", "a hand-cranked coffee grinder", "A small wooden grinder has a brass crank above a covered grinding chamber and collection drawer.", SizeCategory.Small, ItemQuality.Standard, 1700.0, 22.0m, "oak", householdTags, ["Holdable", "Destroyable_Misc"], "Early Modern coffee-processing tool; grinding behaviour is descriptive."),
				new("earlymodern_household_tea_bowl", "bowl", "a glazed tea bowl", "A thin glazed bowl has a rounded foot and an unhandled rim suited to warm tea service.", SizeCategory.Small, ItemQuality.Good, 180.0, 9.0m, "porcelain", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Cup_150ml"], "Early Modern tea service vessel; accepts live liquids."),
				new("earlymodern_household_teapot", "teapot", "a glazed stoneware teapot", "A compact stoneware pot has a fitted lid, side handle, and a short pouring spout for tea service.", SizeCategory.Normal, ItemQuality.Good, 1200.0, 24.0m, "stoneware", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Pitcher_4L"], "Early Modern tea service vessel; accepts live liquids."),
				new("earlymodern_household_tea_caddy", "caddy", "a small tea caddy", "A close-fitting wooden caddy has a simple lid and dry interior for keeping tea leaves or bricks from household damp.", SizeCategory.Small, ItemQuality.Good, 620.0, 18.0m, "oak", householdTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern tea-storage container."),
				new("earlymodern_household_chocolate_pot", "pot", "a tall chocolate pot", "A tall metal pot has a narrow neck and lid opening for stirring thick chocolate during table service.", SizeCategory.Normal, ItemQuality.Good, 1600.0, 38.0m, "copper", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Pot_12L"], "Early Modern chocolate-service vessel; accepts live liquids."),
				new("earlymodern_household_punch_bowl", "bowl", "a wide punch bowl", "A wide glazed bowl is large enough for mixed drink service and a floating ladle at a social table.", SizeCategory.Normal, ItemQuality.Good, 3100.0, 44.0m, "porcelain", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Basin_5L"], "Early Modern punch-service vessel; accepts live liquids."),
				new("earlymodern_household_tobacco_pipe", "pipe", "a long-stemmed clay tobacco pipe", "A white clay bowl rises from a long narrow stem, plain enough for everyday tavern or coffeehouse use.", SizeCategory.Small, ItemQuality.Standard, 70.0, 3.0m, "earthenware", householdTags, ["Holdable", "Destroyable_Misc"], "Early Modern tobacco pipe form; smoking behaviour is not implied by this component set."),
				new("earlymodern_household_snuff_box", "box", "a small brass snuff box", "A small brass box has a close lid and dry interior for a pinch of snuff or other fine household powder.", SizeCategory.Small, ItemQuality.Good, 150.0, 15.0m, "brass", householdTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern personal snuff container."),
				new("earlymodern_household_spittoon", "spittoon", "a brass tavern spittoon", "A low brass vessel has a broad weighted base and flared mouth for public-house use beside benches or a counter.", SizeCategory.Normal, ItemQuality.Standard, 2600.0, 20.0m, "brass", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Basin_5L"], "Early Modern public-house service vessel; accepts live liquids."),
				new("earlymodern_household_tavern_tankard", "tankard", "a lidded pewter tankard", "A heavy pewter tankard has a hinged lid and thumb piece above a broad body for durable tavern service.", SizeCategory.Small, ItemQuality.Standard, 620.0, 12.0m, "pewter", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_Stein"], "Early Modern tavern vessel; accepts live liquids."),
				new("earlymodern_household_tavern_glass_bottle", "bottle", "a dark green glass bottle", "A squat dark glass bottle has a thick lip and rounded base for table wine, beer, or cordial service.", SizeCategory.Small, ItemQuality.Standard, 520.0, 10.0m, "glass", householdTags, ["Holdable", "Destroyable_Misc", "LContainer_BeerBottle"], "Early Modern bottle; accepts live liquids."),
				new("earlymodern_household_dice_pair", "dice", "a pair of bone dice", "Two small bone cubes are carefully marked with dark pips for tavern games and household wagers.", SizeCategory.Small, ItemQuality.Standard, 30.0, 2.0m, "bone", householdTags, ["Holdable", "Destroyable_Misc", "Dice_d6"], "Early Modern dice using the existing die component."),
				new("earlymodern_household_playing_cards", "cards", "a packet of playing cards", "A tied packet of stiff printed cards carries simple repeating backs and blank faces for a builder-authored deck design.", SizeCategory.Small, ItemQuality.Standard, 160.0, 6.0m, "paper", householdTags, ["Holdable", "Destroyable_Misc"], "Early Modern card deck; no card-game engine behaviour is claimed."),
				new("earlymodern_household_scoreboard", "board", "a tavern score board", "A painted wooden board has columns and pegs for keeping visible scores, debts, or team tallies.", SizeCategory.Normal, ItemQuality.Standard, 2400.0, 14.0m, "oak", householdTags, ["Destroyable_Furniture"], "Early Modern tavern display; scoring mechanics are descriptive."),
				new("earlymodern_household_coffeehouse_table", "table", "a round coffeehouse table", "A small round oak table has a sturdy pedestal base and a top marked by cups, pipes, and folded papers.", SizeCategory.Large, ItemQuality.Standard, 18000.0, 85.0m, "oak", furnitureTags, ["Destroyable_Furniture", "Table_Four"], "Early Modern coffeehouse furniture; intentionally not holdable."),
				new("earlymodern_household_coffeehouse_bench", "bench", "a long coffeehouse bench", "A long oak bench has a simple rail back and broad seat worn smooth by public-house patrons.", SizeCategory.Large, ItemQuality.Standard, 24000.0, 72.0m, "oak", furnitureTags, ["Destroyable_Furniture", "Chair_Triple"], "Early Modern public-house seating; intentionally not holdable."),
				new("earlymodern_household_account_box", "box", "a lockable account box", "A compact oak box has an iron-hasp lid and divided interior for receipts, coins, and loose account papers.", SizeCategory.Normal, ItemQuality.Good, 4200.0, 38.0m, "oak", householdTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern account-storage box; lock behaviour is not claimed."),
				new("earlymodern_household_framed_mirror", "mirror", "a framed looking glass", "A small polished looking glass is set into a carved oak frame for household or shop display.", SizeCategory.Normal, ItemQuality.Good, 5200.0, 56.0m, "glass", householdTags, ["Destroyable_Furniture"], "Early Modern decorative household mirror; reflection mechanics are descriptive."),
				new("earlymodern_household_pendulum_clock_case", "clock", "a tall pendulum clock case", "A tall oak case encloses a dial, weight channel, and visible pendulum window beneath a simple hood.", SizeCategory.Large, ItemQuality.Good, 42000.0, 240.0m, "oak", furnitureTags, ["Destroyable_Furniture"], "Early Modern clock form; no runtime timekeeping component is claimed."),
				new("earlymodern_household_escritoire", "escritoire", "a fall-front escritoire", "A polished oak escritoire has a sloping fall front above shallow drawers and pigeonholes for paper and household accounts.", SizeCategory.Large, ItemQuality.Good, 52000.0, 220.0m, "oak", furnitureTags, ["Destroyable_Furniture", "Container_Writing_Desk_Drawers"], "Early Modern writing furniture; intentionally not holdable."),
				new("earlymodern_household_glass_display_cabinet", "cabinet", "a glazed display cabinet", "A tall oak cabinet has glazed doors and narrow shelves for porcelain, curiosities, or other visible household objects.", SizeCategory.Large, ItemQuality.Good, 48000.0, 260.0m, "oak", furnitureTags, ["Destroyable_Furniture", "Container_Glass_Cabinet"], "Early Modern display furniture; intentionally not holdable."),
				new("earlymodern_household_fire_screen", "screen", "a folding fire screen", "A light framed screen of wood and textile panels stands between a hearth and nearby chairs to soften direct heat.", SizeCategory.Large, ItemQuality.Standard, 9800.0, 45.0m, "oak", furnitureTags, ["Destroyable_Furniture"], "Early Modern hearth furniture; no heat-transfer mechanic is claimed."),
				new("earlymodern_household_brass_chamberstick", "chamberstick", "a brass chamberstick", "A low brass candle holder has a finger loop, drip pan, and socket for carrying a short candle around a house.", SizeCategory.Small, ItemQuality.Standard, 440.0, 9.0m, "brass", householdTags, ["Holdable", "Destroyable_Misc"], "Early Modern lighting accessory; no light-source component is claimed.")
			]);
	}
}
