using MudSharp.Framework;
using MudSharp.GameItems;
using MudSharp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DatabaseSeeder.Seeders
{
    public partial class ItemSeeder
    {
        MudSharp.Models.GameItemProto? CreateItem(string stableReference,
                                                  string noun,
                                                  string sdesc,
                                                  string? ldesc,
                                                  string fdesc,
                                                  SizeCategory size,
                                                  ItemQuality quality,
                                                  double weightInGrams,
                                                  decimal inherentCost,
                                                  bool skinnable,
                                                  bool hideFromPlayers,
                                                  string material,
                                                  IEnumerable<string> tags,
                                                  IEnumerable<string> components,
                                                  string? morphToUniqueReference,
                                                  string? morphEmote,
                                                  TimeSpan? morphTimer,
                                                  string? destroyedItemUniqueReference)
        {
            if (_items.TryGetValue(stableReference, out var existing))
            {
                ApplyItemLifecycleSettings(existing, morphToUniqueReference, morphEmote, morphTimer, destroyedItemUniqueReference);
                return existing;
            }

            existing = _context!.GameItemProtos.Local
                .AsEnumerable()
                .FirstOrDefault(x => x.ShortDescription.Equals(sdesc, StringComparison.OrdinalIgnoreCase)) ??
                       _context.GameItemProtos.AsEnumerable()
                           .FirstOrDefault(x => x.ShortDescription.Equals(sdesc, StringComparison.OrdinalIgnoreCase));
            if (existing is not null)
            {
                _items[stableReference] = existing;
                _items[existing.ShortDescription] = existing;
                ApplyItemLifecycleSettings(existing, morphToUniqueReference, morphEmote, morphTimer, destroyedItemUniqueReference);
                return existing;
            }

            GameItemProto dbitem = new()
            {
                Id = _nextId++,
                Name = noun.ToLowerInvariant(),
                Keywords = new ExplodedString(sdesc.Strip_A_An()).Words.Distinct().ListToCommaSeparatedValues(" "),
                MaterialId = _materials[material].Id,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = _dbAccount.Id,
                    BuilderDate = _now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = _dbAccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = _now
                },
                RevisionNumber = 0,
                Size = (int)size,
                Weight = weightInGrams,
                ReadOnly = false,
                LongDescription = ldesc,
                BaseItemQuality = (int)quality,
                ShortDescription = sdesc,
                FullDescription = fdesc,
                PermitPlayerSkins = skinnable,
                CostInBaseCurrency = inherentCost,
                IsHiddenFromPlayers = hideFromPlayers,
                MorphTimeSeconds = 0,
                MorphEmote = "$0 $?1|morphs into $1|decays into nothing$.",
            };
            foreach (string item in tags)
            {
                if (string.IsNullOrEmpty(item))
                {
                    continue;
                }

                if (!_tagsByFullPath.ContainsKey(item))
                {
                    return null;
                }

                dbitem.GameItemProtosTags.Add(new GameItemProtosTags
                {
                    GameItemProto = dbitem,
                    TagId = _tagsByFullPath[item].Id
                });
            }

            foreach (string item in components)
            {
                if (string.IsNullOrEmpty(item))
                {
                    continue;
                }

                if (!_components.ContainsKey(item))
                {
                    return null;
                }

                dbitem.GameItemProtosGameItemComponentProtos.Add(new GameItemProtosGameItemComponentProtos
                {
                    GameItemProto = dbitem,
                    GameItemComponent = _components[item]
                });
            }

            _context!.GameItemProtos.Add(dbitem);
            _items[stableReference] = dbitem;
            _items[dbitem.ShortDescription] = dbitem;
            ApplyItemLifecycleSettings(dbitem, morphToUniqueReference, morphEmote, morphTimer, destroyedItemUniqueReference);
            return dbitem;
        }

        private void ApplyItemLifecycleSettings(GameItemProto item,
                                                string? morphToUniqueReference,
                                                string? morphEmote,
                                                TimeSpan? morphTimer,
                                                string? destroyedItemUniqueReference)
        {
            if (string.IsNullOrWhiteSpace(morphToUniqueReference) &&
                string.IsNullOrWhiteSpace(morphEmote) &&
                morphTimer is null &&
                string.IsNullOrWhiteSpace(destroyedItemUniqueReference))
            {
                return;
            }

            if (!string.IsNullOrWhiteSpace(morphToUniqueReference) &&
                _items.TryGetValue(morphToUniqueReference, out var morphItem))
            {
                item.MorphGameItemProtoId = morphItem.Id;
            }

            if (morphTimer is not null)
            {
                item.MorphTimeSeconds = (int)morphTimer.Value.TotalSeconds;
            }

            if (!string.IsNullOrWhiteSpace(morphEmote))
            {
                item.MorphEmote = morphEmote;
            }

            if (!string.IsNullOrWhiteSpace(destroyedItemUniqueReference) &&
                _items.TryGetValue(destroyedItemUniqueReference, out var destroyedItem))
            {
                item.OnDestroyedGameItemProtoId = destroyedItem.Id;
            }
        }

        
        public void SeedReworkItems()
        {
            if (_questionAnswers?.TryGetValue("eras", out var eras) != true ||
                string.IsNullOrWhiteSpace(eras))
            {
                return;
            }

            if (eras.Contains("antiquity", StringComparison.InvariantCultureIgnoreCase))
            {
                SeedAntiquityClothing();
                SeedAntiquityHouseholdCraftTools();
                SeedAntiquityWritingImplementsAndDocuments();
                SeedAntiquityMedicalItems();
                SeedAntiquityJewellery();
                SeedAntiquityArmour();
                SeedAntiquityContainers();
                SeedAntiquityDoorsAndLocks();
                SeedAntiquityRepairKits();
                SeedAntiquityHouseholdFurniture();
                SeedAntiquityWeaponsShieldsAccessories();
                SeedAntiquityApiaryItems();
                SeedAntiquityFoodAndBeverageItems();
            }

            if (eras.Contains("medieval", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (eras.Contains("renaissance", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (eras.Contains("earlymodern", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (eras.Contains("revolution", StringComparison.InvariantCultureIgnoreCase))
            {

            }

            if (eras.Contains("modern", StringComparison.InvariantCultureIgnoreCase))
            {

            }

			if (eras.Contains("atomic", StringComparison.InvariantCultureIgnoreCase))
			{

			}

			if (eras.Contains("computer", StringComparison.InvariantCultureIgnoreCase))
			{

			}
		}
    }
}
