#nullable enable

using System;
using System.Collections.Generic;
using MudSharp.GameItems;

namespace DatabaseSeeder.Seeders;

public partial class ItemSeeder
{
	// Gate 1 reuse identities. New admissions require a first-definition review, not a fallback to a supplement.
	private static readonly IReadOnlySet<string> ApprovedHistoricalClothingReuseReferences = new HashSet<string>(StringComparer.Ordinal)
	{
		"earlymodern_andeancolonial_clothing_wool_poncho",
		"earlymodern_colonial_clothing_full_cotton_skirt",
		"earlymodern_colonialnorthamerica_clothing_soft_moccasins",
		"earlymodern_dutch_clothing_wooden_clogs",
		"earlymodern_footwear_indianocean_ropesole_deckshoes",
		"earlymodern_footwear_northamerican_furlined_moccasinboots",
		"earlymodern_italian_clothing_striped_cotton_petticoat",
		"earlymodern_joseon_clothing_full_baji_trousers",
		"earlymodern_maghrebi_clothing_hooded_wool_djellaba",
		"earlymodern_maghrebi_clothing_short_fitted_caftan",
		"earlymodern_maghrebi_clothing_sleeveless_gandoura",
		"earlymodern_maritimeseasia_clothing_patterned_sarong",
		"earlymodern_noble_shared_silk_stockings",
		"earlymodern_qing_clothing_long_sidefastened_robe",
		"earlymodern_religious_daoist_cloud_shoes",
		"earlymodern_religious_hindu_sacred_thread",
		"earlymodern_religious_jain_mouthcloth",
		"earlymodern_religious_reformed_preaching_bands",
		"earlymodern_religious_sikh_chola",
		"earlymodern_religious_sikh_kachera",
		"earlymodern_religious_theravada_underrobe",
		"earlymodern_religious_theravada_upperrobe",
		"earlymodern_religious_tibetan_mantle",
		"earlymodern_religious_tibetan_shamtab",
		"earlymodern_religious_tibetan_vest",
		"earlymodern_religious_zoroastrian_kusti",
		"earlymodern_religious_zoroastrian_prayer_cap",
		"earlymodern_religious_zoroastrian_sudreh",
		"earlymodern_southasian_clothing_light_cotton_shawl",
		"earlymodern_western_military_canvas_gaiters",
		"medieval_cotton_sari",
		"medieval_daoist_cloud_sleeved_robe",
		"medieval_daoist_cross_collar_robe",
		"medieval_daoist_ritual_cap",
		"medieval_eastern_black_riassa",
		"medieval_eastern_epimanikia",
		"medieval_eastern_epitrachelion",
		"medieval_eastern_kamilavkion",
		"medieval_eastern_phelonion",
		"medieval_eastern_sticharion",
		"medieval_fine_silk_sari",
		"medieval_hindu_kaupina",
		"medieval_hindu_white_priest_dhoti",
		"medieval_islamic_plain_imam_qamis",
		"medieval_jain_white_ascetic_robe",
		"medieval_jain_white_shoulder_wrap",
		"medieval_jewish_skullcap",
		"medieval_jewish_tallit_gadol",
		"medieval_jewish_tallit_katan",
		"medieval_latin_amice",
		"medieval_latin_dalmatic_vestment",
		"medieval_latin_linen_cincture",
		"medieval_latin_maniple",
		"medieval_latin_stole",
		"medieval_leather_smith_apron",
		"medieval_linen_wimple",
		"medieval_shinto_miko_red_hakama",
		"medieval_shinto_miko_white_kosode",
		"medieval_shinto_priest_eboshi",
		"medieval_shinto_priest_hakama",
		"medieval_shinto_white_joe_robe",
		"medieval_short_cotton_bodice",
		"medieval_tablet_woven_garters",
		"preindustrial_clothing_plain_leather_belt",
		"preindustrial_clothing_simple_woven_sash",
		"renaissance_africancourt_broad_waistwrapper",
		"renaissance_africancourt_longsleeve_sideslit_tunic",
		"renaissance_frontier_split_skirt_riding_boots",
		"renaissance_institution_academic_robe",
		"renaissance_institution_academic_squarecap",
		"renaissance_institution_chasuble",
		"renaissance_institution_closed_monastic_sandals",
		"renaissance_institution_full_cowl",
		"renaissance_institution_linen_surplus",
		"renaissance_institution_liturgical_alb",
		"renaissance_institution_monastic_habit",
		"renaissance_institution_monastic_scapular",
		"renaissance_institution_plain_cassock",
		"renaissance_institution_processional_cope",
		"renaissance_japanese_full_pleated_hakama",
		"renaissance_japanese_short_openjacket",
		"renaissance_japanese_smallsleeve_wraprobe",
		"renaissance_japanese_splittoe_socks",
		"renaissance_japanese_tied_straw_travelsandals",
		"renaissance_japanese_unlined_summerrobe",
		"renaissance_japanese_wooden_clogs",
		"renaissance_mesoamerican_rectangular_blouse",
		"renaissance_ottoman_full_salwar_trousers",
		"renaissance_shared_clothing_breast_wrap",
		"renaissance_shared_clothing_cloth_headwrap",
		"renaissance_shared_clothing_drawstring_drawers",
		"renaissance_shared_clothing_face_veil",
		"renaissance_shared_clothing_footed_stockings",
		"renaissance_shared_clothing_footwraps",
		"renaissance_shared_clothing_fur_lined_coat",
		"renaissance_shared_clothing_gathered_skirt",
		"renaissance_shared_clothing_leather_gloves",
		"renaissance_shared_clothing_leather_sandals",
		"renaissance_shared_clothing_long_head_veil",
		"renaissance_shared_clothing_long_undershirt",
		"renaissance_shared_clothing_mittens",
		"renaissance_shared_clothing_neck_kerchief",
		"renaissance_shared_clothing_rectangular_mantle",
		"renaissance_shared_clothing_short_head_veil",
		"renaissance_shared_clothing_short_undershirt",
		"renaissance_shared_clothing_shoulder_shawl",
		"renaissance_shared_clothing_soft_slippers",
		"renaissance_shared_clothing_straight_underrobe",
		"renaissance_shared_clothing_textile_sandals",
		"renaissance_southasian_bunched_ankletrousers",
		"renaissance_southasian_flat_wound_turban",
		"renaissance_southasian_long_sideslit_tunic",
		"renaissance_southasian_toepost_woodensandals",
	};

	// Original primary definitions shared by their historical modules and later-era reuse.
	// Moving these records does not approve their prose, fixed colours or wear profiles for the later wardrobe.
	private static readonly HistoricalClothingItemSpec[] HistoricalClothingPrimaryItems =
	[
		new("medieval_jewish_tallit_gadol",
			"tallit",
			"a $colour1 wool tallit gadol",
			null,
			"A broad rectangle of $colour1 wool forms this tallit, with narrow $colour2 stripes woven across its ends. The light cloth gathers into soft folds without losing the straight line of its edges. Long, knotted fringes hang separately from the four corners. Shorter threads finish the ends, leaving the long sides plain and the striped bands clearly visible.",
			SizeCategory.Normal,
			ItemQuality.Good,
			420.0,
			40.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_2Colour",
				"Wear_Mantle",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_HeavyClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_jewish_tallit_katan",
			"tallit",
			"a $colour wool tallit katan",
			null,
			"Two straight panels of $colour wool hang from the shoulders of this small tallit. A simple opening at the centre admits the head, while the open sides leave four distinct corners. Each corner carries a long knotted fringe below the neatly finished edge. The lightly woven body is otherwise plain, with little bulk to interrupt the fall of another garment over it.",
			SizeCategory.Small,
			ItemQuality.Standard,
			230.0,
			22.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Vest",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_jewish_skullcap",
			"skullcap",
			"a $colour wool skullcap",
			null,
			"Shallow seams divide the $colour wool of this skullcap into curved panels. They meet at the crown and spread towards a narrow, evenly finished rim. The soft fabric forms a close, rounded cup with no brim or hanging flap. Small stitches secure the turned edge, leaving the outside untrimmed and the wool's fine nap visible between the seams.",
			SizeCategory.Small,
			ItemQuality.Standard,
			60.0,
			6.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Headwear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Skullcap",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_islamic_plain_imam_qamis",
			"qamis",
			"a plain $colour cotton qamis",
			null,
			"This qamis has a long, straight body cut from light $colour cotton. Its sleeves follow the arms without the deep hanging folds of a wide-sleeved robe. The front is unornamented, and narrow seams join the cloth with little raised bulk. An even hem finishes the lower edge, beneath broad panels whose close weave remains opaque despite their lightness.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			420.0,
			18.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_hindu_white_priest_dhoti",
			"dhoti",
			"a $colour cotton dhoti",
			null,
			"A long rectangle of $colour cotton forms this dhoti, with firm edges and a narrow finished hem at either end. The cloth is light enough to gather into closely stacked folds. Its length allows a section to pass between the legs while the remaining breadth forms the lower drape. There are no sewn leg tubes, buttons or fitted waistband to interrupt the continuous fabric.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			360.0,
			16.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Loincloth",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_tablet_woven_garters",
			"garters",
			"a pair of $colour tablet-woven garters",
			null,
			"These $colour tablet-woven garters are narrow wool bands with a firm, patterned structure. Each strip is long enough to wrap neatly around the leg, with cleanly finished ends that can lie flat against hose or chausses. The $colour tone shows best across the raised weave and makes them more refined than plain work ties.",
			SizeCategory.Small,
			ItemQuality.Good,
			60.0,
			16.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Legwear"
			],
			[
				"Holdable",
				"Wear_Garters_Layer_0_1",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_latin_amice",
			"amice",
			"a $colour linen amice",
			null,
			"This amice is a broad rectangle of smooth $colour linen, sized to fold around the neck and shoulders. Fine stitches hold its narrow turned hems flat against the cloth. Slender ties extend from the corners, providing the only fastenings. The middle is left unembroidered, so the fine weave and overlapping folds remain the most visible details.",
			SizeCategory.Small,
			ItemQuality.Standard,
			120.0,
			10.0m,
			true,
			false,
			"linen",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Scarf",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_latin_linen_cincture",
			"cincture",
			"a $colour linen cincture",
			null,
			"Several strands of $colour linen are worked together into this narrow cincture. The braided surface is firm along its length but supple enough to bend into a close knot. Simple finished ends hang below the tied portion without metal tips or separate fittings. Its even width and shallow ridges give the cord a distinct texture against a smooth robe.",
			SizeCategory.Small,
			ItemQuality.Standard,
			80.0,
			6.0m,
			true,
			false,
			"linen",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Belts"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Waist_Layer_0_1",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_latin_maniple",
			"maniple",
			"a $colour silk maniple",
			null,
			"This $colour silk maniple is a short band of fine cloth made to hang from the forearm. The silk is light and smooth, with the $colour shade most visible across the folded central panel. Its ends are carefully squared, giving the small vestment a deliberate and formal outline.",
			SizeCategory.Small,
			ItemQuality.Good,
			60.0,
			30.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Bracer",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_latin_dalmatic_vestment",
			"dalmatic",
			"a fine $colour silk dalmatic",
			null,
			"This fine $colour silk dalmatic is a loose, straight vestment with broad sleeves and a squared body. The $colour silk hangs smoothly from the shoulders, leaving the sleeve openings wide and visible. Its formal cut gives it a robe-like dignity while keeping the shape distinct from a closed cloak or mantle.",
			SizeCategory.Normal,
			ItemQuality.Good,
			650.0,
			140.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_linen_wimple",
			"wimple",
			"a $colour linen wimple",
			null,
			"This $colour linen wimple is a linen head and neck covering shaped by smooth folds around the throat and lower face. The fabric is light but close, leaving the outer edge neat enough to sit under a veil or hood. The $colour dye is simple and even, showing most clearly across the broad panels and worn edges.",
			SizeCategory.Small,
			ItemQuality.Standard,
			160.0,
			9.0m,
			true,
			false,
			"linen",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Headwear"
			],
			[
				"Holdable",
				"Wear_Veil",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing",
				"Variable_BasicColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_sticharion",
			"sticharion",
			"a $colour linen sticharion",
			null,
			"Long panels of $colour linen give this sticharion a straight, nearly floor-length fall. Close sleeves extend from a simply finished shoulder line. Fine, even seams lie flat against the cloth rather than forming raised decorative bands. The lower hem is carefully turned, and the lightly creased linen shows an unbroken surface without embroidery or contrasting trim.",
			SizeCategory.Normal,
			ItemQuality.Good,
			480.0,
			40.0m,
			true,
			false,
			"linen",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe_Layer_0_5_NonBulky",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_epitrachelion",
			"epitrachelion",
			"a $colour silk epitrachelion",
			null,
			"This $colour silk epitrachelion is a paired stole joined at the neck and falling in two long panels down the front. The $colour silk has a formal sheen, broken by the fold where the fabric sits around the collar. Its length, symmetry, and careful edging make it distinct from an ordinary scarf.",
			SizeCategory.Small,
			ItemQuality.Good,
			190.0,
			70.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Scarf",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_epimanikia",
			"epimanikia",
			"a pair of $colour silk epimanikia",
			null,
			"These $colour silk epimanikia are fitted cuffs made to wrap around the lower sleeves. The silk panels are small but carefully shaped, with ties or narrow bands visible at the inner wrist. Their $colour surface gives a bright, formal finish to the hands and forearms.",
			SizeCategory.Small,
			ItemQuality.Good,
			80.0,
			50.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Gloves"
			],
			[
				"Holdable",
				"Wear_Bracers",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_phelonion",
			"phelonion",
			"a fine $colour silk phelonion",
			null,
			"This fine $colour silk phelonion is a wide sleeveless outer vestment with a rounded fall from the shoulders. The front is cut to clear the hands while the back drops in a fuller sweep, showing the $colour silk in deep folds. Its form resembles a ceremonial mantle, but the head opening and continuous body give it a distinctive liturgical shape.",
			SizeCategory.Normal,
			ItemQuality.Good,
			780.0,
			170.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Poncho",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_black_riassa",
			"riassa",
			"a $colour wool riassa",
			null,
			"This riassa is cut from ample lengths of $colour wool, with a loose body and broad sleeves. The cloth falls in long folds from the shoulders to the lower hem. Plain seams and narrow edge finishing leave the wool's soft, matte surface exposed. Neither the sleeve ends nor the front edges carry contrasting braid, making the broad outline of the robe its principal feature.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			850.0,
			30.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_eastern_kamilavkion",
			"kamilavkion",
			"a $colour felt kamilavkion",
			null,
			"Dense $colour felt gives this kamilavkion its stiff cylindrical shape. Straight sides rise from the lower rim to a flat, neatly bounded crown. The surface is matte and closely packed, with little loose fibre projecting from it. A plain finished edge runs around the opening, and there is no brim, tassel or attached veil to break the upright outline.",
			SizeCategory.Small,
			ItemQuality.Standard,
			170.0,
			20.0m,
			true,
			false,
			"felt",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Headwear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Hat",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_hindu_kaupina",
			"kaupina",
			"a plain $colour cotton kaupina",
			null,
			"This kaupina consists of a narrow length of light $colour cotton. Its centre broadens enough to form a small covering panel, while the remaining cloth folds into a compact loincloth. Fine hems finish the exposed edges without adding bulky reinforcement. There is no embroidery or contrasting border, and the plain weave is visible across the unbroken centre.",
			SizeCategory.Small,
			ItemQuality.Standard,
			90.0,
			4.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Loincloth",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_jain_white_ascetic_robe",
			"robe",
			"a plain $colour cotton robe",
			null,
			"Light $colour cotton forms the broad, loosely wrapped body of this robe. The fabric falls in long folds rather than following a fitted waist. Narrow hems secure the edges, and the exposed cloth has a plain, close weave without embroidery. Its simple construction leaves the overlap and drape visible without added braid, metallic trim or a contrasting border.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			420.0,
			16.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_jain_white_shoulder_wrap",
			"wrap",
			"a $colour cotton shoulder wrap",
			null,
			"This shoulder wrap is a light rectangle of $colour cotton, broad through the middle and straight along its sides. Narrow hems enclose the cut edges with small, even stitches. The plain weave remains visible across the undecorated surface. Its soft folds gather readily over the shoulders, with no sleeves, clasps or fitted collar to hold a prescribed shape.",
			SizeCategory.Small,
			ItemQuality.Standard,
			160.0,
			8.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Mantle",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_HeavyClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_daoist_cross_collar_robe",
			"robe",
			"a $colour cross-collared cotton robe",
			null,
			"The front panels of this $colour cotton robe overlap beneath a long cross-collar. Ties hold the wrapped closure against a straight, loosely cut body. Long sleeves retain a plain outline, without the broad extensions of a cloud-sleeved overrobe. The cotton is smooth and closely woven, and narrow seams and hems provide its only visible finishing.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			520.0,
			24.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe_Layer_0_5_NonBulky",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_daoist_cloud_sleeved_robe",
			"robe",
			"a fine $colour cloud-sleeved robe",
			null,
			"This fine $colour cloud-sleeved robe is a silk ritual garment with broad sleeves and a loose cross-collar body. The sleeves spread widely from the arm, making the $colour silk fall in soft ceremonial folds. Its shape is more expansive than an ordinary robe, giving the garment a deliberate temple-formal presence.",
			SizeCategory.Normal,
			ItemQuality.Good,
			680.0,
			130.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_daoist_ritual_cap",
			"cap",
			"a $colour cloth ritual cap",
			null,
			"Stiffened panels of $colour cotton give this cap a compact, angular outline. Small seams join the panels without rounding away their distinct edges. The lower opening is neatly finished and sits beneath a crown that holds its shape without a projecting brim. Its surface is plain, with the close weave and slight changes of plane visible instead of embroidered ornament.",
			SizeCategory.Small,
			ItemQuality.Standard,
			90.0,
			12.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Headwear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Hat",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_shinto_white_joe_robe",
			"jōe",
			"a $colour hemp jōe robe",
			null,
			"Broad sleeves spread from the straight body of this $colour hemp jōe. The crisp cloth holds distinct folds along the shoulders and the wrapped front. Carefully finished edges follow the collar, sleeve openings and lower hem without contrasting decoration. The hemp's fine, slightly uneven fibres remain visible across the otherwise plain surface.",
			SizeCategory.Normal,
			ItemQuality.Good,
			520.0,
			42.0m,
			true,
			false,
			"hemp",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_shinto_priest_hakama",
			"hakama",
			"a pair of $colour hemp hakama",
			null,
			"These hakama have broad legs cut from crisp $colour hemp, with deep pleats descending from the waist. The folds give them a full, almost skirt-like outline while retaining separate leg openings. Long cloth ties extend from the upper edge to secure the garment. Evenly turned hems finish the broad lower openings, and the fabric carries no applied embroidery or contrasting trim.",
			SizeCategory.Normal,
			ItemQuality.Good,
			480.0,
			34.0m,
			true,
			false,
			"hemp",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Legwear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Trousers",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_shinto_priest_eboshi",
			"eboshi",
			"a $colour lacquered eboshi",
			null,
			"This tall headpiece has a folded silk body stiffened beneath a smooth $colour lacquer surface. Its narrow crown rises upright above a close-fitting lower band, with crisp changes of angle along the folded sides. The coating follows the underlying creases without hiding their sharp outline. A fine seam runs down the back, and the plain outer faces catch small highlights along their raised edges.",
			SizeCategory.Small,
			ItemQuality.Good,
			110.0,
			38.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Headwear"
			],
			[
				"Holdable",
				"Wear_Hat",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing",
				"Variable_LacquerColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_shinto_miko_white_kosode",
			"kosode",
			"a $colour hemp kosode",
			null,
			"This $colour hemp kosode has a straight body and a neatly overlapping front. Its sleeves end in small openings, leaving the surrounding cloth to gather in shallow folds. Narrow seams join the panels, and a continuous collar band follows the wrapped neckline. The hemp is plain and carefully finished, without an attached sash or a contrasting embroidered border.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			420.0,
			24.0m,
			true,
			false,
			"hemp",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_shinto_miko_red_hakama",
			"hakama",
			"a pair of pleated $colour hemp hakama",
			null,
			"Long pleats shape the $colour hemp of these broad-legged hakama. They open below the waist into generous folds while the separate legs retain wide, evenly hemmed openings. Cloth ties extend from the upper edge for wrapping and fastening. The panels are undecorated, leaving the crisp fold lines and the slight texture of the hemp visible across their breadth.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			460.0,
			28.0m,
			true,
			false,
			"hemp",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Legwear"
			],
			[
				"Holdable",
				"Variable_Colour",
				"Wear_Trousers",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing"
			],
			null,
			null,
			null,
			null),
		new("medieval_leather_smith_apron",
			"apron",
			"a $colour leather smith's apron",
			null,
			"This apron has a broad chest panel and a long lower fall cut from substantial $colour leather. The hide's grain is visible across its unadorned surface, with shallow folds where the thick panel bends. A sturdy neck loop supports the upper edge, and narrower leather straps extend from the sides to tie behind the waist. Small reinforced joins secure the straps, while the cut edges are rounded and smoothed.",
			SizeCategory.Small,
			ItemQuality.Standard,
			650.0,
			28.0m,
			true,
			false,
			"leather",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Apron",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing",
				"Variable_LeatherColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_cotton_sari",
			"sari",
			"a $colour cotton sari",
			null,
			"This $colour cotton sari is a long wrapped garment with enough length to form both lower drape and upper fold. The cloth relies on pleating, tucking, and wrapping rather than seams, leaving the edge visible along the fall. The $colour dye is simple and even, showing most clearly across the broad panels and worn edges.",
			SizeCategory.Normal,
			ItemQuality.Standard,
			520.0,
			18.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_BasicColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_fine_silk_sari",
			"sari",
			"a fine $colour silk sari",
			null,
			"This fine $colour silk sari is a long wrapped garment with enough length to form both lower drape and upper fold. The cloth relies on pleating, tucking, and wrapping rather than seams, leaving the edge visible along the fall. The $colour dye reads cleanly across the cloth, with richer depth where the folds overlap and catch shadow.",
			SizeCategory.Normal,
			ItemQuality.Good,
			420.0,
			140.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Robe",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_short_cotton_bodice",
			"bodice",
			"a short $colour cotton bodice",
			null,
			"This short $colour cotton bodice is a short fitted upper-body garment with a close waist, shaped sides, and narrow shoulder coverage. It is meant to sit with a wrapped lower cloth or skirt, keeping the torso neat without heavy layering. The $colour dye is simple and even, showing most clearly across the broad panels and worn edges.",
			SizeCategory.Small,
			ItemQuality.Standard,
			180.0,
			10.0m,
			true,
			false,
			"cotton",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Shirt",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing",
				"Variable_BasicColour"
			],
			null,
			null,
			null,
			null),
		new("medieval_latin_stole",
			"stole",
			"a $colour silk stole",
			null,
			"This $colour silk stole is a long, narrow band of cloth with neatly weighted ends and a smooth lustre. The silk catches light along its length, making the $colour tone appear richer where the fabric bends. Its construction is formal and restrained, with straight edges and a clearly ceremonial fall.",
			SizeCategory.Small,
			ItemQuality.Good,
			110.0,
			50.0m,
			true,
			false,
			"silk",
			[
				"Market / Clothing / Luxury Clothing",
				"Functions / Worn Items / Bodywear"
			],
			[
				"Holdable",
				"Wear_Scarf",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_FineColour"
			],
			null,
			null,
			null,
			null),
		new("preindustrial_clothing_plain_leather_belt",
			"belt",
			"a plain $colour leather belt",
			null,
			"A long strip of $colour leather forms this plain belt, its straight edges rounded and smoothly burnished. The grain of the hide remains visible between faint lengthwise creases. One end passes through a simple metal buckle, with a row of small holes along the other end for adjustment. A close-fitting keeper holds the loose tail against the strap, leaving the broad outer surface free of tooling or stitched decoration.",
			SizeCategory.Small,
			ItemQuality.Standard,
			180.0,
			10.0m,
			true,
			false,
			"leather",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Belts"
			],
			[
				"Holdable",
				"Wear_Waist",
				"Destroyable_Clothing",
				"Insulation_Minor",
				"Armour_LightClothing",
				"Belt_2",
				"Variable_LeatherColour"
			],
			null,
			null,
			null,
			null) { LegacyAliasReference = "medieval_plain_leather_belt" },
		new("preindustrial_clothing_simple_woven_sash",
			"sash",
			"a $colour woven sash",
			null,
			"This $colour woven sash is a long wool band with firm selvages and simple squared ends. It is made to wrap, knot, or girdle clothing without adding a hard buckle or metal fitting. The $colour dye is simple and even, showing most clearly across the broad panels and worn edges.",
			SizeCategory.Small,
			ItemQuality.Standard,
			120.0,
			6.0m,
			true,
			false,
			"wool",
			[
				"Market / Clothing / Standard Clothing",
				"Functions / Worn Items / Belts"
			],
			[
				"Holdable",
				"Wear_Sash",
				"Destroyable_Clothing",
				"Insulation_Moderate",
				"Armour_LightClothing",
				"Variable_BasicColour",
				"Belt_6"
			],
			null,
			null,
			null,
			null) { LegacyAliasReference = "medieval_simple_woven_sash" },
	];
}
