#nullable enable

using MudSharp.GameItems;

namespace DatabaseSeeder.Seeders;

public partial class ItemSeeder
{
	private void SeedEarlyModernScienceNavigationOpticsAndMeasurement()
	{
		var instrumentTags = new[] { "Era / Early Modern Era", "Market / Household Goods / Standard Wares" };
		var furnitureTags = new[] { "Era / Early Modern Era", "Market / Household Goods / Standard Furniture" };
		SeedStraightforwardEraCatalogueItems(
			"Early Modern science, navigation, optics, and measurement catalogue",
			[
				new("earlymodern_science_compound_microscope", "microscope", "a brass compound microscope", "A brass tube sits above a small stage and mirror in a compact instrument for close visual examination.", SizeCategory.Small, ItemQuality.Good, 1150.0, 96.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern optical instrument; no magnification mechanic is claimed."),
				new("earlymodern_science_lens_case", "case", "a leather lens case", "A padded leather case has divided spaces for small optical lenses and careful workshop transport.", SizeCategory.Small, ItemQuality.Good, 480.0, 18.0m, "leather", instrumentTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern optical-workshop storage."),
				new("earlymodern_science_glass_lens_blank", "blank", "a ground glass lens blank", "A round clear glass blank has a rough ground edge ready for polishing into a small optical lens.", SizeCategory.Small, ItemQuality.Standard, 140.0, 9.0m, "glass blank", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern optics stock."),
				new("earlymodern_science_mercury_barometer", "barometer", "a mercury barometer", "A tall glass tube and cistern are mounted in a narrow wooden frame with a simple marked scale.", SizeCategory.Normal, ItemQuality.Good, 2200.0, 120.0m, "glass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern pressure instrument; no pressure-reading mechanic is claimed."),
				new("earlymodern_science_spirit_thermometer", "thermometer", "a spirit thermometer", "A fine glass tube and coloured liquid are fixed to a small marked board for comparative temperature observation.", SizeCategory.Small, ItemQuality.Good, 380.0, 68.0m, "glass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern temperature instrument; no temperature-reading mechanic is claimed."),
				new("earlymodern_science_pocket_watch", "watch", "a brass pocket watch", "A round brass watch case has a glass face, hands, and a winding stem attached to a short chain.", SizeCategory.Small, ItemQuality.Good, 260.0, 150.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern watch form; no runtime timekeeping component is claimed."),
				new("earlymodern_science_backstaff", "backstaff", "a wooden backstaff", "A graduated wooden backstaff has a sliding vane and shaded sight for taking a sun observation without looking directly at it.", SizeCategory.Normal, ItemQuality.Good, 820.0, 46.0m, "oak", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern navigation instrument; no automatic observation mechanic is implied."),
				new("earlymodern_science_octant", "octant", "a brass reflecting octant", "A framed brass arc has mirrors, a sight, and a marked limb for late-period angular observation.", SizeCategory.Small, ItemQuality.Good, 1150.0, 110.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Late Early Modern navigation instrument; date admission belongs to world content."),
				new("earlymodern_science_parallel_rules", "rules", "a pair of parallel rules", "Two linked brass rules slide evenly across a chart for plotting parallel courses and measured lines.", SizeCategory.Small, ItemQuality.Good, 230.0, 22.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern chart-working tool; no route calculation is implied."),
				new("earlymodern_science_protractor", "protractor", "a brass protractor", "A semicircular brass protractor is engraved with a simple angular scale for charts and workshop drawings.", SizeCategory.Small, ItemQuality.Standard, 150.0, 12.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern drawing and survey tool."),
				new("earlymodern_science_weight_set", "weights", "a nested brass weight set", "A fitted wooden box holds a graduated nest of brass weights for balances and merchant measures.", SizeCategory.Small, ItemQuality.Good, 1700.0, 45.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern balance accessory; no automatic measurement mechanic is implied."),
				new("earlymodern_science_celestial_globe", "globe", "a small celestial globe", "A painted globe is set within a brass meridian ring and wooden horizon stand for astronomical display.", SizeCategory.Normal, ItemQuality.Good, 3800.0, 140.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Early Modern astronomical display; no observation mechanic is implied."),
				new("earlymodern_science_orrery", "orrery", "a small brass orrery", "A compact brass gearwork carries small spheres on arms around a central body as a late-period astronomical demonstration.", SizeCategory.Normal, ItemQuality.Good, 5600.0, 260.0m, "brass", instrumentTags, ["Holdable", "Destroyable_Misc"], "Late Early Modern astronomical display; date admission belongs to world content."),
				new("earlymodern_science_herbarium_folder", "folder", "a pressed-plant herbarium folder", "A stiff paper folder holds leaves and small plant specimens between labelled sheets for study and comparison.", SizeCategory.Small, ItemQuality.Standard, 420.0, 14.0m, "paper", instrumentTags, ["Holdable", "Destroyable_Misc", "Container_Document_Pouch"], "Early Modern natural-history storage; labels remain builder-authored."),
				new("earlymodern_science_mineral_specimen_box", "box", "a divided mineral specimen box", "A shallow oak box has padded divisions for labelled stones, ores, and small mineral samples.", SizeCategory.Small, ItemQuality.Good, 1450.0, 36.0m, "oak", instrumentTags, ["Holdable", "Destroyable_Misc", "Container_PreIndustrial_CompartmentBox"], "Early Modern natural-history storage."),
				new("earlymodern_science_insect_case", "case", "a glazed insect case", "A small glazed case has a lined back for pinned insect specimens and handwritten labels.", SizeCategory.Small, ItemQuality.Good, 780.0, 30.0m, "oak", instrumentTags, ["Holdable", "Destroyable_Misc", "Container_Glass_Casket"], "Early Modern natural-history display case."),
				new("earlymodern_science_sample_vial", "vial", "a stoppered sample vial", "A small clear glass vial has a ground stopper for dry specimens, powders, or a small liquid sample.", SizeCategory.Small, ItemQuality.Standard, 120.0, 5.0m, "glass", instrumentTags, ["Holdable", "Destroyable_Misc", "LContainer_Medicine_Vial_30ml"], "Early Modern sample vessel; accepts live liquids."),
				new("earlymodern_science_laboratory_retort", "retort", "a glass laboratory retort", "A round glass body tapers into a long downward neck for visible distillation demonstrations and workshop work.", SizeCategory.Normal, ItemQuality.Good, 1100.0, 48.0m, "glass", instrumentTags, ["Holdable", "Destroyable_Misc", "LContainer_PreIndustrial_Pot_12L"], "Early Modern laboratory glass; distillation behaviour is not implied."),
				new("earlymodern_science_specimen_cabinet", "cabinet", "a natural-history specimen cabinet", "A tall oak cabinet has shallow labelled drawers for shells, mineral samples, dried plants, and other collections.", SizeCategory.Large, ItemQuality.Good, 62000.0, 320.0m, "oak", furnitureTags, ["Destroyable_Furniture", "Container_Dresser"], "Early Modern collection furniture; intentionally not holdable."),
				new("earlymodern_science_instrument_stand", "stand", "a brass instrument stand", "A three-legged brass stand supports a portable instrument at a stable working height in an observatory or survey room.", SizeCategory.Large, ItemQuality.Standard, 9800.0, 74.0m, "brass", furnitureTags, ["Destroyable_Furniture"], "Early Modern instrument support; mounting mechanics are not implied.")
			]);
	}
}
