#nullable enable

using MudSharp.GameItems;
using System;

namespace DatabaseSeeder.Seeders;

public partial class ItemSeeder
{
	// Previous source-shape audit marker retained until the medieval no-op audit is retired:
	// private void SeedMedievalComponentGapItems() { }
	private void SeedMedievalComponentGapItems()
	{
		(string StableReference, string Noun, string Sdesc, string Fdesc, SizeCategory Size, ItemQuality Quality, double Weight, decimal Cost, string Material, string[] Tags, string[] Components)[] items =
		[
			("medieval_industry_stock_plank_bundle", "bundle", "a bundle of worked planks", "This cord-tied bundle holds straight worked planks with squared edges and saw marks, ready for chests, doors, shelves, shields, or furniture frames.", SizeCategory.Large, ItemQuality.Standard, 12000.0, 24.0m, "oak", [ "Market / Raw Materials", "Market / Construction Materials", "Functions / Material Functions / Household Craft Stock / Furniture Timber Stock" ], [ "Holdable", "Destroyable_Furniture" ]),
			("medieval_industry_stock_timber_beam", "beam", "a squared timber beam", "This heavy timber beam has been hewn and roughly squared for furniture, doors, frames, presses, or workshop apparatus.", SizeCategory.Large, ItemQuality.Standard, 18000.0, 30.0m, "oak", [ "Market / Raw Materials", "Market / Construction Materials", "Functions / Material Functions / Household Craft Stock / Furniture Timber Stock" ], [ "Holdable", "Destroyable_Furniture" ]),
			("medieval_industry_stock_shaft_blanks", "bundle", "a bundle of shaft blanks", "These long ash blanks have been split, shaved, and roughly straightened for tool handles, arrows, spears, poles, or furniture pegs.", SizeCategory.Normal, ItemQuality.Standard, 3200.0, 18.0m, "ash", [ "Market / Raw Materials", "Functions / Material Functions / Antiquity Equipment Stock / Weapon Shaft Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_bow_stave", "stave", "a seasoned bow stave", "This long ash stave has been split and seasoned until the grain runs cleanly along its length, ready for bowyer work.", SizeCategory.Large, ItemQuality.Good, 1100.0, 42.0m, "ash", [ "Market / Raw Materials", "Functions / Material Functions / Antiquity Equipment Stock / Bow Stave" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_shield_board", "board", "a shield-board blank", "This joined wooden board is roughly shaped for a shield face, with the central boss space still uncut and the surface unfinished.", SizeCategory.Normal, ItemQuality.Standard, 3600.0, 28.0m, "oak", [ "Market / Raw Materials", "Functions / Material Functions / Antiquity Equipment Stock / Shield Board Stock" ], [ "Holdable", "Destroyable_Furniture" ]),
			("medieval_industry_stock_handle_blanks", "bundle", "a bundle of handle blanks", "Short pieces of ash and beech have been squared and shaved into rough handle blanks for knives, files, chisels, hammers, and small tools.", SizeCategory.Small, ItemQuality.Standard, 900.0, 10.0m, "ash", [ "Market / Raw Materials", "Functions / Material Functions / Household Craft Stock / Carved Wood Stock" ], [ "Holdable", "Destroyable_Misc" ]),

			("medieval_industry_stock_yarn_skein", "skein", "a skein of spun yarn", "This skein of clean spun yarn is looped and tied so it can be dyed, traded, or wound for weaving.", SizeCategory.Small, ItemQuality.Standard, 250.0, 8.0m, "wool", [ "Market / Raw Materials / Cloth", "Functions / Material Functions / Textile Commodity / Spun Yarn" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_sewing_thread", "spool", "a spool of sewing thread", "This small spool carries tightly wound linen thread for garments, books, pouches, and light leather work.", SizeCategory.VerySmall, ItemQuality.Standard, 60.0, 5.0m, "linen", [ "Market / Raw Materials / Cloth", "Functions / Material Functions / Textile Commodity / Spun Yarn" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_cord_bundle", "bundle", "a bundle of twisted cord", "Several lengths of twisted hemp cord are looped and tied for lacing, binding, scrolls, stitching heavy goods, or small fittings.", SizeCategory.Small, ItemQuality.Standard, 420.0, 8.0m, "hemp", [ "Market / Raw Materials", "Functions / Material Functions / String" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_rope_coil", "coil", "a coil of hemp rope", "This coil of hemp rope is laid in firm turns and bound through the middle for hauling, tying loads, binding frames, or workshop rigging.", SizeCategory.Normal, ItemQuality.Standard, 2800.0, 24.0m, "hemp", [ "Market / Raw Materials", "Functions / Material Functions / String" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_plain_cloth_bolt", "bolt", "a bolt of plain wool cloth", "This bolt of plain wool cloth is tightly rolled and undyed, suitable for garments, bags, padding, coverings, or later dyeing.", SizeCategory.Normal, ItemQuality.Standard, 4200.0, 60.0m, "wool", [ "Market / Raw Materials / Cloth", "Functions / Material Functions / Textile Commodity / Garment Cloth / Woven Cloth" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_canvas_bolt", "bolt", "a bolt of heavy canvas", "This roll of heavy canvas is woven from coarse fibre and folded tight for sacks, covers, pads, tents, and tool rolls.", SizeCategory.Normal, ItemQuality.Standard, 5200.0, 48.0m, "canvas", [ "Market / Raw Materials / Cloth", "Functions / Material Functions / Textile Commodity / Garment Cloth / Woven Cloth" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_felt_sheet", "sheet", "a sheet of pressed felt", "This sheet of felt is dense, springy, and slightly uneven at the edges, ready for caps, padding, footwear, saddle liners, filters, or warm household stock.", SizeCategory.Normal, ItemQuality.Standard, 900.0, 18.0m, "felt", [ "Market / Raw Materials / Cloth", "Functions / Material Functions / Textile Commodity / Prepared Textile Fibre" ], [ "Holdable", "Destroyable_Clothing" ]),

			("medieval_industry_stock_leather_panel", "panel", "a tanned leather panel", "This panel of tanned leather has been scraped, softened, and squared for cutting into bags, belts, shoes, covers, armour pieces, or repairs.", SizeCategory.Normal, ItemQuality.Standard, 1200.0, 34.0m, "leather", [ "Market / Raw Materials", "Functions / Material Functions / Leather Commodity / Leather Panel" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_hardened_leather_panel", "panel", "a hardened leather panel", "This dark hardened leather panel has been shaped and stiffened so it keeps a shallow curve for armour plates, cases, splints, and reinforced covers.", SizeCategory.Normal, ItemQuality.Good, 1400.0, 48.0m, "leather", [ "Market / Repair Supplies / Weapon and Armour Repair Supplies", "Functions / Material Functions / Leather Commodity / Hardened Leather Panel" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_leather_strap_bundle", "bundle", "a bundle of leather straps", "These cut leather straps are bundled by length and ready for buckles, hinges, packs, quivers, harness, shields, book clasps, and repairs.", SizeCategory.Small, ItemQuality.Standard, 500.0, 16.0m, "leather", [ "Market / Repair Supplies / General Repair Supplies", "Functions / Material Functions / Leather Commodity / Leather Strap" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_leather_thong_bundle", "bundle", "a bundle of leather thongs", "A tight bundle of narrow leather thongs is looped and tied for lacing, binding, armour scales, shoes, pouches, parchment frames, and repairs.", SizeCategory.VerySmall, ItemQuality.Standard, 220.0, 9.0m, "leather", [ "Market / Repair Supplies / General Repair Supplies", "Functions / Material Functions / Leather Commodity / Leather Thong" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_rawhide_cord_bundle", "bundle", "a bundle of rawhide cord", "This stiff bundle of rawhide cord is dried and twisted for shields, drums, tack, bindings, and heavy repairs.", SizeCategory.Small, ItemQuality.Standard, 350.0, 12.0m, "rawhide", [ "Market / Raw Materials", "Functions / Material Functions / Leather Commodity / Rawhide Cord" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_parchment_sheet", "sheet", "a prepared parchment sheet", "This pale parchment sheet has been scraped, stretched, and rubbed smooth enough to take ruling or ink.", SizeCategory.Small, ItemQuality.Standard, 28.0, 18.0m, "parchment", [ "Market / Writing Materials / Parchment", "Functions / Material Functions / Writing Craft Stock / Parchment Sheet Stock" ], [ "Holdable", "Destroyable_Paper" ]),
			("medieval_industry_stock_rag_paper_sheet", "sheet", "a rag-paper sheet", "This rag-paper sheet is soft, pale, lightly sized, and ready for letters, quires, patterns, or administrative work.", SizeCategory.Small, ItemQuality.Standard, 12.0, 8.0m, "paper", [ "Market / Writing Materials / Paper", "Functions / Writing Goods" ], [ "Holdable", "Destroyable_Paper" ]),
			("medieval_industry_stock_book_board_pair", "boards", "a pair of book boards", "These two thin wooden boards have been cut and smoothed to match as book covers, ready for drilling, covering, or lacing.", SizeCategory.Small, ItemQuality.Standard, 420.0, 12.0m, "beech", [ "Market / Writing Materials / Codices", "Functions / Material Functions / Writing Craft Stock / Bookbinding Stock" ], [ "Holdable", "Destroyable_Misc" ]),

			("medieval_industry_stock_iron_bar", "bar", "a wrought-iron bar", "This wrought-iron bar is straight, dark, and squared enough for forging into tools, fittings, nails, hinges, locks, or weapon stock.", SizeCategory.Normal, ItemQuality.Standard, 2400.0, 36.0m, "wrought iron", [ "Market / Raw Materials", "Functions / Material Functions / Primary Production / Primary Production Commodity / Metal Bar Stock Commodity" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_bronze_bar", "bar", "a bronze casting bar", "This bronze bar has been cast into a narrow workable length for small vessels, jewellery, fittings, or tool parts.", SizeCategory.Small, ItemQuality.Standard, 1600.0, 72.0m, "bronze", [ "Market / Raw Materials", "Market / Raw Materials / Bronze", "Functions / Material Functions / Primary Production / Primary Production Commodity / Metal Bar Stock Commodity" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_wire_coil", "coil", "a coil of drawn wire", "This coil of drawn bronze wire is wound tight and tied for jewellery, mail links, pins, small springs, or bindings.", SizeCategory.Small, ItemQuality.Good, 420.0, 55.0m, "bronze", [ "Functions / Material Functions / Jewellery Craft Stock / Jewellery Wire Stock", "Functions / Joining / Tie / Tie Wire" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_rivet_packet", "packet", "a packet of iron rivets", "This small parchment packet holds short iron rivets sorted by size for armour, hinges, straps, locks, and furniture fittings.", SizeCategory.VerySmall, ItemQuality.Standard, 500.0, 16.0m, "wrought iron", [ "Market / Repair Supplies / General Repair Supplies", "Functions / Joining / Fastening / Rivet" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_nail_packet", "packet", "a packet of iron nails", "This small canvas packet holds hand-forged nails and tacks with irregular heads for construction and repair work.", SizeCategory.VerySmall, ItemQuality.Standard, 650.0, 12.0m, "wrought iron", [ "Market / Construction Materials", "Functions / Joining / Fastening / Nail" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_sheet_metal", "sheet", "a sheet of thin wrought iron", "This thin sheet of wrought iron has been hammered and trimmed into a broad workable plate for armour scales, fittings, boxes, lanterns, and hardware.", SizeCategory.Normal, ItemQuality.Standard, 1800.0, 42.0m, "wrought iron", [ "Market / Raw Materials", "Functions / Material Functions / Primary Production / Primary Production Commodity / Metal Billet Commodity" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_blade_blank", "blank", "an iron blade blank", "This forged blade blank has a rough tang, tapered body, and thick blunt edge awaiting grinding and heat treatment.", SizeCategory.Small, ItemQuality.Standard, 760.0, 35.0m, "wrought iron", [ "Market / Repair Supplies / Weapon and Armour Repair Supplies", "Functions / Material Functions / Antiquity Equipment Stock / Weapon Blade Stock" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_weapon_head_blank", "blank", "a socketed weapon-head blank", "This iron blank has been forged into a rough socket and pointed head suitable for spear, polearm, or tool work.", SizeCategory.Small, ItemQuality.Standard, 920.0, 32.0m, "wrought iron", [ "Market / Repair Supplies / Weapon and Armour Repair Supplies", "Functions / Material Functions / Antiquity Equipment Stock / Weapon Head Stock" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_armour_ring_packet", "packet", "a packet of armour rings", "This small packet holds many iron rings split or overlapped for mail work and armour repair.", SizeCategory.VerySmall, ItemQuality.Standard, 800.0, 34.0m, "wrought iron", [ "Market / Repair Supplies / Weapon and Armour Repair Supplies", "Functions / Material Functions / Antiquity Equipment Stock / Armour Ring Stock" ], [ "Holdable", "Destroyable_HeavyMetal" ]),
			("medieval_industry_stock_armour_scale_bundle", "bundle", "a bundle of armour scales", "These small overlapping scales have been cut from leather and punched along the top edge for later lacing onto backing.", SizeCategory.Small, ItemQuality.Standard, 700.0, 24.0m, "leather", [ "Market / Repair Supplies / Weapon and Armour Repair Supplies", "Functions / Material Functions / Antiquity Equipment Stock / Armour Scale Stock" ], [ "Holdable", "Destroyable_Clothing" ]),

			("medieval_industry_stock_clay_body_lump", "lump", "a lump of prepared clay body", "This lump of prepared clay body has been kneaded with temper and wrapped to keep it workable for vessels, tiles, moulds, or small fired goods.", SizeCategory.Normal, ItemQuality.Standard, 4200.0, 6.0m, "clay", [ "Market / Raw Materials / Clay", "Functions / Material Functions / Household Craft Stock / Pottery Clay Body" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_fired_brick_stack", "stack", "a stack of fired bricks", "This cord-bound stack holds hard red-brown bricks ready for ovens, hearths, kilns, walls, and workshop fixtures.", SizeCategory.Large, ItemQuality.Standard, 28000.0, 18.0m, "brick", [ "Market / Construction Materials / Brick", "Functions / Material Functions / Primary Production / Primary Production Commodity / Fired Brick Commodity" ], [ "Holdable", "Destroyable_Furniture" ]),
			("medieval_industry_stock_roof_tile_stack", "stack", "a stack of fired roof tiles", "This stack of curved fired tiles is tied with straw padding between the pieces for roofing, kiln-setting, or construction work.", SizeCategory.Large, ItemQuality.Standard, 22000.0, 24.0m, "ceramic tile", [ "Market / Construction Materials / Roofing Materials", "Functions / Material Functions / Primary Production / Primary Production Commodity / Roof Tile Commodity" ], [ "Holdable", "Destroyable_Furniture" ]),
			("medieval_industry_stock_lime_mortar_lump", "lump", "a lump of lime mortar", "This pale lump of lime mortar is gritty, damp, and ready to be worked into joints, plaster, tile bedding, or small repairs.", SizeCategory.Small, ItemQuality.Standard, 1500.0, 4.0m, "lime", [ "Market / Construction Materials", "Functions / Material Functions / Primary Production / Primary Production Commodity" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_glass_batch", "batch", "a batch of prepared glass mix", "This gritty batch of sand, ash, and flux is measured and mixed for glasshouse melting but has not yet been fused.", SizeCategory.Small, ItemQuality.Standard, 2200.0, 22.0m, "sand", [ "Market / Raw Materials", "Functions / Material Functions / Primary Production / Primary Production Commodity" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_glass_pane_blank", "pane", "a rough glass pane blank", "This rough greenish glass pane has been flattened and cooled but still needs trimming, polishing, or leading before use.", SizeCategory.Small, ItemQuality.Standard, 750.0, 35.0m, "glass", [ "Market / Raw Materials", "Functions / Material Functions / Household Craft Stock / Glass Vessel Blank" ], [ "Holdable", "Destroyable_Glassware" ]),

			("medieval_industry_stock_ink_cake", "cake", "a black ink cake", "This compact black cake is made from soot-rich pigment and binder pressed into a hard block that must be ground or wetted before use.", SizeCategory.Tiny, ItemQuality.Standard, 35.0, 12.0m, "charcoal", [ "Market / Writing Materials / Ink", "Functions / Material Functions / Writing Craft Stock / Ink Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_glue_cake", "cake", "a hide-glue cake", "This amber-brown glue cake has been rendered from hide and bone stock, then dried into a brittle slab for heating and reuse.", SizeCategory.VerySmall, ItemQuality.Standard, 120.0, 8.0m, "bone", [ "Market / Repair Supplies / General Repair Supplies", "Functions / Joining / Adhesion / Glue" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_seal_wax_stick", "stick", "a red seal-wax stick", "This narrow red stick of sealing wax is shaped for warming and pressing under a seal for documents, packets, and closures.", SizeCategory.Tiny, ItemQuality.Standard, 35.0, 10.0m, "beeswax", [ "Market / Writing Materials", "Functions / Material Functions / Writing Craft Stock / Scrollmaking Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_wax_tablet_blank", "tablet", "a wax-tablet blank", "This small wooden tablet frame has been prepared to receive a wax writing surface but is not yet a finished writable tablet.", SizeCategory.Small, ItemQuality.Standard, 220.0, 12.0m, "beeswax", [ "Market / Writing Materials", "Functions / Material Functions / Writing Craft Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_glass_bead_blanks", "packet", "a packet of glass bead blanks", "This little packet holds small glass blanks and canes cut for bead making, rosaries, trim, or inlay stock.", SizeCategory.VerySmall, ItemQuality.Good, 180.0, 28.0m, "glass", [ "Functions / Material Functions / Jewellery Craft Stock / Jewellery Bead Stock" ], [ "Holdable", "Destroyable_Glassware" ]),
			("medieval_industry_stock_cabochon_blank", "blank", "a polished cabochon blank", "This small domed stone blank has been roughly shaped and smoothed for a ring, brooch, seal, or pendant setting.", SizeCategory.Tiny, ItemQuality.Good, 18.0, 35.0m, "stone", [ "Market / Raw Materials", "Functions / Material Functions / Jewellery Craft Stock / Jewellery Setting Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_jewellery_setting_packet", "packet", "a packet of simple jewellery settings", "This small packet holds thin bronze settings and collars for beads, cabochons, brooches, pendants, and rings.", SizeCategory.VerySmall, ItemQuality.Good, 160.0, 42.0m, "bronze", [ "Functions / Material Functions / Jewellery Craft Stock / Jewellery Setting Stock" ], [ "Holdable", "Destroyable_HeavyMetal" ]),

			("medieval_industry_stock_bandage_roll", "roll", "a roll of clean bandage linen", "This roll of clean linen is torn into long strips and wrapped tight for dressing wounds, packing kits, or cutting into smaller medical pieces.", SizeCategory.Small, ItemQuality.Standard, 180.0, 10.0m, "linen", [ "Market / Medicine / Treatment Supplies", "Functions / Medical Treatment / Bandage", "Functions / Material Functions / Medical Craft Stock / Dressing Stock" ], [ "Holdable", "Destroyable_Clothing" ]),
			("medieval_industry_stock_suture_thread", "spool", "a spool of suture thread", "This little spool holds fine prepared gut thread wound under light tension for medical stitching or specialist repair.", SizeCategory.Tiny, ItemQuality.Good, 25.0, 20.0m, "gut", [ "Market / Medicine / Surgical Supplies", "Functions / Joining / Sewing / Surgical Suturing", "Functions / Material Functions / Medical Craft Stock / Suture Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_splint_blank", "blank", "a padded splint blank", "This straight wooden splint blank is smoothed, wrapped with a little linen, and ready to be cut or tied for immobilising an injured limb.", SizeCategory.Small, ItemQuality.Standard, 240.0, 8.0m, "ash", [ "Market / Medicine / Treatment Supplies", "Functions / Medical Treatment / Splint", "Functions / Material Functions / Medical Craft Stock / Splint Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_salve_base_pot", "pot", "a pot of salve base", "This small beeswax-rich pot holds a plain greasy salve base ready to take herbs, resin, honey, or mineral powders.", SizeCategory.VerySmall, ItemQuality.Standard, 220.0, 14.0m, "beeswax", [ "Market / Medicine / Apothecary Goods", "Functions / Material Functions / Medical Craft Stock / Salve Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_poultice_stock_packet", "packet", "a packet of poultice stock", "This packet holds dry absorbent herbal and fibre stock ready to be mixed into a poultice or compress.", SizeCategory.VerySmall, ItemQuality.Standard, 90.0, 8.0m, "herb", [ "Market / Medicine / Apothecary Goods", "Functions / Material Functions / Medical Craft Stock / Poultice Stock" ], [ "Holdable", "Destroyable_Misc" ]),
			("medieval_industry_stock_repair_supply_packet", "packet", "a packet of mixed repair supplies", "This packet holds small scraps of thread, leather, glue, wax, rivets, and cord for use in later specialist repair-kit crafts.", SizeCategory.Small, ItemQuality.Standard, 420.0, 18.0m, "linen", [ "Market / Repair Supplies / General Repair Supplies" ], [ "Holdable", "Destroyable_Misc" ])
		];

		Array.ForEach(items, item => CreateItem
		(
			item.StableReference,
			item.Noun,
			item.Sdesc,
			null,
			item.Fdesc,
			item.Size,
			item.Quality,
			item.Weight,
			item.Cost,
			false,
			false,
			item.Material,
			item.Tags,
			item.Components,
			null,
			null,
			null,
			null
		));
	}
}
