#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Body.Traits;
using MudSharp.Body;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Form.Material;
using MudSharp.Form.Shape;
using MudSharp.Framework;
using MudSharp.FutureProg;
using MudSharp.GameItems.Components;
using MudSharp.GameItems.Interfaces;
using MudSharp.GameItems;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System;

namespace DatabaseSeeder.Seeders;

public partial class UsefulSeeder
{
    private GameItemComponentProto CreateItemProto(long id, DateTime now, string type, string name, string description, string definition)
    {
        GameItemComponentProto component = new()
        {
            Id = id,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = _dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = _dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = type,
            Name = name,
            Description = description,
            Definition = definition
        };
        return AddGameItemComponent(_context, component);
    }

    private GameItemComponentProto CreateComponent(FuturemudDatabaseContext context,
        ref long nextId, Account account, DateTime now, string type, string name,
        string description, string definition)
    {
        GameItemComponentProto component = new()
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = account.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = account.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = type,
            Name = name,
            Description = description,
            Definition = definition
        };

        return AddGameItemComponent(context, component);
    }

    private GameItemComponentProto UpsertComponent(FuturemudDatabaseContext context,
        ref long nextId, Account account, DateTime now, string type, string name,
        string description, string definition)
    {
        if (!_itemProtos.TryGetValue(name, out GameItemComponentProto? existing))
        {
            existing = context.GameItemComponentProtos
                .FirstOrDefault(x => x.Name == name && x.EditableItem.RevisionStatus == 4);
        }

        if (existing is not null)
        {
            existing.Type = type;
            existing.Description = description;
            existing.Definition = definition;
            _itemProtos[existing.Name] = existing;
            return existing;
        }

        return CreateComponent(context, ref nextId, account, now, type, name, description, definition);
    }

    private GameItemComponentProto CreateTorchComponent(FuturemudDatabaseContext context,
    ref long nextId, Account account, DateTime now, string name, string description,
    int illuminationProvided, int secondsOfFuel, bool requiresIgnitionSource,
    string lightEmote, string extinguishEmote, string tenPercentFuelEcho,
    string fuelExpendedEcho)
    {
        string definition = @$"<Definition>
<IlluminationProvided>{illuminationProvided}</IlluminationProvided>
<SecondsOfFuel>{secondsOfFuel}</SecondsOfFuel>
<RequiresIgnitionSource>{requiresIgnitionSource.ToString().ToLower()}</RequiresIgnitionSource>
<LightEmote><![CDATA[{lightEmote}]]></LightEmote>
<ExtinguishEmote><![CDATA[{extinguishEmote}]]></ExtinguishEmote>
<TenPercentFuelEcho><![CDATA[{tenPercentFuelEcho}]]></TenPercentFuelEcho>
<FuelExpendedEcho><![CDATA[{fuelExpendedEcho}]]></FuelExpendedEcho>
</Definition>";
        return CreateComponent(context, ref nextId, account, now, "Torch", name, description,
        definition);
    }

    private GameItemComponentProto CreateLanternComponent(FuturemudDatabaseContext context,
    ref long nextId, Account account, DateTime now, string name, string description,
    int illuminationProvided, double fuelCapacity, bool requiresIgnitionSource,
    string lightEmote, string extinguishEmote, string tenPercentFuelEcho,
    string fuelExpendedEcho, long liquidFuelId, double fuelPerSecond)
    {
        string definition = @$"<Definition>
<IlluminationProvided>{illuminationProvided}</IlluminationProvided>
<FuelCapacity>{fuelCapacity.ToString(System.Globalization.CultureInfo.InvariantCulture)}</FuelCapacity>
<RequiresIgnitionSource>{requiresIgnitionSource.ToString().ToLower()}</RequiresIgnitionSource>
<LightEmote><![CDATA[{lightEmote}]]></LightEmote>
<ExtinguishEmote><![CDATA[{extinguishEmote}]]></ExtinguishEmote>
<TenPercentFuelEcho><![CDATA[{tenPercentFuelEcho}]]></TenPercentFuelEcho>
<FuelExpendedEcho><![CDATA[{fuelExpendedEcho}]]></FuelExpendedEcho>
<LiquidFuel>{liquidFuelId}</LiquidFuel>
<FuelPerSecond>{fuelPerSecond.ToString(System.Globalization.CultureInfo.InvariantCulture)}</FuelPerSecond>
</Definition>";
        return CreateComponent(context, ref nextId, account, now, "Lantern", name, description,
        definition);
    }

    private GameItemComponentProto CreateWaterSourceComponent(FuturemudDatabaseContext context,
    ref long nextId, Account account, DateTime now, string name, string description,
    double liquidCapacity, long defaultLiquidId, double refillRate, bool useOnOffForRefill)
    {
        string definition = $"<Definition LiquidCapacity=\"{liquidCapacity.ToString(System.Globalization.CultureInfo.InvariantCulture)}\" Closable=\"false\" Transparent=\"false\" OnceOnly=\"false\" DefaultLiquid=\"{defaultLiquidId}\" RefillRate=\"{refillRate.ToString(System.Globalization.CultureInfo.InvariantCulture)}\" UseOnOffForRefill=\"{useOnOffForRefill.ToString().ToLower()}\" RefillingProg=\"0\" CanBeEmptiedWhenInRoom=\"false\" />";
        return CreateComponent(context, ref nextId, account, now, "WaterSource", name, description,
        definition);
    }

    private GameItemComponentProto AddGameItemComponent(FuturemudDatabaseContext context, GameItemComponentProto component)
    {
        if (_itemProtos.TryGetValue(component.Name, out GameItemComponentProto? existing))
        {
            return existing;
        }

        existing = context.GameItemComponentProtos
            .FirstOrDefault(x => x.Name == component.Name && x.EditableItem.RevisionStatus == 4);
        if (existing is not null)
        {
            _itemProtos[existing.Name] = existing;
            return existing;
        }

        context.GameItemComponentProtos.Add(component);
        _itemProtos[component.Name] = component;
        return component;
    }

    internal void SeedModernItemsForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        SeedModernItems(context, new List<string>());
        context.SaveChanges();
    }

    internal void SeedGeneralCoverageForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedAdditionalBuilderExamples(context, now, dbaccount, ref nextId);
        SeedSmokeables(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedWornTraitChangersForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedWornTraitChangers(context, now, dbaccount, ref nextId, new List<string>());
        context.SaveChanges();
    }

    internal void SeedVariablesForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedVariables(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedRepairKitsForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        _tags = context.Tags.ToDictionaryWithDefault(x => x.Name, x => x, StringComparer.OrdinalIgnoreCase);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedRepairKits(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedMedievalIndustryToolComponentsForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedMedievalIndustryToolComponents(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedAntiquityComponentGapCoverageForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedWaterSources(context, now, dbaccount, ref nextId);
        SeedDice(context, now, dbaccount, ref nextId);
        SeedAdditionalBuilderExamples(context, now, dbaccount, ref nextId);
        SeedSealAndMeasurementComponents(context, now, dbaccount, ref nextId);
        SeedOfferingAndIncenseComponents(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedLockAndWaterSourceCoverageForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedLocks(now, ref nextId);
        SeedWaterSources(context, now, dbaccount, ref nextId);
        context.SaveChanges();
    }

    internal void SeedContainersForTesting(FuturemudDatabaseContext context)
    {
        _context = context;
        PrepareItemProtoCache(context);
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
        SeedContainers(new Dictionary<string, string>(), new List<string>(), now, dbaccount, ref nextId);
        context.SaveChanges();
    }

	internal void SeedEraDependencyComponentsForTesting(FuturemudDatabaseContext context)
	{
		_context = context;
		PrepareItemProtoCache(context);
		DateTime now = DateTime.UtcNow;
		Account dbaccount = context.Accounts.First();
		long nextId = context.GameItemComponentProtos.Any() ? context.GameItemComponentProtos.Max(x => x.Id) + 1 : 1;
		SeedEraDependencyComponents(context, now, dbaccount, ref nextId);
		context.SaveChanges();
	}

    private void SeedItemsPart1(FuturemudDatabaseContext context, IReadOnlyDictionary<string, string> questionAnswers,
            ICollection<string> errors)
    {
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Max(x => x.Id) + 1;
        _context = context;

        SeedContainers(questionAnswers, errors, now, dbaccount, ref nextId);
        context.SaveChanges();

        SeedLiquidContainers(questionAnswers, errors, now, dbaccount, ref nextId);
        context.SaveChanges();

        SeedDoors(questionAnswers, errors, now, dbaccount, ref nextId);
        context.SaveChanges();

        SeedLocks(now, ref nextId);
        SeedWritingImplements(context, now, dbaccount, ref nextId);
    }

    private void SeedItemsPart2(FuturemudDatabaseContext context, IReadOnlyDictionary<string, string> questionAnswers,
        ICollection<string> errors)
    {
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Max(x => x.Id) + 1;

        SeedInsulation(context, now, dbaccount, ref nextId);
        SeedGlasses(context, now, dbaccount, ref nextId);
        SeedIdentityObscuring(context, now, dbaccount, ref nextId);
    }

    private void SeedItemsPart3(FuturemudDatabaseContext context,
        IReadOnlyDictionary<string, string> questionAnswers, ICollection<string> errors)
    {
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Max(x => x.Id) + 1;

        SeedDestroyables(context, now, dbaccount, ref nextId);
        SeedVariables(context, now, dbaccount, ref nextId);
        SeedChairs(context, now, dbaccount, ref nextId);
        SeedRangedCoverItemComponents(context, now, ref nextId);
        SeedTables(context, now, dbaccount, ref nextId);
        SeedWornExpansion(context, now, dbaccount, ref nextId);
        SeedWornTraitChangers(context, now, dbaccount, ref nextId, errors);
        SeedHealthRelatedItems(context, now, dbaccount, ref nextId);
        SeedProsthetics(context, now, dbaccount, ref nextId);
        SeedDice(context, now, dbaccount, ref nextId);
    }

    private void SeedItemsPart4(FuturemudDatabaseContext context,
        IReadOnlyDictionary<string, string> questionAnswers, ICollection<string> errors)
    {
        DateTime now = DateTime.UtcNow;
        Account dbaccount = context.Accounts.First();
        long nextId = context.GameItemComponentProtos.Max(x => x.Id) + 1;

        SeedLighting(context, now, dbaccount, ref nextId);
        SeedWaterSources(context, now, dbaccount, ref nextId);
        SeedRepairKits(context, now, dbaccount, ref nextId);
        SeedMedievalIndustryToolComponents(context, now, dbaccount, ref nextId);
		SeedEraDependencyComponents(context, now, dbaccount, ref nextId);
        SeedAdditionalBuilderExamples(context, now, dbaccount, ref nextId);
        SeedSealAndMeasurementComponents(context, now, dbaccount, ref nextId);
        SeedOfferingAndIncenseComponents(context, now, dbaccount, ref nextId);
        SeedSmokeables(context, now, dbaccount, ref nextId);
    }
}
