namespace MudSharp.Body.Traits
{
	public enum TraitBonusContext
	{
		None,
		UnarmedDamageCalculation,
		ArmedDamageCalculation,
		CarryingCapacity,
		DraggingCapacity,
		StaggeringBlowCheck,
		StaggeringBlowDefenseCheck,
		UnbalancingBlowCheck,
		UnbalancingBlowDefenseCheck,
		ProjectLabourQualification,
		BreathingRate,
		HoldBreathLength,
		Buoyancy,
		Encumbrance,
		CombatPowerMoveStamina,
		CombatGraceMoveStamina,
		CombatRelativeStrengthDefenseStamina,
		BreakoutFromGrapple,
		OpposeBreakoutFromGrapple,
		SpellDuration,
		SpellCost,
		JobEffortCalculation,
		MusketMisfire,
		UnjamGunDuration
	}
}