#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Body.Traits;
using MudSharp.Body;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Form.Material;
using MudSharp.Form.Shape;
using MudSharp.Framework;
using MudSharp.FutureProg;
using MudSharp.GameItems.Components;
using MudSharp.GameItems.Interfaces;
using MudSharp.GameItems;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System;

namespace DatabaseSeeder.Seeders;

public partial class UsefulSeeder
{
    private void SeedDestroyables(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Destroyables

        GameItemComponentProto component = new()
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Misc",
            Description = "Makes an item destroyable. Relatively low HP, for miscellaneous items",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(pow(size,1.2) * (quality+1))]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.25"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0.25"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Weapon",
            Description = "Makes an item destroyable. Designed for Weapons.",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(20 * quality) + (pow(size,1.2) * (quality+1))]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.1"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0.25"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Armour",
            Description = "Makes an item destroyable. Designed for Armour.",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(100 * quality) + (pow(size,1.2) * (quality+1) * 10)]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.1"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0.1"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Clothing",
            Description = "Makes an item destroyable. Designed for Clothing.",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(2 * quality) + (pow(size,1.2) * (quality+1))]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.01"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Door",
            Description = "Makes an item destroyable. Designed for Doors.",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(20 * quality) + (pow(size,1.2) * (quality+1) * 5)]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.1"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0.25"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Destroyable",
            Name = "Destroyable_Furniture",
            Description = "Makes an item destroyable. Designed for Furniture.",
            Definition = @"<Definition>
   <HpExpression><![CDATA[(30 * quality) + (pow(size,1.2) * (quality+1) * 5)]]></HpExpression>
   <DamageMultipliers>
	 <DamageMultiplier type=""0"" multiplier=""0.25"" />
	 <DamageMultiplier type=""1"" multiplier=""0.25"" />
	 <DamageMultiplier type=""2"" multiplier=""0.1"" />
	 <DamageMultiplier type=""3"" multiplier=""0.05"" />
	 <DamageMultiplier type=""4"" multiplier=""0.05"" />
	 <DamageMultiplier type=""5"" multiplier=""0"" />
	 <DamageMultiplier type=""6"" multiplier=""0"" />
	 <DamageMultiplier type=""7"" multiplier=""0.25"" />
	 <DamageMultiplier type=""8"" multiplier=""0.25"" />
	 <DamageMultiplier type=""9"" multiplier=""0.05"" />
	 <DamageMultiplier type=""10"" multiplier=""0.25"" />
	 <DamageMultiplier type=""11"" multiplier=""0"" />
	 <DamageMultiplier type=""12"" multiplier=""0"" />
	 <DamageMultiplier type=""13"" multiplier=""0"" />
	 <DamageMultiplier type=""14"" multiplier=""0.25"" />
	 <DamageMultiplier type=""15"" multiplier=""0.25"" />
	 <DamageMultiplier type=""16"" multiplier=""0.05"" />
	 <DamageMultiplier type=""17"" multiplier=""0.10"" />
	 <DamageMultiplier type=""18"" multiplier=""0.10"" />
	 <DamageMultiplier type=""19"" multiplier=""0.00"" />
	 <DamageMultiplier type=""20"" multiplier=""0.05"" />
	 <DamageMultiplier type=""21"" multiplier=""0.25"" />
	 <DamageMultiplier type=""22"" multiplier=""0.25"" />
   </DamageMultipliers>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedVariables(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Variables

        CharacteristicDefinition colour = context.CharacteristicDefinitions.First(x => x.Name == "Colour");
        CharacteristicDefinition colour1 = context.CharacteristicDefinitions.First(x => x.Name == "Colour1");
        CharacteristicDefinition colour2 = context.CharacteristicDefinitions.First(x => x.Name == "Colour2");
        CharacteristicDefinition colour3 = context.CharacteristicDefinitions.First(x => x.Name == "Colour3");
        CharacteristicDefinition fineColour = context.CharacteristicDefinitions.First(x => x.Name == "Fine Colour");
        CharacteristicDefinition drabColour = context.CharacteristicDefinitions.First(x => x.Name == "Drab Colour");
        CharacteristicDefinition gem = context.CharacteristicDefinitions.First(x => x.Name == "Gem");
        CharacteristicDefinition fineGem = context.CharacteristicDefinitions.First(x => x.Name == "Fine Gem");
        CharacteristicDefinition commonStone = context.CharacteristicDefinitions.First(x => x.Name == "Common Stone");
        CharacteristicDefinition jewelleryMotif = context.CharacteristicDefinitions.First(x => x.Name == "Jewellery Motif");
        CharacteristicDefinition flower = context.CharacteristicDefinitions.First(x => x.Name == "Flower");
        CharacteristicDefinition metalFinish = context.CharacteristicDefinitions.First(x => x.Name == "Metal Finish");
        CharacteristicDefinition beadPattern = context.CharacteristicDefinitions.First(x => x.Name == "Bead Pattern");
        CharacteristicDefinition jewelleryShape = context.CharacteristicDefinitions.First(x => x.Name == "Jewellery Shape");
        CharacteristicDefinition inlayStyle = context.CharacteristicDefinitions.First(x => x.Name == "Inlay Style");
        CharacteristicProfile allColours = context.CharacteristicProfiles.First(x => x.Name == "All_Colours");
        CharacteristicProfile basicColours = context.CharacteristicProfiles.First(x => x.Name == "Basic_Colours");
        CharacteristicProfile fineColours = context.CharacteristicProfiles.First(x => x.Name == "Fine_Colours");
        CharacteristicProfile drabColours = context.CharacteristicProfiles.First(x => x.Name == "Drab_Colours");
        CharacteristicProfile gemColours = context.CharacteristicProfiles.First(x => x.Name == "Gem_Colours");
        CharacteristicProfile fineGemColours = context.CharacteristicProfiles.First(x => x.Name == "Fine_Gem_Colours");
        CharacteristicProfile commonStones = context.CharacteristicProfiles.First(x => x.Name == "Common_Stones");
        CharacteristicProfile jewelleryMotifs = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Motifs");
        CharacteristicProfile jewelleryFlowers = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Flowers");
        CharacteristicProfile jewelleryMetalFinishes = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Metal_Finishes");
        CharacteristicProfile jewelleryBeadPatterns = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Bead_Patterns");
        CharacteristicProfile jewelleryShapes = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Shapes");
        CharacteristicProfile jewelleryInlayStyles = context.CharacteristicProfiles.First(x => x.Name == "Jewellery_Inlay_Styles");
        GameItemComponentProto component;

        void AddSingleVariableComponent(ref long componentId, string name, string description, CharacteristicProfile profile,
            CharacteristicDefinition definition)
        {
            component = new GameItemComponentProto
            {
                Id = componentId++,
                RevisionNumber = 0,
                EditableItem = new EditableItem
                {
                    RevisionNumber = 0,
                    RevisionStatus = 4,
                    BuilderAccountId = dbaccount.Id,
                    BuilderDate = now,
                    BuilderComment = "Auto-generated by the system",
                    ReviewerAccountId = dbaccount.Id,
                    ReviewerComment = "Auto-generated by the system",
                    ReviewerDate = now
                },
                Type = "Variable",
                Name = name,
                Description = description,
                Definition = @$"<Definition>
   <Characteristic Profile=""{profile.Id}"" Value=""{definition.Id}"" />
 </Definition>"
            };
            AddGameItemComponent(context, component);
            context.SaveChanges();
        }

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_Colour",
            Description = "Gives an item a random variable called $colour.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        AddSingleVariableComponent(ref nextId, "Variable_JewelleryMotif",
            "Gives an item a random variable called $motif from the Jewellery_Motifs list.",
            jewelleryMotifs, jewelleryMotif);
        AddSingleVariableComponent(ref nextId, "Variable_Flower",
            "Gives an item a random variable called $flower from the Jewellery_Flowers list.",
            jewelleryFlowers, flower);
        AddSingleVariableComponent(ref nextId, "Variable_MetalFinish",
            "Gives an item a random variable called $finish from the Jewellery_Metal_Finishes list.",
            jewelleryMetalFinishes, metalFinish);
        AddSingleVariableComponent(ref nextId, "Variable_BeadPattern",
            "Gives an item a random variable called $beadpattern from the Jewellery_Bead_Patterns list.",
            jewelleryBeadPatterns, beadPattern);
        AddSingleVariableComponent(ref nextId, "Variable_JewelleryShape",
            "Gives an item a random variable called $shape from the Jewellery_Shapes list.",
            jewelleryShapes, jewelleryShape);
        AddSingleVariableComponent(ref nextId, "Variable_InlayStyle",
            "Gives an item a random variable called $inlay from the Jewellery_Inlay_Styles list.",
            jewelleryInlayStyles, inlayStyle);

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_BasicColour",
            Description = "Gives an item a random variable called $colour from the Basic_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_FineColour",
            Description = "Gives an item random variables called $colour and $finecolor from the Fine_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour.Id}"" />
   <Characteristic Profile=""{fineColours.Id}"" Value=""{fineColour.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_DrabColour",
            Description = "Gives an item random variables called $colour and $drabcolor from the Drab_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour.Id}"" />
   <Characteristic Profile=""{drabColours.Id}"" Value=""{drabColour.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_Gem",
            Description = "Gives an item a random variable called $gemcolor, plus the importer alias $gem, from the Gem_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{gemColours.Id}"" Value=""{gem.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_FineGem",
            Description = "Gives an item a random variable called $finegemcolor from the Fine_Gem_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{fineGemColours.Id}"" Value=""{fineGem.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_CommonStone",
            Description = "Gives an item a random variable called $commonstone, plus the importer alias $stone, from the Common_Stones list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{commonStones.Id}"" Value=""{commonStone.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_RpiMixedVariables",
            Description =
                "Gives an imported RPI item the common colour, fine colour, drab colour, gem, fine gem, and common stone variables.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour.Id}"" />
   <Characteristic Profile=""{fineColours.Id}"" Value=""{fineColour.Id}"" />
   <Characteristic Profile=""{drabColours.Id}"" Value=""{drabColour.Id}"" />
   <Characteristic Profile=""{gemColours.Id}"" Value=""{gem.Id}"" />
   <Characteristic Profile=""{fineGemColours.Id}"" Value=""{fineGem.Id}"" />
   <Characteristic Profile=""{commonStones.Id}"" Value=""{commonStone.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_2Colour",
            Description = "Gives an item 2 random variables called $colour1 and $colour2.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour2.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_2BasicColour",
            Description = "Gives an item 2 random variables called $colour1 and $colour2 from the Basic_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour2.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_2FineColour",
            Description = "Gives an item 2 random variables called $colour1 and $colour2 from the Fine_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour2.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_2DrabColour",
            Description = "Gives an item 2 random variables called $colour1 and $colour2 from the Drab_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour2.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_3Colour",
            Description = "Gives an item 3 random variables called $colour1, $colour2, and $colour3",
            Definition = @$"<Definition>
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour2.Id}"" />
   <Characteristic Profile=""{allColours.Id}"" Value=""{colour3.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_3BasicColour",
            Description =
                "Gives an item 3 random variables called $colour1, $colour2, and $colour3 from the Basic_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour2.Id}"" />
   <Characteristic Profile=""{basicColours.Id}"" Value=""{colour3.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_3FineColour",
            Description =
                "Gives an item 3 random variables called $colour1, $colour2, and $colour3 from the Fine_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour2.Id}"" />
   <Characteristic Profile=""{fineColours.Id}"" Value=""{colour3.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable",
            Name = "Variable_3DrabColour",
            Description =
                "Gives an item 3 random variables called $colour1, $colour2, and $colour3 from the Drab_Colours list.",
            Definition = @$"<Definition>
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour1.Id}"" />
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour2.Id}"" />
   <Characteristic Profile=""{drabColours.Id}"" Value=""{colour3.Id}"" />
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedVariableWritingImplements(FuturemudDatabaseContext context, DateTime now, Account dbaccount,
        ref long nextId)
    {
        #region Writing Implements

        GameItemComponentProto component;

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Pencil",
            Name = "Variable_Pencil",
            Description = "Makes an item a pencil of variable colour. Use with VARIABLE_COLOUR component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>5000</TotalUses>
   <UsesBeforeSharpening>100</UsesBeforeSharpening>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Pencil",
            Name = "Variable_Pencil_Colour1",
            Description = "Makes an item a pencil of variable colour. Use with VARIABLE_COLOUR1 component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>5000</TotalUses>
   <UsesBeforeSharpening>100</UsesBeforeSharpening>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour1").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Crayon",
            Name = "Variable_Crayon",
            Description = "Makes an item a crayon of variable colour. Use with VARIABLE_COLOUR component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>1000</TotalUses>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Crayon",
            Name = "Variable_Crayon_Colour1",
            Description = "Makes an item a crayon of variable colour. Use with VARIABLE_COLOUR1 component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>1000</TotalUses>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour1").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Biro",
            Name = "Variable_Biro",
            Description = "Makes an item a biro of variable colour. Use with VARIABLE_COLOUR component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>110000</TotalUses>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Biro",
            Name = "Variable_Biro_Colour1",
            Description = "Makes an item a biro of variable colour. Use with VARIABLE_COLOUR1 component.",
            Definition = @$"<Definition>
   <Colour>0</Colour>
   <TotalUses>110000</TotalUses>
   <ColourCharacteristic>{context.CharacteristicDefinitions.First(x => x.Name == "Colour1").Id}</ColourCharacteristic>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedChairs(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Chairs

        GameItemComponentProto component;

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Chair",
            Name = "Chair_Single",
            Description = "Makes an item a chair that can hold a single occupant",
            Definition = @"<Definition ChairSlotsUsed=""1"" ChairOccupantCapacity=""1"" />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Chair",
            Name = "Chair_Double",
            Description = "Makes an item a chair that can hold two occupants",
            Definition = @"<Definition ChairSlotsUsed=""2"" ChairOccupantCapacity=""2"" />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Chair",
            Name = "Chair_Triple",
            Description = "Makes an item a chair that can hold three occupants",
            Definition = @"<Definition ChairSlotsUsed=""3"" ChairOccupantCapacity=""3"" />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Chair",
            Name = "Chair_Quad",
            Description = "Makes an item a chair that can hold four occupants",
            Definition = @"<Definition ChairSlotsUsed=""4"" ChairOccupantCapacity=""4"" />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedRangedCoverItemComponents(FuturemudDatabaseContext context, DateTime now, ref long nextId)
    {
        #region Ranged Cover

        RangedCover unflippedTable = CreateOrGetRangedCover(context, "Upright Table", 1, 1, 1,
            "using $?0|$0|a table|$ as cover",
            "@ move|moves behind $?1|$1|a nearby table|$ and use|uses it to obscure &0's profile",
            3, false);
        RangedCover flippedTable = CreateOrGetRangedCover(context, "Overturned Table", 1, 2, 3,
            "hiding behind $?0|$0|an overturned table|$ as cover",
            "@ duck|ducks behind $?1|$1|a nearby overturned table|$ and begin|begins to use it as cover",
            3, false);
        CreateOrGetRangedCover(context, "Uneven Ground", 0, 1, 6,
            "prone, using the uneven ground as cover",
            "@ go|goes prone and begin|begins to use the uneven ground as cover",
            0, true);
        RangedCover smokeCover = CreateOrGetRangedCover(context, "Smoke", 0, 2, 1,
            "obscured by $?0|$0|the smoke|$",
            "@ move|moves into $?1|$1|the smoke|$ and uses it to obscure &0's form",
            0, true);
        RangedCover sandbagCover = CreateOrGetRangedCover(context, "Sandbag", 1, 2, 3,
            "hiding behind $?0|$0|a sandbag barricade|$, using it as cover",
            "@ take|takes position behind $?1|$1|a sandbag barricade|$ and begin|begins to use it as cover",
            3, false);
        RangedCover treeCover = CreateOrGetRangedCover(context, "Tree", 1, 2, 1,
            "hiding behind $?0|$0|a tree|$ for cover",
            "@ slip|slips behind $?1|$1|a tree|$ and use|uses it to protect &0's vital areas",
            1, false);
        RangedCover bushesCover = CreateOrGetRangedCover(context, "Bushes", 0, 2, 1,
            "hiding in $?0|$0|the bushes|$ for cover",
            "@ take|takes position behind $?1|$1|a bush|$ and use|uses it to obscure &0's profile",
            2, false);
        CreateOrGetRangedCover(context, "Long Grass", 0, 2, 6,
            "hiding in $?0|$0|the long grass|$ for cover",
            "@ take|takes position in $?1|$1|the long grass|$ and use|uses it to obscure &0's profile",
            2, true);
        RangedCover doorwaysCover = CreateOrGetRangedCover(context, "Doorways", 0, 1, 1,
            "using a doorway as cover",
            "@ duck|ducks into a doorway and begin|begins to use it as cover",
            0, false);
        RangedCover rubbleCover = CreateOrGetRangedCover(context, "Rubble", 1, 2, 12,
            "slumped up against $?0|$0|some rubble|$ as cover",
            "@ slump|slumps up against $?1|$1|some rubble|$ and begin|begins to use it as cover",
            2, false);

        context.SaveChanges();

        CreateItemProto(nextId++, now, "Cover", "Cover_Smoke",
            @"Turns an item into ranged cover of type ""Smoke"".",
            $@"<Definition>
   <Cover>{smokeCover.Id}</Cover>
 </Definition>");
        CreateItemProto(nextId++, now, "Cover", "Cover_Sandbag",
            @"Turns an item into ranged cover of type ""Sandbag"".",
            $@"<Definition>
   <Cover>{sandbagCover.Id}</Cover>
 </Definition>");
        CreateItemProto(nextId++, now, "Cover", "Cover_Tree",
            @"Turns an item into ranged cover of type ""Tree"".",
            $@"<Definition>
   <Cover>{treeCover.Id}</Cover>
 </Definition>");
        CreateItemProto(nextId++, now, "Cover", "Cover_Bushes",
            @"Turns an item into ranged cover of type ""Bushes"".",
            $@"<Definition>
   <Cover>{bushesCover.Id}</Cover>
 </Definition>");
        CreateItemProto(nextId++, now, "Cover", "Cover_Doorways",
            @"Turns an item into ranged cover of type ""Doorways"".",
            $@"<Definition>
   <Cover>{doorwaysCover.Id}</Cover>
 </Definition>");
        CreateItemProto(nextId++, now, "Cover", "Cover_Rubble",
            @"Turns an item into ranged cover of type ""Rubble"".",
            $@"<Definition>
   <Cover>{rubbleCover.Id}</Cover>
 </Definition>");
        context.SaveChanges();

        #endregion
    }

    private void SeedTables(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Tables

        GameItemComponentProto component;
        RangedCover flippedTable = context.RangedCovers.First(x => x.Name == "Overturned Table");
        RangedCover unflippedTable = context.RangedCovers.First(x => x.Name == "Upright Table");

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Four",
            Description = "Makes an item a table that can take four occupants",
            Definition = @$"<Definition MaximumChairSlots=""4"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Six",
            Description = "Makes an item a table that can take six occupants",
            Definition = @$"<Definition MaximumChairSlots=""6"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Eight",
            Description = "Makes an item a table that can take eight occupants",
            Definition = @$"<Definition MaximumChairSlots=""8"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Ten",
            Description = "Makes an item a table that can take ten occupants",
            Definition = @$"<Definition MaximumChairSlots=""10"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Twelve",
            Description = "Makes an item a table that can take twelve occupants",
            Definition = @$"<Definition MaximumChairSlots=""12"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Table",
            Name = "Table_Twenty",
            Description = "Makes an item a table that can take twenty occupants",
            Definition = @$"<Definition MaximumChairSlots=""20"">
  <Cover>
	<Flipped>{flippedTable.Id}</Flipped>
	<NotFlipped>{unflippedTable.Id}</NotFlipped>
	<Expression><![CDATA[0]]></Expression>
	<Message><![CDATA[@ try|tries to flip $1, but are|is not strong enough.]]></Message>
  </Cover>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }
}
