#nullable enable

using Microsoft.EntityFrameworkCore;
using MudSharp.Body.Traits;
using MudSharp.Body;
using MudSharp.Database;
using MudSharp.Form.Audio;
using MudSharp.Form.Material;
using MudSharp.Form.Shape;
using MudSharp.Framework;
using MudSharp.FutureProg;
using MudSharp.GameItems.Components;
using MudSharp.GameItems.Interfaces;
using MudSharp.GameItems;
using MudSharp.Health;
using MudSharp.Models;
using MudSharp.RPG.Checks;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System;

namespace DatabaseSeeder.Seeders;

public partial class UsefulSeeder
{
    private void SeedInsulation(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Insulation

        GameItemComponentProto component = new()
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "ClothingInsulation",
            Name = "Insulation_Minor",
            Description = "Makes garment a minor insulator",
            Definition = @"<Definition>
	<InsulatingDegrees>0.5</InsulatingDegrees>
	<ReflectingDegrees>0.5</ReflectingDegrees>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "ClothingInsulation",
            Name = "Insulation_Moderate",
            Description = "Makes garment a moderate insulator",
            Definition = @"<Definition>
	<InsulatingDegrees>1.0</InsulatingDegrees>
	<ReflectingDegrees>0.5</ReflectingDegrees>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "ClothingInsulation",
            Name = "Insulation_Strong",
            Description = "Makes garment a strong insulator",
            Definition = @"<Definition>
	<InsulatingDegrees>2.0</InsulatingDegrees>
	<ReflectingDegrees>0.5</ReflectingDegrees>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "ClothingInsulation",
            Name = "Insulation_Super",
            Description = "Makes garment a super insulator",
            Definition = @"<Definition>
	<InsulatingDegrees>4.0</InsulatingDegrees>
	<ReflectingDegrees>0.5</ReflectingDegrees>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "ClothingInsulation",
            Name = "Insulation_Reflector",
            Description = "Makes garment a good reflector (though not insulator)",
            Definition = @"<Definition>
	<InsulatingDegrees>0.0</InsulatingDegrees>
	<ReflectingDegrees>2.0</ReflectingDegrees>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedGlasses(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Glasses

        GameItemComponentProto component = new()
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Glasses",
            Name = "Glasses",
            Description = "Makes item correct Myopia flaws",
            Definition = @"<Definition></Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedIdentityObscuring(FuturemudDatabaseContext context, DateTime now, Account dbaccount,
        ref long nextId)
    {
        #region IdentityObscuring

        GameItemComponentProto component = new()
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "IdentityObscurer",
            Name = "FullFaceObscurer",
            Description = "Makes garment hide wearer's identity and change descriptions, including whole face",
            Definition = @"<Definition>
	<RemovalEcho><![CDATA[revealing &his $eyeshape $eyecolour eyes, $nose,$?facialhairstyle[ $facialhaircolour $facialhairstyle,][] and $haircolour $hairstyle.]]></RemovalEcho>
	<ShortDescription><![CDATA[&a_an[$?height[$height[@, ]]$frame] @key figure]]></ShortDescription>
	<FullDescription><![CDATA[This individual has their identity obscured on account of the fact that they are wearing @item. You can still tell however that they are &height tall and $framefancy.]]></FullDescription>
	<Difficulty>9</Difficulty>
	<Keywords>
		<Keyword key=""hood"" value=""hooded""/>
		<Keyword key=""helm"" value=""helmed""/>
		<Keyword key=""helmet"" value=""helmeted""/>
		<Keyword key=""mask"" value=""masked""/>
		<Keyword key=""scarf"" value=""scarfed""/>
		<Keyword key=""veil"" value=""veiled""/>
		<Keyword key=""hijab"" value=""hijabed""/>
		<Keyword key=""niqab"" value=""niqabed""/>
		<Keyword key=""burka"" value=""burkad""/>
		<Keyword key=""balaclava"" value=""balaclavad""/>
	</Keywords>
	<Characteristics>
	</Characteristics>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "IdentityObscurer",
            Name = "EyesFreeObscurer",
            Description = "Makes garment hide wearer's identity and change descriptions, but not hiding eyes",
            Definition = @"<Definition>
	<RemovalEcho><![CDATA[revealing &his $nose,$?facialhairstyle[ $facialhaircolour $facialhairstyle,][] and $haircolour $hairstyle.]]></RemovalEcho>
	<ShortDescription><![CDATA[&a_an[$?height[$height[@, ]]$frame] $eyecolour-eyed @key figure]]></ShortDescription>
	<FullDescription><![CDATA[This individual has their identity obscured on account of the fact that they are wearing @item. You can still tell however that they are &height tall and $framefancy, and that they have $eyeshape, $eyecolour eyes.]]></FullDescription>
	<Difficulty>9</Difficulty>
	<Keywords>
		<Keyword key=""hood"" value=""hooded""/>
		<Keyword key=""helm"" value=""helmed""/>
		<Keyword key=""helmet"" value=""helmeted""/>
		<Keyword key=""mask"" value=""masked""/>
		<Keyword key=""scarf"" value=""scarfed""/>
		<Keyword key=""veil"" value=""veiled""/>
		<Keyword key=""hijab"" value=""hijabed""/>
		<Keyword key=""niqab"" value=""niqabed""/>
		<Keyword key=""burka"" value=""burkad""/>
		<Keyword key=""balaclava"" value=""balaclavad""/>
	</Keywords>
	<Characteristics>
	</Characteristics>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable Changer",
            Name = "Wig",
            Description = "Changes hair colour and style when worn",
            Definition = @$"<Definition TargetWearProfile="""">
	<Characteristic Profile=""{context.CharacteristicProfiles.First(x => x.Name == "All Hair Colours").Id}"" Value=""{context.CharacteristicDefinitions.First(x => x.Name == "Hair Colour").Id}""/>
	<Characteristic Profile=""{context.CharacteristicProfiles.First(x => x.Name == "All Hair Styles").Id}"" Value=""{context.CharacteristicDefinitions.First(x => x.Name == "Hair Style").Id}""/>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable Changer",
            Name = "Facial_Wig",
            Description = "Changes facial hair colour and style when worn",
            Definition = @$"<Definition TargetWearProfile="""">
	<Characteristic Profile=""{context.CharacteristicProfiles.First(x => x.Name == "All Facial Hair Colours").Id}"" Value=""{context.CharacteristicDefinitions.First(x => x.Name == "Facial Hair Colour").Id}""/>
	<Characteristic Profile=""{context.CharacteristicProfiles.First(x => x.Name == "All Facial Hair Styles").Id}"" Value=""{context.CharacteristicDefinitions.First(x => x.Name == "Facial Hair Style").Id}""/>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Variable Changer",
            Name = "ColouredContacts",
            Description = "Changes eye colour when worn",
            Definition = @$"<Definition TargetWearProfile="""">
	<Characteristic Profile=""{context.CharacteristicProfiles.First(x => x.Name == "All Eye Colours").Id}"" Value=""{context.CharacteristicDefinitions.First(x => x.Name == "Eye Colour").Id}""/>
</Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedWornExpansion(FuturemudDatabaseContext context, DateTime now, Account dbaccount, ref long nextId)
    {
        #region Worn Expansion

        GameItemComponentProto component;

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Gag",
            Name = "Gag",
            Description = "Makes an item a gag when worn over the mouth",
            Definition = @"<Definition />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Blindfold",
            Name = "Blindfold",
            Description = "Makes an item a blindfold when worn over the eyes",
            Definition = @"<Definition />"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Restraint",
            Name = "Restraint",
            Description =
                @"Turns an item into a restraint when combined with the wearables that are named ""Bound <X>""",
            Definition = @"<Definition>
   <MinimumCreatureSize>4</MinimumCreatureSize>
   <MaximumCreatureSize>8</MaximumCreatureSize>
   <BreakoutDifficulty>7</BreakoutDifficulty>
   <OverpowerDifficulty>7</OverpowerDifficulty>
   <LimbType>0</LimbType>
   <LimbType>1</LimbType>
   <LimbType>2</LimbType>
   <LimbType>3</LimbType>
   <LimbType>4</LimbType>
   <LimbType>5</LimbType>
   <LimbType>6</LimbType>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Restraint",
            Name = "Restraint_Impossible",
            Description =
                @"Turns an item into an impossible to escape restraint when combined with the wearables that are named ""Bound <X>""",
            Definition = @"<Definition>
   <MinimumCreatureSize>4</MinimumCreatureSize>
   <MaximumCreatureSize>8</MaximumCreatureSize>
   <BreakoutDifficulty>11</BreakoutDifficulty>
   <OverpowerDifficulty>11</OverpowerDifficulty>
   <LimbType>0</LimbType>
   <LimbType>1</LimbType>
   <LimbType>2</LimbType>
   <LimbType>3</LimbType>
   <LimbType>4</LimbType>
   <LimbType>5</LimbType>
   <LimbType>6</LimbType>
 </Definition>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Belt",
            Name = "Belt_2",
            Description = "Turns item into a belt that can have 2 attached items of up to size Small",
            Definition = @"<Definition MaximumNumberOfBeltedItems=""2"" MaximumSize=""5""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Belt",
            Name = "Belt_4",
            Description = "Turns item into a belt that can have 4 attached items of up to size Small",
            Definition = @"<Definition MaximumNumberOfBeltedItems=""4"" MaximumSize=""5""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Belt",
            Name = "Belt_6",
            Description = "Turns item into a belt that can have 6 attached items of up to size Small",
            Definition = @"<Definition MaximumNumberOfBeltedItems=""6"" MaximumSize=""5""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Belt",
            Name = "Belt_Large",
            Description = "Turns item into a belt that can have 1 attached item of up to size Normal",
            Definition = @"<Definition MaximumNumberOfBeltedItems=""1"" MaximumSize=""6""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Beltable",
            Name = "Beltable",
            Description = "Allows an item to be attached to a belt",
            Definition = @"<Definition/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Sheath",
            Name = "Sheath",
            Description = "Turns item into a sheath for melee weapons of up to size Normal",
            Definition = @"<Definition StealthDrawDifficulty=""6"" MaximumSize=""6""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Sheath",
            Name = "Sheath_Small",
            Description = "Turns item into a sheath for melee weapons of up to size Small",
            Definition = @"<Definition StealthDrawDifficulty=""4"" MaximumSize=""5""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        component = new GameItemComponentProto
        {
            Id = nextId++,
            RevisionNumber = 0,
            EditableItem = new EditableItem
            {
                RevisionNumber = 0,
                RevisionStatus = 4,
                BuilderAccountId = dbaccount.Id,
                BuilderDate = now,
                BuilderComment = "Auto-generated by the system",
                ReviewerAccountId = dbaccount.Id,
                ReviewerComment = "Auto-generated by the system",
                ReviewerDate = now
            },
            Type = "Sheath",
            Name = "Sheath_Large",
            Description = "Turns item into a sheath for melee weapons of up to size Large",
            Definition = @"<Definition StealthDrawDifficulty=""8"" MaximumSize=""7""/>"
        };
        AddGameItemComponent(context, component);
        context.SaveChanges();

        #endregion
    }

    private void SeedWornTraitChangers(FuturemudDatabaseContext context, DateTime now, Account dbaccount,
        ref long nextId, ICollection<string> errors)
    {
        #region Worn Trait Changers

        var allTraits = context.TraitDefinitions.AsEnumerable().ToList();
        var skippedFamilies = new List<string>();
        long currentId = nextId;
        var grades = new[]
        {
            ("Minor", 2.5),
            ("Moderate", 5.0),
            ("Major", 7.5),
            ("Severe", 10.0)
        };

        TraitDefinition? FindTrait(params string[] names)
        {
            foreach (string name in names)
            {
                TraitDefinition? trait = allTraits.FirstOrDefault(x =>
                    string.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(x.Alias, name, StringComparison.OrdinalIgnoreCase));
                if (trait is not null)
                {
                    return trait;
                }
            }

            return null;
        }

        List<TraitDefinition> UniqueTraits(params TraitDefinition?[] traits)
        {
            var seen = new HashSet<long>();
            var results = new List<TraitDefinition>();
            foreach (TraitDefinition? trait in traits)
            {
                if (trait is null || !seen.Add(trait.Id))
                {
                    continue;
                }

                results.Add(trait);
            }

            return results;
        }

        XElement BuildDefinition(IEnumerable<TraitDefinition> traits, double modifier)
        {
            return new XElement("Definition",
                from trait in traits
                select new XElement("Modifier",
                    new XAttribute("trait", trait.Id),
                    new XAttribute("bonus", modifier),
                    new XAttribute("context", (int)TraitBonusContext.None)));
        }

        void CreateGradedFamily(string key, string description, IReadOnlyCollection<TraitDefinition> traits,
            double sign)
        {
            if (!traits.Any())
            {
                skippedFamilies.Add(key);
                return;
            }

            foreach ((string grade, double magnitude) in grades)
            {
                double modifier = sign * magnitude;
                UpsertComponent(context, ref currentId, dbaccount, now, "WornTraitChanger",
                    $"WornTraitChanger_{key}_{grade}",
                    $"{description} This is the {grade.ToLowerInvariant()} grade at {modifier:N1} per affected trait.",
                    BuildDefinition(traits, modifier).ToString());
            }
        }

        TraitDefinition? hideTrait = FindTrait("Hide", "Hiding", "Stealth");
        TraitDefinition? sneakTrait = FindTrait("Sneak", "Sneaking", "Stealth");
        List<TraitDefinition> stealthTraits = UniqueTraits(hideTrait, sneakTrait);
        if (stealthTraits.Any())
        {
            if (hideTrait is not null && hideTrait.Id != sneakTrait?.Id)
            {
                CreateGradedFamily("HidePenalty", "Makes worn items harder to hide in.", [hideTrait], -1.0);
            }

            if (sneakTrait is not null && sneakTrait.Id != hideTrait?.Id)
            {
                CreateGradedFamily("SneakPenalty", "Makes worn items noisier or more awkward for sneaking.", [sneakTrait],
                    -1.0);
            }

            CreateGradedFamily("StealthPenalty", "Makes worn items harder to hide and sneak in.", stealthTraits, -1.0);
            CreateGradedFamily("StealthBonus", "Helps worn camouflage, soft soles, or fitted clothing support stealth.",
                stealthTraits, 1.0);
        }
        else
        {
            skippedFamilies.Add("StealthPenalty");
            skippedFamilies.Add("StealthBonus");
        }

        TraitDefinition? swimTrait = FindTrait("Swim", "Swimming", "Athletics");
        TraitDefinition? climbTrait = FindTrait("Climb", "Climbing", "Athletics");
        TraitDefinition? flyTrait = FindTrait("Fly", "Flying", "Athletics");
        TraitDefinition? runTrait = FindTrait("Run", "Running", "Athletics");
        List<TraitDefinition> movementPenaltyTraits = UniqueTraits(swimTrait, climbTrait, flyTrait);
        if (movementPenaltyTraits.Any())
        {
            if (swimTrait is not null && swimTrait.Id != climbTrait?.Id && swimTrait.Id != flyTrait?.Id)
            {
                CreateGradedFamily("SwimPenalty", "Makes worn items harder to swim in.", [swimTrait], -1.0);
            }

            if (climbTrait is not null && climbTrait.Id != swimTrait?.Id && climbTrait.Id != flyTrait?.Id)
            {
                CreateGradedFamily("ClimbPenalty", "Makes worn items harder to climb in.", [climbTrait], -1.0);
            }

            if (flyTrait is not null && flyTrait.Id != swimTrait?.Id && flyTrait.Id != climbTrait?.Id)
            {
                CreateGradedFamily("FlyPenalty", "Makes worn items harder to fly in.", [flyTrait], -1.0);
            }

            CreateGradedFamily("MovementPenalty", "Makes worn items harder to swim, climb, or fly in.",
                movementPenaltyTraits, -1.0);
        }
        else
        {
            skippedFamilies.Add("MovementPenalty");
        }

        List<TraitDefinition> movementBonusTraits = UniqueTraits(swimTrait, climbTrait, flyTrait, runTrait);
        if (movementBonusTraits.Any())
        {
            CreateGradedFamily("MovementBonus", "Helps fitted athletic gear support swimming, climbing, flying, or running.",
                movementBonusTraits, 1.0);
        }
        else
        {
            skippedFamilies.Add("MovementBonus");
        }

        if (runTrait is not null)
        {
            CreateGradedFamily("RunningBonus", "Helps good footwear or legwear support running.", [runTrait], 1.0);
        }
        else
        {
            skippedFamilies.Add("RunningBonus");
        }

        List<TraitDefinition> stealthMobilityBonusTraits = UniqueTraits(hideTrait, sneakTrait, swimTrait, climbTrait,
            flyTrait, runTrait);
        if (stealthMobilityBonusTraits.Any())
        {
            CreateGradedFamily("StealthMobilityBonus",
                "Helps specialised worn gear support stealth, swimming, climbing, flying, and running.",
                stealthMobilityBonusTraits, 1.0);
        }
        else
        {
            skippedFamilies.Add("StealthMobilityBonus");
        }

        List<TraitDefinition> manualDexterityTraits = UniqueTraits(
            FindTrait("Palm", "Palming", "Sleight", "Security"),
            FindTrait("Picklock", "Pick Locks", "Lockpicking", "Security"),
            FindTrait("Steal", "Stealing", "Sleight", "Security"),
            FindTrait("Surgery", "Medicine"),
            FindTrait("First Aid", "Healing", "Medicine"),
            FindTrait("Patient Care", "Medicine"),
            FindTrait("Skin", "Skinning", "Survival"),
            FindTrait("Tattoo", "Tattooing"),
            FindTrait("Handwriting"));
        CreateGradedFamily("ManualDexterityPenalty",
            "Makes worn gloves, gauntlets, or similar gear interfere with manual dexterity work.",
            manualDexterityTraits, -1.0);

        TraitDefinition? spotTrait = FindTrait("Spot", "Spotting", "Scan", "Perception");
        TraitDefinition? searchTrait = FindTrait("Search", "Searching", "Perception");
        TraitDefinition? trackTrait = FindTrait("Track", "Tracking", "Perception");
        List<TraitDefinition> visualPerceptionTraits = UniqueTraits(spotTrait, searchTrait, trackTrait);
        CreateGradedFamily("VisualPerceptionPenalty",
            "Makes worn masks, visors, or closed helmets interfere with visual perception.",
            visualPerceptionTraits, -1.0);

        TraitDefinition? listenTrait = FindTrait("Listen", "Listening", "Perception");
        List<TraitDefinition> listeningTraits = UniqueTraits(listenTrait);
        CreateGradedFamily("ListeningPenalty",
            "Makes worn earplugs, heavy helmets, or muffling gear interfere with listening.",
            listeningTraits, -1.0);

        List<TraitDefinition> awarenessTraits = UniqueTraits(spotTrait, searchTrait, trackTrait, listenTrait);
        CreateGradedFamily("AwarenessPenalty",
            "Makes worn hoods, enclosed helmets, or heavy masks interfere with both seeing and hearing.",
            awarenessTraits, -1.0);

        if (skippedFamilies.Any())
        {
            errors.Add(
                $"Skipped worn trait changer component families because the expected Skill Package traits were not found: {string.Join(", ", skippedFamilies.Distinct())}.");
        }

        nextId = currentId;
        context.SaveChanges();

        #endregion
    }
}
