using MudSharp.Construction;
using MudSharp.Construction.Boundary;
using MudSharp.Events;
using MudSharp.Framework.Revision;
using MudSharp.GameItems.Prototypes;

namespace MudSharp.GameItems.Components;

public class DwellingGameItemComponent : GameItemComponent
{
    protected DwellingGameItemComponentProto _prototype;
    public override IGameItemComponentProto Prototype => _prototype;

    private long _entranceRoomId;
    private IRoom _entranceRoom;

    public IRoom EntranceRoom
    {
        get
        {
            if (_entranceRoomId != 0)
            {
                _entranceRoom = Gameworld.Rooms.Get(_entranceRoomId);
                _entranceRoomId = 0;
            }

            return _entranceRoom;
        }
        set => _entranceRoom = value;
    }

    protected override void UpdateComponentNewPrototype(IGameItemComponentProto newProto)
    {
        _prototype = (DwellingGameItemComponentProto)newProto;
    }

    private IRoom GenerateRooms()
    {
        Dictionary<IRoom, IRoom> cellMap = new();
        RoomOverlayPackage package = new(Gameworld, null, $"Autogenerated Dwelling Package {DateTime.UtcNow:R}");
        Gameworld.Add(package);
        IRoom baseRoom = new Room(package, Parent.Location.OwningZone, _prototype.TemplateEntryRoom, true);
        cellMap[_prototype.TemplateEntryRoom] = baseRoom;
        List<IRoom> baseRooms = _prototype.GetTemplateRooms.ToList();
        foreach (IRoom room in baseRooms.Except(baseRoom))
        {
            cellMap[room] = new Room(package, Parent.Location.OwningZone, room, true);
        }

        List<IExit> exitsAlreadyBuilt = new();
        foreach (IRoom room in baseRooms)
        {
            foreach (IRoomExit exit in room.ExitsFor(null))
            {
                if (exitsAlreadyBuilt.Contains(exit.Exit))
                {
                    continue;
                }

                Exit newExit = new(Gameworld, cellMap[room], cellMap[exit.Destination], (Exit)exit.Exit);
                cellMap[room].GetOrCreateOverlay(package).AddExit(newExit);
                cellMap[exit.Destination].GetOrCreateOverlay(package).AddExit(newExit);
                exitsAlreadyBuilt.Add(exit.Exit);
            }
        }

        foreach (KeyValuePair<IRoom, IRoom> room in cellMap)
        {
            Gameworld.ExitManager.UpdateRoomOverlayExits(room.Value, room.Value.CurrentOverlay);
        }

        Exit frontExit = new(Gameworld, Parent.Location, baseRoom, 1.0,
            Gameworld.NonCardinalExitTemplates.Get(
                Gameworld.GetStaticLong("DefaultNonCardinalExitForDwellings")),
            _prototype.EntranceKeyword, _prototype.EntranceKeyword,
            _prototype.EntranceDescription, "the outside")
        {
            AcceptsDoor = true,
            DoorSize = _prototype.DoorSize,
            MaximumSizeToEnter = _prototype.DoorSize,
            MaximumSizeToEnterUpright = _prototype.DoorSize
        };
        IEditableRoomOverlay overlay = Parent.Location.GetOrCreateOverlay(Parent.Location.CurrentOverlay.Package);
        IEditableRoomOverlay otherOverlay = baseRoom.GetOrCreateOverlay(baseRoom.CurrentOverlay.Package);
        overlay.AddExit(frontExit);
        otherOverlay.AddExit(frontExit);
        Gameworld.ExitManager.UpdateRoomOverlayExits(Parent.Location, overlay);
        Gameworld.ExitManager.UpdateRoomOverlayExits(baseRoom, otherOverlay);
        if (_prototype.DoorProto != null)
        {
            IGameItem newItem = _prototype.DoorProto.CreateNew(null);
            frontExit.Door = newItem.GetItemType<IDoor>();
            Gameworld.Add(newItem);
            frontExit.Door.InstalledExit = frontExit;
            newItem.Login();
            newItem.HandleEvent(EventType.ItemFinishedLoading, newItem);
        }

        package.ChangeStatus(RevisionStatus.Current, "Autogenerated", null);
        return baseRoom;
    }

    private void Parent_OnLocationChanged(Form.Shape.ILocateable locatable, IRoomExit exit)
    {
        if (Parent.Location != null)
        {
            EntranceRoom = GenerateRooms();
            Changed = true;
            Parent.OnLocationChanged -= Parent_OnLocationChanged;
        }
    }

    private void DestroyRooms()
    {
        if (EntranceRoom == null)
        {
            return;
        }

        IRoom fallbackRoom = Gameworld.ExitManager.GetAllExits(EntranceRoom)
                                    .First(x => !x.Destination.Temporary &&
                                                x.OutboundDirection == CardinalDirection.Unknown).Destination;
        foreach (IRoom room in EntranceRoom.RoomsInVicinity(10U, exit => true, room => room.Temporary))
        {
            room.Destroy(fallbackRoom);
        }
    }

    #region Overrides of GameItemComponent

    /// <summary>
    ///     Handles any finalisation that this component needs to perform before being deleted.
    /// </summary>
    public override void Delete()
    {
        base.Delete();
        DestroyRooms();
    }

    #endregion

    #region Constructors

    public DwellingGameItemComponent(DwellingGameItemComponentProto proto, IGameItem parent, bool temporary = false) :
        base(parent, proto, temporary)
    {
        _prototype = proto;
        Parent.OnLocationChanged += Parent_OnLocationChanged;
        Changed = true;
    }

    public DwellingGameItemComponent(MudSharp.Models.GameItemComponent component, DwellingGameItemComponentProto proto,
        IGameItem parent) : base(component, parent)
    {
        _prototype = proto;
        _noSave = true;
        LoadFromXml(XElement.Parse(component.Definition));
        _noSave = false;
    }

    public DwellingGameItemComponent(DwellingGameItemComponent rhs, IGameItem newParent, bool temporary = false) : base(
        rhs, newParent, temporary)
    {
        _prototype = rhs._prototype;
        if (!temporary)
        {
            Gameworld.SaveManager.AddInitialisation(this);
        }
        else
        {
            _noSave = true;
        }

        EntranceRoom = GenerateRooms();
        Changed = true;
    }

    protected void LoadFromXml(XElement root)
    {
        _entranceRoomId = long.Parse(root.Element("EntranceCell")?.Value ?? "0");
    }

    public override IGameItemComponent Copy(IGameItem newParent, bool temporary = false)
    {
        return new DwellingGameItemComponent(this, newParent, temporary);
    }

    #endregion

    #region Saving

    protected override string SaveToXml()
    {
        return new XElement("Definition",
            new XElement("EntranceCell", EntranceRoom?.Id ?? 0)
        ).ToString();
    }

    #endregion
}