namespace MudSharp.FutureProg
{
    [System.Flags]
    public enum ProgVariableTypeCode : long
    {
        Unknown = -1L,
        Void = 0L,
        Text = 1L << 0,
        Number = 1L << 1,
        Boolean = 1L << 2,
        Character = 1L << 3,
        Location = 1L << 4,
        Item = 1L << 5,
        Shard = 1L << 6,
        Error = 1L << 7,
        Gender = 1L << 8,
        Zone = 1L << 9,
        Collection = 1L << 10,
        Race = 1L << 11,
        Culture = 1L << 12,
        Chargen = 1L << 13,
        Trait = 1L << 14,
        Clan = 1L << 15,
        ClanRank = 1L << 16,
        ClanAppointment = 1L << 17,
        ClanPaygrade = 1L << 18,
        Currency = 1L << 19,
        Exit = 1L << 20,
        Literal = 1L << 21,
        DateTime = 1L << 22,
        TimeSpan = 1L << 23,
        Language = 1L << 24,
        Accent = 1L << 25,
        Merit = 1L << 26,
        MudDateTime = 1L << 27,
        Calendar = 1L << 28,
        Clock = 1L << 29,
        Effect = 1L << 30,
        Knowledge = 1L << 31,
        Role = 1L << 32,
        Ethnicity = 1L << 33,
        Drug = 1L << 34,
        WeatherEvent = 1L << 35,
        Shop = 1L << 36,
        Merchandise = 1L << 37,
        Outfit = 1L << 38,
        OutfitItem = 1L << 39,
        Project = 1L << 40,
        OverlayPackage = 1L << 41,
        Terrain = 1L << 42,
        Solid = 1L << 43,
        Liquid = 1L << 44,
        Gas = 1L << 45,
        Dictionary = 1L << 46,
        CollectionDictionary = 1L << 47,
        MagicSpell = 1L << 48,
        MagicSchool = 1L << 49,
        MagicCapability = 1L << 50,
        Bank = 1L << 51,
        BankAccount = 1L << 52,
        BankAccountType = 1L << 53,
        LegalAuthority = 1L << 54,
        Law = 1L << 55,
        Crime = 1L << 56,
        Market = 1L << 57,
        MarketCategory = 1L << 58,
        LiquidMixture = 1L << 59,
        Script = 1L << 60,
        Writing = 1L << 61,
        Area = 1L << 62,
        CollectionItem =
            0L | Number | Boolean | Gender | Text | DateTime | TimeSpan | Character | Item | Chargen | Location | Zone |
            Shard | Accent | Language | Race | Culture | Trait | Clan | ClanRank | ClanAppointment | ClanPaygrade |
            Currency | Exit | Merit | MudDateTime | Calendar | Clock | Effect | Knowledge | Role | Ethnicity | Drug |
            WeatherEvent | Shop | Merchandise | Outfit | OutfitItem | OverlayPackage | Terrain | Project |
            Solid | Liquid | Gas | MagicSchool | MagicCapability | MagicSpell | Bank | BankAccount | BankAccountType |
            LegalAuthority | Law | Crime | Market | MarketCategory | LiquidMixture | Script | Writing | Area,
        Perceivable = Item | Character | Location | Zone | Shard,
        Perceiver = Item | Character,
        MagicResourceHaver = Item | Character | Location,
        ReferenceType =
            long.MaxValue ^
            (Text | Number | DateTime | TimeSpan | Literal | Boolean | Error | Gender | Collection | Dictionary | CollectionDictionary | MudDateTime | LiquidMixture),
        ValueType = Text | Number | Boolean | DateTime | TimeSpan | Literal | Gender | MudDateTime | LiquidMixture,
        Anything = long.MaxValue ^ Error,
        Toon = Character | Chargen,
        Tagged = Location | Item | Terrain,
        Material = Solid | Gas | Liquid
    }
}
