#!/usr/bin/env python3
"""Generate the supported Early Modern military catalogue from its source ledger."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Design Documents/Seeding/FutureMUD_EarlyModern_Military_Firearms_Uniforms_Naval_Design_Reference.md"
COMPONENTS = ROOT / "Design Documents/Data/Seeded_Item_Components.json"
OUTPUT = ROOT / "DatabaseSeeder/Seeders/ItemSeeder.EarlyModern.MilitaryManifestData.Generated.cs"


def read(path: Path) -> list[str]:
	return path.read_text(encoding="utf-8-sig").splitlines()


def ticks(value: str) -> tuple[str, ...]:
	return tuple(re.findall(r"`([^`]+)`", value))


def profile_tags() -> dict[str, tuple[str, ...]]:
	profiles: dict[str, tuple[str, ...]] = {}
	for line in read(SOURCE):
		match = re.match(r"^\| `([^`]+)` \| (.+) \|$", line)
		if match and match.group(1).startswith("EM-"):
			profiles[match.group(1)] = ticks(match.group(2))
	if len(profiles) != 29:
		raise ValueError(f"Expected 29 Early Modern military tag profiles, found {len(profiles)}")
	return profiles


def available_components() -> set[str]:
	return {entry["Component Name"] for entry in json.loads(COMPONENTS.read_text(encoding="utf-8"))}


def parse_rows() -> tuple[list[tuple], list[tuple]]:
	profiles = profile_tags()
	available = available_components()
	supported = []
	deferred = []
	for line in read(SOURCE):
		if not line.startswith("| `earlymodern_"):
			continue
		cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
		if len(cells) != 8:
			raise ValueError(f"Malformed Early Modern military catalogue row: {line}")
		stable, sdesc, noun, material, size_quality, weight_cost, components, profile = cells
		stable = ticks(stable)[0]
		noun = ticks(noun)[0]
		material = ticks(material)[0]
		size, quality = (ticks(value)[0] for value in size_quality.split("/"))
		weight, cost = (value.strip().removesuffix("g").removesuffix("m").replace(",", "") for value in weight_cost.split("/"))
		component_names = ticks(components)
		profile = ticks(profile)[0]
		if profile not in profiles:
			raise ValueError(f"Unknown tag profile {profile} for {stable}")
		row = (stable, noun, sdesc, material, size, quality, weight, cost, profiles[profile], component_names, profile)
		(supported if all(component in available for component in component_names) else deferred).append(row)
	if len(supported) + len(deferred) != 1661:
		raise ValueError("Early Modern military source should contain exactly 1,661 new rows")
	return supported, deferred


def cs(value: str) -> str:
	return json.dumps(value, ensure_ascii=False)


def description(sdesc: str, noun: str, material: str) -> str:
	return f"{sdesc.capitalize()} is made chiefly from {material}. Its construction follows the documented Early Modern military form shown by its outward appearance."


def render(row: tuple) -> str:
	stable, noun, sdesc, material, size, quality, weight, cost, tags, components, profile = row
	return f'\t\tnew({cs(stable)}, {cs(noun)}, {cs(sdesc)}, {cs(description(sdesc, noun, material))}, SizeCategory.{size}, ItemQuality.{quality}, {weight}, {cost}m, {cs(material)}, [{", ".join(cs(tag) for tag in tags)}], [{", ".join(cs(component) for component in components)}], {cs(f"Early Modern military source profile {profile}; only currently supported component dependencies are seeded.")}),'


def generate() -> str:
	supported, deferred = parse_rows()
	if not supported or not deferred:
		raise ValueError("Expected both supported and deferred Early Modern military rows")
	return "\n".join([
		"// <auto-generated>",
		"// Generated by scripts/generate-earlymodern-supported-military-manifest.py from the canonical Early Modern military reference and maintained component export.",
		"// Do not edit this file by hand.",
		"// </auto-generated>",
		"#nullable enable",
		"",
		"using MudSharp.GameItems;",
		"",
		"namespace DatabaseSeeder.Seeders;",
		"",
		"public partial class ItemSeeder",
		"{",
		"\tprivate static readonly EarlyModernMilitaryItemSpec[] EarlyModernSupportedMilitaryItemSpecs =",
		"\t[",
		*(render(row) for row in supported),
		"\t];",
		"",
		f"\tinternal const int EarlyModernMilitaryDeferredSourceRows = {len(deferred)};",
		"}",
		"",
	])


def main() -> int:
	parser = argparse.ArgumentParser()
	parser.add_argument("--check", action="store_true")
	args = parser.parse_args()
	content = generate()
	if args.check:
		if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
			print(f"Generated supported military manifest source is stale: {OUTPUT.relative_to(ROOT)}")
			return 1
		return 0
	OUTPUT.write_text(content, encoding="utf-8", newline="\n")
	print(f"Wrote {OUTPUT.relative_to(ROOT)}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
