using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MudSharp.RPG.Law
{
    public enum CrimeTypes
    {
        Assault,
        AssaultWithADeadlyWeapon,
        Battery,
        AttemptedMurder,
        Murder,
        Manslaughter,
        Torture,
        GreviousBodilyHarm,
        Theft,
        Fraud,
        Racketeering,
        CartelCollusion,
        PossessingStolenGoods,
        SellingContraband,
        PossessingContraband,
        TrafficingContraband,
        Vandalism,
        BreakAndEnter,
        Loitering,
        Littering,
        Libel,
        Slander,
        Treason,
        Conspiracy,
        Intimidation,
        Blackmail,
        Trespassing,
        ResistArrest,
        DisobeyLegalInstruction,
        ViolateParole,
        EscapeCaptivity,
        Indecency,
        Immorality,
        PublicIntoxication,
        Blasphemy,
        Apostacy,
        Profanity,
        Vagrancy,
        DestructionOfProperty,
        UnauthorisedDealing,
        Embezzlement,
        Sedition,
        Mayhem,
        ContemptOfCourt,
        ViolateBail,
        Aiding,
        Abetting,
        Accessory,
        Arson,
        Bribery,
        Tyranny,
        Harassment,
        Extortion,
        Rape,
        SexualAssault,
        Negligence,
        Perjury,
        Desertion,
        Mutiny,
        Rebellion,
        Rioting,
        TaxEvasion,
        Gambling,
        ObstructionOfJustice,
        Forgery,
        Adultery,
        Sodomy,
        Fornication,
        Prostitution,
        Kidnapping,
        Slavery,
        Smuggling,
        AnimalCruelty,
        UnlawfulUseOfMagic,
        UnlawfulUseOfPsionics,
        IllegalConsumption
    }
}
