<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MudClientBlazor\MudClientBlazor.csproj" />
		<ProjectReference Include="..\MudWebSocketProxy\MudWebSocketProxy.csproj" />
		<ProjectReference Include="..\MudClientDeployment\MudClientDeployment.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

	<ItemGroup>
		<None Include="..\deploy\windows\Install-MudClient.ps1" Link="DeploymentScripts\Install-MudClient.ps1" CopyToOutputDirectory="PreserveNewest" />
		<None Include="..\deploy\windows\MudClientDeployment.Common.ps1" Link="DeploymentScripts\MudClientDeployment.Common.ps1" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
